apiVersion: apps/v1
kind: Deployment
metadata:
  name: choreo-connect-adapter-green
spec:
  selector:
    matchLabels:
      choreo.component: choreo-connect-adapter-test-p1
  template:
    metadata:
      labels:
        choreo.component: choreo-connect-adapter-test-p1
    spec:
     containers:
       - name: choreo-connect-adapter
         volumeMounts:
           - mountPath: /home/wso2/security/truststore/global-adapter.pem
             name: global-adapter-keystore-vol
             subPath: global-adapter.pem
         env:
         - name: localLabel
           value: test-p1
         - name: environmentLabel
           value: test
     volumes:
        - name: global-adapter-keystore-vol
          configMap:
            name: global-adapter-keystore-vol
