idp-SUPER-ADMIN-USERNAME xxxxxxxxxxxxxxxxxxxx
idp-SUPER-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-DB-USERNAME xxxxxxxxxxxxxxxxxxxx
idp-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-SHARED-DB-USERNAME xxxxxxxxxxxxxxxxxxxx
idp-SHARED-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-BPS-DB-USERNAME xxxxxxxxxxxxxxxxxxxx
idp-BPS-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-USERSTORE-DB-USERNAME xxxxxxxxxxxxxxxxxxxx
idp-USERSTORE-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-CONFIG-DB-USERNAME xxxxxxxxxxxxxxxxxxxx
idp-CONFIG-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-KEYSTORE-PRIMARY-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-KEYSTORE-INTERNAL-PASSWORD xxxxxxxxxxxxxxxxxxxx
idp-ANONYMOUS-USERSTORE-PASSWORD xxxxxxxxxxxxxxxxxxxx
