apim-ADAPTER-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-ENFORCER-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-ANALYTICS-AUTH-TOKEN xxxxxxxxxxxxxxxxxxxx
apim-CHOREO-APIM-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-PRIMARY-KEYSTORE-PSWD xxxxxxxxxxxxxxxxxxxx
apim-PRIMARY-KEYSTORE-KEY-PSWD xxxxxxxxxxxxxxxxxxxx
apim-TLS-KEYSTORE-PSWD xxxxxxxxxxxxxxxxxxxx
apim-TLS-KEYSTORE-KEY-PSWD xxxxxxxxxxxxxxxxxxxx
apim-INTERNAL-KEYSTORE-PSWD xxxxxxxxxxxxxxxxxxxx
apim-INTERNAL-KEYSTORE-KEY-PSWD xxxxxxxxxxxxxxxxxxxx
apim-TRUSTSTORE-PSWD xxxxxxxxxxxxxxxxxxxx
apim-MONGO-DB-ATLAS-PRIVATE-KEY xxxxxxxxxxxxxxxxxxxx
apim-MONGO-DB-ATLAS-PUBLIC-KEY xxxxxxxxxxxxxxxxxxxx
apim-MONGO-DB-PSWD xxxxxxxxxxxxxxxxxxxx
apim-CHOREO-APIM-SHARED-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-CHOREO-APIM-USER-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-CHOREO-IS-ADMIN-PSWD xxxxxxxxxxxxxxxxxxxx
apim-H2-SHARED-DB-PSWD xxxxxxxxxxxxxxxxxxxx
apim-SUPER-ADMIN-PSWD xxxxxxxxxxxxxxxxxxxx
fileshare-STORAGE-ACCOUNT-KEY xxxxxxxxxxxxxxxxxxxx
fileshare-STORAGE-ACCOUNT-NAME xxxxxxxxxxxxxxxxxxxx
redis-PASSWORD xxxxxxxxxxxxxxxxxxxx
analytics-ad-app-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
alert-email-service-SMTP-PASSWORD xxxxxxxxxxxxxxxxxxxx
alert-email-service-SMTP-USERNAME xxxxxxxxxxxxxxxxxxxx
alert-email-service-SMTP-HOST xxxxxxxxxxxxxxxxxxxx
apim-CHOREO-APIM-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-CHOREO-APIM-SHARED-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-CHOREO-APIM-USER-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
asb-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
cc-GLOBAL-ADAPTER-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
globalAdapter-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
enforcer-MANAGEMENT-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-ANALYTICS-AUTH-TOKEN-CP xxxxxxxxxxxxxxxxxxxx
ga-<CUSTOMER-NAME>-PASSWORD xxxxxxxxxxxxxxxxxxxx
tm-<CUSTOMER-NAME>-PASSWORD
