dp-secret-manager-AZURE-KEYVAULT-CLIENT-ID xxxxxxxxxxxxxxxxxxxx
dp-secret-manager-AZURE-KEYVAULT-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
dp-secret-manager-AZURE-KEYVAULT-TENANT-ID xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-RUDDER-MSSQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-MIZZEN-MSSQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CLOUD-MANAGER-MSSQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CICD-MSSQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-RUDDER-MSSQL-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-MIZZEN-MSSQL-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CLOUD-MANAGER-MSSQL-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CICD-MSSQL-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-auth-module-MONGODB-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-auth-module-SERVICE-ACCOUNT-RS256-PASS xxxxxxxxxxxxxxxxxxxx
dp-rudder-MIZZEN-SERVICE-TOKEN xxxxxxxxxxxxxxxxxxxx
dp-mizzen-SERVICE-BUS-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
dp-garbage-collector-MONGODB-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-mizzen-JWT-KEY xxxxxxxxxxxxxxxxxxxx
dp-project-manager xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CICD-GITOPS-AUTH-TOKEN xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CICD-GITOPS xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CICD-ACR xxxxxxxxxxxxxxxxxxxx
dp-CHOREO-CICD-INTERGRATION-APPS xxxxxxxxxxxxxxxxxxxx
dp-project-manager-MONGODB-PASSWORD xxxxxxxxxxxxxxxxxxxx
dp-mizzen-agent-dp-1-TOKEN xxxxxxxxxxxxxxxxxxxx (dev)
dp-mizzen-agent-workspace-1-TOKEN xxxxxxxxxxxxxxxxxxxx (dev)
dp-mizzen-agent-dp-e2-TOKEN xxxxxxxxxxxxxxxxxxxx (dev)
dp-mizzen-agent-routing-TOKEN xxxxxxxxxxxxxxxxxxxx