anomaly-detector-ALERTS-EVENT-HUBS-NAMESPACE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
anomaly-detector-ANOMALY-EVENT-HUBS-NAMESPACE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
anomaly-detector-CHECKPOINT-STORAGE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
anomaly-detector-MODEL-STORAGE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
apim-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
apim-REST-API-CONSUMER-SECRET xxxxxxxxxxxxxxxxxxxx
apim-IDP-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx
app-CHOREO-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
app-deployer-DOCKER-REGISTRY-PASSWORD xxxxxxxxxxxxxxxxxxxx
app-deployer-GITHUB-TOKEN xxxxxxxxxxxxxxxxxxxx
app-deployer-K8S-API-TOKEN xxxxxxxxxxxxxxxxxxxx
app-deployer-APIM-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
app-service-BETA-PROGRAM-PREFINERY-INVITATION-DECODER-KEY xxxxxxxxxxxxxxxxxxxx
app-service-GITHUB-BOT-ACCESS-TOKEN xxxxxxxxxxxxxxxxxxxx
app-service-USER-FEEDBACK-AZURE-BLOB-ACCOUNT-KEY xxxxxxxxxxxxxxxxxxxx
app-deployer-K8S-SERVICE-ACCOUNT xxxxxxxxxxxxxxxxxxxx
fileshare-STORAGE-ACCOUNT-KEY xxxxxxxxxxxxxxxxxxxx
fileshare-STORAGE-ACCOUNT-NAME xxxxxxxxxxxxxxxxxxxx
ast-archiver-DATALAKE-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
datamapper-MODEL-ACCESS-KEY xxxxxxxxxxxxxxxxxxxx
email-service-SMTP-PASSWORD xxxxxxxxxxxxxxxxxxxx
email-service-SMTP-USERNAME xxxxxxxxxxxxxxxxxxxx
email-service-SMTP-HOST xxxxxxxxxxxxxxxxxxxx
email-service-SMTP-PORT xxxxxxxxxxxxxxxxxxxx
email-service-SMTP-SENDER-MAIL xxxxxxxxxxxxxxxxxxxx
gh-CONNECTOR-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
gsuite-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
idp-BACKEND-API-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
idp-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
app-service-AZURE-KEY-VAULT-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
loggingapi-AD-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
obsapi-ADX-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
perfanalyzer-AZURE-ADX-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
perfanalyzer-CHOREO-PERF-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
program-CHOREO-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
redis-PASSWORD xxxxxxxxxxxxxxxxxxxx
service-now-CLIENT-ID xxxxxxxxxxxxxxxxxxxx
service-now-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
service-now-PASSWORD xxxxxxxxxxxxxxxxxxxx
service-now-USERNAME xxxxxxxxxxxxxxxxxxxx
sys-obsapi-AD-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
telemetry-EVENTHUB-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
test-assistant-MODEL-STORAGE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
testbase-CHOREO-DB-PASSWORD xxxxxxxxxxxxxxxxxxxx
capacity-planner-MODEL-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
loggingapi-AZURE-K8S-API-SERVER-ACCESS-TOKEN xxxxxxxxxxxxxxxxxxxx
azure-INSIGHTS-KEY xxxxxxxxxxxxxxxxxxxx
ai-DEP-OPTZ-MODEL-STORAGE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
ai-EVENTHUB-CHECKPOINT-STORAGE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
ai-EVENTHUB-METRICS-NAMESPACE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
ai-TABLE-STORAGE-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
app-CHOREO-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
datacollector-EVENTHUB-CONNECTION-STRING xxxxxxxxxxxxxxxxxxxx
perfanalyzer-CHOREO-PERF-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
program-CHOREO-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
subscriptions-MSSQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
testbase-CHOREO-DB-SQL-PASSWORD xxxxxxxxxxxxxxxxxxxx
observability-data-generator-APIM-CLIENT-ID xxxxxxxxxxxxxxxxxxxx
observability-data-generator-APIM-CLIENT-SECRET xxxxxxxxxxxxxxxxxxxx
idp-PWD-RESET-ADMIN-PASSWORD xxxxxxxxxxxxxxxxxxxx(dev only)
linkerd-viz-AUTH-UNAME-PWD xxxxxxxxxxxxxxxxxxxx(dev only)
