apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
#    checkov.io/skip1: CKV_K8S_22=Skipping till the issue is fixed
#    checkov.io/skip2: CKV_K8S_40=Temporarily suppressing till fixing
#    checkov.io/skip3: CKV_K8S_23=Temporarily suppressing till fixing
    checkov.io/skip4: CKV_K8S_25=No resolution provided in bridgecrew docs
    checkov.io/skip5: CKV_K8S_43=Temporarily suppressing as this requires CICD level changes
  labels:
    choreo.component: apim-devportal
  name: apim-devportal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: apim-devportal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        choreo.component: apim-devportal
      annotations:
        linkerd.io/inject: enabled
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - image: choreocontrolplane.azurecr.io/choreoipaas/choreo-apim-devportal:v0.1.8
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 10500
            runAsGroup: 10500
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add: ["NET_RAW"]
            readOnlyRootFilesystem: true
          name: apim-devportal
          envFrom:
          - configMapRef:
              name: cm-feature-flags
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: 8080
              path: /health
          livenessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: 8080
              path: /health
          ports:
            - containerPort: 8080
              name: devportal-port
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: devportal-conf
              mountPath: /app/devportal.config.js
              subPath: devportal.config.js
      restartPolicy: Always
      volumes:
        - name: devportal-conf
          configMap:
            name: choreo-apim-devportal-conf
      serviceAccountName: sa-choreo-apim
