kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all-network-policy
  namespace: dev-choreo-system-nginx-ingress
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector: {}
  ingress: []
  egress: []

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-controller-network-policy
  namespace: dev-choreo-system-nginx-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: dev-choreo-system
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          linkerd.io/extension: viz
      podSelector: {}
  - ports:
      - port: 80
      - port: 443
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
  