helmCharts:
  - name: csi-secrets-store-provider-azure
    includeCRDs: true
    valuesInline:
      linux:
        image:
          repository: choreocontrolplane.azurecr.io/oss/azure/secrets-store/provider-azure
      secrets-store-csi-driver:
        syncSecret:
          enabled: true
        linux:
          livenessProbeImage:
            repository: choreocontrolplane.azurecr.io/oss/kubernetes-csi/livenessprobe
          registrarImage:
            repository: choreocontrolplane.azurecr.io/oss/kubernetes-csi/csi-node-driver-registrar
          image:
            repository: choreocontrolplane.azurecr.io/oss/kubernetes-csi/secrets-store/driver
          driver:
            resources:
              requests:
                memory: 200Mi
              limits:
                memory: 400Mi
    releaseName: csi-secrets-store-provider-azure
    namespace: csi-secret-store-driver
    version: 1.2.0
    repo: oci://choreocontrolplane.azurecr.io/helm

commonAnnotations:
  kapp.k14s.io/disable-original: ""
  kapp.k14s.io/disable-default-label-scoping-rules: ""
