# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "audit-logging.labels" . | nindent 4 }}
  name: audit-logging
  namespace: {{ .Values.global.namespaces.system }}
spec:
  ports:
    - name: service-port
      port: 8080
      targetPort: service-port
    - name: listener-port
      port: 8090
      targetPort: listener-port
    - name: health-port
      port: 9090
      targetPort: health-port
  selector:
    {{- include "audit-logging.labels" . | nindent 4 }}
