apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../dataplane/
images:
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-adapter
  newTag: choreo-207659080879477305ed605d543719d0044c7aa1
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-enforcer
  newTag: choreo-207659080879477305ed605d543719d0044c7aa1
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-router
  newTag: choreo-207659080879477305ed605d543719d0044c7aa1
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-mizzen-agent
  newTag: main-b17c18693c58f365557d81b8a002297e97650f9d
