apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../dataplane/
images:
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-adapter
  newTag: choreo-4d8868caf656ea1ec99acc26c2917e4c88da7965
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-enforcer
  newTag: choreo-4d8868caf656ea1ec99acc26c2917e4c88da7965
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-router
  newTag: choreo-4d8868caf656ea1ec99acc26c2917e4c88da7965
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-mizzen-agent
  newTag: main-b17c18693c58f365557d81b8a002297e97650f9d
