apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../shared-components/dp-mizzen
  - netpol

patches:
  - path: linkerd-patch.yaml
    target:
      kind: Deployment

namespace: choreodp-system
