CREATE TABLE `release_data.INTEGRATION_TEST_RESULT`
(
BUILD_NUMBER STRING(15),
COMMIT_MSG STRING(127),
TEST_TYPE STRING(7),
TEST_FUNCTION STRING,
OUTCOME STRING(15),
ERROR_MSG STRING,
STACK_TRACE STRING,
CHOREO_ENV STRING(7),
PIPELINE_START_TIME DATETIME
);

CREATE TABLE `release_data.DEPLOYED_COMPONENT`
(
BUILD_NUMBER STRING(15),
CHOREO_ENV STRING(7),
COMPONENT_NAME STRING(127),
IMAGE STRING(127),
TAG STRING(95),
TIME_STAMP DATETIME
);

CREATE TABLE `release_data.RELEASE_PROMOTION`
(
BUILD_NUMBER STRING(15),
COMMIT_MSG STRING(127),
PROMOTION_TIME DATETIME,
SOURCE_ENV STRING(7),
DEST_ENV STRING(7),
RELEASE_ID STRING(47)
);

CREATE TABLE `release_data.CHOREO_ISSUE`
(
  ISSUE_ID STRING(23),
  ISSUE_TITLE STRING(255),
  CREATED_TIME DATETIME
);

CREATE TABLE `release_data.CHOREO_ISSUE_LABEL`
(
  ISSUE_ID STRING(23),
  TIME_STAMP DATETIME,
  LABELS ARRAY<STRING>
);

CREATE TABLE `release_data.CHOREO_ISSUE_CLOSE`
(
  ISSUE_ID STRING(23),
  CLOSED_TIME DATETIME
);
