apiVersion: batch/v1
kind: CronJob
metadata:
  name: choreo-org-stat-data-collector #Name of the cron job
  namespace: choreo-system
  labels:
    choreo.component: choreo-org-stat-data-collector #Label for the cron job
spec:
  schedule: "30 19 * * *" #Cron schedule to run at 1 AM Sri lankan time everyday
  successfulJobsHistoryLimit: 3 #Number of successful job histories to keep
  concurrencyPolicy: Forbid #Concurrency policy to forbid concurrent execution of the job
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            seccomp.security.alpha.kubernetes.io/pod: "runtime/default" #Annotation for seccomp security
            linkerd.io/inject: disabled #Annotation to disable linkerd injection
          labels:
            choreo.component: choreo-org-stat-data-collector #Label for the pod
        spec:
          automountServiceAccountToken: false #Automount service account token setting
          securityContext:
            seccompProfile:
              type: RuntimeDefault #Type of seccomp profile
          restartPolicy: Never #Pod restart policy
          terminationGracePeriodSeconds: 30 #Termination grace period in seconds
          containers:
            - name: choreo-org-stat-data-collector #Name of the container
              image: choreocontrolplane.azurecr.io/choreoipaas/choreo-org-stat-data-collector:latest #Docker image for the container
              securityContext:
                runAsUser: 10500 #User ID to run the container as
                runAsGroup: 10500 #Group ID to run the container as
                allowPrivilegeEscalation: false #Setting for privilege escalation
                readOnlyRootFilesystem: true #Setting for read only root filesystem
                capabilities:
                  drop:
                    - all #Capabilities to drop
              resources:
                limits:
                  cpu: 500m #CPU limit
                  memory: 500Mi #Memory limit
                requests:
                  cpu: 300m #CPU request
                  memory: 400Mi #Memory request
              volumeMounts:
                - name: config #Name of the volume mount
                  mountPath: /home/ballerina/Config.toml #Path to mount the volume
                  subPath: Config.toml
                - name: secret-choreo-org-stat-data-collector
                  mountPath: "/mnt/csi/secret-choreo-org-stat-data-collector"
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: cm-file-choreo-org-stat-data-collector #Name of the config map
            - name: secret-choreo-org-stat-data-collector
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: secret-choreo-org-stat-data-collector
                nodePublishSecretRef:
                  name: csi-secret-store-azure
          serviceAccountName: sa-choreo-default
