helmCharts:
  - name: cert-manager
    includeCRDs: true
    valuesInline:
      global:
        leaderElection:
          namespace: cert-manager
      clusterResourceNamespace: cert-manager
      fullnameOverride: cert-manager
      podDisruptionBudget:
        enabled: true
      extraArgs:
        - --dns01-recursive-nameservers-only
        - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
      startupapicheck:
        enabled: false
      cainjector:
        image:
          repository: choreocontrolplane.azurecr.io/jetstack/cert-manager-cainjector
          tag: v1.14.3
        replicaCount: 2
        podDisruptionBudget:
          enabled: true
      image:
        repository: choreocontrolplane.azurecr.io/jetstack/cert-manager-controller
        tag: v1.14.3
      installCRDs: true
      replicaCount: 2
      webhook:
        image:
          repository: choreocontrolplane.azurecr.io/jetstack/cert-manager-webhook
          tag: v1.14.3
        replicaCount: 2
        podDisruptionBudget:
          enabled: true
      acmesolver:
        image:
          registry: choreocontrolplane.azurecr.io
          repository: jetstack/cert-manager-acmesolver
    releaseName: cert-manager
    version: v1.14.3
    namespace: cert-manager
    repo: oci://choreocontrolplane.azurecr.io/helm

resources:
  - namespace.yaml

commonAnnotations:
  kapp.k14s.io/disable-default-label-scoping-rules: ""
