apiVersion: apps/v1
kind: Deployment
metadata:
  name: choreo-connect-adapter-green
spec:
  replicas: 1  
  selector:
    matchLabels:
      choreo.component: choreo-connect-adapter-default-p2
  template:
    metadata:
      labels:
        choreo.component: choreo-connect-adapter-default-p2
    spec:
     containers:
       - name: choreo-connect-adapter
         env:
         - name: localLabel
           value: default-p2
         - name: environmentLabel
           value: Production and Sandbox
     volumes:
        - name: global-adapter-keystore-vol
          configMap:
            name: global-adapter-keystore-vol
