// -------------------------------------------------------------------------------------
//
// Copyright (c) 2020, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
//
// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.
//
// --------------------------------------------------------------------------------------

.create table alerts (
timestamp: datetime,
obsId: string,
version: string,
nodeId: string,
detectionMethod:string,
featureValues: dynamic
);

.create table alerts ingestion json mapping "alertsMapping"
    '['
    '    { "column" : "timestamp", "Properties":{"Path":"$.timestamp"}},'
    '    { "column" : "obsId", "Properties":{"Path":"$.obsId"}},'
    '    { "column" : "version", "Properties":{"Path":"$.version"}},'
    '    { "column" : "nodeId", "Properties":{"Path":"$.nodeId"}},'
    '    { "column" : "detectionMethod", "Properties":{"Path":"$.detectionMethod"}},'
    '    { "column" : "featureValues", "Properties":{"Path":"$.featureValues"}}'
    ']';
