// Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.

// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.

.create table deployments (
    timestamp: datetime,
    orgId: string,
    projectId: string,
    componentId: string,
    versionId: string,
    environmentId: string,
    isProd: bool,
    status: string,
    count: int
);

.create table deployments ingestion json mapping "deploymentMapping"
    '['
    '    { "column" : "timestamp", "Properties":{"Path":"$.deploymentTime"}},'
    '    { "column" : "orgId", "Properties":{"Path":"$.organizationId"}},'
    '    { "column" : "projectId", "Properties":{"Path":"$.projectId"}},'
    '    { "column" : "componentId", "Properties":{"Path":"$.componentId"}},'
    '    { "column" : "versionId", "Properties":{"Path":"$.versionId"}},'
    '    { "column" : "environmentId", "Properties":{"Path":"$.environmentId"}},'
    '    { "column" : "isProd", "Properties":{"Path":"$.isProd"}},'
    '    { "column" : "status", "Properties":{"Path":"$.status"}},'
    '    { "column" : "count", "Properties":{"Path":"$.deploymentCount"}}'
    ']';
