// Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.

// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.

.create table incidents (
    timestamp: datetime,
    orgId: string,
    projectId: string,
    componentId: string,
    versionId: string,
    environmentId: string,
    commitId: string,
    releaseId: string,
    incidentId: string,
    status: string,
    isProd: bool,
    duration: int
);
