// Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.

// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.

.create table commits (
    timestamp: datetime,
    orgId: string,
    projectId: string,
    componentId: string,
    developerId: string,
    commits: int,
    additions: int,
    deletions: int,
    properties: string
);

.create table commits ingestion json mapping "commitsMapping"
    '['
    '    { "column" : "timestamp", "Properties":{"Path":"$.timestamp"}},'
    '    { "column" : "orgId", "Properties":{"Path":"$.organizationId"}},'
    '    { "column" : "projectId", "Properties":{"Path":"$.projectId"}},'
    '    { "column" : "componentId", "Properties":{"Path":"$.componentId"}},'
    '    { "column" : "developerId", "Properties":{"Path":"$.developerId"}},'
    '    { "column" : "commits", "Properties":{"Path":"$.commits"}},'
    '    { "column" : "additions", "Properties":{"Path":"$.additions"}},'
    '    { "column" : "deletions", "Properties":{"Path":"$.deletions"}},'
    '    { "column" : "properties", "Properties":{"Path":"$.properties"}}'
    ']';
