// -------------------------------------------------------------------------------------
//
// Copyright (c) 2020, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
//
// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.
//
// --------------------------------------------------------------------------------------

.create table metrics (
timestamp: datetime,
obsId: string,
nodeId: string,
version: string,
metricName:string,
value: real,
tags: dynamic
);

.create table metrics ingestion json mapping "metricsMapping"
    '['
    '    { "column" : "timestamp", "Properties":{"Path":"$.timestamp"}},'
    '    { "column" : "obsId", "Properties":{"Path":"$.obsId"}},'
    '    { "column" : "nodeId", "Properties":{"Path":"$.nodeId"}},'
    '    { "column" : "version", "Properties":{"Path":"$.version"}},'
    '    { "column" : "metricName", "Properties":{"Path":"$.metricName"}},'
    '    { "column" : "value", "Properties":{"Path":"$.value"}},'
    '    { "column" : "tags", "Properties":{"Path":"$.tags"}}'
    ']';
