// -------------------------------------------------------------------------------------
//
// Copyright (c) 2020, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
//
// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.
//
// --------------------------------------------------------------------------------------

.create external table MetricsDataLake (
timestamp: datetime,
obsId: string,
nodeId: string,
version: string,
metricName:string,
value: real,
tags: dynamic
)
kind=adl
partition by (Date:datetime = bin(timestamp, 1d))
dataformat=csv
(
   h@'abfss://metrics@<storage-account-name>.dfs.core.windows.net/;sharedkey=<account-key>'
)

.create-or-alter continuous-export <continuous-export-name>
over (metrics)
to table MetricsDataLake
with
(intervalBetweenRuns=1h)
<| metrics
| where metricName != 'telemetry_health_check'
