// Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.

// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.

.create table pixieMetrics (
    timestamp: datetime,
    metricName: string,
    dataplaneId: string,
    releaseId: string,
    attributes: dynamic,
    value: dynamic
);

.create table pixieMetrics ingestion json mapping "pixieMetricsMapping"
    '['
    '    { "column" : "timestamp", "Properties":{"Path":"$.timestamp"}},'
    '    { "column" : "metricName", "Properties":{"Path":"$.metricName"}},'
    '    { "column" : "dataplaneId", "Properties":{"Path":"$.dataplaneId"}},'
    '    { "column" : "releaseId", "Properties":{"Path":"$.releaseId"}},'
    '    { "column" : "attributes", "Properties":{"Path":"$.attributes"}},'
    '    { "column" : "value", "Properties":{"Path":"$.value"}}'
    ']';
