# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: config-deployer-service
  namespace: {{ .Values.global.namespaces.apim }}
  labels:
    {{- include "config-deployer-service.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: config.key
        secretKey: {{ .Values.secrets.privateKey.key | quote }}
        secretPath: {{ .Values.secrets.privateKey.path | quote }}
      - objectName: config.pem
        secretKey: {{ .Values.secrets.publicKey.key | quote }}
        secretPath: {{ .Values.secrets.publicKey.path | quote }}
