apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_22=Not possible to do ATM, as there are some files such as logs and configs written
    checkov.io/skip2: CKV_K8S_43=On hold ,not an high priority issue, requires some CI/CD workflow changes
    checkov.io/skip3: CKV_K8S_8=Temporarily suppressing till fixing
    checkov.io/skip4: CKV_K8S_37=Temporarily suppressing till fixing
    checkov.io/skip5: CKV_K8S_28=Temporarily suppressing till fixing
  labels:
    choreo.component: anomalydetector
  name: anomalydetector
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: anomalydetector
  template:
    metadata:
      labels:
        choreo.component: anomalydetector
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10500
        runAsGroup: 10500
        capabilities:
          drop:
            - all
          add: [ "NET_RAW" ]
        fsGroup: 500
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - env:
        - name: MODEL_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: secret-anomalydetector
              key: MODEL_STORAGE_CONNECTION_STRING
        image: choreocontrolplane.azurecr.io/choreoipaas/anomaly-detector-init:latest
        name: anomalydetector-init
        volumeMounts:
        - name: anomalydetector-models
          mountPath: "/home/python-ai/choreo-ai-anomaly-detector/models"
        - name: anomalydetector-model-metadata
          mountPath: "/home/python-ai/choreo-ai-anomaly-detector/models.properties"
          subPath: "models.properties"
        - name: secret-anomalydetector
          mountPath: "/mnt/csi/secret-anomalydetector"
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 300Mi
      containers:
      - image: choreocontrolplane.azurecr.io/choreoipaas/anomaly-detector:latest
        name: anomalydetector
        env:
          - name: CHECKPOINT_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: secret-anomalydetector
                key: CHECKPOINT_STORAGE_CONNECTION_STRING
          - name: ANOMALY_EVENT_HUBS_NAMESPACE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: secret-anomalydetector
                key: ANOMALY_EVENT_HUBS_NAMESPACE_CONNECTION_STRING
          - name: ALERTS_EVENT_HUBS_NAMESPACE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: secret-anomalydetector
                key: ALERTS_EVENT_HUBS_NAMESPACE_CONNECTION_STRING
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          exec:
            command:
              - ls
              - /home/python-ai/choreo-ai-anomaly-detector/models/supervisedModel
          initialDelaySeconds: 5
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: anomalydetector-models
          mountPath: "/home/python-ai/choreo-ai-anomaly-detector/models/"
        - name: anomalydetector-application-properties
          mountPath: "/home/python-ai/choreo-ai-anomaly-detector/config/"
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: anomalydetector-models
        emptyDir: {}
      - name: anomalydetector-model-metadata
        configMap:
          defaultMode: 420
          name: cm-anomalydetector-model-metadata
      - name: anomalydetector-application-properties
        configMap:
          defaultMode: 420
          name: cm-anomalydetector
      - name: secret-anomalydetector
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-anomalydetector
          nodePublishSecretRef:
            name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
