apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_38=The SA token is required for the linkerd to define service identity
    checkov.io/skip2: CKV_K8S_43=The image tag gets updated to component git hash when deploying
  labels:
    choreo.component: app-service
  name: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: app-service
  template:
    metadata:
      labels:
        choreo.component: app-service
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: choreocontrolplane.azurecr.io/choreoipaas/app-service:latest
        name: app-service
        env:
        - name: CHOREO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-app-db
              key: CHOREO_DB_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-redis
              key: REDIS_PASSWORD
        - name: GITHUB_BOT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-app-service
              key: GITHUB_BOT_ACCESS_TOKEN
        - name: USER_FEEDBACK_AZURE_BLOB_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: secret-app-service
              key: USER_FEEDBACK_AZURE_BLOB_ACCOUNT_KEY
        - name: BETA_PROGRAM_PREFINERY_INVITATION_DECODER_KEY
          valueFrom:
            secretKeyRef:
              name: secret-app-service
              key: BETA_PROGRAM_PREFINERY_INVITATION_DECODER_KEY
        - name: CENTRAL_ORG_REGISTRY_CERTIFICATE_KEY
          valueFrom:
            secretKeyRef:
              name: secret-app-service
              key: CENTRAL_ORG_REGISTRY_CERTIFICATE_KEY
        - name: IDP_BACKEND_API_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-idp
              key: IDP_BACKEND_API_CLIENT_SECRET
        - name: AZURE_KEY_VAULT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-key-vault
              key: AZURE_KEY_VAULT_CLIENT_SECRET
        - name: GH_CONNECTOR_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-github-connector
              key: GH_CONNECTOR_CLIENT_SECRET
        - name: GSUITE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-gsuite
              key: GSUITE_CLIENT_SECRET
        - name: SERVICE_NOW_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: secret-service-now
              key: SERVICE_NOW_CLIENT_ID
        - name: SERVICE_NOW_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-service-now
              key: SERVICE_NOW_CLIENT_SECRET
        - name: SERVICE_NOW_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-service-now
              key: SERVICE_NOW_USERNAME
        - name: SERVICE_NOW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-service-now
              key: SERVICE_NOW_PASSWORD
        envFrom:
        - configMapRef:
            name: env-app-service
        ports:
        - containerPort: 8080
          name: grpc-port
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "bin/grpc_health_probe -addr=:8080 2>&1 | grep -q SERVING"]
          initialDelaySeconds: 20
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 12000
          runAsGroup: 12000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - all
        volumeMounts:
        - mountPath: /app-service.yaml
          name: config
          subPath: app-service.yaml
        - name: secret-redis
          mountPath: "/mnt/csi/secret-redis"
          readOnly: true
        - name: secret-gsuite
          mountPath: "/mnt/csi/secret-gsuite"
          readOnly: true
        - name: secret-app-db
          mountPath: "/mnt/csi/secret-app-db"
          readOnly: true
        - name: secret-app-service
          mountPath: "/mnt/csi/secret-app-service"
          readOnly: true
        - name: secret-idp
          mountPath: "/mnt/csi/secret-idp"
          readOnly: true
        - name: secret-github-connector
          mountPath: "/mnt/csi/secret-github-connector"
          readOnly: true
        - name: secret-key-vault
          mountPath: "/mnt/csi/secret-key-vault"
          readOnly: true
        - name: secret-service-now
          mountPath: "/mnt/csi/secret-service-now"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cm-app-service
      - name: secret-gsuite
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-gsuite
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-redis
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-redis
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-app-db
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-app-db
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-app-service
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-app-service
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-idp
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-idp
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-key-vault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-key-vault
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-github-connector
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-github-connector
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-service-now
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-service-now
          nodePublishSecretRef:
            name: csi-secret-store-azure
      serviceAccountName: sa-choreo-default
