apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_8=Liveness probe not required
    checkov.io/skip2: CKV_K8S_9=Readiness probe not required
  labels:
    choreo.component: billing-console
  name: billing-console
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: billing-console
  template:
    metadata:
      labels:
        choreo.component: billing-console
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: choreocontrolplane.azurecr.io/choreoipaas/billing-console:latest
          name: billing-console
          envFrom:
            - configMapRef:
                name: env-billing-console
          ports:
            - containerPort: 8080
              name: bil-con-port
              protocol: TCP
          securityContext:
            runAsUser: 101
            runAsGroup: 101
      serviceAccountName: sa-choreo-default
