apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_40=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_43=Temporarily suppressing till fixing
    checkov.io/skip3: CKV_K8S_38=Temporarily suppressing till fixing
    checkov.io/skip4: CKV_K8S_28=Temporarily suppressing till fixing
    checkov.io/skip5: CKV_K8S_37=Temporarily suppressing till fixing
  labels:
    choreo.component: cp-graphql
  name: cp-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: cp-graphql
  strategy: {}
  template:
    metadata:
      labels:
        choreo.component: cp-graphql
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cp-graphql
          image: choreocontrolplane.azurecr.io/choreoipaas/choreo-cp-graphql:latest
          env:
          - name: APIM_REST_API_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: secret-cp-graphql
                key: APIM_REST_API_CONSUMER_SECRET
          - name: IDP_BACKEND_API_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secret-idp
                key: IDP_BACKEND_API_CLIENT_SECRET
          ports:
            - containerPort: 9090
              name: gql-port
            - containerPort: 9091      # To be used for readiness/liveness probes (internal)
              name: health
            - containerPort: 9092      # To be used for public health check (external)
              name: healthz
            - containerPort: 9095      # This is a temporary http gateway until the CORS issues fixed. https://github.com/ballerina-platform/ballerina-standard-library/issues/1475
              name: http-port
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /liveness
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 768Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 100
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config
              mountPath: /home/ballerina/Config.toml
              subPath: Config.toml
            - name: secret-cp-graphql
              mountPath: "/mnt/csi/secret-cp-graphql"
              readOnly: true
            - name: secret-idp
              mountPath: "/mnt/csi/secret-idp"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: cm-cp-graphql-config
        - name: secret-cp-graphql
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-cp-graphql
            nodePublishSecretRef:
              name: csi-secret-store-azure
        - name: secret-idp
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-idp
            nodePublishSecretRef:
              name: csi-secret-store-azure
      serviceAccountName: sa-choreo-default
