apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_25=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_38=The SA token is required for the linkerd to define service identity
  labels:
    choreo.component: crypto-key-service
  name: crypto-key-service
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: crypto-key-service
  template:
    metadata:
      labels:
        choreo.component: crypto-key-service
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: crypto-key-service
          imagePullPolicy: Always
          image: choreocontrolplane.azurecr.io/choreoipaas/choreo-crypto-key-service:latest
          envFrom:
            - secretRef:
                name: secret-crypto-key-service
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 250m
              memory: 400Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          ports:
            - containerPort: 9091
              name: http-port
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /cryptokeyservice/health
              port: http-port
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /cryptokeyservice/health
              port: http-port
          volumeMounts:
            - name: config
              mountPath: /home/ballerina/Config.toml
              subPath: Config.toml
            - name: crypto-service-ingress-tls-secret
              mountPath: /mnt/csi/crypto-service-ingress-tls-secret
            - name: secret-crypto-key-service
              mountPath: /mnt/csi/secret-crypto-key-service
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: cm-file-crypto-key-service
        - name: crypto-service-ingress-tls-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: crypto-service-ingress-tls-secret
            nodePublishSecretRef:
              name: csi-secret-store-azure
        - name: secret-crypto-key-service
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-crypto-key-service
            nodePublishSecretRef:
              name: csi-secret-store-azure
      serviceAccountName: sa-choreo-default
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              choreo.component: crypto-key-service
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              choreo.component: crypto-key-service
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
