apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_40=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_38=Temporarily suppressing till fixing
    checkov.io/skip3: CKV_K8S_28=Temporarily suppressing till fixing
    checkov.io/skip4: CKV_K8S_37=Temporarily suppressing till fixing
    checkov.io/skip5: CKV_K8S_20=Temporarily suppressing till fixing
  labels:
    choreo.component: datacollector
  name: datacollector
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: datacollector
  strategy: { }
  template:
    metadata:
      labels:
        choreo.component: datacollector
        antiaffinity: datacollector
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - env:
            - name: IDP_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: IDP_CLIENT_ID
                  name: env-idp-replica
            - name: IDP_ISSUER
              valueFrom:
                configMapKeyRef:
                  key: IDP_ISSUER
                  name: env-idp-replica
            - name: IDP_HOST
              valueFrom:
                configMapKeyRef:
                  key: IDP_HOST
                  name: env-idp-replica
            - name: IDP_JWKS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: IDP_JWKS_ENDPOINT
                  name: cm-idp-replica
            - name: EVENTHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secret-datacollector
                  key: EVENTHUB_CONNECTION_STRING
            - name: EVENTHUB_SHARED_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-datacollector
                  key: EVENTHUB_SHARED_ACCESS_KEY
          envFrom:
            - configMapRef:
                name: env-datacollector
          image: choreocontrolplane.azurecr.io/choreoipaas/data-collector:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10500
            runAsGroup: 10500
            readOnlyRootFilesystem: true
          name: datacollector
          volumeMounts:
            - name: secret-datacollector
              mountPath: "/mnt/csi/secret-datacollector"
              readOnly: true
          ports:
            - containerPort: 9090
              name: collector-port
              protocol: TCP
            - containerPort: 9091      # To be used for readiness/liveness probes (internal)
              name: health
              protocol: TCP
            - containerPort: 9092      # To be used for public health check (external)
              name: healthz
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /liveness
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 250m
              memory: 300Mi
      volumes:
        - name: secret-datacollector
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-datacollector
            nodePublishSecretRef:
              name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: antiaffinity
                    operator: In
                    values:
                      - datacollector
              topologyKey: kubernetes.io/hostname
