apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_43=Risk accepted
    checkov.io/skip2: CKV_K8S_25=Temporarily suppressing till fixing
  labels:
    choreo.component: delete-manager
    choreo.dataplane: "true"
  name: delete-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: delete-manager
  template:
    metadata:
      labels:
        choreo.component: delete-manager
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      automountServiceAccountToken: false
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: delete-manager
          imagePullPolicy: Always
          image: choreocontrolplane.azurecr.io/choreoipaas/delete-manager:latest
          resources:
            limits:
              cpu: 350m
              memory: 400Mi
            requests:
              cpu: 300m
              memory: 300Mi
          envFrom:
            - configMapRef:
                name: env-dp-delete-manager
          env:
            - name: MSSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-delete-manager
                  key: MSSQL_PASSWORD
            - name: ASB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secret-delete-manager
                  key: ASB_CONNECTION_STRING
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
              add: ["NET_RAW"]
          ports:
            - containerPort: 8000
              name: http-port
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /api/v1/healthz
              port: http-port
          livenessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /api/v1/healthz
              port: http-port
          volumeMounts:
            - name: secret-delete-manager
              mountPath: /mnt/csi/secret-delete-manager
              readonly: true
      volumes:
        - name: secret-delete-manager
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-delete-manager
            nodePublishSecretRef:
              name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
