apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_43=Risk Accepted
    checkov.io/skip2: CKV_K8S_8=Temporarily suppressing till fixing
    checkov.io/skip3: CKV_K8S_25=Temporarily suppressing till fixing
    checkov.io/skip4: CKV_K8S_22=Risk Accepted
  labels:
    choreo.component: deploymentoptimizer
  name: deploymentoptimizer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      choreo.component: deploymentoptimizer
  template:
    metadata:
      labels:
        choreo.component: deploymentoptimizer
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 500
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - env:
        - name: MODEL_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: secret-deploymentoptimizer
              key: MODEL_STORAGE_CONNECTION_STRING
        image: choreocontrolplane.azurecr.io/choreoipaas/deployment-optimizer-init:latest
        name: deploymentoptimizer-init
        volumeMounts:
        - name: deploymentoptimizer-models
          mountPath: "/home/python-ai/choreo-ai-deployment-optimizer/models"
        - name: deploymentoptimizer-model-metadata
          mountPath: "/home/python-ai/choreo-ai-deployment-optimizer/models.properties"
          subPath: "models.properties"
        - name: secret-deploymentoptimizer
          mountPath: "/mnt/csi/secret-deploymentoptimizer"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 10500
          runAsGroup: 10500
          capabilities:
            drop:
              - all
            add: [ "NET_RAW" ]
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
      containers:
      - image: choreocontrolplane.azurecr.io/choreoipaas/deployment-optimizer:latest
        name: deploymentoptimizer
        env:
          - name: AZURE_CHECKPOINT_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: secret-ai-eventhub-checkpoint
                key: AZURE_CHECKPOINT_STORAGE_CONNECTION_STRING
          - name: EVENT_HUBS_NAMESPACE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: secret-ai-eventhub-metrics
                key: EVENT_HUBS_NAMESPACE_CONNECTION_STRING
          - name: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secret-loggingapi
                key: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
          - name: TABLE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: secret-ai-storage-table
                key: TABLE_CONNECTION_STRING
        envFrom:
          - configMapRef:
              name: env-deployment-optimizer
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          exec:
            command:
              - ls
              - /home/python-ai/choreo-ai-deployment-optimizer/models/XGboost_model.sav
          initialDelaySeconds: 5
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: deploymentoptimizer-models
          mountPath: "/home/python-ai/choreo-ai-deployment-optimizer/models/"
        - name: deploymentoptimizer-application-properties
          mountPath: "/home/python-ai/choreo-ai-deployment-optimizer/config/"
        - name: secret-loggingapi
          mountPath: "/mnt/csi/secret-loggingapi"
          readOnly: true
        - name: secret-ai-storage-table
          mountPath: "/mnt/csi/secret-ai-storage-table"
          readOnly: true
        - name: secret-ai-eventhub-metrics
          mountPath: "/mnt/csi/secret-ai-eventhub-metrics"
          readOnly: true
        - name: secret-ai-eventhub-checkpoint
          mountPath: "/mnt/csi/secret-ai-eventhub-checkpoint"
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 10500
          runAsGroup: 10500
          capabilities:
            drop:
              - all
            add: [ "NET_RAW" ]
      volumes:
      - name: deploymentoptimizer-models
        emptyDir: {}
      - name: deploymentoptimizer-model-metadata
        configMap:
          defaultMode: 420
          name: cm-deploymentoptimizer-model-metadata
      - name: deploymentoptimizer-application-properties
        configMap:
          defaultMode: 420
          name: cm-deploymentoptimizer
      - name: secret-loggingapi
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-loggingapi
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-ai-storage-table
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-ai-storage-table
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-ai-eventhub-metrics
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-ai-eventhub-metrics
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-ai-eventhub-checkpoint
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-ai-eventhub-checkpoint
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-deploymentoptimizer
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-deploymentoptimizer
          nodePublishSecretRef:
            name: csi-secret-store-azure
      restartPolicy: Always
