apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_25=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_38=The SA token is required for the linkerd to define service identity
  labels:
    choreo.component: dp-secret-manager
    choreo.dataplane: "true"
  name: dp-secret-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: dp-secret-manager
  template:
    metadata:
      labels:
        choreo.component: dp-secret-manager
        antiaffinity: dp-secret-manager
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      automountServiceAccountToken: true
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dp-secret-manager
          imagePullPolicy: Always
          image: choreocontrolplane.azurecr.io/choreoipaas/dp-secret-manager:latest
          resources:
            limits:
              cpu: 350m
              memory: 400Mi
            requests:
              cpu: 300m
              memory: 300Mi
          envFrom:
            - configMapRef:
                name: env-dp-secret-manager
          env:
          - name: AZURE_KEYVAULT_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: secret-dp-secret-manager
                key: AZURE_KEYVAULT_CLIENT_ID
          - name: AZURE_KEYVAULT_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secret-dp-secret-manager
                key: AZURE_KEYVAULT_CLIENT_SECRET
          - name: AZURE_KEYVAULT_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: secret-dp-secret-manager
                key: AZURE_KEYVAULT_TENANT_ID
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
              add: [ "NET_RAW" ]
          ports:
            - containerPort: 8000
              name: http-port
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /api/v1/healthz
              port: http-port
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /api/v1/healthz
              port: http-port
          volumeMounts:
          - name: secret-dp-secret-manager
            mountPath: /mnt/csi/secret-dp-secret-manager
            readonly: true
      volumes:
      - name: secret-dp-secret-manager
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-dp-secret-manager
          nodePublishSecretRef:
            name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: antiaffinity
                  operator: In
                  values:
                  - dp-secret-manager
              topologyKey: kubernetes.io/hostname
