apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    choreo.component: dp-secret-manager
    choreo.dataplane: true
  name: dp-secret-manager
spec:
  replicas: 0
  selector:
    matchLabels:
      choreo.component: dp-secret-manager
  template:
    metadata:
      labels:
        choreo.component: dp-secret-manager
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dp-secret-manager
          imagePullPolicy: Always
          image: choreocontrolplane.azurecr.io/choreoipaas/dp-secret-manager:latest
          resources:
            limits:
              cpu: 350m
              memory: 400Mi
            requests:
              cpu: 300m
              memory: 300Mi
          env:
          - name: AZURE_KEYVAULT_CLIENT_ID
            valueFrom:
              secretKeyRef: secret-sm
              key: AZURE_KEYVAULT_CLIENT_ID
          - name: AZURE_KEYVAULT_CLIENT_SECRET
            valueFrom:
              secretKeyRef: secret-sm
              key: AZURE_KEYVAULT_CLIENT_SECRET
          - name: AZURE_KEYVAULT_TENANT_ID
            valueFrom:
              secretKeyRef: secret-sm
              key: AZURE_KEYVAULT_TENANT_ID
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8000
              name: http-port
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /api/v1/healthz
              port: http-port
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /api/v1/healthz
              port: http-port
      volumeMounts:
      - mountPath: /config/config.json
        name: config
        subPath: config.json
      - name: secret-sm
        mountPath: /mnt/csi/secret-sm
        readonly: true
      volumes:
      - name: config
        configMap: 
          name: cm-dp-secret-manager
      - name: secret-sm
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-dp-secret-manager
          nodePublishSecretRef:
            name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
