apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_40=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_43=Temporarily suppressing till fixing
    checkov.io/skip3: CKV_K8S_38=Temporarily suppressing till fixing
    checkov.io/skip4: CKV_K8S_28=Temporarily suppressing till fixing
    checkov.io/skip5: CKV_K8S_37=Temporarily suppressing till fixing
    checkov.io/skip6: CKV_K8S_20=Temporarily suppressing till fixing
    checkov.io/skip7: CKV_K8S_31=Temporarily suppressing till fixing
    checkov.io/skip8: CKV_K8S_29=Temporarily suppressing till fixing
  labels:
    choreo.component: obsapi
  name: obsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: obsapi
  template:
    metadata:
      labels:
        choreo.component: obsapi
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        # --------------------------------------------------------
          # INTERNAL
        - name: AST_CACHE_MAX_SIZE_MB
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: AST_CACHE_MAX_SIZE_MB
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: LOG_LEVEL
        - name: SKIP_AUTH
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: SKIP_AUTH
          # NEGOTIATOR
        - name: NEGOTIATOR_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: NEGOTIATOR_GRPC_ADDRESS
          # APPSERVICE
        - name: APPSERVICE_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: APPSERVICE_GRPC_ADDRESS
          # IDP
        - name: IDP_URL
          valueFrom:
            configMapKeyRef:
              name: cm-idp-replica
              key: IDP_URL
        - name: IDP_TOKEN_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: cm-idp-replica
              key: IDP_TOKEN_ENDPOINT
        - name: IDP_JWKS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: cm-idp-replica
              key: IDP_JWKS_ENDPOINT
        - name: IDP_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: cm-idp-replica
              key: IDP_CLIENT_ID
          # AZURE ADX
        - name: AZURE_ADX_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: AZURE_ADX_CLIENT_ID
        - name: AZURE_ADX_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: AZURE_ADX_ENDPOINT
        - name: AZURE_ADX_DB
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: AZURE_ADX_DB
        - name: AZURE_ADX_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: AZURE_ADX_TENANT_ID
        - name: AZURE_ADX_METRIC_TABLE
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: AZURE_ADX_METRIC_TABLE
        - name: AZURE_ADX_TRACE_TABLE
          valueFrom:
            configMapKeyRef:
              name: cm-obsapi
              key: AZURE_ADX_TRACE_TABLE
        - name: AZURE_ADX_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-obsapi
              key: AZURE_ADX_CLIENT_SECRET
        # --------------------------------------------------------
        image: choreocontrolplane.azurecr.io/choreoipaas/observability-api:latest
        securityContext:
          runAsUser: 100
          runAsGroup: 1000
          readOnlyRootFilesystem: true
        name: obsapi
        ports:
        - containerPort: 9095
          name: obsapi-port
          protocol: TCP
        - containerPort: 9096
          name: grpc-port
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            port: obsapi-port
            path: /readiness
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            port: obsapi-port
            path: /liveness
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /mnt/csi/secret-obsapi
          name: secret-obsapi
          readOnly: true
      volumes:
      - name: secret-obsapi
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-obsapi
          nodePublishSecretRef:
            name: csi-secret-store-azure
      serviceAccountName: sa-choreo-default
