apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip2: CKV_K8S_43=Temporarily suppressing till fixing
    checkov.io/skip7: CKV_K8S_31=Temporarily suppressing till fixing
    checkov.io/skip8: CKV_K8S_29=Temporarily suppressing till fixing
  labels:
    choreo.component: sys-obsapi
  name: sys-obsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: sys-obsapi
  strategy: {}
  template:
    metadata:
      labels:
        choreo.component: sys-obsapi
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: b7a_log_level
              valueFrom:
                configMapKeyRef:
                  key: B7A_LOG_LEVEL
                  name: cm-loglevel-sys-obsapi
            - name: IDP_ISSUER
              valueFrom:
                configMapKeyRef:
                  key: IDP_ISSUER
                  name: env-idp-replica
            - name: IDP_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: IDP_CLIENT_ID
                  name: env-idp-replica
            - name: IDP_HOST
              valueFrom:
                configMapKeyRef:
                  key: IDP_HOST
                  name: env-idp-replica
            - name: IDP_JWKS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: IDP_JWKS_ENDPOINT
                  name: cm-idp-replica
            - name: AZURE_LA_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  key: AZURE_ACTIVEDIRECTORY_TENANT_ID
                  name: cm-sys-obsapi
            - name: AZURE_LA_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: AZURE_ACTIVEDIRECTORY_CLIENT_ID
                  name: env-sys-obsapi
            - name: AZURE_LA_WORKSPACE_ID
              valueFrom:
                configMapKeyRef:
                  key: LOG_WORKSPACE_ID
                  name: env-loganalytics-replica
            - name: NEGOTIATOR_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: NEGOTIATOR_GRPC_ADDRESS
                  name: cm-sys-obsapi
            - name: APP_SERVICE_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: APP_SERVICE_GRPC_ADDRESS
                  name: cm-sys-obsapi
            - name: AZURE_LA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-sys-obsapi
                  key: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
          envFrom:
            - configMapRef:
                name: env-k8sservice-replica
          image: choreocontrolplane.azurecr.io/choreoipaas/choreo-sys-obsapi:latest
          securityContext:
            runAsUser: 10500
            runAsGroup: 10500
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - all
          name: sys-obsapi
          volumeMounts:
          - name: secret-sys-obsapi
            mountPath: "/mnt/csi/secret-sys-obsapi"
            readOnly: true
          ports:
            - containerPort: 9098
              name: sys-obsapi-port
              protocol: TCP
            - containerPort: 9096      # To be used for readiness/liveness probes (internal)
              name: health
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 60
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /liveness
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 300m
              memory: 512Mi
      volumes:
      - name: secret-sys-obsapi
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-sys-obsapi
          nodePublishSecretRef:
            name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
