apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_38=The SA token is required for the linkerd to define service identity
  labels:
    choreo.component: testbase
  name: testbase
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: testbase
  strategy: {}
  template:
    metadata:
      labels:
        choreo.component: testbase
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
        - name: IDP_ISSUER
          valueFrom:
            configMapKeyRef:
              key: IDP_ISSUER
              name: env-idp-replica
        - name: IDP_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: IDP_CLIENT_ID
              name: env-idp-replica
        - name: IDP_HOST
          valueFrom:
            configMapKeyRef:
              key: IDP_HOST
              name: env-idp-replica
        - name: IDP_JWKS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: IDP_JWKS_ENDPOINT
              name: cm-idp-replica
        - name: CHOREO_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_NAME
              name: cm-choreo-testbase-db
        - name: CHOREO_DB_MAX_POOL
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_MAX_POOL
              name: cm-choreo-testbase-db    
        - name: CHOREO_APP_DEPLOYER_SERVICE_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: CHOREO_APP_DEPLOYER_SERVICE_GRPC_ADDRESS
              name: cm-testbase
        - name: CHOREO_WS_MANAGER_SERVICE_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: CHOREO_WS_MANAGER_SERVICE_GRPC_ADDRESS
              name: cm-testbase
        - name: CHOREO_APP_SERVICE_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: CHOREO_APP_SERVICE_GRPC_ADDRESS
              name: cm-testbase
        - name: CHOREO_DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: secret-testbase-db
             key: CHOREO_DB_PASSWORD
        envFrom:
        - configMapRef:
            name: env-choreo-testbase-db
        image: choreocontrolplane.azurecr.io/choreoipaas/choreo-testbase:v0.7.2
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 12000
          runAsGroup: 12000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - all
        name: testbase
        volumeMounts:
        - name: secret-testbase-db
          mountPath: "/mnt/csi/secret-testbase-db"
          readOnly: true
        readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
             port: health
             path: /health
        livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
             port: health
             path: /health
        ports:
        - containerPort: 9090
          name: tb-sport
          protocol: TCP
        - containerPort: 9091
          name: health
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 300m
            memory: 512Mi
      volumes:
      - name: secret-testbase-db
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-testbase-db
          nodePublishSecretRef:
            name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
