apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_25=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_22=Temporarily suppressing till fixing
    checkov.io/skip3: CKV_K8S_38=The SA token is required for the linkerd to define service identity
  labels:
    choreo.component: test-assistant
  name: test-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: test-assistant
  template:
    metadata:
      labels:
        choreo.component: test-assistant
        antiaffinity: test-assistant
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: choreocontrolplane.azurecr.io/choreoipaas/test-assistant:latest
          name: test-assistant
          envFrom:
            - configMapRef:
                name: env-test-assistant
            - configMapRef:
                name: cm-test-assistant
            - secretRef:
                name: secret-test-assistant
          volumeMounts:
            - name: secret-test-assistant
              mountPath: "/mnt/csi/secret-test-assistant"
              readOnly: true
            - mountPath: "/temp-data-dir"
              name: temp-data-dir
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: ta-port
              path: /readiness
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: ta-port
              path: /liveness
          resources:
            limits:
              cpu: 500m
              memory: 2300Mi
            requests:
              cpu: 400m
              memory: 2200Mi
          ports:
            - containerPort: 5000
              name: ta-port
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10500
            runAsGroup: 10500
            capabilities:
              drop:
                - all
              add:
                - NET_RAW
      volumes:
        - name: temp-data-dir
          emptyDir: {}
        - name: secret-test-assistant
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-test-assistant
            nodePublishSecretRef:
              name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: antiaffinity
                    operator: In
                    values:
                      - test-assistant
              topologyKey: kubernetes.io/hostname
