apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    checkov.io/skip1: CKV_K8S_40=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_43=Temporarily suppressing till fixing
    checkov.io/skip3: CKV_K8S_38=Temporarily suppressing till fixing
    checkov.io/skip4: CKV_K8S_28=Temporarily suppressing till fixing
    checkov.io/skip5: CKV_K8S_37=Temporarily suppressing till fixing
  labels:
    choreo.component: workspace-manager
  name: workspace-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: workspace-manager
  template:
    metadata:
      labels:
        choreo.component: workspace-manager
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: choreocontrolplane.azurecr.io/choreoipaas/workspace-manager:latest
        name: workspace-manager
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-redis
              key: REDIS_PASSWORD
        - name: AZURE_INSIGHTS_KEY
          valueFrom:
            secretKeyRef:
              key: AZURE_INSIGHTS_KEY
              name: secret-azure-insights
        envFrom:
        - configMapRef:
            name: common-env-variables
        - configMapRef:
            name: env-workspace-manager
        ports:
        - containerPort: 8080
          name: grpc-port
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "bin/grpc_health_probe -addr=:8080 2>&1 | grep -q SERVING"]
          initialDelaySeconds: 20
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /workspace-manager.yaml
          name: config
          subPath: workspace-manager.yaml
        - mountPath: /apps
          name: pvc-userappstorage
        - name: secret-redis
          mountPath: "/mnt/csi/secret-redis"
          readOnly: true
        - mountPath: /mnt/csi/secret-azure-insights
          name: secret-azure-insights
          readOnly: true
        - name: secret-azure-storage-account
          mountPath: "/mnt/csi/secret-azure-storage-account"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cm-workspace-manager
      - name: pvc-userappstorage
        persistentVolumeClaim:
          claimName: pvc-userappstorage
      - name: secret-redis
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-redis
          nodePublishSecretRef:
            name: csi-secret-store-azure
      - name: secret-azure-insights
        csi:
          driver: secrets-store.csi.k8s.io
          nodePublishSecretRef:
            name: csi-secret-store-azure
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-azure-insights
      - name: secret-azure-storage-account
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secret-azure-storage-account
          nodePublishSecretRef:
            name: csi-secret-store-azure
      serviceAccountName: sa-choreo-workspace-manager
