[server]
port="8080"

[dataplane]
namespace="apk"

[apim]
apimHost="{{.APIM_HOST}}"
apimUsername="choreo_dev_apim_admin"
configDeployerHost="{{.CONFIG_DEPLOYER_HOST}}"

[mizzen]
mizzenHost="http://dp-mizzen:8080"

[database]
dbHost="{{.GW_ADAPTER_DB_HOST}}"
dbUsername="choreo_gateway_adapter_db_user"

[logger]
level="{{.LOG_LEVEL}}"
