apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runners
spec:
  replicas: 1
  template:
    metadata: {}
    spec:
      organization: choreo-userapps-gitops-prod
      image: choreocontrolplane.azurecr.io/choreoipaas/gh-runner:latest
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: 1500m
          memory: 1Gi
      tolerations:
        - effect: NoSchedule
          key: ghrunner
          operator: Exists
      nodeSelector:
        execution-mode: ghrunner
      workDir: /home/runner/workspace
      env:
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: LOG_DEBUG_DISABLED
          value: "true"
      labels:
        - choreo-custom-runner
      dockerdContainerResources:
        limits:
          cpu: "1"
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 2Gi
