resources:
  - frontend.yaml
  - negotiator.yaml
  - obsapi.yaml
  - telemetry.yaml
  - loggingapi.yaml
  - programanalyzer.yaml
  - perfanalyzer-estimator.yaml
  - datamapper.yaml
  - testbase.yaml
  - api-server.yaml
  - app-deployer.yaml
  - app-service.yaml
  - workspace-manager.yaml
  - email-service.yaml
  - connectords.yaml
  - sys-obsapi.yaml
  - apim-service.yaml
  - language-server.yaml
