apiVersion: apps/v1
kind: Deployment
metadata:
  name: choreo-alerting-api
  namespace: choreo-observability
  labels:
    choreo.component: choreo-alerting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: choreo-alerting-api
  template:
    metadata:
      labels:
        choreo.component: choreo-alerting-api
    spec:
      serviceAccountName: choreo-alerting-api
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: choreo-alerting-api
          image: choreocontrolplane.azurecr.io/choreoipaas/choreo-alerting-api:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 10500
            runAsGroup: 10500
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          envFrom:
            - configMapRef:
                name: choreo-alerting-api-conf
            - secretRef:
                name: secret-alert-api
          volumeMounts:
            - name: alerting-api-spc
              mountPath: "/mnt/secrets"
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 800Mi
            requests:
              cpu: 250m
              memory: 500Mi
      restartPolicy: Always
      volumes:
        - name: alerting-api-spc
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-alert-api
            nodePublishSecretRef:
              name: csi-secret-store-azure
