apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    choreo.component: choreo-connect-deployment-internal
  name: choreo-connect-deployment-internal
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: choreo-connect-deployment-internal
  targetCPUUtilizationPercentage: 75