[privateDataPlane]
enabled = true

[keystore]
  certPath = "/home/wso2/security/keystore/global-adapter.pem"
  keyPath = "/home/wso2/security/keystore/global-adapter.key"

[truststore]
  location = "/home/wso2/security/truststore"

# Control plane's connection details
[controlPlane]
  serviceUrl = "http://choreo-am-service:9763"
  username = "{{.CONTROLPLANE_USERNAME}}"
  password = "$env{cp_admin_pwd}"

[database]
  name = 'choreo_global_adapter_db'
  username = 'choreo_global_adapter_db_user'
  password = '$env{ga_db_pwd}'
  host = '{{.DB_HOST}}'
  port = 1433
  validationQuery = 'select 1'
  [database.pooloptions]
  maxActive = 500
  maxIdle = 30

[gAAPIServer]
  host = '0.0.0.0'
  port = '9745'
