# --------------------------------------------------------------------
# Copyright (c) 2021, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------

# Deployment for Adapter

apiVersion: apps/v1
kind: Deployment
metadata:
  name: choreo-connect-adapter
  annotations:
    checkov.io/skip1: CKV_K8S_43=Temporarily suppressing as this requires CICD level changes
    checkov.io/skip2: CKV_K8S_25=Temporarily suppressing as there is no defined fix for this by the Bridgecrew
spec:
  replicas: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      choreo.component: choreo-connect-adapter
  template:
    metadata:
      labels:
        choreo.component: choreo-connect-adapter
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10500
        runAsGroup: 10500
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: choreo-connect-adapter
          volumeMounts:
            - mountPath: /home/wso2/security/keystore/mg.key
              name: secret-mgw-keystore
              readOnly: true
              subPath: ADAPTER_KEYSTORE_KEY
            - mountPath: /home/wso2/security/keystore/mg.pem
              name: secret-mgw-keystore
              readOnly: true
              subPath: ADAPTER_KEYSTORE_CERTIFICATE
            - mountPath: /home/wso2/security/truststore/controlplane.pem
              name: secret-mgw-truststore
              readOnly: true
              subPath: CONTROL_PLANE_CERTIFICATE
            - mountPath: /home/wso2/security/truststore/mg.pem
              name: secret-mgw-truststore
              readOnly: true
              subPath: ADAPTER_TRUSTSTORE_CERTIFICATE
            - mountPath: /home/wso2/security/truststore/global-adapter.pem
              name: global-adapter-keystore-vol
              subPath: global-adapter.pem
            - mountPath: /home/wso2/security/truststore/consul/consul-agent-ca.pem
              name: secret-mgw-adapter-consul
              readOnly: true
              subPath: CONSUL_AGENT_CERTIFICATE
            - mountPath: /home/wso2/security/truststore/consul/local-dc-client-consul-0-key.pem
              name: secret-mgw-adapter-consul
              readOnly: true
              subPath: CONSUL_DC_CLIENT_KEY
            - mountPath: /home/wso2/security/truststore/consul/local-dc-client-consul-0.pem
              name: secret-mgw-adapter-consul
              readOnly: true
              subPath: CONSUL_DC_CLIENT_CERTIFICATE
            - mountPath: /home/wso2/conf
              name: adapter-config
            - name: secret-mgw
              mountPath: /mnt/csi/secret-mgw
              readOnly: true
            - name: secret-asb
              mountPath: /mnt/csi/secret-asb
              readOnly: true
          image: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-adapter:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
              add: ["NET_RAW"]
          envFrom:
          - configMapRef:
              name: cm-feature-flags
          env:
            - name: ADAPTER_PRIVATE_KEY_PATH
              value: "/home/wso2/security/keystore/mg.key"
            - name: ADAPTER_PUBLIC_CERT_PATH
              value: "/home/wso2/security/keystore/mg.pem"
            - name: adapter_admin_pwd
              valueFrom:
                secretKeyRef:
                  key: ADAPTER_ADMIN_PASSWORD
                  name: secret-mgw
            - name: enforcer_managemenet_password
              valueFrom:
                secretKeyRef:
                  key: ENFORCER_MANAGEMENT_PASSWORD
                  name: secret-mgw
            - name: cp_admin_pwd
              valueFrom:
                secretKeyRef:
                  key: SUPER_ADMIN_PSWD
                  name: secret-apim
            - name: ASB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secret-asb
                  key: ASB_CONNECTION_STRING
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "750m"
          ports:
            - containerPort: 18000
            - containerPort: 9843
          livenessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            exec:
              command: [ "sh", "check_health.sh" ]
            initialDelaySeconds: 8
            periodSeconds: 5
      volumes:
        - name: adapter-config
          configMap:
            name: mgw-adapter-enforcer-conf
        - name: global-adapter-keystore-vol
          configMap:
            name: global-adapter-keystore-vol
        - name: secret-mgw
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-mgw
            nodePublishSecretRef:
              name: csi-secret-store-azure
        - name: secret-mgw-keystore
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-mgw-keystore
            nodePublishSecretRef:
              name: csi-secret-store-azure
        - name: secret-mgw-truststore
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-mgw-truststore
            nodePublishSecretRef:
              name: csi-secret-store-azure
        - name: secret-mgw-adapter-consul
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-mgw-adapter-consul
            nodePublishSecretRef:
              name: csi-secret-store-azure
        - name: secret-asb
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-asb
            nodePublishSecretRef:
              name: csi-secret-store-azure
      restartPolicy: Always
