# -------------------------------------------------------------------------------------
#
# Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: choreo-appdev-sts-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    tenantId: da76d684-740f-4d94-8717-9d5fb21dd1f9
    keyVaultName: dev-csi-64
    objects: |
      array:
        - |
          objectName: dp-sts-client-secret-encryption-key
          objectType: secret
          objectAlias: DP_STS_CLIENT_SECRET_ENCRYPTION_KEY
          objectVersion: "{{.CHOREO_STS_CLIENT_SECRET_ENCRYPTION_KEY}}"
        - |
          objectName: redis-cluster-password-tmp
          objectType: secret
          objectAlias: CHOREO_STS_REDIS_PASSWORD
          objectVersion: "{{.CHOREO_STS_REDIS_PASSWORD}}"
