apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-dp-kv-resolver
spec:
  secretObjects:
    - secretName: secret-dp-kv-resolver
      type: Opaque
      data:
        - objectName: AZURE_KEYVAULT_CLIENT_ID
          key: AZURE_KEYVAULT_CLIENT_ID
        - objectName: AZURE_KEYVAULT_CLIENT_SECRET
          key: AZURE_KEYVAULT_CLIENT_SECRET
        - objectName: AZURE_KEYVAULT_TENANT_ID
          key: AZURE_KEYVAULT_TENANT_ID
  parameters:
    objects: |
      array:
        - |
          objectName: {{.AZURE_KEYVAULT_CLIENT_ID_OBJ_NAME | default "dp-secret-manager-kv-client-id"}}
          objectType: secret
          objectAlias: AZURE_KEYVAULT_CLIENT_ID
          objectVersion: "{{.AZURE_KEYVAULT_CLIENT_ID}}"
        - |
          objectName: {{.AZURE_KEYVAULT_CLIENT_SECRET_OBJ_NAME | default "dp-secret-manager-keyvault-client-secret"}}
          objectType: secret
          objectAlias: AZURE_KEYVAULT_CLIENT_SECRET
          objectVersion: "{{.AZURE_KEYVAULT_CLIENT_SECRET}}"
        - |
          objectName: {{.AZURE_KEYVAULT_TENANT_ID_OBJ_NAME | default "tenant-id"}}
          objectType: secret
          objectAlias: AZURE_KEYVAULT_TENANT_ID
          objectVersion: "{{.AZURE_KEYVAULT_TENANT_ID}}"
