apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: alert-configuration-service
  name: alert-configuration-service
spec:
  ports:
    - name: an-port
      port: 8080
      targetPort: an-port
  selector:
    choreo.component: alert-configuration-service
