apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: app-dev-user-mgt-service
  name: app-dev-user-mgt-service
  namespace: choreo-system
spec:
  ports:
    - name: service-port
      port: 8080
      protocol: TCP
      targetPort: service-port
  selector:
    choreo.component: app-dev-user-mgt-service
