apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: app-dev-authorization-service
  name: app-dev-authorization-service
  namespace: choreo-system
spec:
  ports:
    - name: service-port
      port: 9090
      protocol: TCP
      targetPort: service-port
    - name: health-port
      port: 9091
      protocol: TCP
      targetPort: health-port
  selector:
    choreo.component: app-dev-authorization-service
