apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: audit-logging
  name: audit-logging
spec:
  ports:
    - name: service-port
      port: 8080
      targetPort: service-port
    - name: listener-port
      port: 8090
      targetPort: listener-port
    - name: health-port
      port: 9090
      targetPort: health-port

  selector:
    choreo.component: audit-logging
