apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: cio-query-api-service
  name: cio-query-api-service
spec:
  ports:
    - name: service-port
      port: 4000
      targetPort: service-port
  selector:
    choreo.component: cio-query-api-service
