apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: connection-service
  name: connection-service
spec:
  ports:
    - name: http-port
      port: 9000
      targetPort: http-port
    - name: healthz
      port: 9001
      targetPort: healthz

  selector:
    choreo.component: connection-service
