apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: connectords
  name: connectords
spec:
  ports:
    - name: cds-sport
      port: 9090
      targetPort: cds-sport
  selector:
    choreo.component: connectords
