apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: cp-ris
  name: cp-ris
spec:
  ports:
    - name: service-port
      port: 9090
      targetPort: service-port
    - name: health-port
      port: 9091
      targetPort: health-port

  selector:
    choreo.component: cp-ris
