apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: cp-sis
  name: cp-sis
spec:
  ports:
    - name: health-port
      port: 9090
      targetPort: health-port
    - name: internal-port
      port: 9091
      targetPort: internal-port
    - name: public-port
      port: 9092
      targetPort: public-port

  selector:
    choreo.component: cp-sis
