apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: devops-portal
  name: devops-portal
spec:
  ports:
    - name: do-portal-port
      port: 8001
      targetPort: do-portal-port
  selector:
    choreo.component: devops-portal
