apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: devops-portal-api
  name: devops-portal-api
spec:
  ports:
    - name: devops-portal-api-port
      port: 8089
      targetPort: devops-portal-api-port

  selector:
    choreo.component: devops-portal-api
