apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: dp-cloud-manager
    choreo.dataplane: "true"
  name: dp-cloud-manager
spec:
  ports:
    - name: dp-cloud-manager-port
      port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    choreo.component: dp-cloud-manager
