apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: image-share-service
  name: image-share-service
spec:
  ports:
    - name: http-port
      port: 9090
      targetPort: http-port

  selector:
    choreo.component: image-share-service
