apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: marketplace
  name: marketplace
spec:
  ports:
    - name: http-port
      port: 9090
      targetPort: http-port
    - name: healthz
      port: 9092
      targetPort: healthz

  selector:
    choreo.component: marketplace
