apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: marketplace
  name: marketplace
spec:
  ports:
    - name: marketplace-port
      port: 9090
      targetPort: marketplace-port
    - name: healthz
      port: 9092
      targetPort: healthz
    - name: dependecy-config-port
      port: 9091
      targetPort: dependecy-config-port

  selector:
    choreo.component: marketplace
