apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: usagehandler-service
  name: usagehandler-service
spec:
  ports:
    - name: grpc-port
      port: 9090
      targetPort: grpc-port
    - name: healthz
      port: 9092
      targetPort: healthz

  selector:
    choreo.component: metered-usage-handler-service
