apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: moesif-service
  name: moesif-service
spec:
  ports:
    - name: internal-http
      port: 8080
      targetPort: internal-http
    - name: external-http
      port: 8081
      targetPort: external-http
    - name: healthz
      port: 9092
      targetPort: healthz

  selector:
    choreo.component: moesif-service
