apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: obsapi
  name: obsapi
spec:
  ports:
    - name: obsapi-port
      port: 9095
      targetPort: obsapi-port
    - name: grpc-port
      port: 9096
      targetPort: grpc-port
  selector:
    choreo.component: obsapi
