apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: obsmanager
  name: obsmanager
spec:
  ports:
    - name: obsmanager-port
      port: 9094
      targetPort: obsmanager-port
  selector:
    choreo.component: obsmanager
