apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: pdp-uptime
  name: pdp-uptime
spec:
  ports:
    - name: pdp-manager-port
      port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    choreo.component: pdp-manager
