apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: perfanalyzer-estimator
  name: perfanalyzer-estimator
spec:
  ports:
    - name: perfan-port
      port: 5005
      protocol: TCP
      targetPort: perfan-port
  selector:
    choreo.component: perfanalyzer-estimator
