apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: workspace-manager
  name: workspace-manager
spec:
  ports:
    - name: workspace-manager-port
      port: 8080
      protocol: TCP
      targetPort: grpc-port
  selector:
    choreo.component: workspace-manager
