apiVersion: v1
kind: Service
metadata:
  name: log-enricher-service
  labels:
    app: log-enricher
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: log-enricher-port
      protocol: TCP
      name: log-enricher-port
  selector:
    app: log-enricher
