# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

configMapGenerator:
  - name: testgpt-cm-file
    behavior: create
    files:
      - testgpt/Config.toml
  - name: testgpt-cm
    behavior: create
    literals:
      - AZURE_LA_TENANT_ID=da76d684-740f-4d94-8717-9d5fb21dd1f9
  - name: env-obs-assistant-cm
    behavior: create
    literals:
      - LOG_API_URL={{.LOG_API_URL}}
      - SYS_METRICS_API_URL={{.SYS_METRICS_API_URL}}
      - APP_METRICS_API_URL={{.APP_METRICS_API_URL}}
      - AZURE_OPENAI_ENDPOINT={{.AZURE_OPENAI_ENDPOINT}}
  - name: env-insights-assistant-cm
    behavior: create
    literals:
      - INSIGHT_API_URL={{.INSIGHT_API_URL}}
      - CIO_API_URL={{.CIO_API_URL}}
      - CP_GRAPHQL_API_URL={{.CP_GRAPHQL_API_URL}}
      - CP_API_URL={{.CP_API_URL}}
      - AZURE_OPENAI_ENDPOINT={{.AZURE_OPENAI_ENDPOINT}}
      - REGION={{.REGION}}
  - name: env-docs-assistant
    behavior: create
    literals:
      - AZURE_OPENAI_ENDPOINT={{.AZURE_OPENAI_ENDPOINT}}
      - CP_AZURE_OPENAI_ENDPOINT={{.CP_AZURE_OPENAI_ENDPOINT | default "https://eastus2.api.cognitive.microsoft.com/" }}
      - ZILLIZ_CLOUD_URI={{.ZILLIZ_CLOUD_URI}}
  - name: env-marketplace-assistant-cm
    behavior: create
    literals:
      - ZILLIZ_CLOUD_URI={{.ZILLIZ_CLOUD_URI}}
      - AZURE_ENDPOINT={{.AZURE_ENDPOINT}}
      - AZURE_CHAT_DEPLOYMENT={{.AZURE_CHAT_DEPLOYMENT}}
      - AZURE_CHAT_VERSION={{.AZURE_CHAT_VERSION}}
      - AZURE_EMBEDDING_DEPLOYMENT={{.AZURE_EMBEDDING_DEPLOYMENT}}
      - SOURCE_PLATFORM={{.SOURCE_PLATFORM}}
      - COLLECTION_NAME={{.COLLECTION_NAME}}
  - name: env-ai-copilot-cm
    behavior: create
    literals:
      - AZURE_OPENAI_ENDPOINT={{.AZURE_OPENAI_ENDPOINT}}
      - CHOREO_JWT_AUDIENCE={{.CHOREO_JWT_AUDIENCE}}
      - CHOREO_JWT_JWKS_URL={{.CHOREO_JWT_JWKS_URL}}
      - REDIS_HOST_URL={{.REDIS_HOST_URL}}
      - DOCS_ASSISTANT_ENABLED={{.DOCS_ASSISTANT_ENABLED}}
      - MARKETPLACE_ASSISTANT_ENABLED={{.MARKETPLACE_ASSISTANT_ENABLED}}
      - TEST_ASSISTANT_ENABLED={{.TEST_ASSISTANT_ENABLED}}
      - RUNTIME_METRICS_ASSISTANT_ENABLED={{.RUNTIME_METRICS_ASSISTANT_ENABLED}}
