# --------------------------------------------------------------------
# Copyright (c) 2022, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------

extensions:
  oauth2client:
    client_id: ${STS_CLIENT_ID}
    client_secret: ${STS_CLIENT_SECRET}
    token_url: ${STS_TOKEN_URL}
    endpoint_params:
      audience: ${STS_CLIENT_ID}
  health_check/liveness:
    endpoint: "0.0.0.0:13133"
    path: "/liveness"
  health_check/readiness:
    endpoint: "0.0.0.0:13134"
    path: "/readiness"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  k8smetadataoverlay:
  filter:
    metrics:
      include:
        match_type: regexp
        resource_attributes:
          - key: namespace.flow
            value: (dp-.*|.*-->dp-.*)

exporters:
  otlp:
    endpoint: ${OTLP_CP_ENDPOINT}
    auth:
      authenticator: oauth2client
    tls:
      insecure: false

service:
  extensions: [oauth2client, health_check/liveness, health_check/readiness]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [k8smetadataoverlay, filter]
      exporters: [otlp]
