helmCharts:
  - name: reflector
    valuesInline:
      fullnameOverride: reflector
      image:
        repository: choreocontrolplane.azurecr.io/emberstack/kubernetes-reflector
    releaseName: reflector
    namespace: reflector
    version: 7.1.288
    repo: oci://choreocontrolplane.azurecr.io/helm

resources:
  - namespace.yaml
  - secret-provider-class.yaml

namespace: reflector
