apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: reflector-secrets
annotations:
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "^dp-builds-.+"
spec:
  secretObjects:
    - secretName: choreo-image-pull-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: mi-dist-and-mi-blob-ad-application-image-pull-secret
          key: .dockerconfigjson
  parameters:
    objects: |
      array:
        - |
          objectName: mi-dist-and-mi-blob-ad-application-image-pull-secret
          objectType: secret
          objectAlias: mi-dist-and-mi-blob-ad-application-image-pull-secret
          objectVersion: "{{.mi-dist-and-mi-blob-ad-application-image-pull-secret}}"
