apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: reflector-secrets
spec:
  secretObjects:
    - secretName: choreo-image-pull-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: mi-dist-and-mi-blob-ad-application-password
          key: .dockerconfigjson
  parameters:
    objects: |
      array:
        - |
          objectName: mi-dist-and-mi-blob-ad-application-password
          objectType: secret
          objectAlias: mi-dist-and-mi-blob-ad-application-password
          objectVersion: "{{.mi-dist-and-mi-blob-ad-application-password}}"


