choreo-ai-multivariate-anomaly-detector-alert-manager=master-78a9599c2e8aaf23fa214bc7a2205bf2a635bb58
choreo-ai-multivariate-anomaly-detector-model-coordinator=master-33297be5f567f77596adadc12a8c239ccbedaa45
