apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    choreo.component: trimble-private-global-adapter
  name: trimble-private-global-adapter
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trimble-private-global-adapter
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
