# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

replicas: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
image:
  repository: choreoipaas/choreo-resource-authorization-service
  tag: latest
serviceAccount:
  annotations: {}
vault:
  roleName: config-deployer-service
config:
  asgardeoTokenIssuerConf: https://api.asgardeo.io/oauth2/token
  logLevel: INFO
  orgLevelPermissionsList:
    - apim:admin
    - billing:tier_view
    - billing:invoice_view
    - billing:subscription_manage
    - billing:payment_method_manage
    - billing:org_manage
    - urn:choreosystem:customdomainapi:custom_domain_manage
    - urn:choreosystem:customdomainapi:custom_domain_create
    - urn:choreosystem:customdomainapi:custom_domain_delete
    - urn:choreosystem:customdomainapi:custom_domain_update
    - apim:environment_manage
    - urn:choreosystem:choreoauditloggingapi:audit_logs_view
    - urn:choreosystem:choreoauditloggingapi:audit_logs_manage
    - urn:choreosystem:organizationmanagement:theme_manage
    - urn:choreosystem:organizationmanagement:theme_view
    - urn:choreosystem:organizationmanagement:theme_create
    - urn:choreosystem:organizationmanagement:theme_delete
    - urn:choreosystem:organizationmanagement:theme_deploy
    - urn:choreosystem:organizationmanagement:self_signup_manage
    - urn:choreosystem:organizationmanagement:self_signup_config_view
    - urn:choreosystem:organizationmanagement:self_signup_approval_view
    - urn:choreosystem:organizationmanagement:self_signup_approval_update
    - urn:choreosystem:organizationmanagement:self_signup_config_update
    - urn:choreosystem:organizationmanagement:enterprise_login_config_manage
    - urn:choreosystem:organizationmanagement:enterprise_login_config_view
    - urn:choreosystem:organizationapi:org_manage
    - choreo:domain_manage
    - choreo:url_mapping_approve
    - urn:choreosystem:usermanagement:user_view
    - urn:choreosystem:usermanagement:user_delete
    - urn:choreosystem:usermanagement:user_update
    - urn:choreosystem:usermanagement:role_create
    - urn:choreosystem:usermanagement:role_update
    - urn:choreosystem:usermanagement:role_delete
    - urn:choreosystem:usermanagement:role_manage
    - urn:choreosystem:usermanagement:invitation_view
    - urn:choreosystem:usermanagement:invitation_send
    - urn:choreosystem:usermanagement:invitation_delete
    - urn:choreosystem:usermanagement:invitation_manage
    - urn:choreosystem:usermanagement:user_manage
    - urn:choreosystem:onpremkeymanagement:on_prem_key_manage
    - urn:choreosystem:onpremkeymanagement:on_prem_key_view
    - urn:choreosystem:onpremkeymanagement:on_prem_key_create
    - urn:choreosystem:onpremkeymanagement:on_prem_key_delete
    - urn:choreosystem:onpremkeymanagement:on_prem_key_update
    - choreo:insights_org_view
secrets:
  spiceDBPresharedKey:
    path: choreo-cp/data/choreo-authorization/resource-authorization-service
    key: spiceDBPresharedKey
