resources:
- ../../apim/deployment/choreo-connect
- ../../apim/service/choreo-connect

nameSuffix: -default-p1

patchesStrategicMerge:
- adapter.yaml
- deployment.yaml
- adapter-service.yaml
- router-service.yaml
