resources:
  - ../base
namespace: dev-choreo-system

patches:
  - path: ingress-http-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-http
  - path: ingress-grpc-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-grpc