[cp_configuration_service.config]
configServerPort = 8080
internalHealthCheckPort = 8081
externalHealthCheckPort = 8082
maxHeaderSize = 65536
rudderServiceUrl = "http://dp-rudder:80"
secretManagerUrl = "http://dp-secret-manager:80"
cloudManagerUrl = "http://dp-cloud-manager:80"
dbHost = "{{.DB_HOST}}"
dbUsername = "{{.DB_USERNAME}}"
dbName = "{{.DB_NAME}}"
dbPasswordPath = "/mnt/csi/secret-configuration-service/CONFIGURATION_SERVICE_DB_PASSWORD"
mappingDbHost = "{{.MAPPING_DB_HOST}}"
mappingDbUsername = "{{.MAPPING_DB_USERNAME}}"
mappingDbName = "{{.MAPPING_DB_NAME}}"
mappingDbPasswordPath = "/mnt/csi/secret-configuration-service/CONFIGURATION_MAPPING_SERVICE_DB_PASSWORD"
