[choreo.resource_authz_service]
# Service configs
grpcApiPortConf = 9090
enableServiceReflectionConf = true
maxHeaderSizeConf = 65536

[choreo.resource_authz_service.authzSpiceDb]
# Service configs
jwtKeyUserGroupsConf = "groups"
authHeaderKeyConf = "x-jwt-assertion"
getProjectUuidRegexConf = '^.*/|\+.+'
getGroupUuidRegexConf =  '^.*\+'
objectUuidRegexConf = '^([a-zA-Z0-9_\-=]{20,36})$'
permissionRegexConf = '^(([a-zA-Z0-9_\-]+:)*[a-zA-Z0-9_\-]+|([a-zA-Z0-9_\-]+\.)*[a-zA-Z0-9_\-]+)$'
isActionAuthorizationEnabled = {{.ACTION_AUTHORIZATION_ENABLED}}

# SpiceDB configs
enableCheckPermissionConsistencyConf = true

# Permissions
projectViewPermissionConf = "choreo:project_view"
projectUpdatePermissionConf = "{{.PROJECT_UPDATE_PERMISSION | default "choreo:project_manage"}}"
projectDeletePermissionConf = "{{.PROJECT_DELETE_PERMISSION | default "choreo:project_manage"}}"
userManagementPermissionConf = "{{.USER_MANAGEMENT_PERMISSION}}"
roleViewPermissionConf = "{{.ROLE_VIEW_PERMISSION}}"
roleCreatePermissionConf = "{{.ROLE_CREATE_PERMISSION}}"
roleUpdatePermissionConf = "{{.ROLE_UPDATE_PERMISSION}}"
roleDeletePermissionConf = "{{.ROLE_DELETE_PERMISSION}}"

# Asgardeo token validation
asgardeoTokenIssuerConf = "{{.ASGARDEO_TOKEN_ISSUER}}"

orgLevelPermissionsList = {{.ORG_LEVEL_PERMISSIONS | default "[]"}}
envSpecificPermissionsList = {{.ENV_SPECIFIC_PERMISSIONS | default "[]"}}

[choreo.resource_authz_service.spicedbGrpcClient]
# SpiceDB configs
spiceDbGrpcPortConf = 50051
spiceDbHttpSchemeConf = "http://"
spiceDbHostConf = "spicedb-cluster.spicedb-operator.svc.cluster.local"
spiceDbAuthTokenFilePath = "/mnt/csi/secret-authz-management/SPICEDB-PRESHARED-KEY"


[ballerina.log]
level = "{{.LOG_LEVEL}}"
