# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
image:
  registry: ghcr.io
  repository: authzed/spicedb-operator
  tag: v1.12.0
serviceAccount:
  annotations: {}
secrets:
  presharedKey:
    path: choreo-cp/data/spicedb-operator/spicedb-operator
    key: presharedKey
  datastoreURI:
    path: choreo-cp/data/spicedb-operator/spicedb-operator
    key: datastoreURI
vault:
  roleName: spicedb-operator
