resources:
  - ../common-namespaces-dataplane/cert-manager
  - ../common-namespaces-dataplane/choreo-ai
  - ../common-namespaces-dataplane/choreo-observability
  - ../common-namespaces-dataplane/csi-secret-store-driver
  - ../common-namespaces-dataplane/keda
  - ../common-namespaces-dataplane/reloader
