# The configuration file for mgw

[keystore]
  certPath = "/home/wso2/security/keystore/global-adapter.pem"
  keyPath = "/home/wso2/security/keystore/global-adapter.key"

[truststore]
  location = "/home/wso2/security/truststore"

# Control plane's connection details
[controlPlane]
  serviceUrl = "https://choreo-am-service:9443/"
  username = "{{.CONTROLPLANE_USERNAME}}"
  password = "$env{cp_admin_pwd}"
  environmentLabels = ["Dev-Internal", "Prod-Internal"]
  #retryInterval = 5
  #skipSSLVerification=true
  # Message broker connection URL of the control plane
  [controlPlane.brokerConnectionParameters]
    eventListeningEndpoints = ["$env{ASB_CONNECTION_STRING}"]
    reconnectInterval = 5000
    reconnectRetryCount = 60
  [controlPlane.httpClient]
    # Request Timeout in Seconds (This is for REST API calls made from global adapter to APIManager)
    requestTimeOut = {{.CONTROLPLANE_REQUEST_TIMEOUT}}

[server]
  host = '0.0.0.0'
  port = '9843'
  partitionSize = 1000
  [[server.users]]
    username = '{{.SERVER_USERNAME}}'
    password = '$env{ga_admin_pwd}'

[database]
  name = 'choreo_global_adapter_db'
  username = 'choreo_global_adapter_db_user'
  password = '$env{ga_db_pwd}'
  host = '{{.DATABASE_HOST}}'
  port = 1433
  validationQuery = 'select 1'
  [database.pooloptions]
  maxActive = {{.DATABASE_MAX_ACTIVE}}
  maxIdle = {{.DATABASE_MAX_IDLE}}

[redisServer]
  host = '{{.REDIS_SERVER_HOST}}'
  port = 6380
  password = '$env{redis_host_pwd}'
  clientName = 'global-adapter'
  databaseIndex = 0
  connectionPoolSize = 3
  maxRetryCount = 10

[orgBlocking]
enabled = true
