apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-app-db
  namespace: dev-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgBANODRY0uDPy+DEK5+Sxg9UsI0NhTCRP1siib+IlKTPIvxE+uTGPIXJl8D+X2uAEu8hPa91t1/YVOz9N85IlfUykbOf8PEzZaO/oxAbLZMDk5LK20HS0x35vmDAV4OU1X4yGhjmpkX7iYG9mfOxAeiCg3DTcnzPAVeOlGaX1VDMPR4nu6W8eRtmx/9Clk8CJ66oCut7OFH15Aum/eVrgK7OKcIKmdhBdk5NSbNH60Nh0ycUPu3cSB2rTvZDmOAL5HoaU3sLdYSCpmrbWZ6ALSYrcKaxcj0j21aArBWd1X9Xz/71hYKly2e94LB2U02WgrngK9drVoIGhMSbBm62/tomMQDOf/nfCGx+bI4/euAn6cwl9AlsUztaC3QUpVFjJvRukJ38+Me7qwQxFlTvvl45+A49ulZp/SMBQZCx73aNXkoen9Mni2vLfKAswQLscjqGf2kO1Zj8Rl8XTycci0gtRd/iSsOYjFS5RDpLn+8vJE5AjWUSjb2+wnZH7smHMc51nSFxNm3hbbfSxo7w174j7NnUGX3WS7F36DSMdcPRLPO1qmf/8ljkMwpJdZnf1WKn9k02vL9FsOCwD6UyGshkHTaEs4MRsekfvjWnztp7klEe/C8C1XqQmMTRhR9rbxnQ5t3c3RKiIxPNrDq3L/eHiFVo7vx5ZvLjvdA8f706tIwvKPEqzIcnuL0p7sPX+cAAtVz0R+x+UwWWeY=
  template:
    metadata:
      creationTimestamp: null
      name: secret-app-db
      namespace: dev-choreo-system

