apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-loggingapi
  namespace: dev-choreo-system
spec:
  encryptedData:
    AZURE_ACTIVEDIRECTORY_CLIENT_SECRET: AgA7+65EOrgynN16GYMXvesf5P2zsjPJbrL/7oi/i3cObNYwG4MJQWRNvWMf5eGZMFJSCjnrkJecH9dz+PwhASmf7ni1x8AFNACOI1miy4T3NjYlLa4MA8y+krQ7T6G/N4BOJBpZly5ANWBPMK5ViZDJ6r7kkGGVjbbAmAwvf+vqacUc0J4jJAov/PQhg4yz9OnKq3EigWG0IC75KhLwgAYWxB+QRqHqMEvtBzvo8zPgj9YKrWzLKBAgKtLYcBa1VnyNfZhpMA+aoebGIzs+7vvhfcRgdmq9vUWRz1yXvwdPHbyHzxFGrS07Vr5gAX5AQudGNtEx2/WwBVVqW3q34hER45RKtcj5U7hfV0a/zgs1s+jLP8D/iKmYNqaJlKihGSg9qhXc+JAngdXJJMXTp8cNbwTzwFJuFr/ULh3fZJdz9SF+8NzdOsf8C12/TEs6Bv7ZvZx9Hl9+FVV5pPPv88c71surgifdR9ip3H7tECoeWosiwJVWuiCm8GEC1JFXjq9xTaKqFQ8lIj9FScr0GdTT6r2Am1rf97RpRFnwj6mwTZrczmjgqHjtzE/urpeMUkPp4/lV/JTX1jUIrXj0/ZMZz3gTBoPcSeGq1j3sXbSnKf2G6RvszWuaOoG8LijXPiblqZ16B6D8dVZhNtbitghrm+wy8sQEPUor0Am8+sl8BfF8y9Y6tXoGK9RLIRojHBpd1CxEm+HJez/qWPTZ3URuOG5hk3Ex2fkeIquREtDvdA==
  template:
    metadata:
      creationTimestamp: null
      name: secret-loggingapi
      namespace: dev-choreo-system

