apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-obsapi
  namespace: dev-choreo-system
spec:
  encryptedData:
    AZURE_TIMESERIESINSIGHTS_CLIENT_SECRET: AgBV7ZKhHVQgT2TVFhFo+7yKw9u4PASshZFkv75ED/HFxi19UZjy/Ifl+5FO1naBFmqb7whYb+oM1zxlPhGsSoV5RX8UxSDDvuUFBfqiCl/VG6QLLPaoRBOOztwfwQGlY/VgEL0K9trTPb/5rEV8bJQQ2LE+X2GdLr/0+4BywtOfIZcvA3i/c4hlBM5+WWzVM4AYoN53TcrEFLUTrkfUtTNZGdxfsA8Ozs8vKc7JHlgHyL7kw71fZcT1s0r1HPWywVqIrKE88b08jE2lVk0UFV54KcBD8Fl4vAf8Ss10Qm9wpExayyh0RYt/yJzl4/sZZVkQ/uPYwfUNwV7z8+Ygr6FAQtds+H/E7VQWPW++rBN7R5RS5jbtJPM5E4RALlnTa+RGuT65kavj2Pn2hoK+wnsV1GVrcOllEIzMgQdgt7c97omH0z9hOAJoywzo9Ytq039xEYYbbWjR5MS2bLmQvgRMO+HKnaDhVq6vB5Un1tNo0eDj5ktPAh29Ob3uRuPjAtzWP1u1jqcsJ4HqxD8dj+Y71fSh0Whqlzzg/VLZF8Ba2xsF6OIQ9MPDa+aAr7mFJV/nrOycsJQDRkUDuLoMWxH6uRoWqbS3sxyw5oytrEASR8eYvck0ZoPgU2Fyg+k6v2WpEyj5n7tjoQ2k/XaSehJtbefXaO4+lhFkLPimib0Yd34j0O2oyhX1iTyf14YvNb+UIgeD273OsTraU30HU9jTUogdW0FqA2molB+gqtTNwA==
  template:
    metadata:
      creationTimestamp: null
      name: secret-obsapi
      namespace: dev-choreo-system

