apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-perfanalyzer
  namespace: dev-choreo-system
spec:
  encryptedData:
    AZURE_TIMESERIESINSIGHTS_CLIENT_SECRET: AgCfzRcQTMV4DQUDZQxYGH2naQSaHL2/vcFQV+7XhveRvcd/DoNKjQQlReh0i2Sm8HQahi6K3Qoad9isyjmf53t7nT+PoZBOP83ry7W37aEyzKZHMFOYO8bcaszmhEVLjk9cgj47sfcyXHdG1HUDU2PHcSMVTSPx9sSz2QjYPulkBDAK711h4XttFAE8pjtnKjd5XkNYtLzEWnMGmevEonR2ezuZdKrjOgpzKk5ygHhlP/remx7uhPv0rYusnp+Dzu8vm+2AUKqwRvLz/oCMQuOM9IL9yBGD4XLWH5f5ah0usPkCqrYrz/Or0kTQB5MocdJv0TQv7fwHUgq+XD4YJfNj2dnq/vOAuGc0KANUJL/0YqZZdfVwFg6jDC91VtATcNrY5R9j8LDLxaMDAXwMKvj69oMbvq+x5Lo9/bCxSeUDzStKGM422oInY0lUWZbA83dJZwM2hxVnOPEUX4XV3xTQ8S3ypEQaN4OdwZ/4ICVcVkqSpwon2BLfl2eMuAza+YfjxgX6TsM7/DtEjT3+USgmUgbiNNEVp9y8R0vFLcrjkFuZvw/6nHYb2+zX6yDr2cUv8U8u/YL1tXeUlPDSaw6ATYmwaCA1oaA2+6KzOkzQVfGwgAaOrm+rsjKjSc5oZ6asTk7FaDm11n3kwE1cA1ymlga04Q15tHnH2LNqCBFobOkniRpWfiyEweOKf/Xmtvq1ef6h7vFLiumVfkwTtc3fXQqenJVBeGL0vQZ5l/4AEA==
    CHOREO_PERF_DB_PASSWORD: AgADzBE5AUa4q/8VuZcDqyyjOKpFy9GeiWbZ/sAa3PNEjL2JSC+ZgojbLQNzAaY5tC6Ud1Jy7e1GdBciXiWmnyNXOV4Z55hYmqp9SQDvpKRIEzNgxLQH6HWWKQ4hPpxFKtvB1pxP/KS0OEf/I/bBEMKykFDmA167oa5nHbWllcOv1mke2Y+A8O03aCu0pckFeB7qJgWIFVjCJe921OQ5mQdPWZ0iQSjo7J+3kL0FXzyBvKStkeMqNV2zEksqsjhwK1JaEXprZPqPhlC0tuJphCcuhSf+d+sjApOZ9QjIFQvxJr4/UoHquuS7F7B4Tcd+ti+KwZl9AHW5xssSoFUE/0cr3pMNrigJbQNR4k3e7wPbyqkfXTKd7zEhz+5BKfAzJAysMQuY2ZEBg3hnSpgpqrkGv25IlB/XBh/w9POUZwRAz8/L+lhkWw811P3VgrhHzb24w/B9c8nUfP7e/ytJdnRAJo7wyR75x6R5kqh/nZU++03DG69qYkKAEU6/JlYsAurzdCKTVAPC78zylk19LVrCcJ/4rtPq06Fj1swetNiC4qu5zsiV2ZeUtPZiCrAHicmgRJKl1ZS64Yltn3h/viDYTDUByTwysffT4QGloB7L5C5J66BQHOkORztN14kfI5v46wYIP9RrnDTzdVSIQmD633cdAyPKI/w8XErgr3VoKPnwZXaOQwE/HwUwh7euKENfr4ak3i3sz+R8yDk=
  template:
    metadata:
      creationTimestamp: null
      name: secret-perfanalyzer
      namespace: dev-choreo-system

