apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-perf-db
  namespace: dev-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgBW3ZqSmwF8IC3w241ofvSfdMRTp5At9c9ldrFYwMR4Kk/us6sS7CRZBZ9hgfOLn38Dq9V7MEF43JpAGBr++URtuwRO8fDrO3VuF/taIGC9Mmd+0ek1INDY91WJWiYsTIfKw2og+SOfcNlJudKNQFJk8ls+XUE5b3S09G7F2tCWQzNSVj2rPNo0Q4HtYnnJ7iuC4V/j5FQvopsPJZaTpy0mZnPZ3kSeirPe77PYp2P6tsEcWH+gmoFJayTS7jDP9uPl2c1THGFM+JvsvGA8iEwc1L9wzElUjHDOmRKnuRyFVhVsqSLQjpe8DYZsO/2N2LvisHRS5Qy7GZwGU+cG5iql3EUy8eMpcJXu62jfUy2eCNiaDpHbFuMxbgubRiJjxPj3ElTJjkE1A3Edxj47k8KIQH2aGxUkKVOuXX9SQVGAv/46dlkyspYGjlSyUMPOlhA1LSAGZlsdeaSor7dD+67sL8mYAIhGXsxge0lJOw7rrJKvSud0iAJ9oYmjb61one4p5xHnINVFqDnXQc4RGaHi5zxyYy0EQ8JwJ4ZxVcLXtyyv/k0xEIfV5rEbZ8YXBhn7iOBotqy4eVtnHgQ2kpy4Cjbu2lt9SdEBvarPRLyG8H2xnAQO+f4NMlWLMwoG83g5TaLyKJw/S32cdKezUS6CuGIInR+I3qPaZv0mkjyzH77mzyIwVl3LLMmgO2nY/yYkidzwO8NTJW18iH8=
  template:
    metadata:
      creationTimestamp: null
      name: secret-perf-db
      namespace: dev-choreo-system

