apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-trace-db
  namespace: dev-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgB/febKmSApGCz9urWSie892yB2vY+FJcG5z828Ah1/xfS6bLnyu4FVhUuiWN5YfaK7DBYiL65VqW+JIv+vdjIz4dFBwnOs6sGvbIg7UT8SISWwxaxdmzg8CVaaerhwuDi8lNNG8948cYgFtIZBdT+VuaASkf7Y8aAyUqWuZctavNwn/+OiZFgjO8dD3MfLdovov0qFmadBgDBovUcAaq+y5F5I7P2KHGcLpsHhL39yDUvGQqu4nvHtsYhvpRdYSGW/pc1PJOGAoV5y+JSgKZnxhuuLKVun5DRlAZv+uBONnz9UtNnrwwOBTJpB04iOGZRP9CSCygfr9Gt4HIRZnKV6QhJ/npUV8DGYOxLnJ4GZzyuzp6qh13cjb3x1eyxCu2we3UnXdPqOTuV5Y9JUVx0AkfQRLUxvm5U/AXN7OBbAC/vfO/o+FaqyBe5PbZm6ypKcI7mKORKtGzdmu/lMm/9qiyFddTOUY67BUVOR7ctr01PkUW7uqGt7vafH6EBOFFYYbWQKsr0Vs5LcUXIMH+FxbaOc5peA05A+0G/vFuo6RxQ4bfosYpgsJ3suiIafzOLqAB5fvthh/EoPKzZALPRGOrR+HxV9H1D/DUVkhb50aNSJC5ph3o1d8H9OtevuT6JjZzxWnMHys1xDRMSIy4pDuVyVUMFgcMxL5Z6HE98jzJ8V/UQ7cQzMfDj87kVrVAg3bLA+0SBldqqzSt8=
  template:
    metadata:
      creationTimestamp: null
      name: secret-trace-db
      namespace: dev-choreo-system

