# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: subscriptions-service
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    {{- include "subscriptions-service.labels" . | nindent 4 }}
spec:
  provider: vault
  secretObjects:
    - secretName: subscriptions-service
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: CHOREO_STEP_DB_PASSWORD
          key: CHOREO_STEP_DB_PASSWORD
        - objectName: CACHE_PASSWORD
          key: CACHE_PASSWORD
        - objectName: CHOREO_SUBSCRIPTIONS_ASB_AUTH_TOKEN
          key: CHOREO_SUBSCRIPTIONS_ASB_AUTH_TOKEN
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: DB_PASSWORD
        secretKey: {{ .Values.secrets.dbPassword.key | quote }}
        secretPath: {{ .Values.secrets.dbPassword.path | quote }}
      - objectName: CHOREO_STEP_DB_PASSWORD
        secretKey: {{ .Values.secrets.stepDBPassword.key | quote }}
        secretPath: {{ .Values.secrets.stepDBPassword.path | quote }}
      - objectName: CACHE_PASSWORD
        secretKey: {{ .Values.secrets.redisPassword.key | quote }}
        secretPath: {{ .Values.secrets.redisPassword.path | quote }}
      - objectName: CHOREO_SUBSCRIPTIONS_ASB_AUTH_TOKEN
        secretKey: {{ .Values.secrets.asbAuthToken.key | quote }}
        secretPath: {{ .Values.secrets.asbAuthToken.path | quote }}
