# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_38=The SA token is required for the linkerd to define service identity
  labels:
    {{- include "resource-authorization-service.labels" . | nindent 4 }}
  name: resource-authorization-service
  namespace: {{ .Values.global.namespaces.authz }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "resource-authorization-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "resource-authorization-service.labels" . | nindent 8 }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: choreo-resource-authorization-service
          image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9090
              name: service-port
            - containerPort: 9091
              name: health-port
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:9091
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:9091
            initialDelaySeconds: 20
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 300Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10500
            runAsGroup: 10500
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: config
              mountPath: /home/ballerina/Config.toml
              subPath: Config.toml
            - name: secret-authz-service
              mountPath: "/mnt/csi/secret-authz-management"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: resource-authorization-service
        - name: secret-authz-service
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: resource-authorization-service
      serviceAccountName: resource-authorization-service
      {{- if .Values.autoscaling.enabled }}
      {{- $minReplicas := .Values.autoscaling.minReplicas | int64 }}
      {{- if ge $minReplicas 2 }}
      {{- include "resource-authorization-service.affinity" . | nindent 6 }}
      {{- end }}
      {{- end }}
