IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_connection_service_db_user')
BEGIN
    CREATE USER [choreo_connection_service_db_user] with password = N'xxxxxxxxxxxxx'
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo_connection_service_db TO choreo_connection_service_db_user
END;
GO

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[CONNECTION]') AND TYPE IN (N'U'))
CREATE TABLE CONNECTION(
    ID UNIQUEIDENTIFIER NOT NULL,
    ORGANIZATION_ID UNIQUEIDENTIFIER NOT NULL,
    PROJECT_ID UNIQUEIDENTIFIER NOT NULL,
    COMPONENT_ID UNIQUEIDENTIFIER,
    NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NTEXT,
    SERVICE_ID UNIQUEIDENTIFIER NOT NULL,
    SCHEMA_ID UNIQUEIDENTIFIER NOT NULL,
    IS_PARTIAL TINYINT NOT NULL,
    SOURCE NVARCHAR(255) NOT NULL,
    SUBSCRIPTION_ID UNIQUEIDENTIFIER,
    STATUS NTEXT,
    VERSION NVARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'CONNECTION_ORGANIZATION_ID_PROJECT_ID_COMPONENT_ID_INDEX')
DROP INDEX CONNECTION.CONNECTION_ORGANIZATION_ID_PROJECT_ID_COMPONENT_ID_INDEX
CREATE INDEX CONNECTION_ORGANIZATION_ID_PROJECT_ID_COMPONENT_ID_INDEX ON
    CONNECTION(
        ORGANIZATION_ID,
        PROJECT_ID,
        COMPONENT_ID
    );

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'CONNECTION_SERVICE_ID_INDEX')
DROP INDEX CONNECTION.CONNECTION_SERVICE_ID_INDEX
CREATE INDEX CONNECTION_SERVICE_ID_INDEX ON
    CONNECTION(
        SERVICE_ID
    );

ALTER TABLE
    CONNECTION ADD CONSTRAINT CONNECTION_ID_PK PRIMARY KEY(ID);
