-- Create User
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_proxy_deployer_db_user')
BEGIN
    CREATE USER [choreo_proxy_deployer_db_user] with password = N'xxxxxxxxxxxxx'
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo_proxy_deployer_db TO choreo_proxy_deployer_db_user
END;
GO

-- Create Prody Deployer Table --
IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PROXY_DEPLOYER_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE PROXY_DEPLOYER_STATUS(
	REQUEST_ID VARCHAR(50) NOT NULL,
    API_ID VARCHAR(50) NOT NULL,
    ORGANIZATION_ID VARCHAR(50) NOT NULL,
    PROCESS VARCHAR(50) NOT NULL,
    ENVIRONMENT_ID VARCHAR(50),
    CURRENT_ACTION VARCHAR(50),
    NEXT_ACTION VARCHAR(50),
    STATUS VARCHAR(15),
    PRIMARY KEY (REQUEST_ID),
);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'PROXY_DEPLOYER_STATUS_BY_API_ID')
DROP INDEX PROXY_DEPLOYER_STATUS.PROXY_DEPLOYER_STATUS_BY_API_ID
CREATE INDEX PROXY_DEPLOYER_STATUS_BY_API_ID ON PROXY_DEPLOYER_STATUS(API_ID);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[COMPONENT_BUILD_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE COMPONENT_BUILD_MAPPING(
    ID INTEGER NOT NULL IDENTITY(1,1),
    COMPONENT_ID VARCHAR(50) NOT NULL,
    BUILD_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT COMP_ID_BUILD_ID UNIQUE (COMPONENT_ID, BUILD_ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PM_RUDDER_COMPONENT_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE PM_RUDDER_COMPONENT_MAPPING(
    ID INTEGER NOT NULL IDENTITY(1,1),
    PROXY_COMPONENT_ID VARCHAR(50) NOT NULL,
    MEDIATION_COMPONENT_ID VARCHAR(50) NOT NULL,
    MEDIATION_COMPONENT_NAME VARCHAR(100),
    IS_REPO_CREATED bit DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[API_VERSION_BRANCH_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE API_VERSION_BRANCH_MAPPING(
    COMPONENT_BUILD_REF INTEGER NOT NULL,
    API_ID VARCHAR(50) NOT NULL,
    MEDIATION_VERSION_ID VARCHAR(50) NOT NULL,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    MEDIATION_REF_ID int NOT NULL,
    CONSTRAINT API_ID_RUDDER_VID UNIQUE (API_ID, MEDIATION_VERSION_ID, BRANCH_NAME, COMPONENT_BUILD_REF),
    CONSTRAINT API_VERSION_BRANCH_MAPPING_FK FOREIGN KEY (COMPONENT_BUILD_REF) REFERENCES COMPONENT_BUILD_MAPPING(ID) ON DELETE CASCADE,
    CONSTRAINT API_VERSION_BRANCH_RUDDER_MAPPING_FK FOREIGN KEY (MEDIATION_REF_ID) REFERENCES PM_RUDDER_COMPONENT_MAPPING(ID) ON DELETE CASCADE
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BUILD_COMMIT_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE BUILD_COMMIT_MAPPING(
    COMPONENT_BUILD_REF INTEGER NOT NULL,
    COMMIT_HASH VARCHAR(50) NOT NULL,
    FOREIGN KEY (COMPONENT_BUILD_REF) REFERENCES COMPONENT_BUILD_MAPPING(ID) ON DELETE CASCADE
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BUILD_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE BUILD_STATUS(
    COMPONENT_BUILD_REF INTEGER NOT NULL,
    API_ID VARCHAR(50) NOT NULL,
    REVISION_ID VARCHAR(50),
    MEDIATION_ATTACHED BIT,
    START_TIME DATETIME NULL DEFAULT NULL,
    FINISHED_TIME DATETIME NULL DEFAULT NULL,
    STATUS VARCHAR(25),
    FOREIGN KEY (COMPONENT_BUILD_REF) REFERENCES COMPONENT_BUILD_MAPPING(ID) ON DELETE CASCADE
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BUILD_STAGE_INFO]') AND TYPE IN (N'U'))
CREATE TABLE BUILD_STAGE_INFO(
    COMPONENT_BUILD_REF INTEGER NOT NULL,
    STAGE VARCHAR(50) NOT NULL,
    META_INFO VARCHAR(MAX),
    STARTED_TIME DATETIME NULL DEFAULT NULL,
    FINISHED_TIME DATETIME NULL DEFAULT NULL,
    STATUS VARCHAR(15),
    FOREIGN KEY (COMPONENT_BUILD_REF) REFERENCES COMPONENT_BUILD_MAPPING(ID) ON DELETE CASCADE
);
