-- Create User
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_proxy_deployer_db_user')
BEGIN
    CREATE USER [choreo_proxy_deployer_db_user] FOR LOGIN [choreo_proxy_deployer_db_user]
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo_proxy_deployer_db TO choreo_proxy_deployer_db_user
END;
GO

-- Create Prody Deployer Table --
IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PROXY_DEPLOYER_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE PROXY_DEPLOYER_STATUS(
	REQUEST_ID VARCHAR(50) NOT NULL,
    API_ID VARCHAR(50) NOT NULL,
    ORGANIZATION_ID VARCHAR(50) NOT NULL,
    PROCESS VARCHAR(50) NOT NULL,
    ENVIRONMENT_ID VARCHAR(50),
    CURRENT_ACTION VARCHAR(50),
    NEXT_ACTION VARCHAR(50),
    STATUS VARCHAR(15),
    PRIMARY KEY (REQUEST_ID),
);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'PROXY_DEPLOYER_STATUS_BY_API_ID')
DROP INDEX PROXY_DEPLOYER_STATUS.PROXY_DEPLOYER_STATUS_BY_API_ID
CREATE INDEX PROXY_DEPLOYER_STATUS_BY_API_ID ON PROXY_DEPLOYER_STATUS(API_ID);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[COMPONENT_BUILD_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE COMPONENT_BUILD_MAPPING(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    COMPONENT_ID VARCHAR(50) NOT NULL,
    BUILD_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT COMP_ID_BUILD_ID UNIQUE (COMPONENT_ID, BUILD_ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[API_VERSION_BRANCH_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE API_VERSION_BRANCH_MAPPING(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    API_ID VARCHAR(50) NOT NULL,
    RUDDER_VERSION_ID VARCHAR(50) NOT NULL,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT API_ID_RUDDER_VID UNIQUE (API_ID, RUDDER_VERSION_ID, BRANCH_NAME)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BUILD_COMMIT_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE BUILD_COMMIT_MAPPING(
    ID INTEGER NOT NULL,
    COMMIT_HASH VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID) REFERENCES COMPONENT_BUILD_MAPPING(ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PM_RUDDER_COMPONENT_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE PM_RUDDER_COMPONENT_MAPPING(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PM_COMPONENT_ID VARCHAR(50) NOT NULL,
    RUDDER_COMPONENT_ID VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BUILD_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE BUILD_STATUS(
    ID INTEGER NOT NULL,
    API_ID VARCHAR(50) NOT NULL,
    REVISION_ID VARCHAR(50),
    MEDIATION_ATTACHED boolean,
    START_TIME TIMESTAMP NULL DEFAULT NULL,
    FINISHED_TIME TIMESTAMP NULL DEFAULT NULL,
    STATUS VARCHAR(15),
    FOREIGN KEY (ID) REFERENCES COMPONENT_BUILD_MAPPING(ID)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BUILD_STAGE_INFO]') AND TYPE IN (N'U'))
CREATE TABLE BUILD_STAGE_INFO(
    ID INTEGER NOT NULL,
    STAGE VARCHAR(50) NOT NULL,
    META_INFO VARCHAR(MAX),
    STARTED_TIME TIMESTAMP NULL DEFAULT NULL,
    FINISHED_TIME TIMESTAMP NULL DEFAULT NULL,
    STATUS VARCHAR(15),
    FOREIGN KEY (ID) REFERENCES COMPONENT_BUILD_MAPPING(ID),
    CONSTRAINT B_S_INFO_ID_STAGE UNIQUE (ID, STAGE)
);
