CREATE
DATABASE choreo_org_remover_db;

CREATE TABLE ORG_COMPONENT_MAPPING
(
    [ID]             int NOT NULL IDENTITY,
    [ORG_ID]         varchar(100) NOT NULL,
    [COMPONENT_NAME] varchar(250) NOT NULL,
    [STATUS]         varchar(45)  DEFAULT 'PENDING',
    [REQUEST_ID]     varchar(100) NOT NULL,
    PRIMARY KEY ([ID]),
    CONSTRAINT [ORG_ID_COMPONENT_UNIQUE] UNIQUE  ([ORG_ID],[COMPONENT_NAME])
);

CREATE TABLE ORG_REMOVER_COMPONENT
(
    [COMPONENT_ID]   int NOT NULL IDENTITY,
    [UUID]           varchar(100) NOT NULL,
    [COMPONENT_NAME] varchar(250) NOT NULL,
    PRIMARY KEY ([COMPONENT_ID]),
    CONSTRAINT [UUID_UNIQUE] UNIQUE ([UUID]),
    CONSTRAINT [COMPONENT_NAME_UNIQUE] UNIQUE  ([COMPONENT_NAME])
);


CREATE TABLE ERROR_RESPONSE
(
    [ID]                   INT NOT NULL IDENTITY,
    [COMPONENT_MAPPING_ID] INT NULL,
    [ERROR_MSG]            VARCHAR(max) NULL,
    PRIMARY KEY ([ID]),
    CONSTRAINT [COMPONENT_MAPPING_KEY]
        FOREIGN KEY ([COMPONENT_MAPPING_ID])
            REFERENCES org_component_mapping ([ID])
            ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX [COMPONENT_MAPPING_KEY_idx] ON ERROR_RESPONSE ([COMPONENT_MAPPING_ID] ASC);
