-- Create User
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'choreo-alerts-db') AND NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_alerts_db_user')
BEGIN
    CREATE USER [choreo_alerts_db_user] with password = N'xxxxxxxxxxxxx'
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo-alerts-db TO choreo_alerts_db_user
END;
GO

CREATE TABLE API_ALERT_CONFIG
(
    UUID VARCHAR(255) NOT NULL,
    ORG_ID VARCHAR(255) NOT NULL,
    ENV_ID VARCHAR(255) NOT NULL,
    PUBLISHER VARCHAR(255) NOT NULL,
    TIME VARCHAR(255) NOT NULL,
    SEVERITY VARCHAR(255) NOT NULL,
    METADATA NVARCHAR(MAX) NOT NULL,
    PROPERTIES NVARCHAR(MAX) NOT NULL,
    EVENT_TYPE VARCHAR(255) NOT NULL,
    COUNT INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY (UUID)
);

CREATE TABLE ALERT_TYPE
(
    UUID         VARCHAR(255) NOT NULL,
    NAME         VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (UUID),
    CONSTRAINT CON_NAME_UNIQUE_KEY_CONSTRAINT UNIQUE (NAME)
);

CREATE TABLE ALERT_ORG_CONFIG
(
    ORG_ID     VARCHAR(255) NOT NULL,
    IS_ENABLED BIT          NOT NULL DEFAULT 0,
    PRIMARY KEY (ORG_ID)
);

CREATE TABLE ALERT_TYPE_CONFIG
(
    UUID          VARCHAR(255) NOT NULL,
    ALERT_TYPE_ID VARCHAR(255) NOT NULL,
    ORG_ID        VARCHAR(255) NOT NULL,
    IS_ENABLED    BIT          NOT NULL DEFAULT 0,
    PRIMARY KEY (UUID),
    CONSTRAINT CON_ALERT_TYPE_CONFIG_REF_ORG_ID FOREIGN KEY (ORG_ID) REFERENCES ALERT_ORG_CONFIG (ORG_ID),
    CONSTRAINT CON_ALERT_TYPE_CONFIG_REF_ALERT_TYPE_ID FOREIGN KEY (ALERT_TYPE_ID) REFERENCES ALERT_TYPE (UUID),
    CONSTRAINT CON_ALERT_TYPE_CONFIG_UNIQUE_KEY_CONSTRAINT UNIQUE (ORG_ID, ALERT_TYPE_ID)
);

CREATE TABLE RECIPIENT
(
    UUID      VARCHAR(255) NOT NULL,
    CONFIG_ID VARCHAR(255) NOT NULL,
    TYPE      VARCHAR(255) NOT NULL,
    ADDRESS   VARCHAR(255) NOT NULL,
    PRIMARY KEY (UUID),
    CONSTRAINT CON_RECIPIENT_REF_CONFIG_ID FOREIGN KEY (CONFIG_ID) REFERENCES ALERT_TYPE_CONFIG (UUID)
);
