-- Create User
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_proxy_deployer_db_user')
BEGIN
    CREATE USER [choreo_proxy_deployer_db_user] FOR LOGIN [choreo_proxy_deployer_db_user]
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo_proxy_deployer_db TO choreo_proxy_deployer_db_user
END;
GO

-- Create Prody Deployer Table --
IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PROXY_DEPLOYER_STATUS]') AND TYPE IN (N'U'))
CREATE TABLE PROXY_DEPLOYER_STATUS(
	REQUEST_ID VARCHAR(50) NOT NULL,
    API_ID VARCHAR(50) NOT NULL,
    ORGANIZATION_ID VARCHAR(50) NOT NULL,
    PROCESS VARCHAR(50) NOT NULL,
    ENVIRONMENT_ID VARCHAR(50),
    CURRENT_ACTION VARCHAR(50),
    NEXT_ACTION VARCHAR(50),
    STATUS VARCHAR(15),
    PRIMARY KEY (REQUEST_ID),
);

IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'PROXY_DEPLOYER_STATUS_BY_API_ID')
DROP INDEX PROXY_DEPLOYER_STATUS.PROXY_DEPLOYER_STATUS_BY_API_ID
CREATE INDEX PROXY_DEPLOYER_STATUS_BY_API_ID ON PROXY_DEPLOYER_STATUS(API_ID);

