CREATE TABLE API_ALERT_CONFIG
(
    UUID VARCHAR(255) NOT NULL,
    ORG_ID VARCHAR(255) NOT NULL,
    ENV_ID VARCHAR(255) NOT NULL,
    PUBLISHER VARCHAR(255) NOT NULL,
    TIME VARCHAR(255) NOT NULL,
    SEVERITY VARCHAR(255) NOT NULL,
    METADATA NVARCHAR(MAX) NOT NULL,
    PROPERTIES NVARCHAR(MAX) NOT NULL,
    EVENT_TYPE VARCHAR(255) NOT NULL,
    COUNT INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    PRIMARY KEY (UUID)
)
