CREATE USER 'choreo_app_db_user'@'%' IDENTIFIED BY 'pw_app_db_user';
CREATE USER 'choreo_perf_db_user'@'%' IDENTIFIED BY 'pw_perf_db_user';
CREATE USER 'choreo_program_db_user'@'%' IDENTIFIED BY 'pw_program_db_user';
CREATE USER 'choreo_testbase_db_user'@'%' IDENTIFIED BY 'pw_testbase_db_user';
CREATE USER 'choreo_apim_db_user'@'%' IDENTIFIED BY 'pw_apim_db_user';
CREATE USER 'choreo_apim_shared_db_user'@'%' IDENTIFIED BY 'pw_apim_db_user';
CREATE USER 'choreo_apim_user_db_user'@'%' IDENTIFIED BY 'pw_apim_db_user';
CREATE USER 'choreo-aiexp-db-reader'@'%' IDENTIFIED BY 'pw_aiexp_db_reader';
CREATE USER 'choreo_step_db_user'@'%' IDENTIFIED BY 'pw_step_db_user';
CREATE USER 'choreo_proxy_deployer_db_user'@'%' IDENTIFIED BY 'pw_proxy_deployer_db_user';

GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_app_db`.* TO 'choreo_app_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_perf_db`.* TO 'choreo_perf_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON `choreo_program_db`.* TO 'choreo_program_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_testbase_db`.* TO 'choreo_testbase_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_apim_db`.* TO 'choreo_apim_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_apim_shared_db`.* TO 'choreo_apim_shared_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_apim_user_db`.* TO 'choreo_apim_user_db_user'@'%';
GRANT SELECT ON `choreo_perf_db`.* TO 'choreo-aiexp-db-reader'@'%';
GRANT SELECT ON `choreo_program_db`.* TO 'choreo-aiexp-db-reader'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_step_db`.* TO 'choreo_step_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_codeserver_db`.* TO 'choreo_codeserver_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_proxy_deployer_db`.* TO 'choreo_proxy_deployer_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_cp_sis_db`.* TO 'choreo_cp_sis_db_user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `choreo_app_dev_user_mgt_db`.* TO 'choreo_app_dev_user_mgt_db_user'@'%';
