---
# -------------------------------------------------------------------------------------
#
# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.azure.keyVault.secretProviderClass }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    userAssignedIdentityID: "{{ .Values.azure.keyVault.activeDirectory.servicePrincipal.appId }}"
    keyvaultName: "{{ .Values.azure.keyVault.name }}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: DB-SERVER-ADMIN-USERNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: DB-SERVER-ADMIN-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: app-CHOREO-DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: perfanalyzer-CHOREO-PERF-DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: program-CHOREO-DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: testbase-CHOREO-DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: apim-CHOREO-APIM-DB-PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: "{{ .Values.azure.keyVault.activeDirectory.tenantId }}"
    resourceGroup: "{{ .Values.azure.keyVault.resourceManager.resourceGroup }}"
    subscriptionId: "{{ .Values.azure.keyVault.resourceManager.subscriptionId }}"
