[choreo.audit_logging.configs]
auditEventListenerApiPort = 8090
stsClientId = "{{.STS_CLIENT_ID}}"
stsTokenEndpointHost = "{{.STS_TOKEN_ENDPOINT_HOST}}"
hubURL = "{{.HUB_URL}}"
topic = "{{.TOPIC}}"
callbackURL = "{{.CALLBACK_URL}}"
azureLogIngestionBaseUrl = "{{.AZURE_LOG_INGESTION_BASE_URL}}"
azureDcrImmutableId = "{{.AZURE_DCR_IMMUTABLE_ID}}"
azureCustomTableName = "ChoreoAuditLogs_CL"
azureLogIngestionAPIVersion = "2021-11-01-preview"
azureLogIngestionAPIScopes = "https://monitor.azure.com//.default"
azureLogIngestionClientRetryInterval = 1.0
azureLogIngestionClientRetryCount = 3
enableEventCollectViaAMA = {{.ENABLE_EVENT_COLLECT_VIA_AMA}}
enableEventCollectViaAzureIngestionAPI = {{.ENABLE_EVENT_COLLECT_VIA_AZURE_INGESTION_API}}
enableEventQueryFromCustomTable = {{.ENABLE_EVENT_QUERY_FROM_CUSTOM_TABLE}}
auditLoggingApiPort = 8080
region = "{{.REGION}}"
clusterName = "{{.CLUSTER_NAME}}"
namespace = "{{.NAMESPACE}}"
containerName = "{{.CONTAINER_NAME}}"
auditLogFilter = "[AUDIT_LOG]"
healthCheckInterval = "10m"
azureLaTenantId = "{{.AZURE_LA_TENANT_ID}}"
azureLaClientId = "{{.AZURE_LA_CLIENT_ID}}"
choreoJwtIssuer = "{{.CHOREO_JWT_ISSUER}}"
choreoJwtAudience = "{{.CHOREO_JWT_AUDIENCE}}"
site24x7JwtAudience = "{{.SITE24x7_JWT_AUDIENCE}}"
choreoJwtJwksUrl = "{{.CHOREO_JWT_JWKS_URL}}"
site24x7OrgUuid = "{{.SITE24x7_ORG_UUID}}"
healthCheckServicePort = 9090
[choreo.audit_logging.configs.azureLaWorkspaceIds]
US = "{{.US_LA_WORKSPACE_ID}}"

[ballerina.log]
level = "{{.LOG_LEVEL}}"
