resources:
  - tm-1-deployment.yaml
  - tm-1-hpa.yaml
  - tm-1-pdb.yaml
  - tm-1-service.yaml

configMapGenerator:
  - name: env-tm-1
    behavior: create
    literals:
      - JVM_MEM_OPTS="-Xms2048m -Xmx2048m"
      - PROFILE_NAME=traffic-manager

commonLabels:
  deployment: choreo-tm-1
