# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: choreo-connect-global-adapter
  namespace: {{ .Values.global.namespaces.apim }}
  labels:
    {{- include "choreo-connect-global-adapter.labels" . | nindent 4 }}
spec:
  provider: vault
  secretObjects:
    - secretName: choreo-connect-global-adapter
      type: Opaque
      data:
        - objectName: ga_admin_pwd
          key: ga_admin_pwd
        - objectName: ga_db_pwd
          key: ga_db_pwd
        - objectName: apim_admin_pwd
          key: apim_admin_pwd
        - objectName: asb_connection_string
          key: asb_connection_string
        - objectName: redis_password
          key: redis_password
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: mg.key
        secretKey: {{ .Values.secrets.mgwPrivateKey.key | quote }}
        secretPath: {{ .Values.secrets.mgwPrivateKey.path | quote }}
      - objectName: mg.pem
        secretKey: {{ .Values.secrets.mgwPublicKey.key | quote }}
        secretPath: {{ .Values.secrets.mgwPublicKey.path | quote }}
      - objectName: global-adapter.key
        secretKey: {{ .Values.secrets.gaPrivateKey.key | quote }}
        secretPath: {{ .Values.secrets.gaPrivateKey.path | quote }}
      - objectName: global-adapter.pem
        secretKey: {{ .Values.secrets.gaPublicKey.key | quote }}
        secretPath: {{ .Values.secrets.gaPublicKey.path | quote }}
      - objectName: ga_admin_pwd
        secretKey: {{ .Values.secrets.gaAdminPassword.key | quote }}
        secretPath: {{ .Values.secrets.gaAdminPassword.path | quote }}
      - objectName: ga_db_pwd
        secretKey: {{ .Values.secrets.gaDBPassword.key | quote }}
        secretPath: {{ .Values.secrets.gaDBPassword.path | quote }}
      - objectName: apim_admin_pwd
        secretKey: {{ .Values.secrets.apimAdminPassword.key | quote }}
        secretPath: {{ .Values.secrets.apimAdminPassword.path | quote }}
      - objectName: asb_connection_string
        secretKey: {{ .Values.secrets.asbConnectionString.key | quote }}
        secretPath: {{ .Values.secrets.asbConnectionString.path | quote }}
      - objectName: redis_password
        secretKey: {{ .Values.secrets.redisPassword.key | quote }}
        secretPath: {{ .Values.secrets.redisPassword.path | quote }}
