configMapGenerator:
  - name: cm-file-choreo-org-stat-data-collector
    behavior: create
    files:
      - choreo-org-stat/data-collector/Config.toml
  - name: cm-file-choreo-org-stat-data-publisher
    behavior: create
    files:
      - choreo-org-stat/data-publisher/application.properties
  - name: cm-file-choreo-bq-data-pipeline
    behavior: create
    files:
      - choreo-org-stat/bq-data-pipeline/application.properties
  - name: env-choreo-bq-data-pipeline
    behavior: create
    literals:
      - BIG_QUERY_TABLE_ID_FOR_APP_INSIGHTS="{{.BIG_QUERY_TABLE_ID_FOR_APP_INSIGHTS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_SUBSCRIPTIONS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_SUBSCRIPTIONS}}"
      - FIRST_RUN="{{.FIRST_RUN}}"
      - DURATION="{{.DURATION}}"
      - APP_DB_SERVER="{{.APP_DB_SERVER}}"
      - SUBSCRIPTIONS_DB_SERVER="{{.SUBSCRIPTIONS_DB_SERVER}}"
      - SCIM2_API_URL="{{.SCIM2_API_URL}}"
