configMapGenerator:
  - name: cm-file-choreo-org-stat-data-collector
    behavior: create
    files:
      - choreo-org-stat/data-collector/Config.toml
  - name: cm-file-choreo-org-stat-data-publisher
    behavior: create
    files:
      - choreo-org-stat/data-publisher/application.properties
  - name: cm-file-choreo-bq-data-pipeline
    behavior: create
    files:
      - choreo-org-stat/bq-data-pipeline/application.properties
  - name: env-choreo-bq-data-pipeline
    behavior: create
    literals:
      - BIG_QUERY_BASE_PATH = "{{.BIG_QUERY_BASE_PATH}}"
      - BIG_QUERY_TABLE_ID_FOR_APP_INSIGHTS="{{.BIG_QUERY_TABLE_ID_FOR_APP_INSIGHTS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_SUBSCRIPTIONS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_SUBSCRIPTIONS}}"
      - FIRST_RUN="{{.FIRST_RUN}}"
      - DURATION="{{.DURATION}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_PROJECT_MANAGER="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_PROJECT_MANAGER}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APP_ENVIRONMENTS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APP_ENVIRONMENTS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APPS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APPS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_DEPLOYMENT_HISTORIES="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_DEPLOYMENT_HISTORIES}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_CONTAINERS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_CONTAINERS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_ENVIRONMENTS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_ENVIRONMENTS}}"
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_PERMISSION={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_PERMISSION}}
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_USER={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_USER}}
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION}}
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION_USER_MAPPING={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION_USER_MAPPING}}
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIER="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIER}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIERV2="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIERV2}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTION="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTION}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTIONV2="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTIONV2}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_THRESHOLD="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_THRESHOLD}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_APP_ENVIRONMENTS="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_APP_ENVIRONMENTS | default "choreo_rudder_db.app_environments"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_APPS="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_APPS | default "choreo_rudder_db.apps"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_DEPLOYMENT_HISTORIES_TABLE="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_DEPLOYMENT_HISTORIES | default "choreo_rudder_db.deployment_histories"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_CONTAINERS_TABLE="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_CONTAINERS | default "choreo_rudder_db.containers"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_ENVIRONMENTS="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_ENVIRONMENTS | default "choreo_rudder_db.environments"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_EGRESS_POLICIES="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_EGRESS_POLICIES | default "choreo_rudder_db.egress_policies"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_EGRESS_POLICY_OVERRIDES="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_EGRESS_POLICY_OVERRIDES | default "choreo_rudder_db.egress_policy_overrides"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_EGRESS_POLICY_STATUSES="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_EGRESS_POLICY_STATUSES | default "choreo_rudder_db.egress_policy_statuses"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_APP_VOLUMES="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_APP_VOLUMES | default "choreo_rudder_db.app_volumes"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_COMPONENT_ENDPOINTS="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_COMPONENT_ENDPOINTS | default "choreo_rudder_db.component_endpoints"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_IMAGES="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_IMAGES | default "choreo_rudder_db.images"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_EXECUTIONS="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_EXECUTIONS | default "choreo_rudder_db.executions"}}"
      - BIG_QUERY_TABLE_FOR_RUDDER_DB_CUMULATIVE_DEPLOYMENT_TIME="{{.BIG_QUERY_TABLE_FOR_RUDDER_DB_CUMULATIVE_DEPLOYMENT_TIME | default "choreo_rudder_db.cumulative_deployment_time"}}"
      - BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_COMPONENTS="{{.BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_COMPONENTS}}"
      - BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_AM_PROJECTS="{{.BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_AM_PROJECTS}}"
      - CHOREO_PM_FIRST_RUN="{{.CHOREO_PM_FIRST_RUN}}"
      - CHOREO_RUDDER_FIRST_RUN="{{.CHOREO_RUDDER_FIRST_RUN}}"
      - CHOREO_APP_FIRST_RUN="{{.CHOREO_APP_FIRST_RUN}}"
      - CHOREO_PM_ALL_FIRST_RUN="{{.CHOREO_PM_ALL_FIRST_RUN}}"
      - CHOREO_SUBS_DB_FIRST_RUN="{{.CHOREO_SUBS_DB_FIRST_RUN}}"
      - APP_INSIGHTS_DATA_PROCESSOR_ENABLED="{{.APP_INSIGHTS_DATA_PROCESSOR_ENABLED}}"
      - CHOREO_APP_DB_ALL_DATA_PROCESSOR_ENABLED="{{.CHOREO_APP_DB_ALL_DATA_PROCESSOR_ENABLED}}"
      - CHOREO_SUBSCRIPTIONS_DB_DATA_PROCESSOR_ENABLED="{{.CHOREO_SUBSCRIPTIONS_DB_DATA_PROCESSOR_ENABLED}}"
      - CHOREO_SUBSCRIPTIONS_DB_ALL_DATA_PROCESSOR_ENABLED="{{.CHOREO_SUBSCRIPTIONS_DB_ALL_DATA_PROCESSOR_ENABLED}}"
      - CHOREO_PROJECT_MANAGER_DB_DATA_PROCESSOR_ENABLED="{{.CHOREO_PROJECT_MANAGER_DB_DATA_PROCESSOR_ENABLED}}"
      - CHOREO_RUDDER_DB_DATA_PROCESSOR_ENABLED="{{.CHOREO_RUDDER_DB_DATA_PROCESSOR_ENABLED}}"
      - CHOREO_PROJECT_MANAGER_DB_ALL_DATA_PROCESSOR_ENABLED="{{.CHOREO_PROJECT_MANAGER_DB_ALL_DATA_PROCESSOR_ENABLED}}"
