configMapGenerator:
  - name: cm-file-choreo-org-stat-data-collector
    behavior: create
    files:
      - choreo-org-stat/data-collector/Config.toml
  - name: cm-file-choreo-org-stat-data-publisher
    behavior: create
    files:
      - choreo-org-stat/data-publisher/application.properties
  - name: cm-file-choreo-bq-data-pipeline
    behavior: create
    files:
      - choreo-org-stat/bq-data-pipeline/application.properties
  - name: env-choreo-bq-data-pipeline
    behavior: create
    literals:
      - BIG_QUERY_TABLE_ID_FOR_APP_INSIGHTS="{{.BIG_QUERY_TABLE_ID_FOR_APP_INSIGHTS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_SUBSCRIPTIONS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_SUBSCRIPTIONS}}"
      - FIRST_RUN="{{.FIRST_RUN}}"
      - DURATION="{{.DURATION}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_PROJECT_MANAGER="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_PROJECT_MANAGER}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APP_ENVIRONMENTS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APP_ENVIRONMENTS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APPS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_APPS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_DEPLOYMENT_HISTORIES="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_DEPLOYMENT_HISTORIES}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_CONTAINERS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_CONTAINERS}}"
      - BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_ENVIRONMENTS="{{.BIG_QUERY_TABLE_ID_FOR_ANALYTICS_CHOREO_ENVIRONMENTS}}"
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_PERMISSION={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_PERMISSION}}
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_USER={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_USER}}
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION}}
      - BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION_USER_MAPPING={{.BIG_QUERY_TABLE_ID_FOR_APP_DB_ORGANIZATION_USER_MAPPING}}
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIER="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIER}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIERV2="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_TIERV2}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTION="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTION}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTIONV2="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_SUBSCRIPTIONV2}}"
      - BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_THRESHOLD="{{.BIG_QUERY_TABLE_ID_FOR_CHOREO_SUBSCRIPTIONS_DB_THRESHOLD}}"
      - BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_COMPONENTS="{{.BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_COMPONENTS}}"
      - BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_AM_PROJECTS="{{.BIG_QUERY_TABLE_ID_FOR_PROJECT_DB_AM_PROJECTS}}"
      - CHOREO_PM_FIRST_RUN="{{.CHOREO_PM_FIRST_RUN}}"
      - CHOREO_RUDDER_FIRST_RUN="{{.CHOREO_RUDDER_FIRST_RUN}}"
      - CHOREO_APP_FIRST_RUN="{{.CHOREO_APP_FIRST_RUN}}"
      - CHOREO_PM_ALL_FIRST_RUN="{{.CHOREO_PM_ALL_FIRST_RUN}}"
      - ENABLE_PROJECT_MANAGER_DB_ALL_DATA_PROCESSOR="{{.ENABLE_PROJECT_MANAGER_DB_ALL_DATA_PROCESSOR}}"
