apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-choreo-bq-data-pipeline
spec:
  secretObjects:
    - secretName: secret-choreo-bq-data-pipeline
      type: Opaque
      data:
        - objectName: GOOGLE_APPLICATION_CREDENTIALS
          key: GOOGLE_APPLICATION_CREDENTIALS
        - objectName: CHOREO_APP_INSIGHTS_API_KEY
          key: CHOREO_APP_INSIGHTS_API_KEY
        - objectName: CHOREO_APP_INSIGHTS_APP_ID
          key: CHOREO_APP_INSIGHTS_APP_ID
        - objectName: SUBSCRIPTIONS_DB_PASSWORD
          key: SUBSCRIPTIONS_DB_PASSWORD
        - objectName: APP_DB_PASSWORD
          key: APP_DB_PASSWORD
        - objectName: SCIM2_API_PASSWORD
          key: SCIM2_API_PASSWORD
        - objectName: MONGODB_PASSWORD
          key: MONGODB_PASSWORD
        - objectName: RUDDER_DB_PASSWORD
          key: RUDDER_DB_PASSWORD
        - objectName: BILLING_DB_PASSWORD
          key: BILLING_DB_PASSWORD
  parameters:
    objects: |
      array:
        - |
          objectName: bq-data-pipeline-google-sa-credentials
          objectType: secret
          objectAlias: GOOGLE_APPLICATION_CREDENTIALS
          objectVersion: "{{.GOOGLE_APPLICATION_CREDENTIALS}}"
        - |
          objectName: bq-data-pipeline-choreo-app-insights-api-key
          objectType: secret
          objectAlias: CHOREO_APP_INSIGHTS_API_KEY
          objectVersion: "{{.CHOREO_APP_INSIGHTS_API_KEY}}"
        - |
          objectName: bq-data-pipeline-choreo-app-insights-app-id
          objectType: secret
          objectAlias: CHOREO_APP_INSIGHTS_APP_ID
          objectVersion: "{{.CHOREO_APP_INSIGHTS_APP_ID}}"
        - |
          objectName: choreo-subscriptions-db-mssql-password
          objectType: secret
          objectAlias: SUBSCRIPTIONS_DB_PASSWORD
          objectVersion: "{{.SUBSCRIPTIONS_DB_PASSWORD}}"
        - |
          objectName: choreo-app-db-mssql-password
          objectType: secret
          objectAlias: APP_DB_PASSWORD
          objectVersion: "{{.APP_DB_PASSWORD}}"
        - |
          objectName: idp-SCIM-BACKEND-API-USER-PASSWORD
          objectType: secret
          objectAlias: SCIM2_API_PASSWORD
          objectVersion: "{{.SCIM2_API_PASSWORD}}"
        - |
          objectName: dp-project-manager-MONGODB-PASSWORD
          objectType: secret
          objectAlias: MONGODB_PASSWORD
          objectVersion: "{{.MONGODB_PASSWORD}}"
        - |
          objectName: dp-CHOREO-RUDDER-MSSQL-PASSWORD
          objectType: secret
          objectAlias: RUDDER_DB_PASSWORD
          objectVersion: "{{.RUDDER_DB_PASSWORD}}"
        - |
          objectName: billing-DB-SQL-PASSWORD
          objectType: secret
          objectAlias: BILLING_DB_PASSWORD
          objectVersion: "{{.BILLING_DB_PASSWORD}}"
