resources:
  - org-stat-data-collector.yaml
  - org-stat-data-publisher.yaml
  - choreo-bq-data-pipeline.yaml

patches:
  - path: patch.json
    target:
      group: secrets-store.csi.x-k8s.io
      version: v1
      kind: SecretProviderClass
