apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-choreo-org-stat-data-publisher
spec:
  secretObjects:
    - secretName: secret-choreo-org-stat-data-publisher
      type: Opaque
      data:
        - objectName: ANALYTICS_DB_PASSWORD
          key: ANALYTICS_DB_PASSWORD
        - objectName: KUSTO_CLIENT_SECRET
          key: KUSTO_CLIENT_SECRET
        - objectName: SAS_TOKEN
          key: SAS_TOKEN
        - objectName: GOOGLE_SHEETS_CLIENT_SECRET
          key: GOOGLE_SHEETS_CLIENT_SECRET
        - objectName: GOOGLE_SHEETS_TOKEN
          key: GOOGLE_SHEETS_TOKEN
        - objectName: GOOGLE_SHEETS_REFRESH_TOKEN
          key: GOOGLE_SHEETS_REFRESH_TOKEN
        - objectName: APIM_ADMIN_API_PASSWORD
          key: APIM_ADMIN_API_PASSWORD
        - objectName: APP_DB_PASSWORD
          key: APP_DB_PASSWORD
        - objectName: SCIM2_API_PASSWORD
          key: SCIM2_API_PASSWORD
        - objectName: BILLING_DB_PASSWORD
          key: BILLING_DB_PASSWORD
        - objectName: SUBSCRIPTIONS_DB_PASSWORD
          key: SUBSCRIPTIONS_DB_PASSWORD
        - objectName: MONGODB_PASSWORD
          key: MONGODB_PASSWORD
        - objectName: STRIPE_API_KEY
          key: STRIPE_API_KEY
        - objectName: LOG_ANALYTICS_CLIENT_SECRET
          key: LOG_ANALYTICS_CLIENT_SECRET
        - objectName: RUDDER_DB_PASSWORD
          key: RUDDER_DB_PASSWORD
  parameters:
    objects: |
      array:
        - |
          objectName: org-stat-ANALYTICS-DB-PASSWORD
          objectType: secret
          objectAlias: ANALYTICS_DB_PASSWORD
          objectVersion: "{{.ANALYTICS_DB_PASSWORD}}"
        - |
          objectName: org-stat-KUSTO-CLIENT-SECRET
          objectType: secret
          objectAlias: KUSTO_CLIENT_SECRET
          objectVersion: "{{.KUSTO_CLIENT_SECRET}}"
        - |
          objectName: org-stat-SAS-TOKEN
          objectType: secret
          objectAlias: SAS_TOKEN
          objectVersion: "{{.SAS_TOKEN}}"
        - |
          objectName: org-stat-GOOGLE-SHEETS-CLIENT-SECRET
          objectType: secret
          objectAlias: GOOGLE_SHEETS_CLIENT_SECRET
          objectVersion: "{{.GOOGLE_SHEETS_CLIENT_SECRET}}"
        - |
          objectName: org-stat-GOOGLE-SHEETS-TOKEN
          objectType: secret
          objectAlias: GOOGLE_SHEETS_TOKEN
          objectVersion: "{{.GOOGLE_SHEETS_TOKEN}}"
        - |
          objectName: org-stat-GOOGLE-SHEETS-REFRESH-TOKEN
          objectType: secret
          objectAlias: GOOGLE_SHEETS_REFRESH_TOKEN
          objectVersion: "{{.GOOGLE_SHEETS_REFRESH_TOKEN}}"
        - |
          objectName: org-stat-ADMIN-PORTAL-PASSWORD
          objectType: secret
          objectAlias: APIM_ADMIN_API_PASSWORD
          objectVersion: "{{.APIM_ADMIN_API_PASSWORD}}"
        - |
          objectName: choreo-app-db-mssql-password
          objectType: secret
          objectAlias: APP_DB_PASSWORD
          objectVersion: "{{.APP_DB_PASSWORD}}"
        - |
          objectName: idp-SCIM-BACKEND-API-USER-PASSWORD
          objectType: secret
          objectAlias: SCIM2_API_PASSWORD
          objectVersion: "{{.SCIM2_API_PASSWORD}}"
        - |
          objectName: billing-DB-SQL-PASSWORD
          objectType: secret
          objectAlias: BILLING_DB_PASSWORD
          objectVersion: "{{.BILLING_DB_PASSWORD}}"
        - |
          objectName: choreo-subscriptions-db-mssql-password
          objectType: secret
          objectAlias: SUBSCRIPTIONS_DB_PASSWORD
          objectVersion: "{{.SUBSCRIPTIONS_DB_PASSWORD}}"
        - |
          objectName: dp-project-manager-MONGODB-PASSWORD
          objectType: secret
          objectAlias: MONGODB_PASSWORD
          objectVersion: "{{.MONGODB_PASSWORD}}"
        - |
          objectName: org-stat-STRIPE-API-KEY
          objectType: secret
          objectAlias: STRIPE_API_KEY
          objectVersion: "{{.STRIPE_API_KEY}}"
        - |
          objectName: choreo-log-analytics-read-org-stats-dashboard
          objectType: secret
          objectAlias: LOG_ANALYTICS_CLIENT_SECRET
          objectVersion: "{{.LOG_ANALYTICS_CLIENT_SECRET}}"
        - |
          objectName: dp-CHOREO-RUDDER-MSSQL-PASSWORD
          objectType: secret
          objectAlias: RUDDER_DB_PASSWORD
          objectVersion: "{{.RUDDER_DB_PASSWORD}}"
