resources:
  repositories:
    - repository: BASE_REPOSITORY
      type: github
      name: wso2-enterprise/choreo-control-plane
      ref: refs/heads/main-ci
      endpoint: choreo-cicd-committer
  webhooks:
    - webhook: AzureComponentVersionUpdateTrigger
      connection: system-azure-resource-version-update-trigger-connection

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: BASE_REPOSITORY
    persistCredentials: true
  - task: Bash@3
    displayName: Update Azure component version
    inputs:
      targetType: inline
      script: |
        echo "Pipeline triggered from a webhook"

        componentName="${{ parameters.AzureComponentVersionUpdateTrigger.componentName }}"
        newVersion="${{ parameters.AzureComponentVersionUpdateTrigger.newVersion }}"

        ## Check the component type sent through the webhook. Exit if it is unrecognized.
        ## Otherwise new files will be created for each such component type
        case ${{ parameters.AzureComponentVersionUpdateTrigger.componentType }} in
          app-service)
            versionFilename=app-service-deployer.properties
            ;;
          function-app)
            versionFilename=function-app-deployer.properties
            ;;
          machine-learning)
            versionFilename=machine-learning-deployer.properties
            ;;
          stream-analytics-job)
            versionFilename=stream-analytics-job-deployer.properties
            ;;
          autotrainer)
            versionFilename=ai-autotrainer-deployer.properties
            ;;
          *)
            echo "[ERROR] Unrecognized component type"
            exit 1
            ;;
        esac

        git config --global user.email "choreo-cicd@wso2.com"
        git config --global user.name "Choreo CI Agent"

        if [ ! -d azure-resources/base-ci ]; then
          mkdir -p azure-resources/base-ci
        fi
        cd azure-resources/base-ci
        if [ ! -f $versionFilename ]; then
          touch $versionFilename
          git add $versionFilename
        fi

        ## Build can be retriggered for the same commit. Then there is nothing to update
        if grep -q "$componentName=$newVersion" $versionFilename; then
          echo "$componentName is already at version $newVersion. Nothing to update"
          exit 0
        fi

        echo "Updating $componentName version to $newVersion..."
        if grep -q "$componentName" $versionFilename; then
          sed -i "s/$componentName.*/$componentName=$newVersion/" $versionFilename
        else
          echo "$componentName=$newVersion" >> $versionFilename
        fi
        sort --output=$versionFilename $versionFilename

        git diff
        git commit -am "Update component version in $(Build.BuildNumber)"
        git remote -v
        git branch -al
        if git push origin HEAD:$(Build.SourceBranchName) ; then
          echo "Changes pushed successfully"
        else
          git fetch origin
          git merge --no-edit --strategy recursive --strategy-option theirs origin/$(Build.SourceBranchName)
          git push origin HEAD:$(Build.SourceBranchName)
        fi
