trigger: none

variables:
  - group: ad-app-expiry-alert

jobs:
  - job: CheckAppExpiry
    timeoutInMinutes: 0
    steps:
      - script: .azure/src/entra-apps/get_expiring_entra_apps.sh
        displayName: Get expiring entra apps
        workingDirectory: .azure/src/entra-apps
        env:
          CLIENT_ID: $(client_id)
          CLIENT_SECRET: $(client_secret)
          TENANT_ID: da76d684-740f-4d94-8717-9d5fb21dd1f9
          OUTPUT_PATH: $(Build.ArtifactStagingDirectory)
          BUILD_URL: "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=artifacts&pathAsName=false&type=publishedArtifacts"
          WEBHOOK_URL: $(webhook_url)
      - task: PublishPipelineArtifact@1
        condition: failed()
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifact: output
          publishLocation: 'pipeline'
