resources:
  repositories:
    - repository: choreo-common-pipeline-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise

trigger: none

pr:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: install/install-yamllint.yaml@choreo-common-pipeline-templates
  - template: install/install-shellcheck.yaml@choreo-common-pipeline-templates
  - script: |
      npm install -g markdownlint-cli
    displayName: Install markdownlint-cli
  - script: |
      yamllint -c .yamllint/config.yaml .
    displayName: Lint YAML files
  - script: |
      shellcheck ./**/*.sh
    displayName: Lint Shell scripts
  - script: |
      markdownlint '**/*.md'
    displayName: Lint Markdown files
