# Suppressed Checks
# CKV_K8S_14 - Image Tag Should be Fixed - Not Latest or Blank
# CKV_K8S_15 - Image Pull Policy should be Always
# CKV_K8S_35 - Prefer using secrets as files over secrets as environment variables

resources:
  repositories:
  - repository: TEMPLATE_REPOSITORY
    type: github
    name: wso2-enterprise/choreo-common-pipeline-templates
    ref: refs/heads/main
    endpoint: choreo-cicd
  - repository: templates
    type: github
    name: wso2-enterprise/azure-pipeline-templates
    ref: refs/heads/dev
    endpoint: choreo-cicd

trigger: none

pr:
  branches:
    include:
    - 'main'

pool:
  vmImage: ubuntu-latest

stages:
- stage: kustomize
  displayName: 'Run Kustomize checks'
  jobs:
  - job: kustomize
    pool: 
      vmImage: ubuntu-latest
    steps:
      - template: install/install-kustomize.yml@TEMPLATE_REPOSITORY
      - script: |
          set -eo pipefail
          cd kustomize/base
          mkdir build
          $KUSTOMIZE build . | tee build/kustomize-all.yml
        displayName: 'Generate k8s artifacts'
      - script: |
          echo "Running Checkov Scan!"
          sudo apt-get install python3.7
          pip3 install --upgrade pip && pip3 install --upgrade setuptools
          pip3 install dataclasses
          pip3 install checkov
          /home/vsts/.local/bin/checkov -f kustomize/base/build/kustomize-all.yml --framework kubernetes \
          --skip-check CKV_K8S_14,CKV_K8S_15,CKV_K8S_35
        displayName: 'Kustomize code scan using Checkov'
- stage: helm
  displayName: 'Run Helm checks'
  jobs:
  - job: CustomYamlLintConfigsforHelm
    pool: 
      vmImage: ubuntu-latest
    steps:
      - script: |
          echo "Change .github/linters/.yaml-lint.yml file"
          sed -i "s|*dbscripts-for-structure-configmap.yaml|*|g" .github/linters/.yaml-lint.yml
          sed -i "s|*dbscripts-for-structure-idp-configmap.yaml|!/*template.yaml|g" .github/linters/.yaml-lint.yml
        displayName: 'Generate k8s artifacts'
  - template: cd-pipelines/templates/static-scan-helm.yaml@templates
    parameters:
      HELM_CHART_NAME: 'databases'
      HELM_INPUT_VALUES: 'azure.database.server=azure_database_server'
      CHECKOV_SUPPRESSIONS: 'CKV_K8S_14,CKV_K8S_15,CKV_K8S_35'
