resources:
  repositories:
    - repository: choreo-common-pipeline-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise

trigger: none

pr:
  branches:
    include:
      - 'main'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      docker run \
        -e DEFAULT_BRANCH=$(System.PullRequest.TargetBranch) \
        -e RUN_LOCAL=true \
        -e VALIDATE_YAML=true \
        -e VALIDATE_BASH=true \
        -v $(System.DefaultWorkingDirectory):/tmp/lint ghcr.io/super-linter/super-linter:slim-latest
  - script: |
      set -eo pipefail
      mapfile -t charts < <(find . -name "Chart.y*ml" -depth 2)
      for chart in "${charts[@]}"; do
        path=${chart%Chart.y*ml}
        helm lint "$path"
      done
    displayName: Helm Lint
    workingDirectory: cdp-helm-charts
