resources:
  webhooks:
  - webhook: ImageUpdateTrigger
    connection: system-image-update-trigger-connection
  repositories:
  - repository: TEMPLATE_REPOSITORY
    type: github
    name: wso2-enterprise/choreo-common-pipeline-templates
    ref: refs/heads/main
    endpoint: choreo-cicd

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
- template: install/install-kustomize.yml@TEMPLATE_REPOSITORY
- script: |
    echo "Pipeline triggered from a webhook"
    updatedImages="${{ parameters.ImageUpdateTrigger.updatedImages }}"
    
    cd kustomize/base-ci

    trimmedUpdatedImages=${updatedImages//$'\n'/}
    echo "Repos : $trimmedUpdatedImages"
    echo "$trimmedUpdatedImages" | tr ',' '\n' | while read imageName; do
      echo "Updating image tag for $imageName"
      $KUSTOMIZE edit set image "$imageName"
    done

    git config --global user.email "choreo-cicd@wso2.com"
    git config --global user.name "Choreo CI Agent"
    git diff
    git commit -am "Update image tags in $(Build.BuildNumber)"
    git remote -v
    git branch -al
    if git push origin HEAD:$(Build.SourceBranchName) ; then
      echo "Changes pushed successfully"
    else
      git fetch origin
      git merge --no-edit --strategy recursive --strategy-option theirs origin/$(Build.SourceBranchName)
      git push origin HEAD:$(Build.SourceBranchName)
    fi
  displayName: 'Update image latest tags'
