resources:
  webhooks:
    - webhook: ImageUpdateTrigger
      connection: system-image-update-trigger-connection
  repositories:
    - repository: TEMPLATE_REPOSITORY
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise
    - repository: BASE_REPOSITORY
      type: github
      name: wso2-enterprise/choreo-control-plane
      ref: refs/heads/main-ci
      endpoint: choreo-cicd-committer

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: BASE_REPOSITORY
    persistCredentials: true
  - template: install/install-kustomize.yml@TEMPLATE_REPOSITORY
  - script: .azure/src/image-update/updater.sh
    displayName: Update latest image tags
    env:
      UPDATED_CONFIGS: ${{ parameters.ImageUpdateTrigger.updatedConfigs }}
      BRANCH: $(Build.SourceBranchName)
      BUILD_NUMBER: $(Build.BuildNumber)
      UPDATED_IMAGE_MAP: ${{ parameters.ImageUpdateTrigger.updatedImageMap }}
      UPDATED_IMAGES: ${{ parameters.ImageUpdateTrigger.updatedImages }}
      CLUSTER_NAME: ${{ parameters.ImageUpdateTrigger.clusterName }}
      CLUSTER_CONFIG_PATH: $(Build.SourcesDirectory)/.azure/src/image-update/cluster-mapping.yaml
      BASE_PATH: $(Build.SourcesDirectory)
