resources:
  repositories:
  - repository: CP_OVERLAY_REPOSITORY
    type: github
    name: wso2-enterprise/choreo-cp-env-overlay
    ref: refs/heads/stage-ci
    endpoint: choreo-cicd-committer

trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: OVERLAY_WORKING_DIRECTORY
  value: choreo-cp-env-overlay

jobs:
- job: approvalForStage
  displayName: Wait for approval
  timeoutInMinutes: 10080 # job times out in 7 days
  pool: server
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 10080 # task times out in 7 days
    inputs:
      notifyUsers: |
        asankaab@wso2.com
        ching@wso2.com
        sachithka@wso2.com
        shana@wso2.com
        shafana@wso2.com
      instructions: 'Please resume to update stage base version to $(Build.SourceVersion)'
      onTimeout: 'reject'
- job: UpdateStage
  dependsOn: approvalForStage
  condition: succeeded()
  displayName: Update stage
  steps:
  - checkout: self
  - checkout: CP_OVERLAY_REPOSITORY
    persistCredentials: true
  - script: |
      git config --global user.email "choreo-cicd@wso2.com"
      git config --global user.name "Choreo CI Agent"
      
      echo "$(Build.SourceBranchName)" > kustomize/base.version
      git diff
      git commit -am "Update base version to $(Build.SourceBranchName)"
      git remote -v
      if git push origin HEAD:stage-ci ; then
        echo "Changes pushed successfully"
      else
        git fetch origin
        git merge --no-edit --strategy recursive --strategy-option theirs origin/stage-ci
        git push origin HEAD:stage-ci
      fi
    displayName: 'Update base version'
    workingDirectory: $(OVERLAY_WORKING_DIRECTORY)
