resources:
  repositories:
  - repository: CP_OVERLAY_REPOSITORY
    type: github
    name: wso2-enterprise/choreo-cp-env-overlay
    ref: refs/heads/dev-ci
    endpoint: choreo-cicd-committer

trigger:
  batch: true
  branches:
    include:
    - main-ci
  paths:
    include:
    - azure-resources/base-ci/*
    - kustomize/*
    - .azure/control-plane-update.yml
    - e2e-tests-cypress/*
    - integration-tests/*
    - cdn/versions.yaml

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: OVERLAY_WORKING_DIRECTORY
  value: choreo-cp-env-overlay

steps:
- checkout: self
- checkout: CP_OVERLAY_REPOSITORY
  persistCredentials: true
- script: |
    git config --global user.email "choreo-cicd@wso2.com"
    git config --global user.name "Choreo CI Agent"
    
    echo "$(Build.SourceVersion)" > kustomize/basev2.version
    git diff
    git commit -am "Update base version tags in $(Build.SourceVersion)"
    git remote -v
    if git push origin HEAD:dev-ci ; then
      echo "Changes pushed successfully"
    else
      git fetch origin
      git merge --no-edit --strategy recursive --strategy-option theirs origin/dev-ci
      git push origin HEAD:dev-ci
    fi
  displayName: 'Update base version'
  workingDirectory: $(OVERLAY_WORKING_DIRECTORY)
