resources:
  repositories:
    - repository: TEMPLATE_REPOSITORY
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise
    - repository: OVERLAY_REPOSITORY
      type: github
      name: wso2-enterprise/choreo-cp-env-overlay
      ref: refs/heads/dev-ci
      endpoint: wso2-enterprise

trigger: none

pr:
  branches:
    include:
      - 'main'
      - 'deprecated'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: PlanExecution
    displayName: 'Calculating Changes'
    jobs:
      - job: DecideChecks
        steps:
          - template: templates/calculate-changes.yaml
            parameters:
              PIPELINE_DEFINITION: '.azure/control-plane-deploy-pr-check.yml'
      - job: CPPRCheck
        pool: choreo-dev-custom-cp-vmss-agents
        dependsOn: DecideChecks
        condition: >-
          or(eq(dependencies.DecideChecks.outputs['DetermineRun.runAllChecks'], 'true'),
          eq(dependencies.DecideChecks.outputs['DetermineRun.runCPPRCheck'], 'true'))
        steps:
          - checkout: self
          - checkout: OVERLAY_REPOSITORY
          - checkout: TEMPLATE_REPOSITORY
          - template: install/install-kustomize.yml@TEMPLATE_REPOSITORY
          - template: install/install-kapp.yml@TEMPLATE_REPOSITORY
          - script: |
              echo '{ "bip": "172.35.0.1/16" }' | sudo tee /etc/docker/daemon.json
              sudo systemctl restart docker
            displayName: 'Change Docker Bridge IP'
          - template: templates/run-build.yml
            parameters:
              OVERLAY_SUB_DIR: 'dev-control-plane'
              AZURE_SUBSCRIPTION: 'choreo-dev-aks-rg'
              AKS_RESOURCE_GROUP: 'choreo-dev-aks-rg'
              AKS_CLUSTER_NAME: 'choreo-dev-controlplane-aks-cluster'
              APP_NAME: 'choreo-dev-replica'
              BASE_KUSTOMIZATION_FILE: 'kustomize/dev-control-plane/base/kustomization.yaml'
      - job: DataplanePRCheck
        pool: choreo-dev-custom-dp-vmss-agents
        dependsOn: DecideChecks
        condition: >-
          or(eq(dependencies.DecideChecks.outputs['DetermineRun.runAllChecks'], 'true'),
          eq(dependencies.DecideChecks.outputs['DetermineRun.runDataplanePRCheck'], 'true'))
        steps:
          - checkout: self
          - checkout: TEMPLATE_REPOSITORY
          - template: install/install-kustomize.yml@TEMPLATE_REPOSITORY
          - template: install/install-kapp.yml@TEMPLATE_REPOSITORY
          - script: |
              echo '{ "bip": "172.35.0.1/16" }' | sudo tee /etc/docker/daemon.json
              sudo systemctl restart docker
            displayName: 'Change Docker Bridge IP'
          - template: templates/run-build.yml
            parameters:
              OVERLAY_SUB_DIR: 'dev-dataplane'
              AZURE_SUBSCRIPTION: 'choreo-dev-dataplane-e1-aks-rg'
              AKS_RESOURCE_GROUP: 'choreo-dev-dataplane-e1-aks-rg'
              AKS_CLUSTER_NAME: 'choreo-dev-dataplane-aks-cluster'
              APP_NAME: 'choreo-dev-replica'
              BASE_KUSTOMIZATION_FILE: 'kustomize/dev-dataplane/base/kustomization.yaml'
              UPDATE_KUSTOMIZE_CI_PATH: 's/- ..\/..\/..\/..\/choreo-control-plane\/kustomize\/dataplane-ci/- ..\/..\/..\/..\/choreo-control-plane\/kustomize\/dataplane/'
      - job: RoutingClusterPRCheck
        pool: choreo-dev-custom-dp-vmss-agents
        dependsOn: DecideChecks
        condition: >-
          or(eq(dependencies.DecideChecks.outputs['DetermineRun.runAllChecks'], 'true'),
          eq(dependencies.DecideChecks.outputs['DetermineRun.runRoutingClusterPRCheck'], 'true'))
        steps:
          - checkout: self
          - checkout: TEMPLATE_REPOSITORY
          - template: install/install-kustomize.yml@TEMPLATE_REPOSITORY
          - template: install/install-kapp.yml@TEMPLATE_REPOSITORY
          - script: |
              echo '{ "bip": "172.35.0.1/16" }' | sudo tee /etc/docker/daemon.json
              sudo systemctl restart docker
            displayName: 'Change Docker Bridge IP'
          - template: templates/run-build.yml
            parameters:
              OVERLAY_SUB_DIR: 'dev-routing'
              AZURE_SUBSCRIPTION: 'choreo-dev-routing-aks-rg'
              AKS_RESOURCE_GROUP: 'choreo-dev-routing-aks-rg'
              AKS_CLUSTER_NAME: 'choreo-dev-routing-aks-cluster'
              APP_NAME: 'choreo-dev-replica'
              BASE_KUSTOMIZATION_FILE: 'kustomize/dev-routing/base/kustomization.yaml'
              UPDATE_KUSTOMIZE_CI_PATH: 's/- ..\/..\/..\/..\/choreo-control-plane\/kustomize\/routing-ci/- ..\/..\/..\/..\/choreo-control-plane\/kustomize\/routing/'
