trigger:
  batch: true
  branches:
    include:
    - azure-pipeline

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing customize in the environment"
    mkdir $HOME/bin
    pushd $HOME/bin
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    export PATH=$HOME/bin:$PATH
    echo $PATH
    popd
  displayName: Setup kustomize'
