trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - kustomize/base/*
    - kustomize/dev/*
    - .azure/dev-deploy.yml

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing kustomize in the environment"
    mkdir $HOME/bin
    pushd $HOME/bin
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    echo "##vso[task.setvariable variable=KUSTOMIZE]$(HOME)/bin/kustomize"
    popd
  displayName: 'Setup kustomize'
- script: |
    cd kustomize
    mkdir build
    $KUSTOMIZE build dev | tee build/kustomize-all.yml
  displayName: 'Generate k8s artifacts'
- task: Kubernetes@1
  displayName: 'kubectl apply'
  inputs:
    kubernetesServiceEndpoint: 'choreo-dev-aks'
    command: apply
    arguments: '-f kustomize/build/kustomize-all.yml'
