trigger: none
pr: none

variables:
  - group: routing-merger

steps:
  - script: |
      pip3 install bs4
    displayName: 'Install tools and requirements'
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath' # 'filePath' | 'inline'. Required. Script source. Default: filePath.
      scriptPath: scripts/routing-merger/test_routing_merger.py
      arguments: "$(MANAGED_AUTH_USERNAME) $(MANAGED_AUTH_PASSWORD)"
