# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_25=Temporarily suppressing till fixing
    checkov.io/skip2: CKV_K8S_38=The SA token is required for the linkerd to define service identity
  labels:
    {{- include "sts-mgt-service.labels" . | nindent 4 }}
  name: sts-mgt-service
  namespace: {{ .Values.global.namespaces.system }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sts-mgt-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sts-mgt-service.labels" . | nindent 8 }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sts-mgt-service
          image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: service-port
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: service-port
              path: /health
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: service-port
              path: /health
          resources:
            limits:
              cpu: 300m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 500Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10500
            runAsGroup: 10500
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: sts-mgt-service
          volumeMounts:
            - name: secret-sts-mgt-service
              mountPath: "/mnt/csi/secret-sts-mgt-svc"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: secret-sts-mgt-service
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: sts-mgt-service
      serviceAccountName: sts-mgt-service
      {{- if .Values.autoscaling.enabled }}
      {{- $minReplicas := .Values.autoscaling.minReplicas | int64 }}
      {{- if ge $minReplicas 2 }}
      {{- include "sts-mgt-service.affinity" . | nindent 6 }}
      {{- end }}
      {{- end }}
