[b7a.observability]
enabled=true
provider="choreo"

[b7a.observability.choreo.reporter]
hostname="periscope.dv.choreo.dev"
port=443

[b7a.observability.choreo.application]
secret="sec_65d6a92f-7220-4577-997d-77dc3d40e815"
