apiVersion: apps/v1
kind: Deployment
metadata:
  name: choreo-connect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: choreo-connect-deployment-dev-us-east-azure-p1
  template:
    metadata:
      labels:
        choreo.component: choreo-connect-deployment-dev-us-east-azure-p1
    spec:
     initContainers:
       - name: init-adapter-service
         command: [ 'sh', '-c', 'echo -e "Checking for the availability of Adapter"; while ! nc -z adapter-dev-us-east-azure-p1 18000; do sleep 1; printf "-"; done; echo -e "  >> Adapter has started";' ]
     containers:
       - name: choreo-connect-enforcer
         env:
         - name: ADAPTER_HOST
           value: adapter-dev-us-east-azure-p1
         - name: ENFORCER_LABEL
           value: dev-us-east-azure
       - name: choreo-connect-router
         env:
         - name: ADAPTER_HOST
           value: adapter-dev-us-east-azure-p1
         - name: ROUTER_LABEL
           value: dev-us-east-azure           
