# --------------------------------------------------------------------
# Copyright (c) 2022, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-kv-resolver
  labels:
    choreo.component: dp-kv-resolver
  annotations:
    checkov.io/skip1: CKV_K8S_38=Need this to read kubeconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: dp-kv-resolver
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        choreo.component: dp-kv-resolver
        antiaffinity: dp-kv-resolver
        userapp-ingress-allowed: "true"
    spec:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kube-rbac-proxy
          image: choreocontrolplane.azurecr.io/choreoipaas/kube-rbac-proxy:latest
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          ports:
            - containerPort: 8443
              name: proxy-port
          livenessProbe:
            tcpSocket:
              port: proxy-port
          readinessProbe:
            tcpSocket:
              port: proxy-port
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
        - name: manager
          image: choreocontrolplane.azurecr.io/choreoipaas/dp-kv-resolver:latest
          args:
            - --health-probe-bind-address=:8081
            - --leader-elect
          command:
            - /manager
          ports:
            - containerPort: 9090
              name: api-port
              protocol: TCP
            - containerPort: 8081
              name: probe-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probe-port
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe-port
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: 2Gi
              cpu: "1"
            limits:
              memory: 4Gi
              cpu: "1.5"
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          envFrom:
            - configMapRef:
                name: env-dp-kv-resolver
            - secretRef:
                name: secret-dp-kv-resolver
                optional: true
          volumeMounts:
            - name: secret-dp-kv-resolver
              mountPath: /mnt/csi/secret-dp-kv-resolver
              readOnly: true
      volumes:
        - name: secret-dp-kv-resolver
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-dp-kv-resolver
            nodePublishSecretRef:
              name: csi-secret-store-azure
      restartPolicy: Always
      serviceAccountName: dp-kv-resolver-controller-manager
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: antiaffinity
                    operator: In
                    values:
                      - dp-kv-resolver
              topologyKey: kubernetes.io/hostname
