[choreo_cp_endpoint_resolver.config]
servicePort=9090
healthPort=9092

rudderEndpoint = "http://dp-rudder:80/api/v1"
projectManagerEndpoint = "http://dp-project-manager:80/api/v1"
apimEndpoint = "{{.APIM_HOST_URL}}"

apimClientId = "{{.APIM_REST_API_CONSUMER_KEY}}"

[ballerina.log]
format="json"
level="{{.LOG_LEVEL}}"
