apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
spec:
  minReplicas: 50
  maxReplicas: 70
  scaleTargetRef:
    name: runners
  scaleUpTriggers:
    - githubEvent:
        checkRun:
          types: [ "created" ]
          status: "queued"
      amount: 1
      duration: "2m"
