apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
spec:
  minReplicas: 50
  maxReplicas: 70
  scaleTargetRef:
    name: runners
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      # The duration field sets the maximum amount of time to wait for a scale-down event in 
      # case if a scale-up event is not received.
      # This value should account for the time it takes to run the workflow job and 
      # the time it takes to start the runner including image pull time.
      duration: "30m"
