apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: choreo-aws-marketplace-client-pdb
  labels:
    choreo.component: choreo-aws-marketplace-client
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      choreo.component: choreo-aws-marketplace-client
