apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cp-gw-adapter
  namespace: choreo-system
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      choreo.component: cp-gw-adapter
