resources:
  - alert-notification-service.yaml
  - analytics-subscription.yaml
  - anomaly-detector.yaml
  - api-server.yaml
  - apim-service.yaml
  - app-deployer.yaml
  - app-service.yaml
  - connector-builder.yaml
  - connectords.yaml
  - console-next.yaml
  - cp-graphql.yaml
  - datacollector.yaml
  - datamapper.yaml
  - delete-manager.yaml
  - dp-cicd.yaml
  - dp-cloud-manager.yaml
  - dp-garbage-collector.yaml
  - dp-mizzen.yaml
  - dp-project-manager.yaml
  - dp-rudder.yaml
  - dp-secret-manager.yaml
  - dp-utility-api.yaml
  - email-service.yaml
  - frontend.yaml
  - loggingapi.yaml
  - multivariate-anomaly-detector-notification-manager.yaml
  - negotiator.yaml
  - obsapi.yaml
  - orgremover.yaml
  - perfanalyzer-estimator.yaml
  - quota-limiter.yaml
  - subscriptions.yaml
  - sys-obsapi.yaml
  - telemetry.yaml
  - test-assistant.yaml
  - testbase.yaml
  - workspace-manager.yaml
  - shared-image-viewer.yaml
