SELECT
  BUILD_NUMBER,
  COUNT(TEST_FUNCTION) AS OUTCOME_COUNT,
  OUTCOME,
  PIPELINE_START_TIME
FROM
  `release_data.INTEGRATION_TEST_RESULT`
WHERE
  CHOREO_ENV = "prod"
  AND TEST_TYPE = "int"
  AND PIPELINE_START_TIME BETWEEN PARSE_DATE('%Y%m%d', @DS_START_DATE)
  AND PARSE_DATE('%Y%m%d', @DS_END_DATE)
GROUP BY
  BUILD_NUMBER,
  PIPELINE_START_TIME,
  OUTCOME
ORDER BY
  PIPELINE_START_TIME DESC
LIMIT
  1000
