# -------------------------------------------------------------------------------------
#
# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: Secret
metadata:
  name: superset-secret-custom-config
  namespace: superset
type: Opaque
stringData:
  superset-secret.config: |
    DB_USER = superset_admin
    DB_PASS = SUPERSET_DB_PASS
    DB_HOST = postgresql-choreo-<ENV>-eastus2-001.postgres.database.azure.com
    DB_PORT = 5432
    DB_NAME = superset
    REDIS_HOST = superset-redis-headless
    REDIS_PORT = 6379
    REDIS_PASSWORD =

  superset_init.sh: |
    #!/bin/sh
    set -eu
    echo "Upgrading DB schema..."
    superset db upgrade
    echo "Initializing roles..."
    superset init

    echo "Creating admin user..."
    superset fab create-admin \
                    --username admin \
                    --firstname Superset \
                    --lastname Admin \
                    --email integration-choreo-group@wso2.com \
                    --password SUPERSET_ADMIN_USER_PASS \
                    || true

    if [ -f "/app/configs/import_datasources.yaml" ]; then
      echo "Importing database connections.... "
      superset import_datasources -p /app/configs/import_datasources.yaml
    fi

  superset_bootstrap.sh: |
    #!/bin/bash
    rm -rf /var/lib/apt/lists/* && \
    pip install \
      psycopg2-binary==2.9.1 \
      redis==3.5.3 && \
    if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid 10500" > ~/bootstrap; fi

  superset_config.py: |
    import configparser
    from cachelib.redis import RedisCache

    config = configparser.ConfigParser()
    sec_header = "configs"
    config_path = "/app/pythonpath/superset-secret.config"

    with open(config_path, 'r') as f_config:
        ini_str = '[%s]\n' % sec_header + f_config.read()

    config.read_string(ini_str)

    def get_config(key, fallback=None):
        return config[sec_header].get(key, fallback)

    MAPBOX_API_KEY = get_config('MAPBOX_API_KEY', '')
    CACHE_CONFIG = {
        'CACHE_TYPE': 'redis',
        'CACHE_DEFAULT_TIMEOUT': 300,
        'CACHE_KEY_PREFIX': 'superset_',
        'CACHE_REDIS_HOST': get_config('REDIS_HOST'),
        'CACHE_REDIS_PORT': get_config('REDIS_PORT'),
        'CACHE_REDIS_PASSWORD': get_config('REDIS_PASSWORD'),
        'CACHE_REDIS_DB': get_config('REDIS_DB', 1),
    }
    DATA_CACHE_CONFIG = CACHE_CONFIG

    SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{get_config('DB_USER')}:{get_config('DB_PASS')}@{get_config('DB_HOST')}:{get_config('DB_PORT')}/{get_config('DB_NAME')}"
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    SECRET_KEY = get_config('SECRET_KEY', 'thisISaSECRET_1234')

    # Flask-WTF flag for CSRF
    WTF_CSRF_ENABLED = True
    # Add endpoints that need to be exempt from CSRF protection
    WTF_CSRF_EXEMPT_LIST = []
    # A CSRF token that expires in 1 year
    WTF_CSRF_TIME_LIMIT = 60 * 60 * 24 * 365
    class CeleryConfig(object):
        CELERY_IMPORTS = ('superset.sql_lab', )
        CELERY_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}
        BROKER_URL = f"redis://{get_config('REDIS_HOST')}:{get_config('REDIS_PORT')}/0"
        CELERY_RESULT_BACKEND = f"redis://{get_config('REDIS_HOST')}:{get_config('REDIS_PORT')}/0"

    CELERY_CONFIG = CeleryConfig
    RESULTS_BACKEND = RedisCache(
        host=get_config('REDIS_HOST'),
        port=get_config('REDIS_PORT'),
        key_prefix='superset_results'
    )
