apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-choreo_perf_db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /home/docker/choreo_perf_db
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  volumeMode: Filesystem
  claimRef:
    name: pvc-choreo_perf_db
