apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-choreodb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /home/docker/choreo_db
  persistentVolumeReclaimPolicy: Delete
  storageClassName: file
  volumeMode: Filesystem
