apiVersion: v1
kind: Service
metadata:
  name: router-green
  labels:
    choreo.component: choreo-connect-deployment-default-p2
spec:
  selector:
    choreo.component: choreo-connect-deployment-default-p2
