apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: choreo-sts
  name: choreo-sts
  namespace: choreo-sts
spec:
  ports:
    - name: service-port
      port: 9000
      targetPort: service-port
      protocol: TCP
  selector:
    choreo.component: choreo-sts
