# list of all appenders
#add entry "syslog" to use the syslog appender
appenders=CARBON_CONSOLE, CARBON_LOGFILE, AUDIT_CONSOLE, AUDIT_LOGFILE, ATOMIKOS_LOGFILE, CARBON_TRACE_LOGFILE,ERROR_LOGFILE, OPEN_TRACING,SERVICE_APPENDER, TRACE_APPENDER, osgi, CORRELATION_CONSOLE, CORRELATION_LOGFILE, BOTDATA_APPENDER, HTTP_ACCESS
#, syslog
# CARBON_CONSOLE is set to be a ConsoleAppender using a PatternLayout.
appender.CARBON_CONSOLE.type=Console
appender.CARBON_CONSOLE.name=CARBON_CONSOLE
appender.CARBON_CONSOLE.layout.type=PatternLayout
appender.CARBON_CONSOLE.layout.pattern=[%d{DEFAULT}] %5p %X{Correlation-ID} - %c{1} %m%n
appender.CARBON_CONSOLE.filter.threshold.type=ThresholdFilter
appender.CARBON_CONSOLE.filter.threshold.level=DEBUG
# CARBON_LOGFILE is set to be a DailyRollingFileAppender using a PatternLayout.
appender.CARBON_LOGFILE.type=RollingFile
appender.CARBON_LOGFILE.name=CARBON_LOGFILE
appender.CARBON_LOGFILE.fileName=${sys:carbon.home}/repository/logs/wso2carbon.log
appender.CARBON_LOGFILE.filePattern=${sys:carbon.home}/repository/logs/wso2carbon-%d{MM-dd-yyyy}.log
appender.CARBON_LOGFILE.layout.type=PatternLayout
appender.CARBON_LOGFILE.layout.pattern=TID: [%tenantId] [%appName] [%d] %5p {%c} %X{Correlation-ID} - %m%ex%n
appender.CARBON_LOGFILE.policies.type=Policies
appender.CARBON_LOGFILE.policies.time.type=TimeBasedTriggeringPolicy
appender.CARBON_LOGFILE.policies.time.interval=1
appender.CARBON_LOGFILE.policies.time.modulate=true
appender.CARBON_LOGFILE.policies.size.type=SizeBasedTriggeringPolicy
appender.CARBON_LOGFILE.policies.size.size=10MB
appender.CARBON_LOGFILE.strategy.type=DefaultRolloverStrategy
appender.CARBON_LOGFILE.strategy.max=20
appender.CARBON_LOGFILE.filter.threshold.type=ThresholdFilter
appender.CARBON_LOGFILE.filter.threshold.level=DEBUG
# Appender config to AUDIT_LOGFILE
appender.AUDIT_LOGFILE.type=RollingFile
appender.AUDIT_LOGFILE.name=AUDIT_LOGFILE
appender.AUDIT_LOGFILE.fileName=${sys:carbon.home}/repository/logs/audit.log
appender.AUDIT_LOGFILE.filePattern=${sys:carbon.home}/repository/logs/audit-%d{MM-dd-yyyy}.log
appender.AUDIT_LOGFILE.layout.type=PatternLayout
appender.AUDIT_LOGFILE.layout.pattern=TID: [%tenantId] [%d] %5p {%c} %X{Correlation-ID} - %m%ex%n
appender.AUDIT_LOGFILE.policies.type=Policies
appender.AUDIT_LOGFILE.policies.time.type=TimeBasedTriggeringPolicy
appender.AUDIT_LOGFILE.policies.time.interval=1
appender.AUDIT_LOGFILE.policies.time.modulate=true
appender.AUDIT_LOGFILE.policies.size.type=SizeBasedTriggeringPolicy
appender.AUDIT_LOGFILE.policies.size.size=10MB
appender.AUDIT_LOGFILE.strategy.type=DefaultRolloverStrategy
appender.AUDIT_LOGFILE.strategy.max=20
appender.AUDIT_LOGFILE.filter.threshold.type=ThresholdFilter
appender.AUDIT_LOGFILE.filter.threshold.level=INFO
# AUDIT_CONSOLE is set to be a ConsoleAppender using a PatternLayout.
appender.AUDIT_CONSOLE.type=Console
appender.AUDIT_CONSOLE.name=AUDIT_CONSOLE
appender.AUDIT_CONSOLE.layout.type=PatternLayout
appender.AUDIT_CONSOLE.layout.pattern=TID: [%tenantId] [%d] %5p {%c} %X{Correlation-ID} - %m%ex%n
appender.AUDIT_CONSOLE.filter.threshold.type=ThresholdFilter
appender.AUDIT_CONSOLE.filter.threshold.level=INFO
# Appender config to send Atomikos transaction logs to new log file tm.out.
appender.ATOMIKOS_LOGFILE.type=RollingFile
appender.ATOMIKOS_LOGFILE.name=ATOMIKOS_LOGFILE
appender.ATOMIKOS_LOGFILE.fileName=${sys:carbon.home}/repository/logs/tm.out
appender.ATOMIKOS_LOGFILE.filePattern=${sys:carbon.home}/repository/logs/tm-%d{MM-dd-yyyy}.out
appender.ATOMIKOS_LOGFILE.layout.type=PatternLayout
appender.ATOMIKOS_LOGFILE.layout.pattern=[%d] [%tenantId] %5p {%c} - %m%ex%n
appender.ATOMIKOS_LOGFILE.policies.type=Policies
appender.ATOMIKOS_LOGFILE.policies.time.type=TimeBasedTriggeringPolicy
appender.ATOMIKOS_LOGFILE.policies.time.interval=1
appender.ATOMIKOS_LOGFILE.policies.time.modulate=true
appender.ATOMIKOS_LOGFILE.strategy.type=DefaultRolloverStrategy
appender.ATOMIKOS_LOGFILE.strategy.max=20
# Appender config to CARBON_TRACE_LOGFILE
appender.CARBON_TRACE_LOGFILE.type=RollingFile
appender.CARBON_TRACE_LOGFILE.name=CARBON_TRACE_LOGFILE
appender.CARBON_TRACE_LOGFILE.fileName=${sys:carbon.home}/repository/logs/wso2carbon-trace-messages.log
appender.CARBON_TRACE_LOGFILE.filePattern=${sys:carbon.home}/repository/logs/wso2carbon-trace-messages-%d{MM-dd-yyyy}.log
appender.CARBON_TRACE_LOGFILE.layout.type=PatternLayout
appender.CARBON_TRACE_LOGFILE.layout.pattern=[%d] [%tenantId] %5p {%c} - %m%ex%n
appender.CARBON_TRACE_LOGFILE.policies.type=Policies
appender.CARBON_TRACE_LOGFILE.policies.time.type=TimeBasedTriggeringPolicy
appender.CARBON_TRACE_LOGFILE.policies.time.interval=1
appender.CARBON_TRACE_LOGFILE.policies.time.modulate=true
appender.CARBON_TRACE_LOGFILE.policies.size.type=SizeBasedTriggeringPolicy
appender.CARBON_TRACE_LOGFILE.policies.size.size=10MB
appender.CARBON_TRACE_LOGFILE.strategy.type=DefaultRolloverStrategy
appender.CARBON_TRACE_LOGFILE.strategy.max=20
# Appender config to put correlation Log.
appender.CORRELATION_LOGFILE.type=RollingFile
appender.CORRELATION_LOGFILE.name=CORRELATION_LOGFILE
appender.CORRELATION_LOGFILE.fileName=${sys:carbon.home}/repository/logs/correlation.log
appender.CORRELATION_LOGFILE.filePattern=${sys:carbon.home}/repository/logs/correlation-%d{MM-dd-yyyy}-%i.log.gz
appender.CORRELATION_LOGFILE.layout.type=PatternLayout
appender.CORRELATION_LOGFILE.layout.pattern=%d{yyyy-MM-dd HH:mm:ss,SSS}|%X{Correlation-ID}|%t|%m%n
appender.CORRELATION_LOGFILE.policies.type=Policies
appender.CORRELATION_LOGFILE.policies.time.type=TimeBasedTriggeringPolicy
appender.CORRELATION_LOGFILE.policies.time.interval=1
appender.CORRELATION_LOGFILE.policies.time.modulate=true
appender.CORRELATION_LOGFILE.policies.size.type=SizeBasedTriggeringPolicy
appender.CORRELATION_LOGFILE.policies.size.size=10MB
appender.CORRELATION_LOGFILE.strategy.type=DefaultRolloverStrategy
appender.CORRELATION_LOGFILE.strategy.max=20
appender.CORRELATION_LOGFILE.filter.threshold.type=ThresholdFilter
appender.CORRELATION_LOGFILE.filter.threshold.level=INFO
# CORRELATION_CONSOLE is set to be a ConsoleAppender using a PatternLayout.
appender.CORRELATION_CONSOLE.type=Console
appender.CORRELATION_CONSOLE.name=CORRELATION_CONSOLE
appender.CORRELATION_CONSOLE.layout.type=PatternLayout
appender.CORRELATION_CONSOLE.layout.pattern=%d{yyyy-MM-dd HH:mm:ss,SSS}|%X{Correlation-ID}|%t|%m%n
appender.CORRELATION_CONSOLE.filter.threshold.type=ThresholdFilter
appender.CORRELATION_CONSOLE.filter.threshold.level=INFO
appender.ERROR_LOGFILE.type=RollingFile
appender.ERROR_LOGFILE.name=ERROR_LOGFILE
appender.ERROR_LOGFILE.fileName=${sys:carbon.home}/repository/logs/wso2-apigw-errors.log
appender.ERROR_LOGFILE.filePattern=${sys:carbon.home}/repository/logs/wso2-apigw-errors-%d{MM-dd-yyyy}-%i.log.gz
appender.ERROR_LOGFILE.layout.type=PatternLayout
appender.ERROR_LOGFILE.layout.pattern=%d{ISO8601} [%X{ip}-%X{host}] [%t] %5p %c{1} %m%n
appender.ERROR_LOGFILE.policies.type=Policies
appender.ERROR_LOGFILE.policies.time.type=TimeBasedTriggeringPolicy
appender.ERROR_LOGFILE.policies.time.interval=1
appender.ERROR_LOGFILE.policies.time.modulate=true
appender.ERROR_LOGFILE.policies.size.type=SizeBasedTriggeringPolicy
appender.ERROR_LOGFILE.policies.size.size=10MB
appender.ERROR_LOGFILE.strategy.type=DefaultRolloverStrategy
appender.ERROR_LOGFILE.strategy.max=20
appender.ERROR_LOGFILE.filter.threshold.type=ThresholdFilter
appender.ERROR_LOGFILE.filter.threshold.level=WARN
appender.CARBON_SYS_LOG.type=Syslog
appender.CARBON_SYS_LOG.name=CARBON_SYS_LOG
appender.CARBON_SYS_LOG.host=localhost
appender.CARBON_SYS_LOG.facility=USER
appender.CARBON_SYS_LOG.layout.type=PatternLayout
appender.CARBON_SYS_LOG.layout.pattern=[%d] %5p - %x %m {%c}%n
appender.CARBON_SYS_LOG.filter.threshold.type=ThresholdFilter
appender.CARBON_SYS_LOG.filter.threshold.level=DEBUG
appender.OPEN_TRACING.type=RollingFile
appender.OPEN_TRACING.name=OPEN_TRACING
appender.OPEN_TRACING.fileName=${sys:carbon.home}/repository/logs/wso2-apimgt-open-tracing.log
appender.OPEN_TRACING.filePattern=${sys:carbon.home}/repository/logs/wso2-apimgt-open-tracing-%d{MM-dd-yyyy}-%i.log.gz
appender.OPEN_TRACING.layout.type=PatternLayout
appender.OPEN_TRACING.layout.pattern=%d{HH:mm:ss,SSS} [%X{ip}-%X{host}] [%t] %5p %m%nn
appender.OPEN_TRACING.policies.type=Policies
appender.OPEN_TRACING.policies.time.type=TimeBasedTriggeringPolicy
appender.OPEN_TRACING.policies.time.interval=1
appender.OPEN_TRACING.policies.time.modulate=true
appender.OPEN_TRACING.policies.size.type=SizeBasedTriggeringPolicy
appender.OPEN_TRACING.policies.size.size=10MB
appender.OPEN_TRACING.strategy.type=DefaultRolloverStrategy
appender.OPEN_TRACING.strategy.max=20
appender.OPEN_TRACING.filter.threshold.type=ThresholdFilter
appender.OPEN_TRACING.filter.threshold.level=TRACE
appender.TRACE_APPENDER.type=RollingFile
appender.TRACE_APPENDER.name=TRACE_APPENDER
appender.TRACE_APPENDER.fileName=${sys:carbon.home}/repository/logs/wso2-apigw-trace.log
appender.TRACE_APPENDER.filePattern=${sys:carbon.home}/repository/logs/wso2-apigw-trace-%d{MM-dd-yyyy}.log
appender.TRACE_APPENDER.layout.type=PatternLayout
appender.TRACE_APPENDER.layout.pattern=%d{HH:mm:ss,SSS} [%X{ip}-%X{host}] [%t] %5p %c{1} %m%n
appender.TRACE_APPENDER.policies.type=Policies
appender.TRACE_APPENDER.policies.time.type=TimeBasedTriggeringPolicy
appender.TRACE_APPENDER.policies.time.interval=1
appender.TRACE_APPENDER.policies.time.modulate=true
appender.TRACE_APPENDER.strategy.type=DefaultRolloverStrategy
appender.TRACE_APPENDER.strategy.max=20
appender.SERVICE_APPENDER.type=RollingFile
appender.SERVICE_APPENDER.name=SERVICE_APPENDER
appender.SERVICE_APPENDER.fileName=${sys:carbon.home}/repository/logs/wso2-apigw-service.log
appender.SERVICE_APPENDER.filePattern=${sys:carbon.home}/repository/logs/wso2-apigw-service-%i.log
appender.SERVICE_APPENDER.layout.type=PatternLayout
appender.SERVICE_APPENDER.layout.pattern=%d{ISO8601} [%X{ip}-%X{host}] [%t] %5p %c{1} %m%n
appender.SERVICE_APPENDER.policies.type=Policies
appender.SERVICE_APPENDER.policies.size.type=SizeBasedTriggeringPolicy
appender.SERVICE_APPENDER.policies.size.size=1000KB
appender.SERVICE_APPENDER.strategy.type=DefaultRolloverStrategy
appender.SERVICE_APPENDER.strategy.max=10
appender.osgi.type=PaxOsgi
appender.osgi.name=PaxOsgi
appender.osgi.filter=*
# Appender for HTTP Access Logs
appender.HTTP_ACCESS.type=RollingFile
appender.HTTP_ACCESS.name=HTTP_ACCESS
appender.HTTP_ACCESS.fileName=${sys:carbon.home}/repository/logs/http_access.log
appender.HTTP_ACCESS.filePattern=${sys:carbon.home}/repository/logs/http_access-%d{MM-dd-yyyy}.log
appender.HTTP_ACCESS.layout.type=PatternLayout
appender.HTTP_ACCESS.layout.pattern=[%X{Correlation-ID}] %mm%n
appender.HTTP_ACCESS.policies.type=Policies
appender.HTTP_ACCESS.policies.time.type=TimeBasedTriggeringPolicy
appender.HTTP_ACCESS.policies.time.interval=1
appender.HTTP_ACCESS.policies.time.modulate=true
appender.HTTP_ACCESS.policies.size.type=SizeBasedTriggeringPolicy
appender.HTTP_ACCESS.policies.size.size=10MB
appender.HTTP_ACCESS.strategy.type=DefaultRolloverStrategy
appender.HTTP_ACCESS.strategy.max=20
appender.HTTP_ACCESS.filter.threshold.type=ThresholdFilter
appender.HTTP_ACCESS.filter.threshold.level=INFO
# bot detection feature appender
appender.BOTDATA_APPENDER.type=RollingFile
appender.BOTDATA_APPENDER.name=BOTDATA_APPENDER
appender.BOTDATA_APPENDER.fileName=${sys:carbon.home}/repository/logs/wso2-BotDetectedData.log
appender.BOTDATA_APPENDER.filePattern=${sys:carbon.home}/repository/logs/wso2-BotDetectedData-%d{MM-dd-yyyy}.log
appender.BOTDATA_APPENDER.layout.type=PatternLayout
appender.BOTDATA_APPENDER.layout.pattern=[%d] [%tenantId] %5p {%c} - %m%ex%n
appender.BOTDATA_APPENDER.policies.type=Policies
appender.BOTDATA_APPENDER.policies.time.type=TimeBasedTriggeringPolicy
appender.BOTDATA_APPENDER.policies.time.interval=1
appender.BOTDATA_APPENDER.policies.time.modulate=true
appender.BOTDATA_APPENDER.policies.size.type=SizeBasedTriggeringPolicy
appender.BOTDATA_APPENDER.policies.size.size=10MB
appender.BOTDATA_APPENDER.strategy.type=DefaultRolloverStrategy
appender.BOTDATA_APPENDER.strategy.max=20
loggers={{range $loggerKey, $logger := .LOGGERS}}{{$logger.NAME}}{{if notLast $loggerKey $.LOGGERS}}, {{end}}{{end}}
{{- range $logger := .Values.config.loggers }}
logger.{{ $logger.name }}.name = {{ $logger.loggerName }}
logger.{{ $logger.name }}.level = {{ $logger.level }}
{{- range $field := $logger.fields }}
logger.{{ $logger.name }}.{{ $field.field }} = {{ $field.value }}
{{- end }}
{{- end }}
# root loggers
rootLogger.level=ERROR
rootLogger.appenderRef.CARBON_CONSOLE.ref=CARBON_CONSOLE
rootLogger.appenderRef.CARBON_LOGFILE.ref=CARBON_LOGFILE
rootLogger.appenderRef.ERROR_LOGFILE.ref=ERROR_LOGFILE
rootLogger.appenderRef.PaxOsgi.ref=PaxOsgi
#rootLogger.appenderReg.CARBON_SYS_LOG.ref = CARBON_SYS_LOG
#rootLogger.appenderRef.syslog.ref = syslog

category.SERVICE_APPENDER._OpenService_=TRACE_APPENDER, BOTDATA_APPENDER

# Fixing Log4j zero-day (CVE-2021-44228)
log4j2.formatMsgNoLookups=True 
