# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

replicas: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
image:
  repository: choreoipaas/choreo-product-apim
  tag: latest
config:
  hostName: ""
  apimDBURL: "jdbc:sqlserver://sqlfg-choreo-choreo-apim-db-prod.database.windows.net:1433;database=choreo_apim_db;SendStringParametersAsUnicode=false;socketTimeout=60000"
  sharedDBURL: "jdbc:sqlserver://sqlfg-choreo-choreo-apim-shared-db-prod.database.windows.net:1433;database=choreo_apim_shared_db;SendStringParametersAsUnicode=false;socketTimeout=60000"
  sharedDBJDBCInterceptors: "SlowQueryReport(threshold=200)"
  dbURL: "jdbc:sqlserver://sqlfg-choreo-choreo-apim-user-db-prod.database.windows.net:1433;database=choreo_apim_user_db;SendStringParametersAsUnicode=false;socketTimeout=60000"
  mongoDBConnectionString: "mongodb+srv://prod_choreo_db_user:$env{MONGO_DB_PSWD}@choreo-apim-pl-0.lbxa7.mongodb.net/PROD_APIM_DB?retryWrites=true&amp;w=majority"
  persistenceGroupId: ""
  gatewayEnvironments: []
  serviceProviders: []
  jwtAudiences: []
  perOrgSettings: []
  loggers: []
  websubhubURL: "https://publish.websubhub.choreo.dev/hub"
  publisherKeyIssuer: "https://sts.choreo.dev:443/api/am/publisher/v2/apis/internal-key"
  devportalURL: "https://sts.choreo.dev/devportal"
  devportalKeyIssuer: "https://sts.choreo.dev:443/api/am/devportal/v2/apis/test-key"
  devportalV2URL: "https://devportal.choreoapps.dev"
  authzServiceURL: "rpc-api-authz.cloud-internal.wso2.com:9091"
  authzServiceEnabled: false
  instanceBasedAuthzServiceEnabled: true
  instanceBasedAuthzServiceDisabledOrgs: ""
  azureServiceBusPool: []
  jwtIssuerName: "https://sts.choreo.dev:443/oauth2/token"
  jwtJWKSUrl: "https://sts.choreo.dev:443/oauth2/jwks"
  operationPolicyURL: "https://api.central.ballerina.io/2.0/"
  asgardeoSystemAppTokenEndpoint: "https://api.asgardeo.io/oauth2/token"
  asgardeoSystemAppAuthzEndpoint: "https://api.asgardeo.io"
  patHandlerClientId: ""
  apimAIEnable: false
  apimAIClientId: ""
  apimAITokenEndpoint: ""
  apimAIDevportalThemingEndpoint: ""
  apimAIAPIDesignEndpoint: ""
secrets:
  primaryKeystorePassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: primaryKeystorePassword
  primaryKeystoreKeyPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: primaryKeystoreKeyPassword
  tlsKeystorePassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: tlsKeystorePassword
  tlsKeystoreKeyPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: tlsKeystoreKeyPassword
  internalKeystorePassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: internalKeystorePassword
  internalKeystoreKeyPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: internalKeystoreKeyPassword
  truststorePassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: truststorePassword
  choreoAPIMDBPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: choreoAPIMDBPassword
  choreoAPIMSharedDBPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: choreoAPIMSharedDBPassword
  choreoAPIMUserDBPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: choreoAPIMUserDBPassword
  mongoDBAtlasPrivateKey:
    path: choreo-cp/data/choreo-apim/product-apim
    key: mongoDBAtlasPrivateKey
  mongoDBAtlasPublicKey:
    path: choreo-cp/data/choreo-apim/product-apim
    key: mongoDBAtlasPublicKey
  superAdminPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: superAdminPassword
  asgardeoSystemAppClientSecret:
    path: choreo-cp/data/choreo-apim/product-apim
    key: asgardeoSystemAppClientSecret
  apimDashboardUserPassword:
    path: choreo-cp/data/choreo-apim/product-apim
    key: apimDashboardUserPassword
  apimDashboardUserPasswordSHA256:
    path: choreo-cp/data/choreo-apim/product-apim
    key: apimDashboardUserPasswordSHA256
  devportalV2AccessKey:
    path: choreo-cp/data/choreo-apim/product-apim
    key: devportalV2AccessKey
  apimAIClientSecret:
    path: choreo-cp/data/choreo-apim/product-apim
    key: apimAIClientSecret
  asbConnectionString:
    path: choreo-cp/data/choreo-apim/product-apim
    key: asbConnectionString
  primaryKeystore:
    path: choreo-cp/data/choreo-apim/product-apim
    key: primaryKeystore
  tlsKeystore:
    path: choreo-cp/data/choreo-apim/product-apim
    key: tlsKeystore
  internalKeystore:
    path: choreo-cp/data/choreo-apim/product-apim
    key: internalKeystore
  clientTruststore:
    path: choreo-cp/data/choreo-apim/product-apim
    key: clientTruststore
vault:
  roleName: product-apim
serviceAccount:
  annotations: {}
