apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-dp-mizzen-ws
spec:
  podSelector:
    matchLabels:
      choreo.component: dp-mizzen
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8081
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              choreo-ingress-purpose: controlplane-internal
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: controlplane-internal-nginx-ingress
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: choreo-ai
          podSelector:
            matchLabels:
              choreo.component: cost-optimizer-cp
