apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

configMapGenerator:
- envs:
  - common-env-variables.yaml
  name: common-env-variables
  namespace: choreo-system

images:
- name: choreoctrlplane.azurecr.io/choreoipaas/api-server
  newTag: master-f850c8d96636f05a7d9da2bb3e402a2060e29866
- name: choreoctrlplane.azurecr.io/choreoipaas/app-deployer
  newTag: master-f850c8d96636f05a7d9da2bb3e402a2060e29866
- name: choreoctrlplane.azurecr.io/choreoipaas/app-service
  newTag: master-f850c8d96636f05a7d9da2bb3e402a2060e29866
- name: choreoctrlplane.azurecr.io/choreoipaas/ast-archiver
  newTag: master-dccd3e3b849adf740cd22b541c1caeb16edc6f82
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-apim-devportal
  newTag: main-56203889115cb08a234f850bf86a3f94235ef6ab
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-apim-service
  newTag: master-4636a1c093afff10a3da90c64d297f79328faf49
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-connectords
  newTag: master-49a6123fadbc9bb648d70031936d50d703184f33
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-console
  newTag: master-264e9308ddb4ebc23389ff01453f1b7c096842a1
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-linker
  newTag: master-fe2d673c811cee29544744b554f537e7d6476313
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-logging
  newTag: master-06f16a1dd328b8944ae79dccaa68c3e33bee04ab
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-mgw-adapter
  newTag: dd919445-20210525.1
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-mgw-enforcer
  newTag: dd919445-20210525.1
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-mgw-router
  newTag: dd919445-20210525.1
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-negotiator
  newTag: master-01d9ea8f3cfc183e5d1c4647f479f671590de084
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-product-apim
  newTag: v4.0.0-r25052021.1
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-sys-obsapi
  newTag: master-0744da9a091d913a4f8297cd41fb8d0b53a23b22
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-telemetry
  newTag: master-aedbcd4061b3d961758e589616a823ffbb0eb1df
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-testbase
  newTag: master-5415b79a4d0d0f6c164e83fabe03bb1a8bd32465
- name: choreoctrlplane.azurecr.io/choreoipaas/email-service
  newTag: master-45e7f86e3b906888e221b77f8964fd39c87b96c3
- name: choreoctrlplane.azurecr.io/choreoipaas/observability-api
  newTag: master-f7637238a4c13d062af934bbbfce24de32527914
- name: choreoctrlplane.azurecr.io/choreoipaas/observability-data-generator
  newTag: master-114269ed7f997814aedbd2bcc4ef58e66b6063b8
- name: choreoctrlplane.azurecr.io/choreoipaas/workspace-manager
  newTag: master-f850c8d96636f05a7d9da2bb3e402a2060e29866
