apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

configMapGenerator:
- envs:
  - common-env-variables.yaml
  name: common-env-variables
  namespace: choreo-system

images:
- name: choreoctrlplane.azurecr.io/choreoipaas/api-server
  newTag: master-e759742eca0e58bef3a4542ffea838e43cdfc9b5
- name: choreoctrlplane.azurecr.io/choreoipaas/app-deployer
  newTag: master-e759742eca0e58bef3a4542ffea838e43cdfc9b5
- name: choreoctrlplane.azurecr.io/choreoipaas/app-service
  newTag: master-e759742eca0e58bef3a4542ffea838e43cdfc9b5
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-apim-devportal
  newTag: main-93d60fda84d07f4b5d758e72e1deff562ca0eca1
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-console
  newTag: master-e692fb60ff9dc2114af1cfd887615810304fe2c3
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-testbase
  newTag: master-8fd073fdf2412a71c332320e6defddd491dda3d5
- name: choreoctrlplane.azurecr.io/choreoipaas/email-service
  newTag: master-45e7f86e3b906888e221b77f8964fd39c87b96c3
- name: choreoctrlplane.azurecr.io/choreoipaas/observability-api
  newTag: master-798519b479aac720fc48ed52cc846e23d5a04fea
- name: choreoctrlplane.azurecr.io/choreoipaas/workspace-manager
  newTag: master-e759742eca0e58bef3a4542ffea838e43cdfc9b5
