apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

configMapGenerator:
- envs:
  - common-env-variables.yaml
  name: common-env-variables
  namespace: choreo-system

images:
- name: choreocontrolplane.azurecr.io/choreoipaas/analytics-subscription-mgt
  newTag: master-1e9eb5c268af4e528dd438671b0997c81f64d540
- name: choreocontrolplane.azurecr.io/choreoipaas/anomaly-detector
  newTag: master-f6e958c84c1f82c8b5299c3f07facffeef655bef
- name: choreocontrolplane.azurecr.io/choreoipaas/anomaly-detector-init
  newTag: master-f6e958c84c1f82c8b5299c3f07facffeef655bef
- name: choreocontrolplane.azurecr.io/choreoipaas/api-server
  newTag: master-c9a2db1848a4531079586bcb2b60a96b1c311e4f
- name: choreocontrolplane.azurecr.io/choreoipaas/app-deployer
  newTag: master-c9a2db1848a4531079586bcb2b60a96b1c311e4f
- name: choreocontrolplane.azurecr.io/choreoipaas/app-service
  newTag: master-c9a2db1848a4531079586bcb2b60a96b1c311e4f
- name: choreocontrolplane.azurecr.io/choreoipaas/ast-archiver
  newTag: master-0ef2eefa077d72da0beeaa040810cac1fec59e1c
- name: choreocontrolplane.azurecr.io/choreoipaas/capacity-planner
  newTag: master-b3d9ea16d6149b9a4c3f533cc32bc363bb33754f
- name: choreocontrolplane.azurecr.io/choreoipaas/capacity-planner-init
  newTag: master-b3d9ea16d6149b9a4c3f533cc32bc363bb33754f
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-apim-devportal
  newTag: main-f41697421e8ff62c58a8a9fa8e9eda75bfde0152
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-apim-service
  newTag: master-bc83d10668166e2edacd352d13518f8dae41e135
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-connect-global-adapter
  newTag: master-7601541ddea0da16e2cde6df734da6724d96226d
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-connectords
  newTag: master-7a94602d42d293587fa829b6c2da53cec91fe3ce
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-console
  newTag: master-d183f6bda6328e5b9d703b410b8fa1810f7e24b5
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-linker
  newTag: master-17bf9192380343d32d2d362fbfb2c957683a6cac
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-logging
  newTag: master-edb928c28d5ef4520930f87d35bd50b378d80812
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-adapter
  newTag: master-87000c54f7e4c70d1ee055f55f41c1db9a7c457e
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-enforcer
  newTag: master-87000c54f7e4c70d1ee055f55f41c1db9a7c457e
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-mgw-router
  newTag: master-87000c54f7e4c70d1ee055f55f41c1db9a7c457e
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-negotiator
  newTag: master-2cbf9f8b12470408d356a6d2912c9cd9415557cc
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-org-cleanup-service
  newTag: main-d67de5200076e5bcb19ef8e64b7ed24ec299c9e9
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-product-apim
  newTag: v4.0.0-r22082021.1
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-quota-limiter
  newTag: main-c31b9ab56a48aed46c9369ad3510c81f9349b5b4
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-subscriptions
  newTag: main-be38ed57fa159bda84b5107d200cc3f569f80b09
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-sys-obsapi
  newTag: master-7e612aa4a2f4dfa2cc386321c1bbf22e49ce7c89
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-telemetry
  newTag: master-2f0c1d9fe08f96b869b6039593631022207d8164
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-testbase
  newTag: master-7d275b92e7b658ac31e6e721871f86fcb78eefa9
- name: choreocontrolplane.azurecr.io/choreoipaas/data-collector
  newTag: master-1bf1e86c13eb15c8938dfa3d6a611a1a82395498
- name: choreocontrolplane.azurecr.io/choreoipaas/datamapper
  newTag: master-3a668137f90fb85c8a4c166a07663749bf2f12c1
- name: choreocontrolplane.azurecr.io/choreoipaas/datamapper-balo-extractor
  newTag: master-3a668137f90fb85c8a4c166a07663749bf2f12c1
- name: choreocontrolplane.azurecr.io/choreoipaas/datamapper-init
  newTag: master-3a668137f90fb85c8a4c166a07663749bf2f12c1
- name: choreocontrolplane.azurecr.io/choreoipaas/deployment-optimizer
  newTag: master-52b66b62c62d9ac2fa2b87fd365f5b31281a246a
- name: choreocontrolplane.azurecr.io/choreoipaas/deployment-optimizer-init
  newTag: master-52b66b62c62d9ac2fa2b87fd365f5b31281a246a
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-auth-module
  newTag: master-9431bca3789736863bceee6f8e7d9e655e0c9a4a
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-secret-manager
  newTag: master-360727c31f51061a1830bd24190bc2b6263c7999
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-utility-api
  newTag: master-acae11426cdaa6b0ed4fb16295a3eb74791d8e08
- name: choreocontrolplane.azurecr.io/choreoipaas/email-service
  newTag: master-383a669ebacdce65bd5d6d3da49b781bb31de133
- name: choreocontrolplane.azurecr.io/choreoipaas/lang-server
  newTag: master-6bd709986a268d15bd0acd7e6099d218509f495b
- name: choreocontrolplane.azurecr.io/choreoipaas/observability-api
  newTag: master-f0c2b20004fb526f06a08ff101581eb500751610
- name: choreocontrolplane.azurecr.io/choreoipaas/observability-data-generator
  newTag: master-8aa002169a6fa83c40d80d3d5187d75024c84c31
- name: choreocontrolplane.azurecr.io/choreoipaas/perfanalyzer-estimator
  newTag: master-0893c545d01eb62256e25eb4a38b5a04ca87740c
- name: choreocontrolplane.azurecr.io/choreoipaas/perfanalyzer-updater
  newTag: master-0893c545d01eb62256e25eb4a38b5a04ca87740c
- name: choreocontrolplane.azurecr.io/choreoipaas/programanalyzer
  newTag: master-bbf57672e4cadab0cbf803e08b41f89211befa29
- name: choreocontrolplane.azurecr.io/choreoipaas/test-assistant
  newTag: main-7297da627ffd64ca55152e96f5f450fd4809267c
- name: choreocontrolplane.azurecr.io/choreoipaas/test-assistant-init
  newTag: main-7297da627ffd64ca55152e96f5f450fd4809267c
- name: choreocontrolplane.azurecr.io/choreoipaas/workspace-manager
  newTag: master-c9a2db1848a4531079586bcb2b60a96b1c311e4f
