apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-spicedb
spec:
  secretObjects:
    - secretName: secret-spicedb-preshared-key
      type: Opaque
      data:
        - objectName: SPICEDB-PRESHARED-KEY
          key: preshared_key
        - objectName: SPICEDB-DATASTORE-URI
          key: datastore_uri
  parameters:
    objects: |
      array:
        - |
          objectName: choreo-authz-spicedb-preshared-key
          objectType: secret
          objectAlias: SPICEDB-PRESHARED-KEY
          objectVersion: {{.SPICEDB_PRESHARED_KEY}}
        - |
          objectName: AUTHZ-SPICEDB-DATASTORE-URI
          objectType: secret
          objectAlias: SPICEDB-DATASTORE-URI
          objectVersion: {{.SPICEDB_DATASTORE_URI}}
