apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-relay
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: hubble-relay
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
