helmCharts:
  - name: cilium
    includeCRDs: true
    valuesInline:
      aksbyocni:
        enabled: true
      encryption:
        enabled: true
        ipsec:
          interface: cilium_vxlan
        type: ipsec
      hubble:
        enabled: true
        relay:
          enabled: true
          podSecurityContext:
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        ui:
          enabled: true
          backend:
            resources:
              limits:
                cpu: 150m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            livenessProbe:
              enabled: true
          frontend:
            resources:
              limits:
                cpu: 150m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
      nodeinit:
        enabled: true
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      operator:
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
      resources:
        limits:
          cpu: 4000m
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 512Mi
      livenessProbe:
        failureThreshold: 10
        periodSeconds: 30
    releaseName: cilium
    namespace: kube-system
    version: 1.13.0
    repo: oci://choreocontrolplane.azurecr.io/helm

commonAnnotations:
  kapp.k14s.io/disable-original: ""
  kapp.k14s.io/disable-default-label-scoping-rules: ""
