[resource_registry_service.config]
servicePort=9090
healthPort=9092
mongoDBUsername="{{.RESOURCE_REGISTRY_DB_USERNAME}}"
mongoDBClusterUrl="{{.MONGO_DB_CLUSTER_URL}}"
databaseName="{{.RESOURCE_REGISTRY_DB_NAME}}"
collectionName="resources"
collectionTemplate="templates"
mongoDBOptions=""
defaultThumbnailUrl=""

[ballerina.log]
level = "{{.LOG_LEVEL}}"
format="json"
