EVENTHUB_NAMESPACE=choreo-poc-observability-event-hub-ns.servicebus.windows.net/
EVENTHUB_SHARED_ACCESS_POLICY_NAME=choreo-poc-observability-event-hub-sender-policy
METRICS_EVENTHUB_NAME=choreo-poc-observability-metrics-event-hub