# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-service
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    {{- include "app-service.labels" . | nindent 4 }}
spec:
  provider: vault
  secretObjects:
    - secretName: app-service
      type: Opaque
      data:
        - objectName: APP_DB_PASSWORD
          key: CHOREO_DB_PASSWORD
        - objectName: KEY_MANAGER_REGISTRATION_APIM_CLIENT_SECRET
          key: API_MANAGER_CLIENT_SECRET
        - objectName: BETA_PROGRAM_PREFINERY_INVITATION_DECODER_KEY
          key: BETA_PROGRAM_PREFINERY_INVITATION_DECODER_KEY
        - objectName: AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY
          key: AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY
        - objectName: CENTRAL_ORG_REGISTRY_CERTIFICATE_KEY
          key: CENTRAL_ORG_REGISTRY_CERTIFICATE_KEY
        - objectName: MARKETING_CONSENT_APP_CLIENT_SECRET
          key: MARKETING_CONSENT_APP_CLIENT_SECRET
        - objectName: ASGARDEO_CLIENT_SECRET
          key: ASGARDEO_CLIENT_SECRET
        - objectName: IDP_APP_CLIENT_SECRET
          key: IDP_APP_CLIENT_SECRET
        - objectName: PARDOT_USER_LIST_REGISTRATION_APP_KEY
          key: PARDOT_USER_LIST_REGISTRATION_APP_KEY
        - objectName: PARDOT_USER_LIST_REGISTRATION_APP_SECRET
          key: PARDOT_USER_LIST_REGISTRATION_APP_SECRET
        - objectName: SALESFORCE_LEAD_VIA_PARDOT_APP_KEY
          key: SALESFORCE_LEAD_VIA_PARDOT_APP_KEY
        - objectName: SALESFORCE_LEAD_VIA_PARDOT_APP_SECRET
          key: SALESFORCE_LEAD_VIA_PARDOT_APP_SECRET
        - objectName: MAX_MIND_GEO_LOC_COUNTRY_USERNAME
          key: MAX_MIND_GEO_LOC_COUNTRY_USERNAME
        - objectName: MAX_MIND_GEO_LOC_COUNTRY_PASSWORD
          key: MAX_MIND_GEO_LOC_COUNTRY_PASSWORD
        - objectName: PARDOT_STALE_USER_HANDLING_APP_KEY
          key: PARDOT_STALE_USER_HANDLING_APP_KEY
        - objectName: PARDOT_STALE_USER_HANDLING_APP_SECRET
          key: PARDOT_STALE_USER_HANDLING_APP_SECRET
        - objectName: SCIM_BACKEND_API_USER_PASSWORD
          key: SCIM_BACKEND_API_USER_PASSWORD
        - objectName: SERVICE_NOW_CLIENT_ID
          key: SERVICE_NOW_CLIENT_ID
        - objectName: SERVICE_NOW_CLIENT_SECRET
          key: SERVICE_NOW_CLIENT_SECRET
        - objectName: SERVICE_NOW_USERNAME
          key: SERVICE_NOW_USERNAME
        - objectName: SERVICE_NOW_PASSWORD
          key: SERVICE_NOW_PASSWORD
        - objectName: ASB_CONNECTION_STRING
          key: ASB_CONNECTION_STRING
        - objectName: APIM_CLIENT_SECRET
          key: APIM_CLIENT_SECRET
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: APP_DB_PASSWORD
        secretKey: {{ .Values.secrets.appDBPassword.key | quote }}
        secretPath: {{ .Values.secrets.appDBPassword.path | quote }}
      - objectName: KEY_MANAGER_REGISTRATION_APIM_CLIENT_SECRET
        secretKey: {{ .Values.secrets.keyManagerRegistrationAPIMClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.keyManagerRegistrationAPIMClientSecret.path | quote }}
      - objectName: BETA_PROGRAM_PREFINERY_INVITATION_DECODER_KEY
        secretKey: {{ .Values.secrets.invitationDecoderKey.key | quote }}
        secretPath: {{ .Values.secrets.invitationDecoderKey.path | quote }}
      - objectName: AZURE_APP_INSIGHTS_INSTRUMENTATION_KEY
        secretKey: {{ .Values.secrets.azureAppInsightsInstrumentationKey.key | quote }}
        secretPath: {{ .Values.secrets.azureAppInsightsInstrumentationKey.path | quote }}
      - objectName: CENTRAL_ORG_REGISTRY_CERTIFICATE_KEY
        secretKey: {{ .Values.secrets.centralOrgRegistryCertificateKey.key | quote }}
        secretPath: {{ .Values.secrets.centralOrgRegistryCertificateKey.path | quote }}
      - objectName: MARKETING_CONSENT_APP_CLIENT_SECRET
        secretKey: {{ .Values.secrets.markertingConsentAppClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.markertingConsentAppClientSecret.path | quote }}
      - objectName: ASGARDEO_CLIENT_SECRET
        secretKey: {{ .Values.secrets.asgardeoClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.asgardeoClientSecret.path | quote }}
      - objectName: IDP_APP_CLIENT_SECRET
        secretKey: {{ .Values.secrets.idpAppClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.idpAppClientSecret.path | quote }}
      - objectName: PARDOT_USER_LIST_REGISTRATION_APP_KEY
        secretKey: {{ .Values.secrets.pardotUserListRegAppKey.key | quote }}
        secretPath: {{ .Values.secrets.pardotUserListRegAppKey.path | quote }}
      - objectName: PARDOT_USER_LIST_REGISTRATION_APP_SECRET
        secretKey: {{ .Values.secrets.pardotUserListRegAppSecret.key | quote }}
        secretPath: {{ .Values.secrets.pardotUserListRegAppSecret.path | quote }}
      - objectName: SALESFORCE_LEAD_VIA_PARDOT_APP_KEY
        secretKey: {{ .Values.secrets.salesforceLeadPardotAppKey.key | quote }}
        secretPath: {{ .Values.secrets.salesforceLeadPardotAppKey.path | quote }}
      - objectName: SALESFORCE_LEAD_VIA_PARDOT_APP_SECRET
        secretKey: {{ .Values.secrets.salesforceLeadPardotAppSecret.key | quote }}
        secretPath: {{ .Values.secrets.salesforceLeadPardotAppSecret.path | quote }}
      - objectName: MAX_MIND_GEO_LOC_COUNTRY_USERNAME
        secretKey: {{ .Values.secrets.maxMindGeoLocationCountryUsername.key | quote }}
        secretPath: {{ .Values.secrets.maxMindGeoLocationCountryUsername.path | quote }}
      - objectName: MAX_MIND_GEO_LOC_COUNTRY_PASSWORD
        secretKey: {{ .Values.secrets.maxMindGeoLocationCountryPassword.key | quote }}
        secretPath: {{ .Values.secrets.maxMindGeoLocationCountryPassword.path | quote }}
      - objectName: PARDOT_STALE_USER_HANDLING_APP_KEY
        secretKey: {{ .Values.secrets.pardotStaleUserHandlingAppKey.key | quote }}
        secretPath: {{ .Values.secrets.pardotStaleUserHandlingAppKey.path | quote }}
      - objectName: PARDOT_STALE_USER_HANDLING_APP_SECRET
        secretKey: {{ .Values.secrets.pardotStaleUserHandlingAppSecret.key | quote }}
        secretPath: {{ .Values.secrets.pardotStaleUserHandlingAppSecret.path | quote }}
      - objectName: SCIM_BACKEND_API_USER_PASSWORD
        secretKey: {{ .Values.secrets.scimBackendAPIUserPassword.key | quote }}
        secretPath: {{ .Values.secrets.scimBackendAPIUserPassword.path | quote }}
      - objectName: SERVICE_NOW_CLIENT_ID
        secretKey: {{ .Values.secrets.serviceNowClientId.key | quote }}
        secretPath: {{ .Values.secrets.serviceNowClientId.path | quote }}
      - objectName: SERVICE_NOW_CLIENT_SECRET
        secretKey: {{ .Values.secrets.serviceNowClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.serviceNowClientSecret.path | quote }}
      - objectName: SERVICE_NOW_USERNAME
        secretKey: {{ .Values.secrets.serviceNowUsername.key | quote }}
        secretPath: {{ .Values.secrets.serviceNowUsername.path | quote }}
      - objectName: SERVICE_NOW_PASSWORD
        secretKey: {{ .Values.secrets.serviceNowPassword.key | quote }}
        secretPath: {{ .Values.secrets.serviceNowPassword.path | quote }}
      - objectName: ASB_CONNECTION_STRING
        secretKey: {{ .Values.secrets.asbConnectionString.key | quote }}
        secretPath: {{ .Values.secrets.asbConnectionString.path | quote }}
      - objectName: APIM_CLIENT_SECRET
        secretKey: {{ .Values.secrets.apimClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.apimClientSecret.path | quote }}   
