apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-mgw-adapter-consul
spec:
  parameters:
    objects: |
      array:
        - |
          objectName: mgw-CONSUL-AGENT-CERTIFICATE
          objectType: secret
          objectAlias: CONSUL_AGENT_CERTIFICATE
          objectVersion: "{{.CONSUL_AGENT_CERTIFICATE}}"
        - |
          objectName: mgw-CONSUL-DC-CLIENT-KEY
          objectType: secret
          objectAlias: CONSUL_DC_CLIENT_KEY
          objectVersion: "{{.CONSUL_DC_CLIENT_KEY}}"
        - |
          objectName: mgw-CONSUL-DC-CLIENT-CERTIFICATE
          objectType: secret
          objectAlias: CONSUL_DC_CLIENT_CERTIFICATE
          objectVersion: "{{.CONSUL_DC_CLIENT_CERTIFICATE}}"
