apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-mgw-keystore
spec:    
  parameters:
    objects:  |
      array:
        - |
          objectName: apim-mg-keystore-key
          objectType: secret
          objectAlias: ADAPTER_KEYSTORE_KEY
          objectVersion: "{{.ADAPTER_KEYSTORE_KEY}}"
        - |
          objectName: apim-mg-keystore-cert
          objectType: secret
          objectAlias: ADAPTER_KEYSTORE_CERTIFICATE
          objectVersion: "{{.ADAPTER_KEYSTORE_CERTIFICATE}}"
