apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-apim-keystores
spec:
  secretObjects:
    - secretName: secret-apim-keystore-passwords
      type: Opaque
      data:
        - objectName: PRIMARY_KEYSTORE_PSWD
          key: PRIMARY_KEYSTORE_PSWD
        - objectName: PRIMARY_KEYSTORE_KEY_PSWD
          key: PRIMARY_KEYSTORE_KEY_PSWD
        - objectName: TLS_KEYSTORE_PSWD
          key: TLS_KEYSTORE_PSWD
        - objectName: TLS_KEYSTORE_KEY_PSWD
          key: TLS_KEYSTORE_KEY_PSWD
        - objectName: INTERNAL_KEYSTORE_PSWD
          key: INTERNAL_KEYSTORE_PSWD
        - objectName: INTERNAL_KEYSTORE_KEY_PSWD
          key: INTERNAL_KEYSTORE_KEY_PSWD
        - objectName: TRUSTSTORE_PSWD
          key: TRUSTSTORE_PSWD
  parameters:
    objects: |
      array:
        - |
          objectName: apim-INTERNAL-KEYSTORE
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: APIM_INTERNAL_KEYSTORE
          objectVersion: "{{.APIM_INTERNAL_KEYSTORE}}"
        - |
          objectName: apim-internal-keystore-password
          objectType: secret
          objectAlias: INTERNAL_KEYSTORE_PSWD
          objectVersion: "{{.INTERNAL_KEYSTORE_PSWD}}"
        - |
          objectName: apim-INTERNAL-KEYSTORE-KEY-PSWD
          objectType: secret
          objectAlias: INTERNAL_KEYSTORE_KEY_PSWD
          objectVersion: "{{.INTERNAL_KEYSTORE_KEY_PSWD}}"
        - |
          objectName: apim-TLS-KEYSTORE
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: APIM_TLS_KEYSTORE
          objectVersion: "{{.APIM_TLS_KEYSTORE}}"
        - |
          objectName: apim-tls-keystore-password
          objectType: secret
          objectAlias: TLS_KEYSTORE_PSWD
          objectVersion: "{{.TLS_KEYSTORE_PSWD}}"
        - |
          objectName: apim-TLS-KEYSTORE-KEY-PSWD
          objectType: secret
          objectAlias: TLS_KEYSTORE_KEY_PSWD
          objectVersion: "{{.TLS_KEYSTORE_KEY_PSWD}}"
        - |
          objectName: apim-PRIMARY-KEYSTORE
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: APIM_PRIMARY_KEYSTORE
          objectVersion: "{{.APIM_PRIMARY_KEYSTORE}}"
        - |
          objectName: apim-primary-keystore-password
          objectType: secret
          objectAlias: PRIMARY_KEYSTORE_PSWD
          objectVersion: "{{.PRIMARY_KEYSTORE_PSWD}}"
        - |
          objectName: apim-PRIMARY-KEYSTORE-KEY-PSWD
          objectType: secret
          objectAlias: PRIMARY_KEYSTORE_KEY_PSWD
          objectVersion: "{{.PRIMARY_KEYSTORE_KEY_PSWD}}"
        - |
          objectName: apim-truststore-password
          objectType: secret
          objectAlias: TRUSTSTORE_PSWD
          objectVersion: "{{.TRUSTSTORE_PSWD}}"
