apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-app-gateway-oauth-agent
spec:
  secretObjects:
    - secretName: secret-app-gateway-oauth-agent
      type: Opaque
      data:
        - objectName: OAUTH_AGENT_ENC_KEY
          key: OAUTH_AGENT_ENC_KEY
        - objectName: PAT_CLIENT_SECRET
          key: PAT_CLIENT_SECRET
        - objectName: REDIS_PASSWORD
          key: REDIS_PASSWORD
  parameters:
    objects: |
      array:
        - |
          objectName: cp-app-gw-auth-agent-enc-key
          objectType: secret
          objectAlias: OAUTH_AGENT_ENC_KEY
          objectVersion: "{{.OAUTH_AGENT_ENC_KEY}}"
        - |
          objectName: cp-app-gw-auth-agent-pat-client-secret
          objectType: secret
          objectAlias: PAT_CLIENT_SECRET
          objectVersion: "{{.PAT_CLIENT_SECRET}}"
        - |
          objectName: oauth-agent-redis-primary-access-key
          objectType: secret
          objectAlias: REDIS_PASSWORD
          objectVersion: "{{.REDIS_PASSWORD}}"
