apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-redis
spec:
  secretObjects:
    - secretName: secret-redis
      type: Opaque
      data:
        - objectName: REDIS_PASSWORD
          key: REDIS_PASSWORD
        - objectName: US_CDP_2_REDIS_PASSWORD
          key: US_CDP_2_REDIS_PASSWORD
        - objectName: NE_REDIS_PASSWORD
          key: NE_REDIS_PASSWORD
        - objectName: APIS_REDIS_PASSWORD
          key: APIS_REDIS_PASSWORD
  parameters:
    objects: |
      array:
        - |
          objectName: {{.REDIS_PASSWORD_APIM_OBJ_NAME | default "apim-global-adapter-redis-primary-access-key"}}
          objectType: secret
          objectAlias: REDIS_PASSWORD
          objectVersion: "{{.REDIS_PASSWORD_APIM}}"
        - |
          objectName: {{.APIS_REDIS_PASSWORD_APIM_OBJ_NAME | default "apim-global-adapter-redis-primary-access-key"}}
          objectType: secret
          objectAlias: APIS_REDIS_PASSWORD
          objectVersion: "{{.APIS_REDIS_PASSWORD_APIM}}"
        - |
          objectName: cp2wu2-redis-ga-PASSWORD
          objectType: secret
          objectAlias: US_CDP_2_REDIS_PASSWORD
          objectVersion: "{{.US_CDP_2_REDIS_PASSWORD_APIM}}"
        - |
          objectName: {{.REDIS_PASSWORD_NE_APIM_OBJ_NAME | default "apim-global-adapter-redis-primary-access-key"}}
          objectType: secret
          objectAlias: NE_REDIS_PASSWORD
          objectVersion: "{{.NE_REDIS_PASSWORD_APIM}}"
