apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-apk-config-ds-certificate
spec:
  parameters:
    objects: |
      array:
        - |
          objectName: apim-mg-keystore-key
          objectType: secret
          objectAlias: config-ds-KEY
          objectVersion: "{{.config_ds_KEY}}"
        - |
          objectName: apim-mg-keystore-cert
          objectType: secret
          objectAlias: config-ds-CERTIFICATE
          objectVersion: "{{.config_ds_CERTIFICATE}}"
