# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
image:
  repository: choreoipaas/choreo-organization-management
  tag: latest
serviceAccount:
  annotations: {}
secrets:
  subscriptionsDBPassword:
    path: choreo-cp/data/choreo-system/organization-management
    key: subscriptionsDBPassword
  appDBPassword:
    path: choreo-cp/data/choreo-system/organization-management
    key: appDBPassword
  azureAccessKey:
    path: choreo-cp/data/choreo-system/organization-management
    key: azureAccessKey
  keystorePassword:
    path: choreo-cp/data/choreo-system/organization-management
    key: keystorePassword
  choreoOrganizationManagementKeystore:
    path: choreo-cp/data/choreo-system/organization-management
    key: choreoOrganizationManagementKeystore
vault:
  roleName: organization-management
config:
  choreoAppDBUrl: "jdbc:sqlserver://sqlfg-choreo-choreo-app-db-prod.database.windows.net;databaseName=choreo_app_db"
  choreoDefaultThemePath: "/home/ballerina/resources/default_theme.json"
  choreoJwtIssuer: "https://sts.choreo.dev:443/oauth2/token"
  choreoJwtAudience: "ciwnWuwZfbcdzBUcnkhKvi_mcBUa"
  choreoJwtJwksUrl: "https://sts.choreo.dev/oauth2/jwks"
  azureStorageAccount: "choreoproddevportalcdn36"
  choreoAuthHandlerAudiences: 
    - ciwnWuwZfbcdzBUcnkhKvi_mcBUa
    - miFf_pvfsQeeLycfq7kf7bDxbZsa
    - F8ytfAHD7bO3bpUdi2wlWEDqslwa
  choreoSystemOrgUUID: "5659b6b7-1063-41ed-8e39-d91857699255"
  choreoDevportalBaseUrl: "https://devportal.choreo.dev"
  enableEventPublish: true
  websubHubUrl: "https://publish.websubhub.choreo.dev/hub"
  enableEventPublisherMTLS: true
  choreoSubscriptionDBUrl: "jdbc:sqlserver://sqlfg-choreo-choreo-subscriptions-db-prod.database.windows.net:1433;database=choreo_subscriptions_db"
  maxActiveUsers: 1000
