# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dp-secret-manager
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    {{- include "dp-secret-manager.labels" . | nindent 4 }}
spec:
  provider: vault
  secretObjects:
    - secretName: dp-secret-manager
      type: Opaque
      data:
        - objectName: AZURE_KEYVAULT_CLIENT_ID
          key: AZURE_KEYVAULT_CLIENT_ID
        - objectName: AZURE_KEYVAULT_CLIENT_SECRET
          key: AZURE_KEYVAULT_CLIENT_SECRET
        - objectName: AZURE_KEYVAULT_TENANT_ID
          key: AZURE_KEYVAULT_TENANT_ID
        - objectName: AZURE_KEYVAULT_CLIENT_SECRET
          key: SYSTEM_KV_CLIENT_SECRET
        - objectName: AZURE_KEYVAULT_CLIENT_SECRET
          key: US_CDP_1_KV_CLIENT_SECRET
        - objectName: AZURE_KEYVAULT_CLIENT_SECRET
          key: EU_CDP_1_KV_CLIENT_SECRET
        - objectName: US_CDP_2_KV_CLIENT_SECRET
          key: US_CDP_2_KV_CLIENT_SECRET
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: AZURE_KEYVAULT_CLIENT_ID
        secretKey: {{ .Values.secrets.azureKeyVaultClientId.key | quote }}
        secretPath: {{ .Values.secrets.azureKeyVaultClientId.path | quote }}
      - objectName: AZURE_KEYVAULT_CLIENT_SECRET
        secretKey: {{ .Values.secrets.azureKeyVaultClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.azureKeyVaultClientSecret.path | quote }}
      - objectName: AZURE_KEYVAULT_TENANT_ID
        secretKey: {{ .Values.secrets.azureKeyVaultTenantId.key | quote }}
        secretPath: {{ .Values.secrets.azureKeyVaultTenantId.path | quote }}
      - objectName: US_CDP_2_KV_CLIENT_SECRET
        secretKey: {{ .Values.secrets.usCdp2KeyVaultClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.usCdp2KeyVaultClientSecret.path | quote }}
