apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: reflector-secrets
spec:
  secretObjects:
    - secretName: choreo-image-pull-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: mi-blob-ad-application-secret
          key: .dockerconfigjson
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "^dp-builds-.+"
  parameters:
    objects: |
      - objectName: {{.MI_BLOB_AD_APP_SECRET_OBJ_NAME | default "mi-dist-and-mi-blob-ad-application-image-pull-secret" }}
        objectType: secret
        objectAlias: mi-blob-ad-application-secret
        objectVersion: "{{.MI_BLOB_AD_APP_SECRET}}"
