# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

replicas: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
image:
  repository: config-deployer-service
  tag: 1.0.0-amd64
secrets:
  privateKey:
    path: choreo-cp/data/choreo-apim/config-deployer-service
    key: privateKey
  publicKey:
    path: choreo-cp/data/choreo-apim/config-deployer-service
    key: publicKey
vault:
  roleName: config-deployer-service
serviceAccount:
  annotations: {}
