apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-choreo-codeanalyzer
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: file
  capacity:
    storage: 500Mi
  hostPath:
    path: /home/docker/choreo-codeanalyzer
  persistentVolumeReclaimPolicy: Delete