apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium
  namespace: cilium
spec:
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/config: runtime/default
        container.apparmor.security.beta.kubernetes.io/mount-bpf-fs: runtime/default
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cilium-agent
          securityContext:
            allowPrivilegeEscalation: false
      initContainers:
        - name: config
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        - name: mount-cgroup
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        - name: apply-sysctl-overwrites
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        - name: mount-bpf-fs
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            privileged: true
          resources:
            limits:
              cpu: 150m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        - name: clean-cilium-state
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
