kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all-network-policy
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector: {}
  ingress: []
  egress: []

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: identity-server-network-policy
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      deployment: wso2is
  ingress:
  - ports:
    - port: 9443
    from:
    - podSelector: {}
  egress:
  - {}

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-ingress-network-policy
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: nginx-ingress-choreo-idp
      app.kubernetes.io/name: ingress-nginx
  ingress:
  - ports:
    - port: 80
    - port: 443
    - port: 8443
  egress:
  - {}
