[cp.proxyDeployer.config]
maxRevisions = 20

dbUser = "choreo_proxy_deployer_db_user"

proxyDeployerPort = 9095
healthCheckPort = 9091

jwtTokenScopes = ["apim:api_manage", "apim:publisher_settings"]

[ballerina.http.accessLogConfig]
console = true

[ballerina.log]
level = "{{.LOG_LEVEL | default "INFO"}}"
