apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: choreo-control-plane-wildcard-cert
spec:
  acme:
    config:
    - dns01:
        provider: azure-dns
      domains:
      - dv.choreo.dev
      - '*.dv.choreo.dev'
  commonName: dv.choreo.dev
  dnsNames:
  - dv.choreo.dev
  - '*.dv.choreo.dev'
  issuerRef:
    kind: ClusterIssuer
    name: choreo-letsencrypt-prod
  secretName: choreo-control-plane-wildcard-tls
