# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-rules-fluent-bit
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: choreo-observability
            app.kubernetes.io/name: opensearch
      toPorts:
        - ports:
            - port: "9200"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
  ingress:
    # Allow ingress from loggingapi to receive requests to the health check endpoint
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: choreo-observability
            choreo.component: loggingapi
      toPorts:
        - ports:
            - port: "2020"
              protocol: TCP
