apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rules-insights-query-api
spec:
  podSelector:
    matchLabels:
      choreo.component: insights-query-api
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0  # Allow all egress traffic
            except:
              - 169.254.169.254/32  # Except egress to Azure VM metadata endpoint
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: choreo-apim
          podSelector:
            matchLabels:
              cc.component: choreo-connect-deployment
