apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: idp-carbon-keystore
spec:
  secretObjects:
    - secretName: idp-carbon-keystore
      type: Opaque
      data:
        - objectName: IDP_CARBON_KEYSTORE
          key: IDP_CARBON_KEYSTORE
  parameters:
    objects: |
      array:
        - |
          objectName: {{.IDP_CARBON_KEYSTORE_OBJ_NAME | default "idp-CARBON-KEYSTORE-CERTIFICATE"}}
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: IDP_CARBON_KEYSTORE
          objectVersion: "{{.IDP_CARBON_KEYSTORE}}"
