apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-operator-external-metrics-reader
  annotations:
    checkov.io/skip1: CKV_K8S_49=Not an Issue, https://github.com/wso2-enterprise/choreo/issues/20999
