apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
  annotations:
    checkov.io/skip1: CKV_K8S_38=Not an Issue, https://github.com/wso2-enterprise/choreo/issues/20999
    checkov.io/skip2: CKV_K8S_AZURE_WSO2_2=Not an Issue, https://github.com/wso2-enterprise/choreo/issues/20999
spec:
  template:
    spec:
      containers:
      - name: keda-operator
        env:
        - name: KEDA_RESTRICT_SECRET_ACCESS
          value: "true"
        securityContext:
          runAsUser: 10001
      securityContext:
        seccompProfile:
          type: RuntimeDefault
