IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_crypto_key_db_user')
BEGIN
    CREATE USER [choreo_crypto_key_db_user] with password = N'${choreo-crypto-key-db-mssql-password}'
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo_crypto_key_db TO choreo_crypto_key_db_user
END;
GO

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[SSL_CERTIFICATE_INFO]') AND TYPE IN (N'U'))
CREATE TABLE SSL_CERTIFICATE_INFO(
    ID INTEGER NOT NULL IDENTITY(1,1),
    NAME VARCHAR(100) NOT NULL,
    ISSUER VARCHAR(255) NOT NULL,
    COMPONENT_ID VARCHAR(50) NOT NULL,
    ORGANIZATION_ID VARCHAR(50) NOT NULL,
    PROJECT_ID VARCHAR(50) NOT NULL,
    NOT_AFTER VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10),
    PRIMARY KEY (ID),
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[SSL_CERT_SECRET_ENV_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE SSL_CERT_SECRET_ENV_MAPPING(
    ID INTEGER NOT NULL IDENTITY(1,1),
    CERT_ID INTEGER NOT NULL,
    ENVIRONMENT_ID VARCHAR(50) NOT NULL,
    SECRET_ID VARCHAR(50) NOT NULL,
    ENDPOINT_TYPE VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CERT_ID) REFERENCES SSL_CERTIFICATE_INFO(ID) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_CERT_ID_ENV_ID_TYPE UNIQUE (CERT_ID, ENVIRONMENT_ID, SECRET_ID, ENDPOINT_TYPE)
);

IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MTLS_KEY_INFO]') AND TYPE IN (N'U'))
CREATE TABLE MTLS_KEY_INFO(
    ID INTEGER NOT NULL IDENTITY(1,1),
    NAME VARCHAR(100) NOT NULL,
    ORGANIZATION_ID VARCHAR(50) NOT NULL,
    PROJECT_ID VARCHAR(50) NOT NULL,
    NOT_AFTER VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_ORG_ID_NAME UNIQUE (NAME, ORGANIZATION_ID)
);


IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MTLS_KEY_COMPONENT_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE MTLS_KEY_COMPONENT_MAPPING(
    ID INTEGER NOT NULL IDENTITY(1,1),
    MTLS_ID INTEGER NOT NULL,
    COMPONENT_ID VARCHAR(50) NOT NULL,
    COMPONENT_NAME VARCHAR(100),
    PRIMARY KEY (ID),
    FOREIGN KEY (MTLS_ID) REFERENCES MTLS_KEY_INFO(ID) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_MTLS_ID_CMP_ID UNIQUE (MTLS_ID, COMPONENT_ID)
);


IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[MTLS_KEY_SECRET_ENV_MAPPING]') AND TYPE IN (N'U'))
CREATE TABLE MTLS_KEY_SECRET_ENV_MAPPING(
    ID INTEGER NOT NULL IDENTITY(1,1),
    MTLS_ID INTEGER NOT NULL,
    ENVIRONMENT_ID VARCHAR(50) NOT NULL,
    SECRET_ID VARCHAR(50) NOT NULL,
    ENDPOINT_TYPE VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MTLS_ID) REFERENCES MTLS_KEY_INFO(ID) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_MTLS_ID_ENV_ID UNIQUE (MTLS_ID, ENVIRONMENT_ID, SECRET_ID, ENDPOINT_TYPE)
);
