-- Create User
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'choreo_governance_db')
AND NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_governance_db_user')
BEGIN
    CREATE USER [choreo_governance_db_user] WITH PASSWORD = N'${choreo_governance_db_mssql_password}';
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo_governance_db TO choreo_governance_db_user;
END;
GO
-- Create RULESET Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[RULESET]') AND TYPE IN (N'U'))
    CREATE TABLE RULESET (
        RULESET_ID VARCHAR(45) NOT NULL,
        NAME VARCHAR(200) NOT NULL,
        DESCRIPTION VARCHAR(1024),
        RULESET_CONTENT VARBINARY(MAX) NOT NULL,
        APPLIES_TO VARCHAR(100) NOT NULL,
        DOCUMENTATION_LINK VARCHAR(1024),
        PROVIDER VARCHAR(200),
        ORGANIZATION VARCHAR(100) NOT NULL,
        CREATED_BY VARCHAR(255),
        CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY VARCHAR(255),
        LAST_UPDATED_TIME DATETIME,
        CONSTRAINT RULESET_UNIQUE_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
        PRIMARY KEY (RULESET_ID)
    );
-- Create GOVERNANCE_POLICY Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[GOVERNANCE_POLICY]') AND TYPE IN (N'U'))
    CREATE TABLE GOVERNANCE_POLICY (
        POLICY_ID VARCHAR(45) NOT NULL,
        NAME VARCHAR(200) NOT NULL,
        DESCRIPTION VARCHAR(1024),
        ORGANIZATION VARCHAR(100) NOT NULL,
        CREATED_BY VARCHAR(255),
        CREATED_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
        UPDATED_BY VARCHAR(255),
        LAST_UPDATED_TIME DATETIME,
        CONSTRAINT POLICY_UNIQUE_CONSTRAINT UNIQUE (NAME, ORGANIZATION),
        PRIMARY KEY (POLICY_ID)
    );
-- Create GOVERNANCE_POLICY_LABEL Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[GOVERNANCE_POLICY_LABEL]') AND TYPE IN (N'U'))
    CREATE TABLE GOVERNANCE_POLICY_LABEL (
        POLICY_LABEL_ID VARCHAR(45) NOT NULL,
        POLICY_ID VARCHAR(45) NOT NULL,
        LABEL VARCHAR(100) NOT NULL,
        FOREIGN KEY (POLICY_ID) REFERENCES GOVERNANCE_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT POLICY_LABEL_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, LABEL),
        PRIMARY KEY (POLICY_LABEL_ID)
    );
-- Create POLICY_RULESET_MAPPING Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[POLICY_RULESET_MAPPING]') AND TYPE IN (N'U'))
    CREATE TABLE POLICY_RULESET_MAPPING (
        POLICY_RULESET_MAPPING_ID VARCHAR(45) NOT NULL,
        POLICY_ID VARCHAR(45) NOT NULL,
        RULESET_ID VARCHAR(45) NOT NULL,
        FOREIGN KEY (POLICY_ID) REFERENCES GOVERNANCE_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        FOREIGN KEY (RULESET_ID) REFERENCES RULESET(RULESET_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT POLICY_RULESET_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, RULESET_ID),
        PRIMARY KEY (POLICY_RULESET_MAPPING_ID)
    );
-- Create RULESET_RULE Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[RULESET_RULE]') AND TYPE IN (N'U'))
    CREATE TABLE RULESET_RULE (
        RULESET_RULE_ID VARCHAR(45) NOT NULL,
        RULESET_ID VARCHAR(45) NOT NULL,
        RULE_CODE VARCHAR(200) NOT NULL,
        RULE_DESCRIPTION VARCHAR(1024),
        SEVERITY INTEGER,
        FOREIGN KEY (RULESET_ID) REFERENCES RULESET(RULESET_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT RULESET_RULE_UNIQUE_CONSTRAINT UNIQUE (RULESET_ID, RULE_CODE),
        PRIMARY KEY (RULESET_RULE_ID)
    );
-- Create ENDPOINT_DETAILS Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[ENDPOINT_DETAILS]') AND TYPE IN (N'U'))
    CREATE TABLE ENDPOINT_DETAILS (
        ENDPOINT_ID VARCHAR(45) NOT NULL,
        TYPE VARCHAR(50),
        PROJECT_ID VARCHAR(45),
        COMPONENT_ID VARCHAR(45),
        API_ID VARCHAR(45),
        ORGANIZATION VARCHAR(45),
        PRIMARY KEY (ENDPOINT_ID)
    );
-- Create LINTING_RESULT Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LINTING_RESULT]') AND TYPE IN (N'U'))
    CREATE TABLE LINTING_RESULT (
        RULESET_RULE_ID VARCHAR(45) NOT NULL,
        PATH VARBINARY(MAX) NOT NULL,
        ENDPOINT_ID VARCHAR(45) NOT NULL,
        FOREIGN KEY (RULESET_RULE_ID) REFERENCES RULESET_RULE(RULESET_RULE_ID) ON DELETE CASCADE,
        FOREIGN KEY (ENDPOINT_ID) REFERENCES ENDPOINT_DETAILS(ENDPOINT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        PRIMARY KEY (RULESET_RULE_ID, ENDPOINT_ID)
    );
-- Create LINTING_STATUS Table
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[LINTING_STATUS]') AND TYPE IN (N'U'))
    CREATE TABLE LINTING_STATUS (
        RUN_ID VARCHAR(45) NOT NULL,
        POLICY_ID VARCHAR(45),
        RULESET_ID VARCHAR(45),
        ENDPOINT_ID VARCHAR(45),
        STATUS VARCHAR(20),
        STARTED_TIME DATETIME,
        COMPLETED_TIME DATETIME,
        FOREIGN KEY (ENDPOINT_ID) REFERENCES ENDPOINT_DETAILS(ENDPOINT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        FOREIGN KEY (POLICY_ID) REFERENCES GOVERNANCE_POLICY(POLICY_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        FOREIGN KEY (RULESET_ID) REFERENCES RULESET(RULESET_ID) ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT LINTING_STATUS_UNIQUE_CONSTRAINT UNIQUE (POLICY_ID, RULESET_ID, ENDPOINT_ID),
        PRIMARY KEY (RUN_ID)
    );
