-- Create User
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'choreo_cost_optimizer_db') AND NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'choreo_cost_optimizer_db_user')
BEGIN
    CREATE USER [choreo_cost_optimizer_db_user] with password = N'${choreo_cost_optimizer_db_mssql_password}'
    GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON DATABASE::choreo_cost_optimizer_db TO choreo_cost_optimizer_db_user
END;
GO

CREATE TABLE AUTO_OPTIMIZED (
    ID INTEGER PRIMARY KEY IDENTITY(1,1),
    UPDATED_AT DATETIME NOT NULL,
    ORG_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    RELEASE_ID VARCHAR(255) NULL,
    COMPONENT_ID VARCHAR(255) NULL,
    ENVIRONMENT_ID VARCHAR(255) NOT NULL,
    STATUS BIT NOT NULL
);

CREATE TABLE RECOMMENDATIONS (
    ID INTEGER PRIMARY KEY IDENTITY(1,1),
    DATE DATE NOT NULL,
    ORG_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    RELEASE_ID VARCHAR(255) NOT NULL,
    COMPONENT_ID VARCHAR(255) NOT NULL,
    ENVIRONMENT_ID VARCHAR(255) NOT NULL,
    RESOURCE_APPLIED BIT NOT NULL,
    S2Z_APPLIED BIT NOT NULL,
    UNDEPLOY_APPLIED BIT NOT NULL
);

CREATE TABLE RESOURCE_RECOMMENDATIONS (
    ID INTEGER PRIMARY KEY IDENTITY(1,1),
    RECOMMENDATION_ID INTEGER NOT NULL,
    CPU_LIMIT FLOAT NOT NULL,
    CPU_REQUEST FLOAT NOT NULL,
    MEMORY_LIMIT FLOAT NOT NULL,
    MEMORY_REQUEST FLOAT NOT NULL,
    CPU_COST_SAVING FLOAT NOT NULL,
    MEMORY_COST_SAVING FLOAT NOT NULL,
    FOREIGN KEY (RECOMMENDATION_ID) REFERENCES RECOMMENDATIONS(ID) ON DELETE CASCADE
);

CREATE TABLE S2Z_RECOMMENDATIONS (
    ID INTEGER PRIMARY KEY IDENTITY(1,1),
    RECOMMENDATION_ID INTEGER NOT NULL,
    S2Z BIT NOT NULL,
    S2Z_COST_SAVING FLOAT NOT NULL,
    FOREIGN KEY (RECOMMENDATION_ID) REFERENCES RECOMMENDATIONS(ID) ON DELETE CASCADE
);

CREATE TABLE UNDEPLOY_RECOMMENDATIONS (
    ID INTEGER PRIMARY KEY IDENTITY(1,1),
    RECOMMENDATION_ID INTEGER NOT NULL,
    UNDEPLOY BIT NOT NULL,
    UNDEPLOY_COST_SAVING FLOAT NOT NULL,
    FOREIGN KEY (RECOMMENDATION_ID) REFERENCES RECOMMENDATIONS(ID) ON DELETE CASCADE
);
