apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: "${INGRESS_CONTROLLER_INSTANCE}" #"${WORKSPACE_INGRESS_NAMESPACE}"
    app.kubernetes.io/name: "${INGRESS_CONTROLLER_DEPLOYMENT}" #${WORKSPACE_INGRESS_NAMESPACE}-nginx-ingress"
  name: "${INGRESS_CONTROLLER_DEPLOYMENT}" #"${WORKSPACE_INGRESS_NAMESPACE}-nginx-ingress"
  namespace: "${INGRESS_CONTROLLER_NAMESPACE}" #"${WORKSPACE_INGRESS_NAMESPACE}-nginx-plus-ingress"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: "${INGRESS_CONTROLLER_DEPLOYMENT}" #"${WORKSPACE_INGRESS_NAMESPACE}-nginx-ingress"
