# -------------------------------------------------------------------------------------
#
# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

runAsUser: 10500

image:
  repository: choreocontrolplane.azurecr.io/apache/superset-extended
  tag: master-1a8d5458445d7f7387d4fd01343f0b2bc7beb9fa
  pullPolicy: Always

ingress:
  enabled: true
  ingressClassName: prod-choreo-system-nginx
  hosts:
  - superset.choreo.dev
  tls:
  - secretName: prod-choreo-system-wildcard-tls
    hosts:
    - superset.choreo.dev

initImage:
  repository: choreocontrolplane.azurecr.io/busybox
  tag: 1.34_2022-08-17_10-57-44
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

configFromSecret: superset-secret-custom-config

supersetNode:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  connections:
    db_host: postgresql-choreo-prod-eastus2-001.postgres.database.azure.com
    db_port: "5432"
    db_user: superset_admin
    db_name: superset
  initContainers:
    - name: wait-for-postgres
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: "{{ .Values.initImage.pullPolicy }}"
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      envFrom:
        - secretRef:
            name: '{{ tpl .Values.envFromSecret . }}'
      command: ["/bin/sh", "-c", "until nc -zv $DB_HOST $DB_PORT -w1; do echo 'waiting for db'; sleep 1; done"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

supersetWorker:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  initContainers:
    - name: wait-for-postgres
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: "{{ .Values.initImage.pullPolicy }}"
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      envFrom:
        - secretRef:
            name: '{{ tpl .Values.envFromSecret . }}'
      command: ["/bin/sh", "-c", "until nc -zv $DB_HOST $DB_PORT -w1; do echo 'waiting for db'; sleep 1; done"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi


init:
  adminUser:
    username: admin
    firstname: Superset
    lastname: Admin
    email: integration-choreo-group@wso2.com
    password: superset_app_admin
  initContainers:
    - name: wait-for-postgres
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: "{{ .Values.initImage.pullPolicy }}"
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      envFrom:
        - secretRef:
            name: '{{ tpl .Values.envFromSecret . }}'
      command: ["/bin/sh", "-c", "until nc -zv $DB_HOST $DB_PORT -w1; do echo 'waiting for db'; sleep 1; done"]
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi


postgresql:
  enabled: false

redis:
  image:
    registry: choreocontrolplane.azurecr.io
    repository: bitnami/redis
    tag: 7.0.4-debian-11-r7
    pullPolicy: Always
  master:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      runAsUser: 1001
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
