apiVersion: v1
kind: Service
metadata:
  name: adapter
  labels:
    choreo.component: choreo-connect-adapter-dev-us-east-azure-p4
spec:
  selector:
    choreo.component: choreo-connect-adapter-dev-us-east-azure-p4
