apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: appservice
  name: appservice
spec:
  ports:
  - name: appservice-port
    port: 80
    protocol: TCP
    targetPort: appservice-port
  - name: as-grpc-port
    port: 9092
    protocol: TCP
    targetPort: as-grpc-port  
  selector:
    choreo.component: appservice
