apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: capacity-planner
  name: capacity-planner
spec:
  ports:
    - name: cpp-port
      port: 5000
      protocol: TCP
      targetPort: cpp-port
  selector:
    choreo.component: capacity-planner

