apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: codeanalyzer
  name: codeanalyzer
spec:
  ports:
  - name: port-7ydy
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    choreo.component: codeanalyzer