apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: language-server
  name: language-server
spec:
  ports:
  - name: ls-port
    port: 9090
    protocol: TCP
    targetPort: http-port
  selector:
    choreo.component: language-server
