apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: loggingapi
  name: loggingapi
spec:
  ports:
  - name: logapi-port
    port: 9097
    targetPort: logapi-port
  - name: healthz
    port: 9099
    targetPort: healthz
  selector:
    choreo.component: loggingapi
