apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: programanalyzer
  name: programanalyzer
spec:
  ports:
  - name: progan-port
    port: 9000
    protocol: TCP
    targetPort: progan-port
  selector:
    choreo.component: programanalyzer
