apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: test-assistant
  name: test-assistant
spec:
  ports:
    - name: ta-port
      port: 5000
      protocol: TCP
      targetPort: ta-port
  selector:
    choreo.component: test-assistant
