apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    choreo.component: choreo-program-db
  name: choreo-program-db
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: choreo-program-db
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        choreo.component: choreo-program-db
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: choreo-secret
            key: choreo_program_db_password
        image: choreoipaas/choreo_program_db:latest
        name: choreo-program-db
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: choreo-program-db-claim
      volumes:
      - name: choreo-program-db-claim
        persistentVolumeClaim:
          claimName: pvc-choreo-program-db
