apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: spec-populator
  name: spec-populator
spec:
  ports:
    - name: spec-pop-port
      port: 8000
      targetPort: spec-pop-port
  selector:
    choreo.component: spec-populator
