#!/usr/bin/env bash

usage() {
    echo "usage: git ccp init"
    echo ""
    echo "Initialize the git ccp extension"
    echo
}

cmd_default() {
    set_username
}

cmd_help() {
    usage
    exit 0
}
