#!/usr/bin/env bash

usage() {
    echo "usage: git ccp feature <subcommand>"
    echo ""
    echo "Available subcommands are:"
    echo "    init                                 Initialize branches for a new feature"
    echo "    sync <feature-id>                    Sync feature base branch with the environment"
    echo "                                         specific branches "
    echo "    publish <feature-id> <issue-number>  Publish changes by creating pull requests"
    echo "    pending <env>                        List all commits still pending to be merged to"
    echo "                                         the given env prod"
    echo
}

cmd_default() {
    cmd_help
}

cmd_help() {
    usage
    exit 0
}

cmd_init() {
    
    printf "Feature name (use a one without spaces) : "
    read -r answer

    if [ -z "$answer" ]
    then
	echo "Please give a valid feature ID"
	exit 0
    fi

    generate_env_branches "$answer"

    git fetch upstream
    git branch "$MASTER_BRANCH_NAME" "$MASTER_BASE"
    git branch "$DEV_BRANCH_NAME" "$DEV_BASE"
    git branch "$STAGE_BRANCH_NAME" "$STAGE_BASE"
    git branch "$PROD_BRANCH_NAME" "$PROD_BASE"

    git checkout "$MASTER_BRANCH_NAME"
    
    echo
    echo "Summary of actions:"
    echo "- A new branch '$MASTER_BRANCH_NAME' was created, based on '$MASTER_BASE'"
    echo "- A new branch '$DEV_BRANCH_NAME' was created, based on '$DEV_BASE'"
    echo "- A new branch '$STAGE_BRANCH_NAME' was created, based on '$STAGE_BASE'"
    echo "- A new branch '$PROD_BRANCH_NAME' was created, based on '$PROD_BASE'"
    echo "- You are now on branch '$MASTER_BRANCH_NAME'"
    echo ""
    echo "Now, start committing on your feature. When done, use:"
    echo ""
    echo "     git ccp feature sync $answer"
    echo
}

generate_env_branches() {
    T_FEATURE_ID=$1

    MASTER_BASE='upstream/latest-master-release'
    DEV_BASE='upstream/dev'
    STAGE_BASE='upstream/stage'
    PROD_BASE='upstream/prod'

    MASTER_BRANCH_NAME="feature/base/${T_FEATURE_ID}"
    DEV_BRANCH_NAME="feature/dev/${T_FEATURE_ID}"
    STAGE_BRANCH_NAME="feature/stage/${T_FEATURE_ID}"
    PROD_BRANCH_NAME="feature/prod/${T_FEATURE_ID}"
}

parse_args() {
    # parse options
    FLAGS "$@" || exit $?
    eval set -- "${FLAGS_ARGV}"
}

print_summary_of_sync() {
    BRANCH_NAME=$1
    MASTER_BRANCH_NAME=$2
    SYNC_WITH_BASE_STATUS=$3
    SYNC_WITH_UPSTREAM_STATUS=$4
    UPSTREAM_BRANCH_NAME=$5
    PRINT_BASE_SYNC_MESSAGE=$6

    if [ "$PRINT_BASE_SYNC_MESSAGE" == 1 ]
    then
        if [ "$SYNC_WITH_BASE_STATUS" == 0 ]
        then
            echo "- The branch '$BRANCH_NAME' was merged with '$MASTER_BRANCH_NAME'"
        else
            echo "- The branch '$BRANCH_NAME' was failed to be merged with '$MASTER_BRANCH_NAME'"
        fi
    fi

    if [ "$SYNC_WITH_UPSTREAM_STATUS" == 0 ]
    then
        echo "- The branch '$BRANCH_NAME' was merged with '$UPSTREAM_BRANCH_NAME'"
    else
        echo "- The branch '$BRANCH_NAME' was failed to be merged with '$UPSTREAM_BRANCH_NAME'"
    fi
}

cmd_sync() {
    parse_args "$@"

    FEATURE_ID=$1

    if [ -z "$FEATURE_ID" ]; then
	warn "Missing argument <feature-name>"
	usage
	exit 1
    fi

    generate_env_branches "$FEATURE_ID"

    echo "==== Syncing $MASTER_BRANCH_NAME ===="
    git checkout "$MASTER_BRANCH_NAME"
    git merge --no-edit "$MASTER_BASE"
    BASE_SYNC_WITH_UPSTREAM_STATUS=$?
    git push origin "$MASTER_BRANCH_NAME"

    echo -e "\n\n==== Syncing $DEV_BRANCH_NAME ===="
    git checkout "$DEV_BRANCH_NAME"
    git merge --no-edit "$MASTER_BRANCH_NAME"
    DEV_SYNC_WITH_BASE_STATUS=$?
    git merge --no-edit "$DEV_BASE"
    DEV_SYNC_WITH_UPSTREAM_STATUS=$?
    git push origin "$DEV_BRANCH_NAME"

    echo -e "\n\n==== Syncing $STAGE_BRANCH_NAME ===="
    git checkout "$STAGE_BRANCH_NAME"
    git merge --no-edit "$MASTER_BRANCH_NAME"
    STAGE_SYNC_WITH_BASE_STATUS=$?
    git merge --no-edit "$STAGE_BASE"
    STAGE_SYNC_WITH_UPSTREAM_STATUS=$?
    git push origin "$STAGE_BRANCH_NAME"

    echo -e "\n\n==== Syncing $PROD_BRANCH_NAME ===="
    git checkout "$PROD_BRANCH_NAME"
    git merge --no-edit "$MASTER_BRANCH_NAME"
    PROD_SYNC_WITH_BASE_STATUS=$?
    git merge --no-edit "$PROD_BASE"
    PROD_SYNC_WITH_UPSTREAM_STATUS=$?
    git push origin "$PROD_BRANCH_NAME"

    git checkout "$MASTER_BRANCH_NAME"

    echo
    echo "Summary of actions:"
    print_summary_of_sync "$MASTER_BRANCH_NAME" "$MASTER_BRANCH_NAME" "1" "$BASE_SYNC_WITH_UPSTREAM_STATUS" "$MASTER_BASE" "0"
    print_summary_of_sync "$DEV_BRANCH_NAME" "$MASTER_BRANCH_NAME" "$DEV_SYNC_WITH_BASE_STATUS" "$DEV_SYNC_WITH_UPSTREAM_STATUS" "$DEV_BASE" "1"
    print_summary_of_sync "$STAGE_BRANCH_NAME" "$MASTER_BRANCH_NAME" "$STAGE_SYNC_WITH_BASE_STATUS" "$STAGE_SYNC_WITH_UPSTREAM_STATUS" "$STAGE_BASE" "1"
    print_summary_of_sync "$PROD_BRANCH_NAME" "$MASTER_BRANCH_NAME" "$PROD_SYNC_WITH_BASE_STATUS" "$PROD_SYNC_WITH_UPSTREAM_STATUS" "$PROD_BASE" "1"
    echo "- All changes were synced with origin remote"
    echo "- You are now on branch '$MASTER_BRANCH_NAME'"
    echo ""
    echo
}

print_summary_of_publish() {
    BRANCH_NAME=$1
    PUSH_STATUS=$2
    
    if [ "$PUSH_STATUS" == 0 ]
    then
        echo "- The branch '$BRANCH_NAME' was published to control plane repo'"
    else
        echo "- The branch '$BRANCH_NAME' was failed to be published to control plane repo'"
    fi
}

cmd_publish() {
    parse_args "$@"

    FEATURE_ID=$1

    if [ -z "$FEATURE_ID" ]; then
	warn "Missing argument <feature-name>"
	usage
	exit 1
    fi

    ISSUE_ID=$2

    if [ -z "$ISSUE_ID" ]; then
	warn "Missing argument <issue-number>"
	usage
	exit 1
    fi

    set_username

    generate_env_branches "$FEATURE_ID"

    git checkout "$MASTER_BRANCH_NAME"
    gh pr create --head "$USERNAME":"$MASTER_BRANCH_NAME" -B master --title "[BASE] $FEATURE_ID" --body "## Related Issue"$'\n'$'\n'"#$ISSUE_ID"
    BASE_PR_CREATE_MESSAGE=$?

    git checkout "$DEV_BRANCH_NAME"
    gh pr create --head "$USERNAME":"$DEV_BRANCH_NAME" -B dev --title "[DEV] $FEATURE_ID" --body "## Related Issue"$'\n'$'\n'"#$ISSUE_ID"
    DEV_PR_CREATE_MESSAGE=$?

    git checkout "$STAGE_BRANCH_NAME"
    gh pr create --head "$USERNAME":"$STAGE_BRANCH_NAME" -B stage --title "[STAGE] $FEATURE_ID" --body "## Related Issue"$'\n'$'\n'"#$ISSUE_ID"
    STAGE_PR_CREATE_MESSAGE=$?

    git checkout "$PROD_BRANCH_NAME"
    gh pr create --head "$USERNAME":"$PROD_BRANCH_NAME" -B prod --title "[PROD] $FEATURE_ID" --body "## Related Issue"$'\n'$'\n'"#$ISSUE_ID"
    PROD_PR_CREATE_MESSAGE=$?

    git checkout "$MASTER_BRANCH_NAME"

    echo
    echo "Summary of actions:"
    print_summary_of_publish "$MASTER_BRANCH_NAME" "$BASE_PR_CREATE_MESSAGE"
    print_summary_of_publish "$DEV_BRANCH_NAME" "$DEV_PR_CREATE_MESSAGE"
    print_summary_of_publish "$STAGE_BRANCH_NAME" "$STAGE_PR_CREATE_MESSAGE"
    print_summary_of_publish "$PROD_BRANCH_NAME" "$PROD_PR_CREATE_MESSAGE"
    echo "- You are now on branch '$MASTER_BRANCH_NAME'"
    echo ""
    echo
}

cmd_pending() {
    parse_args "$@"

    ENVIRONMENT=$1

    if [ -z "$ENVIRONMENT" ]; then
	warn "Missing argument <environment>"
	usage
	exit 1
    fi

    git fetch upstream
    git --no-pager log "upstream/${ENVIRONMENT}..upstream/master"
}
