#!/bin/sh

usage() {
    echo "usage: git ccp feature <subcommand>"
    echo ""
    echo "Available subcommands are:"
    echo "    init     Initialize branches for a new feature"
    echo
}

cmd_default() {
    cmd_help
}

cmd_help() {
    usage
    exit 0
}

cmd_init() {
    
    printf "Control Plane Feature ID: "
    read answer

    if [ -z "$answer" ]
    then
	echo "Please give a valid feature ID"
	exit 0
    fi

    MASTER_BASE='upstream/latest-master-release'
    DEV_BASE='upstream/dev'
    STAGE_BASE='upstream/stage'
    PROD_BASE='upstream/prod'

    MASTER_BRANCH_NAME="feature/base/${answer}" 
    DEV_BRANCH_NAME="feature/dev/${answer}" 
    STAGE_BRANCH_NAME="feature/stage/${answer}" 
    PROD_BRANCH_NAME="feature/prod/${answer}" 

    git fetch upstream
    git branch $MASTER_BRANCH_NAME $MASTER_BASE 
    git branch $DEV_BRANCH_NAME $DEV_BASE 
    git branch $STAGE_BRANCH_NAME $STAGE_BASE 
    git branch $PROD_BRANCH_NAME $PROD_BASE 

    git checkout $MASTER_BRANCH_NAME
    
    echo
    echo "Summary of actions:"
    echo "- A new branch '$MASTER_BRANCH_NAME' was created, based on '$MASTER_BASE'"
    echo "- A new branch '$DEV_BRANCH_NAME' was created, based on '$DEV_BASE'"
    echo "- A new branch '$STAGE_BRANCH_NAME' was created, based on '$STAGE_BASE'"
    echo "- A new branch '$PROD_BRANCH_NAME' was created, based on '$PROD_BASE'"
    echo "- You are now on branch '$MASTER_BRANCH_NAME'"
    echo ""
    echo "Now, start committing on your feature. When done, use:"
    echo ""
    echo "     gh pr create -B master -w"
    echo
}
