#!/usr/bin/env bash

# Variables
TARGET_BRANCH=latest-master-release
REMOTE_NAME=upstream

# source shflags
GITCCP_DIR=$(dirname "$0")
. "$GITCCP_DIR/shflags"

# configure shflags
DEFINE_boolean 'assume_yes' false 'Automatic yes to prompts' 'y'

# run shflags
FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

git fetch upstream

commits=$(git --no-pager log --reverse --pretty=format:"%H" upstream/prod..upstream/master)

jumpCommit=""
for commitHash in $commits
do
    parentCommits=$(git cat-file -p "$commitHash" | grep -c "^parent ")

    if [[ "$parentCommits" -gt 1 ]]
    then
	jumpCommit=$commitHash
    else
	break
    fi

done

if [[ -n "$jumpCommit" ]]
then
    branchHead=$(git rev-parse upstream/$TARGET_BRANCH)

    if [ "$branchHead" == "$jumpCommit" ]
    then
	echo "Nothing to do. $REMOTE_NAME/$TARGET_BRANCH branch is up to date"
    else
	echo "Updating latest-release-master with $jumpCommit"
	git --no-pager show "$jumpCommit"

	if [ ${FLAGS_assume_yes} -eq ${FLAGS_TRUE} ]
	then
		git push upstream "$jumpCommit:$TARGET_BRANCH"
		echo "$TARGET_BRANCH branch is updated"
		exit 0
	fi

	read -p "Are you sure [y/N]? "  -r
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	    git push upstream "$jumpCommit:$TARGET_BRANCH"
	    echo "$TARGET_BRANCH branch is updated"
	else
	    echo "$TARGET_BRANCH branch is not updated"
	fi
    fi

    echo
else
    echo "Nothing to do. $REMOTE_NAME/$TARGET_BRANCH branch is up to date"
fi

echo
