// Code generated by "stringer -type=OptionalDefinition"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_begin_opt_-0]
	_ = x[REGIONS-1]
	_ = x[IS_PDP_ENABLED-2]
	_ = x[_end_opt_-3]
}

const _OptionalDefinition_name = "_begin_opt_REGIONSIS_PDP_ENABLED_end_opt_"

var _OptionalDefinition_index = [...]uint8{0, 11, 18, 32, 41}

func (i OptionalDefinition) String() string {
	if i < 0 || i >= OptionalDefinition(len(_OptionalDefinition_index)-1) {
		return "OptionalDefinition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptionalDefinition_name[_OptionalDefinition_index[i]:_OptionalDefinition_index[i+1]]
}
