apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: negotiator
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: telemetry
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: obsapi
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loggingapi
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: programanalyzer
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: perfanalyzer
spec:
  maxReplicas: 1
  minReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appservice
spec:
  maxReplicas: 1
  minReplicas: 1
---
