resources:
  - ../base
  - namespace.yaml
  - sealed-secret.yaml
  - sealed-ingress-cert.yaml
  - persistence/pv-choreo_app_db.yaml
  - persistence/pv-choreo_perf_db.yaml
  - persistence/pv-choreo_program_db.yaml
  - persistence/pv-choreo_trace_db.yaml
  - persistence/pvc-choreo_app_db.yaml
  - persistence/pvc-choreo_perf_db.yaml
  - persistence/pvc-choreo_program_db.yaml
  - persistence/pvc-choreo_trace_db.yaml
  - deployment/choreo_app_db.yaml
  - deployment/choreo_perf_db.yaml
  - deployment/choreo_program_db.yaml
  - deployment/choreo_trace_db.yaml
  - service/choreo_app_db.yaml
  - service/choreo_perf_db.yaml
  - service/choreo_program_db.yaml
  - service/choreo_trace_db.yaml

namespace: dev-choreo-system

configMapGenerator:
  - name: cm-frontend
    behavior: merge
    literals:
      - OBSERVE_API=https://dev.choreo.local/graphql
  - name: cm-negotiator
    behavior: create
    literals:
      - CHOREO_APP_URL=http://dev.choreo.local/observe/app/

patches:
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-http
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-grpc

patchesStrategicMerge:
  - hpa-strategy.yaml