apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../billing-console/
images:
- name: choreocontrolplane.azurecr.io/choreoipaas/billing-console
  newTag: billing-52e772b3be513f94cfa8ed48a062d68a4bc099f7
