apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../billing-console/
images:
- name: choreocontrolplane.azurecr.io/choreoipaas/api-server
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
- name: choreocontrolplane.azurecr.io/choreoipaas/app-deployer
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
- name: choreocontrolplane.azurecr.io/choreoipaas/app-service
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
- name: choreocontrolplane.azurecr.io/choreoipaas/billing-console
  newTag: billing-15b5504f8fe9efaa8b071056d1c9b9a91ff543f2
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-apim-devportal
  newTag: main-bb2260d0a6ab33ea2cf7ca77e8a9ca8cbcbd34ba
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-connector-builder
  newTag: master-ec1bbcd17e767bca6d4d3cb04418ccb3613c5642
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-console-next
  newTag: next-edc08303f20681a30827beee9abbb288cf07efe1
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-cp-graphql
  newTag: main-c18bfb72f09dc3cb610a504c53daa25b5ff94498
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-cicd
  newTag: master-803b502fa765805ef9904e9bbf542a344f7c1c79
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-project-manager
  newTag: master-b22e9136e2be2a6997a93a36bad6e64d176986eb
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-rudder
  newTag: master-44dcfbc4b866479ea441519fb5f06f61698cf920
- name: choreocontrolplane.azurecr.io/choreoipaas/email-service
  newTag: master-e1a3312a89b5bd9a3711f92f72b887df1cbfe68c
- name: choreocontrolplane.azurecr.io/choreoipaas/workspace-manager
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
