apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../billing-console/
images:
- name: choreocontrolplane.azurecr.io/choreoipaas/api-server
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
- name: choreocontrolplane.azurecr.io/choreoipaas/app-deployer
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
- name: choreocontrolplane.azurecr.io/choreoipaas/app-service
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
- name: choreocontrolplane.azurecr.io/choreoipaas/billing-console
  newTag: billing-52e772b3be513f94cfa8ed48a062d68a4bc099f7
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-console-next
  newTag: next-f6da186a2e8fb5f794f8353d6402337765a443f0
- name: choreocontrolplane.azurecr.io/choreoipaas/choreo-cp-graphql
  newTag: main-c18bfb72f09dc3cb610a504c53daa25b5ff94498
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-cicd
  newTag: master-27b2f65c578a9c66c6a1893d8c2f515585b258f0
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-project-manager
  newTag: master-b22e9136e2be2a6997a93a36bad6e64d176986eb
- name: choreocontrolplane.azurecr.io/choreoipaas/dp-rudder
  newTag: master-44dcfbc4b866479ea441519fb5f06f61698cf920
- name: choreocontrolplane.azurecr.io/choreoipaas/workspace-manager
  newTag: master-ca0e37588c8746c6ee5ac14f4a6c91d33a8c954c
