apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    choreo.component: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: api-server
  template:
    metadata:
      labels:
        choreo.component: api-server
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: choreoctrlplane.azurecr.io/choreoipaas/api-server:latest
        name: api-server
        env:
        - name: IDP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-idp
              key: IDP_CLIENT_SECRET
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /readyz
            port: http-port
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 30
          httpGet:
            path: /livez
            port: http-port
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - mountPath: /api-server.yaml
          name: config
          subPath: api-server.yaml
      volumes:
      - name: config
        configMap:
          name: cm-api-server
      serviceAccountName: sa-choreo-default
