apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    choreo.component: appservice
  name: appservice
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: appservice
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        choreo.component: appservice
    spec:
      containers:
      - env:
        - name: PLATFORMER_RUDDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: rudder_password
        - name: WORKSPACE_INGRESS_TLS_SECRET
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_INGRESS_TLS_SECRET
              name: cm-appservice
        - name: PLATFORMER_GOOGLE_ID
          valueFrom:
            configMapKeyRef:
              key: PLATFORMER_GOOGLE_ID
              name: cm-appservice
        - name: WORKSPACE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_NAMESPACE
              name: cm-appservice
        - name: IDP_ISSUER
          valueFrom:
            configMapKeyRef:
              key: IDP_ISSUER
              name: cm-appservice
        - name: DISABLE_AUTHN
          valueFrom:
            configMapKeyRef:
              key: DISABLE_AUTHN
              name: cm-appservice
        - name: WORKSPACE_VOLUME_CLAIM
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_VOLUME_CLAIM
              name: cm-appservice
        - name: IDP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: idp_client_secret
        - name: PLATFORMER_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: PLATFORMER_CLUSTER_NAME
              name: cm-appservice
        - name: IDP_AUTH_FLOW
          valueFrom:
            configMapKeyRef:
              key: IDP_AUTH_FLOW
              name: cm-appservice
        - name: IDP_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              key: IDP_REDIRECT_URL
              name: cm-appservice
        - name: EXECUTOR_INGRESS_HOST_SUFFIX
          valueFrom:
            configMapKeyRef:
              key: EXECUTOR_INGRESS_HOST_SUFFIX
              name: cm-appservice
        - name: PLATFORMER_RUDDER_URL
          valueFrom:
            configMapKeyRef:
              key: PLATFORMER_RUDDER_URL
              name: cm-appservice
        - name: REPO_PATH
          valueFrom:
            configMapKeyRef:
              key: REPO_PATH
              name: cm-appservice
        - name: PERISCOPE_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: PERISCOPE_GRPC_ADDRESS
              name: cm-appservice
        - name: REDIS_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: REDIS_ADDRESS
              name: cm-appservice
        - name: PLATFORMER_RUDDER_USERNAME
          valueFrom:
            configMapKeyRef:
              key: PLATFORMER_RUDDER_USERNAME
              name: cm-appservice
        - name: NEGOTIATOR_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: NEGOTIATOR_GRPC_ADDRESS
              name: cm-appservice
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: github_token
        - name: EXECUTOR_SVC_HOST
          valueFrom:
            configMapKeyRef:
              key: EXECUTOR_SVC_HOST
              name: cm-appservice
        - name: DEPLOY_APP_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: DEPLOY_APP_NAMESPACE
              name: cm-appservice
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: CLIENT_ID
              name: cm-appservice
        - name: DEPLOY_INGRESS_SECRET
          valueFrom:
            configMapKeyRef:
              key: DEPLOY_INGRESS_SECRET
              name: cm-appservice
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USERNAME
              name: cm-appservice
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: db_password
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: DATABASE_HOST
              name: cm-appservice
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PORT
              name: cm-appservice
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: cm-appservice
        - name: IDP_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: IDP_CLIENT_ID
              name: cm-appservice
        - name: IDP_HOST
          valueFrom:
            configMapKeyRef:
              key: IDP_HOST
              name: cm-appservice
        - name: EXECUTOR_SVC_PORT
          valueFrom:
            configMapKeyRef:
              key: EXECUTOR_SVC_PORT
              name: cm-appservice
        - name: GITHUB_APP_ORG
          valueFrom:
            configMapKeyRef:
              key: GITHUB_APP_ORG
              name: cm-appservice
        - name: LANG_SERVER_IMAGE
          valueFrom:
            configMapKeyRef:
              key: LANG_SERVER_IMAGE
              name: cm-appservice
        - name: IDP_TENANT_NAME
          valueFrom:
            configMapKeyRef:
              key: IDP_TENANT_NAME
              name: cm-appservice
        - name: IDP_AUTH_RESPONSE_COOKIE_MAX_AGE
          valueFrom:
            configMapKeyRef:
              key: IDP_AUTH_RESPONSE_COOKIE_MAX_AGE
              name: cm-appservice
        - name: DEPLOY_INGRESS_HOST_SUFFIX
          valueFrom:
            configMapKeyRef:
              key: DEPLOY_INGRESS_HOST_SUFFIX
              name: cm-appservice
        - name: GITHUB_USER_EMAIL
          valueFrom:
            configMapKeyRef:
              key: GITHUB_USER_EMAIL
              name: cm-appservice
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: redis_password
        - name: EXECUTOR_IMAGE
          valueFrom:
            configMapKeyRef:
              key: EXECUTOR_IMAGE
              name: cm-appservice
        - name: PLATFORMER_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: PLATFORMER_PROJECT_ID
              name: cm-appservice
        - name: PLATFORMER_ORG_ID
          valueFrom:
            configMapKeyRef:
              key: PLATFORMER_ORG_ID
              name: cm-appservice
        - name: GITHUB_USER
          valueFrom:
            configMapKeyRef:
              key: GITHUB_USER
              name: cm-appservice
        image: choreoipaas/app-service:latest
        imagePullPolicy: IfNotPresent
        name: appservice
        ports:
        - containerPort: 8080
          name: port-7ydy
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 512Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /repo
          name: appservice-claim
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: platformer-1580893230462-5ggle
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: appservice-claim
        persistentVolumeClaim:
          claimName: appservice-claim
