apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    choreo.component: appservice
  name: appservice
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: appservice
  template:
    metadata:
      labels:
        choreo.component: appservice
    spec:
      containers:
      - env:
        - name: DISABLE_AUTHN
          valueFrom:
            configMapKeyRef:
              key: DISABLE_AUTHN
              name: cm-appservice
        - name: REPO_PATH
          valueFrom:
            configMapKeyRef:
              key: REPO_PATH
              name: cm-appservice
        - name: REDIS_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: REDIS_ADDRESS
              name: cm-appservice
        - name: NEGOTIATOR_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: NEGOTIATOR_GRPC_ADDRESS
              name: cm-appservice
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-appservice
              key: GITHUB_TOKEN
        - name: DEPLOY_APP_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: DEPLOY_APP_NAMESPACE
              name: cm-appservice
        - name: APPS_INGRESS_SECRET
          valueFrom:
            configMapKeyRef:
              key: APPS_INGRESS_SECRET
              name: cm-appservice
        # APP DB
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_USERNAME
              name: cm-choreo-app-db
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-app-db
              key: CHOREO_DB_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_HOST
              name: cm-choreo-app-db
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_PORT
              name: cm-choreo-app-db
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_NAME
              name: cm-choreo-app-db
        - name: BALLERINA_CENTRAL_SYNC
          valueFrom:
            configMapKeyRef:
              key: BALLERINA_CENTRAL_SYNC
              name: cm-choreo-app-db
        - name: BALLERINA_CENTRAL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: BALLERINA_CENTRAL_DATABASE_NAME
              name: cm-choreo-app-db
        # -----------------------
        - name: IDP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-idp
              key: IDP_CLIENT_SECRET
        - name: IDP_BACKEND_API_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-idp
              key: IDP_BACKEND_API_CLIENT_SECRET
        - name: IDP_ISSUER
          valueFrom:
            configMapKeyRef:
              key: IDP_ISSUER
              name: cm-idp
        - name: IDP_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: IDP_CLIENT_ID
              name: cm-idp
        - name: IDP_BACKEND_API_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: IDP_BACKEND_API_CLIENT_ID
              name: cm-idp
        - name: IDP_HOST
          valueFrom:
            configMapKeyRef:
              key: IDP_HOST
              name: cm-idp
        - name: IDP_ALLOWED_REDIRECT_URLS
          valueFrom:
            configMapKeyRef:
              key: IDP_ALLOWED_REDIRECT_URLS
              name: cm-idp
        - name: IDP_AUTH_RESPONSE_COOKIE_MAX_AGE
          valueFrom:
            configMapKeyRef:
              key: IDP_AUTH_RESPONSE_COOKIE_MAX_AGE
              name: cm-idp
        - name: IDP_DISABLE_SECURE_COOKIES
          valueFrom:
            configMapKeyRef:
              key: IDP_DISABLE_SECURE_COOKIES
              name: cm-idp
        - name: IDP_TOKEN_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: IDP_TOKEN_ENDPOINT
              name: cm-idp
        - name: IDP_JWKS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: IDP_JWKS_ENDPOINT
              name: cm-idp
        - name: IDP_SCIM_USERS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: IDP_SCIM_USERS_ENDPOINT
              name: cm-idp
        # -----------------------------
        - name: GITHUB_APP_ORG
          valueFrom:
            configMapKeyRef:
              key: GITHUB_APP_ORG
              name: cm-appservice
        - name: LANG_SERVER_IMAGE
          valueFrom:
            configMapKeyRef:
              key: LANG_SERVER_IMAGE
              name: cm-appservice
        - name: DEPLOY_INGRESS_HOST_SUFFIX
          valueFrom:
            configMapKeyRef:
              key: DEPLOY_INGRESS_HOST_SUFFIX
              name: cm-appservice
        - name: GITHUB_USER_EMAIL
          valueFrom:
            configMapKeyRef:
              key: GITHUB_USER_EMAIL
              name: cm-appservice
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-appservice
              key: REDIS_PASSWORD
        - name: GITHUB_USER
          valueFrom:
            configMapKeyRef:
              key: GITHUB_USER
              name: cm-appservice
        - name: WORKSPACE_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_NAMESPACE
              name: cm-appservice
        - name: WORKSPACE_VOLUME_CLAIM
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_VOLUME_CLAIM
              name: cm-appservice
        - name: WORKSPACE_INGRESS_CLASS
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_INGRESS_CLASS
        - name: WORKSPACE_API_INGRESS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_API_INGRESS_HOSTNAME
        - name: WORKSPACE_API_INGRESS_TLS_SECRET
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_API_INGRESS_TLS_SECRET
        - name: WORKSPACE_API_PORT
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_API_PORT
        - name: WORKSPACE_API_CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_API_CORS_ORIGIN
        - name: WORKSPACE_INGRESS_HOST_SUFFIX
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_INGRESS_HOST_SUFFIX
        - name: WORKSPACE_APP_INGRESS_TLS_SECRET
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_APP_INGRESS_TLS_SECRET
        - name: WORKSPACE_DISABLE_AUTO_CLEAN
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_DISABLE_AUTO_CLEAN
        - name: WORKSPACE_CLEAN_INTERVAL_MINUTES
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_CLEAN_INTERVAL_MINUTES
              name: cm-appservice
        - name: WORKSPACE_PERISCOPE_HOST
          valueFrom:
            configMapKeyRef:
              key: WORKSPACE_PERISCOPE_HOST
              name: cm-appservice
        - name: WORKSPACE_IMAGE
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: WORKSPACE_IMAGE
        # ------------------------------
        - name: APPS_K8S_API_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: secret-appservice
              key: APPS_K8S_API_SERVER_URL
        - name: APPS_K8S_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: secret-apps-k8s-service-account
              key: APPS_K8S_SERVICE_ACCOUNT
        - name: APPS_DOCKER_REGISTRY
          valueFrom:
            secretKeyRef:
              name: secret-appservice
              key: APPS_DOCKER_REGISTRY
        - name: APPS_DOCKER_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-appservice
              key: APPS_DOCKER_REGISTRY_USERNAME
        - name: APPS_DOCKER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-appservice
              key: APPS_DOCKER_REGISTRY_PASSWORD
        - name: APPS_INGRESS_CLASS
          valueFrom:
            configMapKeyRef:
              name: cm-appservice
              key: APPS_INGRESS_CLASS
        - name: DISABLE_REDIS_AUTH
          valueFrom:
            configMapKeyRef:
              key: DISABLE_REDIS_AUTH
              name: cm-appservice
        - name: DISABLE_REDIS_TLS
          valueFrom:
            configMapKeyRef:
              key: DISABLE_REDIS_TLS
              name: cm-appservice
        - name: BETA_PROGRAM_ENABLED
          valueFrom:
            configMapKeyRef:
              key: BETA_PROGRAM_ENABLED
              name: cm-appservice
        - name: BETA_PROGRAM_ENFORCE_ON_EXISTING_USERS
          valueFrom:
            configMapKeyRef:
              key: BETA_PROGRAM_ENFORCE_ON_EXISTING_USERS
              name: cm-appservice
        - name: BETA_PROGRAM_PREFINERY_INVITATION_DECODER_KEY
          valueFrom:
            secretKeyRef:
              name: secret-appservice
              key: BETA_PROGRAM_PREFINERY_INVITATION_DECODER_KEY
        - name: BETA_PROGRAM_POST_VALIDATION_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              key: BETA_PROGRAM_POST_VALIDATION_REDIRECT_URL
              name: cm-appservice
        image: choreoipaas/app-service:latest
        name: appservice
        lifecycle:
          # This "sleep" preStop hook delays the Pod shutdown until after the Ingress controller removes the matching Endpoint
          preStop:
            exec:
              command:
                - /bin/sleep
                - "20"
        ports:
        - containerPort: 8080
          name: appservice-port
          protocol: TCP
        - containerPort: 9092
          name: as-grpc-port
          protocol: TCP  
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /readyz
            port: appservice-port  
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /livez
            port: appservice-port
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      serviceAccountName: sa-choreo-appservice
