apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    choreo.component: datamapper
  name: datamapper
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: datamapper
  template:
    metadata:
      labels:
        choreo.component: datamapper
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - env:
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: secret-datamapper
              key: ACCESS_KEY
        image: choreoipaas/datamapper-init:latest
        name: datamapper-init
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: datamapper-models
          mountPath: "/mnt"
        - name: datamapper-models-metadata
          mountPath: "/home/python-ai/choreo-ai-data-mapper/models.properties"
          subPath: "models.properties"
      containers:
      - image: choreoipaas/datamapper:latest
        name: datamapper
        lifecycle:
          # This "sleep" preStop hook delays the Pod shutdown until after the Ingress controller removes the matching Endpoint
          preStop:
            exec:
              command:
                - /bin/sleep
                - "20"
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            port: dm-port
            path: /health
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            port: dm-port
            path: /health
        ports:
        - containerPort: 5000
          name: dm-port
          protocol: TCP
        resources:
          limits:
            cpu: 1100m
            memory: 2048Mi
          requests:
            cpu: 1000m
            memory: 1536Mi
        volumeMounts:
        - name: datamapper-models
          mountPath: "/home/python-ai/choreo-ai-data-mapper/models/"
          subPath: "models"
      volumes:
      - name: datamapper-models
        emptyDir: {}
      - name: datamapper-models-metadata
        configMap:
          defaultMode: 420
          name: cm-datamapper
