resources:
  - anomalydetector.yaml
  - frontend.yaml
  - negotiator.yaml
  - obsapi.yaml
  - telemetry.yaml
  - programanalyzer.yaml
  - perfanalyzer-estimator.yaml
  - loggingapi.yaml
  - datamapper.yaml
  - testbase.yaml
  - api-server.yaml
  - app-service.yaml
  - app-deployer.yaml
  - workspace-manager.yaml
  - email-service.yaml
  - deploymentoptimizer.yaml
  - sys-obsapi.yaml
  - apim-service.yaml

commonAnnotations:
  config.linkerd.io/skip-outbound-ports: 3306,443

