apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    choreo.component: linker
  name: linker
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: linker
  strategy: {}
  template:
    metadata:
      labels:
        choreo.component: linker
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "20"
    spec:
      containers:
      - env:
        - name: b7a_log_level
          valueFrom:
            configMapKeyRef:
              key: B7A_LOG_LEVEL
              name: cm-loglevel-linker
        - name: IDP_ISSUER
          valueFrom:
            configMapKeyRef:
              key: IDP_ISSUER
              name: cm-idp
        - name: IDP_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: IDP_CLIENT_ID
              name: cm-idp              
        - name: IDP_HOST
          valueFrom:
            configMapKeyRef:
              key: IDP_HOST
              name: cm-idp   
        - name: IDP_JWKS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: IDP_JWKS_ENDPOINT
              name: cm-idp                 
        - name: NEGOTIATOR_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: NEGOTIATOR_GRPC_ADDRESS
              name: cm-negotiator
        - name: JWKS_ENDPOINT_PROTOCOL
          valueFrom:
            configMapKeyRef:
              key: JWKS_ENDPOINT_PROTOCOL
              name: cm-linker   
        - name: LINKER_INGRESS_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: LINKER_INGRESS_ADDRESS
              name: cm-linker  
        - name: APPSERVICE_GRPC_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: APPSERVICE_GRPC_ADDRESS
              name: cm-linker            
        image: choreoipaas/choreo-linker:latest
        securityContext:
          runAsUser: 100
          runAsGroup: 1000
        name: linker
        lifecycle:
          # This "sleep" preStop hook delays the Pod shutdown until after the Ingress controller removes the matching Endpoint
          preStop:
            exec:
              command:
                - /bin/sleep
                - "20"
        readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
             port: health
             path: /health
        livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
             port: health
             path: /health
        ports:
        - containerPort: 9090
          name: linker-sport
          protocol: TCP
        - containerPort: 9092
          name: linker-port
          protocol: TCP  
        - containerPort: 9091
          name: health
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 300m
            memory: 512Mi
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
