apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    choreo.component: loggingapi
  name: loggingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: loggingapi
  strategy: {}
  template:
    metadata:
      labels:
        choreo.component: loggingapi
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "20"
    spec:
      containers:
        - env:
            - name: b7a_log_level
              valueFrom:
                configMapKeyRef:
                  key: B7A_LOG_LEVEL
                  name: cm-loglevel-loggingapi
            - name: IDP_ISSUER
              valueFrom:
                configMapKeyRef:
                  key: IDP_ISSUER
                  name: cm-idp
            - name: IDP_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: IDP_CLIENT_ID
                  name: cm-idp
            - name: IDP_HOST
              valueFrom:
                configMapKeyRef:
                  key: IDP_HOST
                  name: cm-idp
            - name: IDP_JWKS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: IDP_JWKS_ENDPOINT
                  name: cm-idp
            - name: JWKS_ENDPOINT_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  key: JWKS_ENDPOINT_PROTOCOL
                  name: cm-loggingapi
            - name: AAD_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  key: AZURE_ACTIVEDIRECTORY_TENANT_ID
                  name: cm-activedirectory
            - name: AAD_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: AZURE_ACTIVEDIRECTORY_CLIENT_ID
                  name: cm-activedirectory
            - name: USER_APPS_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: USER_APPS_NAMESPACE
                  name: cm-k8sservice
            - name: K8S_SERVICE_SUBSCRIPTION_ID
              valueFrom:
                configMapKeyRef:
                  key: K8S_SERVICE_SUBSCRIPTION_ID
                  name: cm-k8sservice
            - name: RESOURCE_GROUP
              valueFrom:
                configMapKeyRef:
                  key: RESOURCE_GROUP
                  name: cm-k8sservice
            - name: CLUSTER_NAME
              valueFrom:
               configMapKeyRef:
                 key: CLUSTER_NAME
                 name: cm-k8sservice
            - name: LOG_WORKSPACE_ID
              valueFrom:
                configMapKeyRef:
                  key: LOG_WORKSPACE_ID
                  name: cm-loganalytics
            - name: AAD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-loggingapi
                  key: AZURE_ACTIVEDIRECTORY_CLIENT_SECRET
          image: choreoipaas/choreo-logging:latest
          securityContext:
            runAsUser: 100
            runAsGroup: 1000
          name: loggingapi
          lifecycle:
            # This "sleep" preStop hook delays the Pod shutdown until after the Ingress controller removes the matching Endpoint
            preStop:
              exec:
                command:
                  - /bin/sleep
                  - "20"
          ports:
            - containerPort: 9097
              name: logapi-port
              protocol: TCP
            - containerPort: 9098
              name: health
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /health
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: health
              path: /health
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 300m
              memory: 512Mi
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
