apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    choreo.component: perfanalyzer
  name: perfanalyzer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      choreo.component: perfanalyzer
  template:
    metadata:
      labels:
        choreo.component: perfanalyzer
    spec:
      containers:
      - image: choreoipaas/perfanalyzer:latest
        name: perfanalyzer
        env:
          - name: AZURE_TIMESERIESINSIGHTS_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: AZURE_TIMESERIESINSIGHTS_CLIENT_SECRET
                name: secret-perfanalyzer
          - name: CHOREO_PERF_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: CHOREO_PERF_DB_PASSWORD
                name: secret-perfanalyzer
        ports:
        - containerPort: 5005
          name: perfan-port
          protocol: TCP
        - containerPort: 5006
          name: perfan-port2
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: perfanalyzer-config
          mountPath: /home/perf-analyzer/config/
      volumes:
      - configMap:
          defaultMode: 420
          name: cm-perfanalyzer
        name: perfanalyzer-config
      serviceAccountName: sa-choreo-default
