IS_PREVIOUS_TRANSACTION={{.PREVIOUS_TRANSACTION}}

UPDATE_SPREADSHEET_ONLY={{.UPDATE_SPREADSHEET_ONLY}}

DRIVER={ODBC Driver 17 for SQL Server}

# Analytics DB connection information
ANALYTICS_DB_SERVER={{.ANALYTICS_DB_SERVER_NAME}}
ANALYTICS_DB=choreo_org_stat_db
ANALYTICS_DB_USERNAME=choreo_org_stat_db_user
ANALYTICS_DB_PASSWORD_FILE_PATH=/mnt/csi/secret-choreo-org-stat-data-publisher/ANALYTICS_DB_PASSWORD

# Kusto connection information
KUSTO_CLUSTER={{.KUSTO_CLUSTER_ID}}
KUSTO_CLIENT_ID={{.KUSTO_CLIENT_ID}}
KUSTO_AUTHORITY_ID={{.KUSTO_AUTHORITY_ID}}
KUSTO_DATABASE={{.KUSTO_DATABASE}}
KUSTO_CLIENT_SECRET_FILE_PATH=/mnt/csi/secret-choreo-org-stat-data-publisher/KUSTO_CLIENT_SECRET

# Observability connection information
AZURE_STORAGE_URL={{.AZURE_STORAGE_URL}}
SAS_TOKEN_FILE_PATH=/mnt/csi/secret-choreo-org-stat-data-publisher/SAS_TOKEN

# Google sheet connection information
GOOGLE_SHEET_KEY={{.GOOGLE_SHEET_KEY}}
TRAFFIC_GOOGLE_SHEET_KEY={{.TRAFFIC_GOOGLE_SHEET_KEY}}
GOOGLE_SHEET_CLIENT_ID={{.GOOGLE_SHEET_CLIENT_ID}}
GOOGLE_SHEET_PROJECT_ID={{.GOOGLE_SHEET_PROJECT_ID}}
GOOGLE_SHEET_AUTH_URI=https://accounts.google.com/o/oauth2/auth
GOOGLE_SHEET_TOKEN_URI=https://oauth2.googleapis.com/token
GOOGLE_SHEET_AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
GOOGLE_SHEET_CLIENT_SECRET_FILE_PATH=/mnt/csi/secret-choreo-org-stat-data-publisher/GOOGLE_SHEETS_CLIENT_SECRET
GOOGLE_SHEET_REDIRECT_URIS=https://developers.google.com/oauthplayground

GOOGLE_SHEET_TOKEN_FILE_PATH=/mnt/csi/secret-choreo-org-stat-data-publisher/GOOGLE_SHEETS_TOKEN
GOOGLE_SHEET_REFRESH_TOKEN_FILE_PATH=/mnt/csi/secret-choreo-org-stat-data-publisher/GOOGLE_SHEETS_REFRESH_TOKEN
GOOGLE_SHEET_SCOPES=https://www.googleapis.com/auth/spreadsheets
GOOGLE_SHEET_EXPIRY=2023-03-01T09:18:33.698223Z

GET_TRAFFIC_DATA = {{.GET_TRAFFIC_DATA}}
REFRESH_TRAFFIC_DATA = {{.REFRESH_TRAFFIC_DATA}}

APIM_ADMIN_API_URL = {{.APIM_ADMIN_API_URL}}
APIM_ADMIN_API_USERNAME = {{.APIM_ADMIN_API_USERNAME}}
APIM_ADMIN_API_PASSWORD_FILE_PATH = /mnt/csi/secret-choreo-org-stat-data-publisher/APIM_ADMIN_API_PASSWORD

CLOUD_MANAGER_URL = http://dp-cloud-manager

MONITORING_ORG_ID = {{.MONITORING_ORG_ID}}
CP_CUSTOMER_ID = {{.CP_CUSTOMER_ID}}
