apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-ai-copilot
spec:
  secretObjects:
    - secretName: secret-ai-copilot
      type: Opaque
      data:
        - objectName: AZURE_OPENAI_API_KEY
          key: AZURE_OPENAI_API_KEY
        - objectName: REDIS_PASSWORD
          key: REDIS_PASSWORD
        - objectName: DATA_COLLECTOR_CONSUMER_KEY
          key: DATA_COLLECTOR_CONSUMER_KEY
        - objectName: DATA_COLLECTOR_CONSUMER_SECRET
          key: DATA_COLLECTOR_CONSUMER_SECRET
  parameters:
    objects: |
      array:
        - |
          objectName: {{.AZURE_OPENAI_API_KEY_OBJ_NAME | default "ai-cogsvc-dp-eastus2-primary-access-key"}}
          objectType: secret
          objectAlias: AZURE_OPENAI_API_KEY
          objectVersion: "{{.AZURE_OPENAI_API_KEY}}"
        - |
          objectName: {{.REDIS_PASSWORD_OBJ_NAME | default "ai-api-test-redis-primary-access-key"}}
          objectType: secret
          objectAlias: REDIS_PASSWORD
          objectVersion: "{{.REDIS_PASSWORD}}"
        - |
          objectName: {{.DATA_COLLECTOR_CONSUMER_KEY_OBJ_NAME | default "ai-data-collector-consumer-key"}}
          objectType: secret
          objectAlias: DATA_COLLECTOR_CONSUMER_KEY
          objectVersion: {{.DATA_COLLECTOR_CONSUMER_KEY}}
        - |
          objectName: {{.DATA_COLLECTOR_CONSUMER_SECRET_OBJ_NAME  | default "ai-data-collector-consumer-secret"}}
          objectType: secret
          objectAlias: DATA_COLLECTOR_CONSUMER_SECRET
          objectVersion: {{.DATA_COLLECTOR_CONSUMER_SECRET}}
