kind: Deployment
metadata:
  name: "choreo-linker-0-deployment"
  annotations:
    checkov.io/skip1: CKV_K8S_38=Required by linkerD
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: "choreo-linker-0-deployment"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10500
            runAsGroup: 10500
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      serviceAccountName: sa-choreo-default
