// -------------------------------------------------------------------------------------
//
// Copyright (c) 2020, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
//
// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
// You may not alter or remove any copyright or other notice from copies of this content.
//
// --------------------------------------------------------------------------------------

.alter table metrics policy partitioning @'{'
  '"PartitionKeys": ['
    '{'
      '"ColumnName": "timestamp",'
      '"Kind": "UniformRange",'
      '"Properties": {'
        '"Reference": "1970-01-01T00:00:00",'
        '"RangeSize": "1.00:00:00"'
      '}'
    '}'
  ']'
'}'

.alter table traceSpans policy partitioning @'{'
  '"PartitionKeys": ['
    '{'
      '"ColumnName": "timestamp",'
      '"Kind": "UniformRange",'
      '"Properties": {'
        '"Reference": "1970-01-01T00:00:00",'
        '"RangeSize": "1.00:00:00"'
      '}'
    '}'
  ']'
'}'
