apiVersion: v1
kind: Service
metadata:
  labels:
    choreo.component: choreo-mysql
  name: choreo-mysql
  namespace: choreo-system  
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    choreo.component: choreo-mysql