apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert --file /Users/azeez/projects/choreo-ipaas/choreo/services/docker-compose.yaml
      -o choreo-k8s
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: choreo-system
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 31250
  selector:
    io.kompose.service: frontend
