[code_challenge_eval.rudder_db]
host = "{{.MSSQL_HOST}}"
user = 'choreo_rudder_admin_db_user'
database = 'choreo_rudder_db'
port = 1433

[code_challenge_eval.platform_services_db]
host = "{{.MSSQL_HOST}}"
user = 'choreo_platform_service_manager_db_user'
database = 'choreo_platform_service_manager_db'
port = 1433

[code_challenge_eval.configuration_db]
host = "{{.MSSQL_HOST}}"
user = 'choreo_configuration_service_db_user'
database = 'choreo_configuration_service_db'
port = 1433

[code_challenge_eval.apim_db]
host = "{{.MSSQL_HOST}}"
user = 'choreo_apim_db_user'
database = 'choreo_apim_db'
port = 1433

[code_challenge_eval.auth]
choreoJwtIssuer = "{{.CHOREO_JWT_ISSUER}}"
choreoJwtAudience = "{{.CHOREO_JWT_AUDIENCE}}"
site24x7JwtAudience = "{{.SITE24x7_JWT_AUDIENCE}}"
choreoJwtJwksUrl = "{{.CHOREO_JWT_JWKS_URL}}"

[ballerina.log]
level = "{{.LOG_LEVEL}}"
