apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
 name: secret-ai-storage-table
spec:
 secretObjects:
   - secretName: secret-ai-storage-table
     type: Opaque
     data:
       - objectName: TABLE_CONNECTION_STRING
         key: TABLE_CONNECTION_STRING
 parameters:
   objects:  |
     array:
       - |
         objectName: ai-TABLE-STORAGE-CONNECTION-STRING
         objectType: secret
         objectAlias: TABLE_CONNECTION_STRING
         objectVersion: "{{.TABLE_CONNECTION_STRING}}"
