apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: choreo-aws-marketplace-client-secrets
  namespace: choreo-system
spec:
  provider: azure
  secretObjects:
    - secretName: choreo-aws-marketplace-client-secret
      type: Opaque
      data:
        - objectName: AWS_ACCESS_KEY_ID
          key: AWS_ACCESS_KEY_ID
        - objectName: AWS_SECRET_ACCESS_KEY
          key: AWS_SECRET_ACCESS_KEY
  parameters:
    objects: |
      array:
        - |
          objectName: aws-marketplace-client-access-key-id
          objectType: secret
          objectAlias: AWS_ACCESS_KEY_ID
          objectVersion: 79e5b6dad2ac419c9c2d75eb1d7ad9e9
        - |
          objectName: aws-marketplace-client-secret-access-key
          objectType: secret
          objectAlias: AWS_SECRET_ACCESS_KEY
          objectVersion: 41cce844524e4e1bbcdc8f2aada37d10
    tenantId: da76d684-740f-4d94-8717-9d5fb21dd1f9
    usePodIdentity: "false"
