apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-contract-service
spec:
  secretObjects:
    - secretName: secret-contract-service
      type: Opaque
      data:
        - objectName: GITHUB_TOKEN
          key: GITHUB_TOKEN
  parameters:
    objects: |
      array:
        - |
          objectName: contract-service-github-pat
          objectType: secret
          objectAlias: GITHUB_TOKEN
          objectVersion: "{{.CHOREO_CONTRACT_SERVICE_GH_TOKEN}}"
