apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-cp-gw-adapter
spec:
  secretObjects:
  - secretName: secret-cp-gw-adapter
    type: Opaque
    data:
      - objectName: SQL_DB_PASSWORD
        key: SQL_DB_PASSWORD
  parameters:
    objects: |
      array:
        - |
          objectName: choreo-gateway-adapter-db-mssql-password
          objectType: secret
          objectAlias: SQL_DB_PASSWORD
          objectVersion: "{{.SQL_DB_PASSWORD}}"
