apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-moesif-service
spec:
  parameters:
    objects: |
      array:
        - |
          objectName: choreo-moesif-key-management-db-mssql-password
          objectType: secret
          objectAlias: CHOREO_MOESIF_KEY_MANAGEMENT_DB_MSSQL_PASSWORD
          objectVersion: "{{.CHOREO_MOESIF_KEY_MANAGEMENT_DB_MSSQL_PASSWORD}}"
        - |
          objectName: moesif-auth-password
          objectType: secret
          objectAlias: MOESIF_AUTH_PWD
          objectVersion: "{{.MOESIF_AUTH_PWD}}"
        - |
          objectName: MOESIF-TLS-CERT
          objectType: secret
          objectAlias: MOESIF_TLS_PVT_KEY
          objectVersion: "{{.MOESIF_TLS_PVT_KEY}"
        - |
          objectName: MOESIF-TLS-CERT
          objectType: cert
          objectAlias: MOESIF_TLS_PUBLIC_CERT
          objectVersion: "{{.MOESIF_TLS_PUBLIC_CERT}}"
