apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-redis
spec:
  secretObjects:
  - secretName: secret-redis
    type: Opaque
    data:
      - objectName: REDIS_PASSWORD
        key: REDIS_PASSWORD
  parameters:
    objects:  |
      array:
        - |
          objectName: common-redis-primary-access-key
          objectType: secret
          objectAlias: REDIS_PASSWORD
          objectVersion: "{{.REDIS_PASSWORD}}"
