apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-sts-mgt-service
  namespace: choreo-system
spec:
  provider: azure
  secretObjects:
    - secretName: secret-sts-mgt-service
      type: Opaque
      data:
        - objectName: CHOREO_STS_MGT_DB_PASSWORD
          key: CHOREO_STS_MGT_DB_PASSWORD
        - objectName: APIM_REST_API_CONSUMER_SECRET
          key: APIM_REST_API_CONSUMER_SECRET
  parameters:
    usePodIdentity: "false"
    tenantId: "da76d684-740f-4d94-8717-9d5fb21dd1f9"
    objects: |
      array:
        - |
          objectName: apim-REST-API-CONSUMER-SECRET
          objectType: secret
          objectAlias: APIM_REST_API_CONSUMER_SECRET
          objectVersion: "{{.APIM_REST_API_CONSUMER_SECRET}}"
        - |
          objectName: choreo-sts-mgt-svc-db-postgresql-password
          objectType: secret
          objectAlias: CHOREO_STS_MGT_DB_PASSWORD
          objectVersion: "{{.CHOREO_STS_MGT_DB_PASSWORD}}"
