apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tls-secret-usage-handler-service
  labels:
    app: metered-usage-handler-service
spec:
  secretObjects:
    - secretName: usage-handler-service-tls
      type: kubernetes.io/tls
      data:
        - objectName: USAGE_SERVICE_INGRESS_TLS_CERTIFICATE_KEYSTORE
          key: tls.key
        - objectName: USAGE_SERVICE_INGRESS_TLS_CERTIFICATE_KEYSTORE
          key: tls.crt
  parameters:
    objects:  |
      array:
        - |
          objectName: usage-service-INGRESS-TLS-CERTIFICATE-KEYSTORE
          objectType: secret
          objectAlias: USAGE_SERVICE_INGRESS_TLS_CERTIFICATE_KEYSTORE
          objectVersion: "{{.USAGE_SERVICE_INGRESS_TLS_CERTIFICATE_KEYSTORE}}"
