client:
  clientSecretEncryptionKeyFile: '/mnt/csi/secret-appdev-user-mgt/client-secret-encryption-key.txt'
  tokenSettings:
    authCodeValidity: '{{.CHOREO_STS_AUTH_CODE_VALIDITY | default 5}}'
    userTokenValidity: '{{.CHOREO_STS_USER_TOKEN_VALIDITY | default 1440}}'
    refreshTokenValidity: '{{.CHOREO_STS_REFRESH_TOKEN_VALIDITY | default 10080}}'
    applicationTokenValidity: '{{.CHOREO_STS_APPLICATION_TOKEN_VALIDITY | default 1440}}'
runtime:
  defaultSignigKeyStore:
    file: '/mnt/csi/secret-appdev-user-mgt/default-signing-keystore.keystore'
    alias: '{{.CHOREO_STS_KEYSTORE_FILE_ALIAS}}'
    passwordFile: '/mnt/csi/secret-appdev-user-mgt/default-signing-keystore-password.txt'
redis:
  username: '{{.CHOREO_STS_REDIS_USERNAME | default "sa"}}'
  passwordFile: '/mnt/csi/secret-appdev-user-mgt/redis-password.txt'
  nodes:
    - '127.0.0.1:6379' # TODO - Suvink - Replace this after the Redis deployment is completed
    - '127.0.0.1:6380'
    - '127.0.0.1:6381'
  pool:
    maxIdleSize: '{{.CHOREO_STS_REDIS_POOL_MAX_IDLE_SIZE | default 50}}'
    maxSize: '{{.CHOREO_STS_REDIS_POOL_MAX_SIZE | default 100}}'
    minIdleSize: '{{.CHOREO_STS_REDIS_POOL_MIN_IDLE_SIZE | default 5}}'
    readWriteTimeout: '{{.CHOREO_STS_REDIS_POOL_READ_WRITE_TIMEOUT | default 2000}}'
    maxWaitTime: '{{.CHOREO_STS_REDIS_POOL_MAX_WAIT_TIME | default 10000}}'
    testOnBorrow: '{{.CHOREO_STS_REDIS_POOL_TEST_ON_BORROW | default true}}'
    testOnReturn: '{{.CHOREO_STS_REDIS_POOL_TEST_ON_RETURN | default true}}'
    lifoEnabled: '{{.CHOREO_STS_REDIS_LIFO_ENABLED | default false}}'
    removeAbandonedTimeout: '{{.CHOREO_STS_REDIS_REMOVE_ABANDONED_TIMEOUT | default 60}}'
services:
  userMgtService:
    host: '{{.CHOREO_STS_USER_MGT_SERVICE_URL}}'
    port: '{{.CHOREO_STS_USER_MGT_SERVICE_PORT | default 8080}}'
  authzService:
    host: '{{.CHOREO_STS_AUTHZ_SERVICE_URL}}'
    port: '{{.CHOREO_STS_AUTHZ_SERVICE_PORT | default 9090}}'
httpClient:
  maxTotal: '{{.CHOREO_STS_HTTP_CLIENT_MAX_TOTAL | default 100}}'
  defaultMaxPerRoute: '{{.CHOREO_STS_HTTP_CLIENT_DEFAULT_MAX_PER_ROUTE | default 10}}'
