apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    kind: pvc-mounts
  name: pvc-userappstorage
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: file
  resources:
    requests:
      storage: 300Mi
