[ballerina.log]
format = "json"
level = "{{.LOG_LEVEL}}"

[[ballerina.log.modules]]
name = "choreo/sysobsapi"
level = "{{.LOG_LEVEL_SYSOBSAPI}}"

[choreo.sysobsapi]
[choreo.sysobsapi.laWorkspaceIds]
US = "{{.US_LA_WORKSPACE_ID}}"
EU = "{{.EU_LA_WORKSPACE_ID}}"
IND = "{{.IND_LA_WORKSPACE_ID}}"
