# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

global:
  choreosystem:
    orgHandle: choreosystem
    orgUUID: ""
  asgardeo:
    consoleUrl: https://console.asgardeo.io
  vault:
    url: http://vault.vault:8200
  redis:
    host: redis-cluster.redis.svc.cluster.local
    port: "6379"
  image:
    registry: choreocontrolplane.azurecr.io
    pullSecrets:
      - name: choreo-image-pull-secret
  namespaces:
    apim: choreo-apim
    system: choreo-system
    observability: choreo-observability
    ai: choreo-ai
    spicedbOperator: spicedb-operator
    authz: choreo-authorization
choreo-apim:
  enabled: true
  apim-devportal:
    enabled: true
  app-gateway-oauth-agent:
    enabled: true
  choreo-connect-global-adapter:
    enabled: true
  choreo-governance-service:
    enabled: true
  choreo-linter-service:
    enabled: true
  config-deployer-service:
    enabled: true
  product-apim:
    enabled: true
spicedb-operator:
  enabled: true
  spicedb-operator:
    enabled: true
choreo-system:
  enabled: true
  api-server:
    enabled: true
  apim-proxy-deployer:
    enabled: true
  app-dev-authz-service:
    enabled: true
  app-service:
    enabled: true
  choreo-console:
    enabled: true
  connection-service:
    enabled: true
  cp-graphql:
    enabled: true
  delete-manager:
    enabled: true
  devops-portal-api:
    enabled: true
  dp-cloud-manager:
    enabled: true
  dp-mizzen:
    enabled: true
  dp-project-manager:
    enabled: true
  dp-rudder:
    enabled: true
  dp-secret-manager:
    enabled: true
choreo-authorization:
  enabled: true
  resource-authorization-service:
    enabled: true
