apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-rules-log-enricher
  namespace: choreo-observability
spec:
  endpointSelector:
    matchLabels:
      choreo.component: log-enricher
  egress:
    # Allow K8s DNS resolution
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    # Allow egress to kube-apiserver to fetch kubernetes events
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
