apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_38=The SA token is required for the linkerd to define service identity
  labels:
    choreo.component: choreo-analytics-api
  name: choreo-analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: choreo-analytics-query-api
  strategy: {}
  template:
    metadata:
      labels:
        choreo.component: choreo-analytics-query-api
        antiaffinity: choreo-analytics-query-api
        app: choreo-analytics-query-api
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: choreo-analytics-query-api
          image: choreocontrolplane.azurecr.io/choreoipaas/choreo-analytics-api:latest
          args:
            - "-Dlog4j2.formatMsgNoLookups=true"
          env:
            - name: KEY_PASS
              valueFrom:
                secretKeyRef:
                  key: ALERT_API_PASSWORD
                  name: keystore-passwords
            - name: KUSTO_APPLICATION_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: KUSTO_APPLICATION_CLIENT_ID
                  name: secret-kusto-query
            - name: KUSTO_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  key: KUSTO_APPLICATION_KEY
                  name: secret-kusto-query
            - name: KUSTO_AUTHORITY_ID
              valueFrom:
                secretKeyRef:
                  key: KUSTO_AUTHORITY_ID
                  name: secret-kusto-query
            - name: KUSTO_RESOURCE_URI
              valueFrom:
                secretKeyRef:
                  key: KUSTO_RESOURCE_URI
                  name: secret-kusto-query
            - name: KUSTO_DATABASE
              valueFrom:
                secretKeyRef:
                  key: KUSTO_DATABASE
                  name: secret-kusto-query
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: TRUSTSTORE_PASSWORD
                  name: keystore-passwords
            - name: TRUSTSTORE_PATH
              value: /mnt/csi/client-truststore/truststore.p12
            - name: ENABLE_DEFAULT_TRUSTSTORE
              value: "false"
            - name: REDIS
              value: "choreo-analytics-query-api"
          envFrom:
            - configMapRef:
                name: choreo-analytics-query-api-conf
            - configMapRef:
                name: choreo-analytics-query-api-cm
            - configMapRef:
                name: choreo-analytics-query-api-env
            - secretRef:
                name: choreo-analytics-query-api-secret
          securityContext:
            runAsUser: 10500
            runAsGroup: 10500
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: secret-idp-configs
              mountPath: "/mnt/csi/secret-idp-configs"
            - name: keystore-passwords
              mountPath: /mnt/csi/certssecrets
              readOnly: true
            - name: query-api-keystores
              mountPath: "/mnt/csi/keys-store"
              readOnly: true
            - name: query-api-client-truststore
              mountPath: "/mnt/csi/client-truststore"
              readOnly: true
          ports:
            - containerPort: 8443
          livenessProbe:
            httpGet:
              path: /healthz/query-api/liveness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/query-api/readiness
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 800Mi
      volumes:
        - name: query-api-keystores
          secret:
            secretName: analytics-api-service-keystore
        - name: query-api-client-truststore
          configMap:
            name: analytics-client-truststore
        - name: secret-sql-db
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-sql-db
        - name: secret-kusto-query
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-kusto-query
        - name: keystore-passwords
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: keystore-passwords
        - name: secret-idp-configs
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-idp-configs
      restartPolicy: Always
      serviceAccountName: dp-loggingapi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: antiaffinity
                    operator: In
                    values:
                      - loggingapi
              topologyKey: kubernetes.io/hostname
