# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cp-graphql
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    {{- include "cp-graphql.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: KEYSTORE_PASSWORD
        secretKey: {{ .Values.secrets.keystorePassword.key | quote }}
        secretPath: {{ .Values.secrets.keystorePassword.path | quote }}
      - objectName: choreo-cp-graphql-keystore.pfx
        secretKey: {{ .Values.secrets.keystorePFX.key | quote }}
        secretPath: {{ .Values.secrets.keystorePFX.path | quote }}
        encoding: base64
