configMapGenerator:
  - name: cm-deploymentoptimizer-model-metadata
    behavior: create
    files:
      - deploymentoptimizer/models.properties
  - name: cm-anomalydetector-model-metadata
    behavior: create
    files:
      - anomalydetector/models.properties
  - name: cm-datamapper
    behavior: create
    files:
      - datamapper/models.properties
  - name: cm-test-assistant
    behavior: create
    files:
      - test-assistant/models.properties
  - name: env-workspace-manager-shared # shared workspace-manager configs across environments
    behavior: create
    literals:
    - WORKSPACE_BALLERINA_VERSION=swan-lake-alpha5
