apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    choreo.component: observability-api
  name: observability-api
spec:
  replicas: 1
  selector:
    matchLabels:
      choreo.component: observability-api
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        io.kompose.network/choreo: "true"
        choreo.component: observability-api
    spec:
      containers:
      - env:
        - name: CHOREO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_HOST
              name: cm-choreodb
        - name: CHOREO_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_NAME
              name: cm-choreodb
        - name: CHOREO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: db_password
        - name: CHOREO_DB_PORT
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_PORT
              name: cm-choreodb
        - name: CHOREO_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: CHOREO_DB_USERNAME
              name: cm-choreodb
        - name: AZURE_TIMESERIESINSIGHTS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: tsi_client_id
        - name: AZURE_TIMESERIESINSIGHTS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: tsi_client_secret
        - name: AZURE_TIMESERIESINSIGHTS_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: tsi_tenant_id 
        - name: AZURE_TIMESERIESINSIGHTS_ENVIRONMENT_FQDN
          valueFrom:
            secretKeyRef:
              name: choreo-secret
              key: tsi_env_fqdn
        image: choreoipaas/observability-api:latest
        imagePullPolicy: ""
        name: observability-api
        ports:
        - containerPort: 9095
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
