apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory","targetAverageValue":"241591910400m"}}]'
  labels:
    choreo.component: observability-api
  name: observability-api
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: observability-api
  targetCPUUtilizationPercentage: 90
