apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner-system
  - apim
  - apim-analytics
  - authz
  - clusterissuers
  - idp
  - system
  - priorityclass
commonLabels:
  app: choreo-control-plane
