resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - persistence/pv-appservice.yaml
  - persistence/pv-programanalyzer.yaml
  - persistence/pvc-appservice.yaml
  - persistence/pvc-programanalyzer.yaml
  - deployment/frontend.yaml
  - deployment/negotiator.yaml
  - deployment/obsapi.yaml
  - deployment/telemetry.yaml
  - deployment/appservice.yaml
  - deployment/programanalyzer.yaml
  - deployment/perfanalyzer.yaml
  - deployment/loggingapi.yaml
  - service/frontend.yaml
  - service/negotiator.yaml
  - service/obsapi.yaml
  - service/telemetry.yaml
  - service/appservice.yaml
  - service/programanalyzer.yaml
  - service/perfanalyzer.yaml
  - service/loggingapi.yaml
  - ingress/grpc.yaml
  - ingress/http.yaml
  - hpa/frontend.yaml
  - hpa/negotiator.yaml
  - hpa/obsapi.yaml
  - hpa/telemetry.yaml
  - hpa/appservice.yaml
  - hpa/loggingapi.yaml
  - hpa/programanalyzer.yaml
  - hpa/perfanalyzer.yaml
  - cronjob/workspace-cleanup.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cm-obsapi
    behavior: create
    literals:
      - AZURE_TIMESERIESINSIGHTS_CLIENT_ID=f3780944-a32e-4b9d-89ed-3b18beb47942
      - AZURE_TIMESERIESINSIGHTS_TENANT_ID=9c3e5d51-c9ab-4565-a419-4248b5d54817
      - AZURE_TIMESERIESINSIGHTS_ENVIRONMENT_FQDN=208dc027-b0ba-416d-8826-4660a6eec433.env.timeseries.azure.com
  - name: cm-programanalyzer
    behavior: create
    files:
      - config/programanalyzer/application.properties
  - name: cm-perfanalyzer
    behavior: create
    files:
      - config/perfanalyzer/db_config.py
      - config/perfanalyzer/tsi_config.py
  - name: cm-frontend
    behavior: create
    literals:
      - APP_API=https://depman.development.choreo.dev
      - AUTH_FLOW=B2C_1_Signup
      - CLIENT_ID=cb4bcbd9-d807-492d-ba42-2ecb12eaa45f
      - LOGS_API=wss://depman.development.choreo.dev
      - OBSERVE_API=https://$(CHOREO_HTTP_INGRESS)/graphql
      - REDIRECT_URL=https://development.choreo.dev/
      - TENANT=choreodevb2c
  - name: cm-choreo-app-db
    behavior: create
    literals:
      - CHOREO_DB_HOST=choreo-app-db
      - CHOREO_DB_NAME=choreo_app_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
  - name: cm-choreo-perf-db
    behavior: create
    literals:
      - CHOREO_DB_HOST=choreo-perf-db
      - CHOREO_DB_NAME=choreo_perf_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
  - name: cm-choreo-program-db
    behavior: create
    literals:
      - CHOREO_DB_HOST=choreo-program-db
      - CHOREO_DB_NAME=choreo_program_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
  - name: cm-choreo-trace-db
    behavior: create
    literals:
      - CHOREO_DB_HOST=choreo-trace-db
      - CHOREO_DB_NAME=choreo_trace_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
  - name: cm-eventhub
    behavior: create
    literals:
      - EVENTHUB_NAMESPACE=choreo-poc-observability-event-hub-ns.servicebus.windows.net/
      - EVENTHUB_SHARED_ACCESS_POLICY_NAME=choreo-poc-observability-event-hub-sender-policy
      - METRICS_EVENTHUB_NAME=choreo-poc-observability-metrics-event-hub
  - name: cm-appservice
    behavior: create
    literals:
      - DEPLOY_APP_NAMESPACE=pxe-dev-platformer-1580639005087-z1go3
      - DEPLOY_INGRESS_HOST_SUFFIX=preprod.choreo.dev
      - DEPLOY_INGRESS_SECRET=choreo-preprod-wildcard-cert
      - DISABLE_AUTHN="false"
      - EXECUTOR_IMAGE=choreoipaas/bexecuter:latest
      - EXECUTOR_INGRESS_HOST_SUFFIX=-test.preprod.choreo.dev
      - EXECUTOR_SVC_HOST=bexecuter
      - EXECUTOR_SVC_PORT="8080"
      - GITHUB_APP_ORG=integration-apps
      - GITHUB_USER_EMAIL=integration2020.wso2@gmail.com
      - GITHUB_USER=wso2-ipaas-bot
      - IDP_AUTH_FLOW=B2C_1_Signup
      - IDP_AUTH_RESPONSE_COOKIE_MAX_AGE="86400"
      - IDP_CLIENT_ID=cb4bcbd9-d807-492d-ba42-2ecb12eaa45f
      - IDP_HOST=https://login.microsoftonline.com
      - IDP_ISSUER=https://choreodevb2c.b2clogin.com/a8d5aca6-c571-40ba-bc0f-d104b73ed587/v2.0/
      - IDP_REDIRECT_URL=https://development.choreo.dev/
      - IDP_TENANT_NAME=choreodevb2c
      - LANG_SERVER_IMAGE=isurulucky/lang-server
      - NEGOTIATOR_GRPC_ADDRESS=choreo-nego-z1jqfgi.pxe-dev-platformer-1580893230462-5ggle.svc:9092
      - PERISCOPE_GRPC_ADDRESS=choreo-nego-z1jqfgi.pxe-dev-platformer-1580893230462-5ggle.svc:80
      - PLATFORMER_CLUSTER_NAME=wso2-aks-chor
      - PLATFORMER_GOOGLE_ID=platformer-1580639005087-z1go3
      - PLATFORMER_ORG_ID=-M-4Q539L2y9RtB02Ttp
      - PLATFORMER_PROJECT_ID=-M-4QFnMxM_qqAizY_Bv
      - PLATFORMER_RUDDER_URL=https://api.rudder.wso2.platformer.com
      - PLATFORMER_RUDDER_USERNAME=wso2
      - REDIS_ADDRESS=choreo-dev.redis.cache.windows.net:6380
      - REPO_PATH=/repo
      - WORKSPACE_INGRESS_TLS_SECRET=choreo-preprod-wildcard-cert
      - WORKSPACE_NAMESPACE=pxe-dev-platformer-1580893230462-5ggle
      - WORKSPACE_VOLUME_CLAIM=appservice-claim
  - name: cm-activedirectory
    behavior: create
    literals:
      - AAD_TENANT_ID=9c3e5d51-c9ab-4565-a419-4248b5d54817
      - AAD_CLIENT_ID=e1d6af4f-9af6-4e97-84ca-bb9f71bfcc54
  - name: cm-k8sservice
    behavior: create
    literals:
      - USER_APPS_NAMESPACE=pxe-dev-platformer-1580639005087-z1go3
      - K8S_SERVICE_SUBSCRIPTION_ID=6e80ff13-db12-4a82-b998-807fbe9b3c4e
      - RESOURCE_GROUP=choreo-poc
      - CLUSTER_NAME=choreo-poc
  - name: cm-loganalytics
    behavior: create
    literals:
      - LOG_WORKSPACE_ID=f8f5b826-f42a-4d1a-803a-d50c2b03d3ab
  - name: cm-workspace-cleanup
    behavior: create
    literals:
      - WORKSPACE_NAMESPACE=pxe-dev-platformer-1580893230462-5ggle

vars:
  - name: CHOREO_HTTP_INGRESS
    objref:
      apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      name: ingress-http
    fieldref:
      fieldpath: spec.rules[0].host
