apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    choreo.component: choreo-mysql-claim
  name: choreo-mysql-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Mi