apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    choreo.component: choreo-mysql-claim
  name: choreo-mysql-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi