apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/apim

images:
- name: choreoctrlplane.azurecr.io/choreoipaas/choreo-apim-devportal
  newTag: main-b2b406c50450bf5b95d32de8a8bcbe976af7eeab
