apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-app-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgAi3aeN990vF7NaJ9WTbC9XkEsdK0vcsv3lI2X+svVuS3DPsSNFU22C1qy1hdvOSfvDUOJkZeaOhBwU1izROxrvSAyqTCFbBgTBuQRV4bjMbkwkcGeL+kUrdgUrqa77CXzWgduigIph6yIHx4mEd+wD5LGqnfqbZ+XNQmzM7AwkmwzDp/LTLiqtjo6LS1+Tu+9oSsLKgjpQAMzBGGzIyOdBEwTjSZMq82Ta//95AsF8Wii4R7dOG9fvgozxqVi9OeIplbmWhXWuQZM0w3PTt55eqnN+04NjXUFOhZgsG7nO3mlOOUC8dTI/YIq6dSPrfBPPL88BTpiwB+V4VMyEloiBu6oN1sGkMzzO6zG/GnUEdAOG8iUHIDd65QG5/jOExplwto8EzAvhy1OfQfiLsP8V73Uoe4tZKXeRQsBDbGowzlTcnAkLF0qxDM0dFmTkmVGHC1O4WuNf3JNSYLWlPDArETObLRfVfr0tbp4kCwSDcheJU/pvuzeaxow0aMqjKT3kZsP+mVUkXNIHaLJyF+81Ek3+Pc6yOAOE6tucO+ZL5BkUmL9Z32+Ma3SYontLQlNg66fH+GjY4S5m5iuOniRrFcbfu3goSchWEHv5UxjIkX5xm54AL0nClj4rl91NZYyexOSoMbuMmO9mpa2U2uWhdnFdrUVFJGtPczpIU/xyqxUH/rHL/4Mu+6azSVexjZjktszMAOhoaKgBe6RVLzsZ
  template:
    metadata:
      creationTimestamp: null
      name: secret-app-db
      namespace: prod-choreo-system

