apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-loggingapi
  namespace: prod-choreo-system
spec:
  encryptedData:
    AZURE_ACTIVEDIRECTORY_CLIENT_SECRET: AgBG32DAPjgYAFa0gcYW3NK/IFEwI7YTpv5CxW0FmU+KJnnKGtHGncsUQVoqmwtYam3nVfOX/UCRmzewUstHENhef2zlM4I+9EbnDasftltmi68U2cmXK7MsvP9ebsmkv3welxkja0HXwXbZeX3q7+MHwFdtsmLNTrBWzxhLC5ThMH40FIVB8MbHQh6YNk5ck8SN9TGylqv4qQvdcgyhbH4Yi4SDwvld1lrFvMzEvHYxRLF7v6BR1jht6oxQ0R+G75ByMiNny3N+qdeAUFOjry2i1bIE+S5qU6wM5+bRX2VhjCjjRV7dOxKUoNYLS6wxB0FOmwAZRX0yvH+JlvBgcKVIW20AFv5k/bSZ2dlrMALnscqbW5C/XAtPM8/vMox8fKTkAsutuYRVXp0uecMbO02p56DtrpUC622g59hdo4xhVEGv7j7R7+R5Wr2pUldDTOdBnygXs71B08UieVIdRys9H4CTJtL9OgL3W6Mnj7c1lhYZXZSgk5wLThmKKa2S9yl1jG1Y7gAWF/FusayyxvgHQeODmAmOq71yLpV6ZBzkzRRjRtINjhcQSZwD19tq89T5hnLTKaJDyb1KyuR2EOBIz/oegxKxm9/F5DEs2KCfk+Piczc6RUf482mPfbtFvaj6Mw39QAxfCjcPYCYiuf1o2/NI0HOCkqxo1AeFY74QEPIU/rQy6iQCMgy8mKri9QCt0TpLVTYcIAcOU81TuGDEjo0jajXCRnEvofD+IznrDQ==
  template:
    metadata:
      creationTimestamp: null
      name: secret-loggingapi
      namespace: prod-choreo-system

