apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-loggingapi
  namespace: prod-choreo-system
spec:
  encryptedData:
    AZURE_ACTIVEDIRECTORY_CLIENT_SECRET: AgBudfV53snTZwPRjQsmUC7ZFiBW+l2KB18wJ1xtGPLJ96ToopIoTm72FkOOngYiJHoDexyJdhWnifV/RyR1dqvMhGdS/8TPfhTxBQ3dJB4O31M4IVKlTUJeSUqcaYoaC0+0OiuEbf8SxC2BCDj4x74MGYGT/send8cy7+bpiKtf8JLIX0Jx82GJqSUoPHuvM03a1450SGfZMRs6EhJYnFfnoZUo87l4ynn+O2BVSCrV2M8MJFYdgDB30YAqZ4UT9RvKcW08INsJEdIvRDCaE+bQLYJ5rqxTMIZRhIh6RtQ2I2gCLoXFxm9MyM2LbJDzd4BH50/of9nny+BAnexQdRg/8ST9ZQzSE0+FqgxL/oXhKKLGZYVbrRrNDQNEQZsZfvSI5GZuGaT8lN1MVFtjgt1zaYNgHGJ90iBbKXD6CXLFIr5SaKA+YE5eZoNJRDQ89J+jvhZLaRCeCP+jrIzkNjwJ2SWheJOYQzgnfdBVOnZNA7kUjTIwLeDDj2osfLUBeNL4+kLOD8FfvOGdrb99dzSTHdcmqlxlIuvcdCI9kdOMS2n2PAjd0sr+jg4GfowTTWnNGAJrR2Ar//j71LHrtWDBqdSGwONXp4cAC3ph+uys2vg+kL6nTcRZW/WvSGuLlgYDyg2J0zQE+hpG/5aKai0z7ZewSebFfBQ13XBb5u5pYd/Cq6xgJenFeTfKOxsJ53CN+VFTI7ENPaK2HiTsyhZ2ZYRNNtQtLlk8AVvX+8K26A==
  template:
    metadata:
      creationTimestamp: null
      name: secret-loggingapi
      namespace: prod-choreo-system

