apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-loggingapi
  namespace: prod-choreo-system
spec:
  encryptedData:
    AZURE_ACTIVEDIRECTORY_CLIENT_SECRET: AgAfWHrVAG7L6HYQeTkW4G8cSX+pYSk9uyM+K09PFtVyS067dKBXM9MI+d6uC3Eto6wYIH2MMa42NAcE/kpjRhhxZ8quuKysmndTn3ZWyTRrxWZvOcrSBMwax8bL5/vRXoJ74Ryz82TwUMSz0jy305QS5c25m7YkzLXbLDxbeiEmBSkJAomf3qr4426Vn4ffto4Zw6iQH3mt18qPDBYyPNCJ7C0oYIuonFkc8OOaSdgo/yqY6KsfHpaPzTLbkhGRo79KAJYIXJAiSF90n7wo0AlCX5h4eKaEqn2RXLtgGnszsO00ckFqh3VzPXVD1ryILRlzz5rIDysIFfzWheX2UsO0IJHvjtYPS9xbhw1amO0MR7Ssjdc7mtDoadocds0g93xv1ZvU36sgOH0PPVs4kJ0Ah705FsXQT7NCLoYCwh1tebxcq2VN0yfvSUZvM3jE9oCAKhXJqH6x7+Bir5fiX3cocgHGtcg8nm6epVbY8xlmSQZruDoyF6/8TruAk1nq1DPD4tqxja3pPUgW9BQgUemFMLwspy9/CQeAi7U8BJpPc1pix/NXc4Tc1gejuY5WwA8qQLL7TDPQ+RcAKm/C9sWiYl0/gwStD9/QX3e4TiXgA1MBlk2R1evg+VAaklQ5bI7tAYuezVLzY8zA3YCarZgb4dxa/ZgQhpBslj00KtZUlcxLYKKo0tUcvkrxx5yh5SLgCC8BXdM43Ly1FxhP9desv4Mg50QVbAvz1lg8R2T5KA==
  template:
    metadata:
      creationTimestamp: null
      name: secret-loggingapi
      namespace: prod-choreo-system

