apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-obsapi
  namespace: prod-choreo-system
spec:
  encryptedData:
    AZURE_TIMESERIESINSIGHTS_CLIENT_SECRET: AgBrbmxQu4wDV7adBmDaPPl8nq0Wj3l/BuX84VJEMMxsKq4CHRMCxn3z/sksY12DrgnVMlkAU9vhU6f9tf8C9y1kBs+4Bt4jIbnqKQlQ1DoHqCxvdBEbaRfxBoRuARnKSda8OdWVcfyjpzPXy4m990H8dw+ZQeGyhv39ZNFw4XZo35Wxq7SIp9Lz/p8HTdMMp+um4oFyGv/6G93OurowM/QEConiRpVnp3hKdj5F6IpDHDqQs1mwwTLp4HX78/HKT7dDWeyvYZGXWjOlnjXcILGJmqOjDhIxJRzyU6vw0U19pMJNtDlP0GiuJiC3D4MwfSsVJmoWw8ReSgTRF1YYlRmPP9knM2kOThRchJtLm26K6NHGjZn04btEeh8P/HHw58mUI5ORM18WJ1QQHbRUc2yVCM57WJPJY4hUySqQOYxjh8byua2FJ/P4PSIMuSRRyDO312SjZ6IEZ7k/bfwAoNvXQLaOml09jg1p3iUdbX5NNhOKnkDhUQFP0gc4Dcb2PhU+vBj87mFKV4Zcl8pBjbp1tbnum43LYAWfUB/NzyK++7hAEHe7LaaIY2OPyhMd8GOaKnH/X9kaFwZ0T7Pz1b1n6Wgh8IUoakILLpQ7/EZYqqH/G+ZrIaxL9W4GgdZyP/ZbBU5PnqlQT9oAWmofilQB1ibBYyRQo7tkXoP7zkTUxnKZwYyTi9xHi9Ylp7Y3JKthPd1r39GhWWl7TeF9V70nZKFQreXdSLQpylsiPhW8eA==
  template:
    metadata:
      creationTimestamp: null
      name: secret-obsapi
      namespace: prod-choreo-system

