apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-perf-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgBF84NFQDqAdM3xnMH+NlqrJr3T+x2wglIuwjqiQd1O240uyfmDDgt2PkQP01zBf21MWnMUclgftsJ0LG20N0Q4EJwQOVfplNFWsRu6hOec/ZtjduxQirmZniVuU54hJ5NsLKm3hY9hr9129ZAf0s1YC5+5AFOU/Tl4GZ5wxbmME+FfLyKPzJxwEP+pHfkyyOZaJC3vQKLT/BNJrbXQNJ0A8/QQX24apTZUvIHxNZ9Xaj2b4I640oUawQ39jMT8fqX6eepHhfW5jRAOCHHwigbDl9ySebblqXLPkGkQk9m+rMZ3iYMRzSyxrEPKNIDjM2irk5KjkTAipkG9Pgmi8VsmPFWpRVvEnDlSIZBLe+K3vBNEBIIiGTDiUiJzikYHO6HDJ7DWyHizU6uSKs9nIh+K9WFjDFyA1bEjBAIm1McqH4sAKxCOqW0eohcpIqsM0VrGYYH0VF+cWUtyuuhot97Iz7yEXm+bcktGLjg+IG8KovT8R5mQ7hkx1cFH4SP3DaPSNCP3Z+SZ42rDB2kd/2y0fnbDy9I8MqWgbcN/QCou/qwhZDrVS8vZYgSQ6odw/XiRMcjjb4LXFtUKVVVr5vX9FTxlbQ3Z7s19VeuVMe1wC/LM67iGNNHW3XSN8omp/LvSvyrkblvv7CGzIz7mFBeQoD+85iFx0SRQE9zw20n+XXMyNw5pW1zpMOj9o51JgK8o3fR0dgry9Y5DZvYi8jTe
  template:
    metadata:
      creationTimestamp: null
      name: secret-perf-db
      namespace: prod-choreo-system

