apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-perf-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgBFrWAGRpSnQBwzIsd4InnxG+x1xfnwDy423Rj4HO6dYA7nbbUFha8GzIdfG8Xp7FzHqYt/pHmTTpcbnIdhhl/WAqrdQtuAb+v+agY5Iq9cY70bvvbKOfMoDTW3ZpXQjgnolJ69qGsXEJkQeo3miOS+gJz0VZug1bMZxCtE2wfVT+4LUZdXttB1nXdj4aGAB2pKUNkwTFo2OudiBaxDGGq3Ojgfx9Wb+jMSc4inJ1Fbw8CuvtvGcsh8rLa2goerAcZa8PRKLsMi+exLtKV2GKf5cw+bMeiHkvbs1tfc+xXjuZsJk0TMs/LCs3dJlhydnAp7ScFOdTl22GgUkpLNqtNOy6JMUjACjgFqSvE+l1uj3Zei+r6NTC7yt7mmwNRUFrFh3eCo6bM9PPyRvEpOiHypO4Jl6vWgaietX+CrELqNlSc9XG7iJjYLyiI2GCOjvscehn1M/by/wT7OqBi1OXjL2j7I0jatD2kblqxFcRJ+42jriT6ALreRI9aWnzGyEQm187jcZsisog9lI/zy1iGRpeGCWp8YDsx3AGELTsp1HNU2RX3yJXUkN/81A0T+4B9ci90njN3w6kWrjraHi9Vjqu1n1ZkhRghbLebRg7HXlhti5Vs2aAZ/qY8LSEwAA4ZqzMBd4C8e1hkncz8SuMTBXO5+geMgIvW2OdE/KcEWwbBg2Ip1ZEHrUQpfYJHAMBsEQOVXqNZvpPpKc9tdhnIX
  template:
    metadata:
      creationTimestamp: null
      name: secret-perf-db
      namespace: prod-choreo-system

