apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-perfanalyzer
  namespace: prod-choreo-system
spec:
  encryptedData:
    AZURE_TIMESERIESINSIGHTS_CLIENT_SECRET: AgBSZ/6uTw2pzx7e4iOUZKSuZDpKd0QhOSJm+dLmw0rL1/Kg3myRUL9UYG5ypmAUhnn32qyBqvSUOlEk5RvjvyrAUkPZksGufmWZ+W6BrRhhwhvkOEwO2l98h3kB6fIWHfBWXQh8opj1ITEU5+eooonrGc/Y9zZpT5bvteyKJaG6vvUEJrG5JezDAZuZN+D1Qsf6rbVI6o8qAEK6HQBmwondGzP7EVBscTeahJ74PSBNHuRm4me1snQqg61Q/Rn0CPcfacY66lWk7USf7+Of3IK3e4awGPpv3aCnK9JQmuFunroLI1kM6IiUYQ/BdXf/ZcpQrC2djtzLzR6yBavw5IXsHwgeM5QYBpQZ541akXouWxhyN4yzg2AmZyEB0ahic727wK4JeweMhBrkNhwNte4Ni3HCTKQAr5sa6lzxifVq0rBBX00UpWKOVHNS/FgeieMD+V/8ACxJxDY1nNVVOOxLgzbFN1txAKnyKwrNfMAl2RrmZ9U5YMob8sV/ocYGeV25ohi96YR1eD6KblHq9WES1xZnARvSOuMphj5StWktODV8kUbtiMueiON587Lp1V6NFn9Hpzp2fU87ucEo1Ymbk/FXj52ve0JV8R+qFT/C//i60AIU5pySEe1/Omp5bohkkRIA8nrEfrCymDv8zHQn9JWrIn/Ayr6il4Fdj3iH8aWZigTOUthN+WCwt9qy2pi95R/wwYkBCCBo4/kcpMt6MRxYknwcYURlwprD0u/Buw==
    CHOREO_PERF_DB_PASSWORD: AgBL/XiXkbdGPVHDTtrJk0qdmaQLyh7SooHW8GS4IzvW7P464y+xcHJ2UWibP1ehVscKqMpOT8Xy5MfuCd9mNKu7IQIsa1Hl/+uQbN829odSJDe4vdLV+mxW6tL0LA7JdYmVTeAWCxxEEi2zVJRnbYEWITT59gkGQapjRu32e/jiGATc8CQ7aM2FZU6rTokki9NjuGHz8fy5Gvaw/5/FL8ZTbS5v3N+8AdoZlsvBSUb2CHDaau3dXtNmMNZ+yE7uYfElxWT2bTiXCIHxsFMbnzmMGXzEUpRnnwIUdSHPeX/SrrkyRhSoNMnUQN4nO7KbFBw/6MWUvIZCzhHFCh0S7UvD78lJDD27SY4LznsvJ9Poqbm9+fNdHHZhSWkn5Jxbmt2/rWNLV9jUeH0Nag+kksSLTgXy0CV/ndq05n6qkKwLm4asGyc2O3fNCN/R7mKReO/aWY97UKF83TH91JcQ39LiTpbbp1aa784z3QGYHsGIzvpRjvBqr4q74UGToQuMHcX9FcgnRTYLBcWd1xSuK0K555bztrrHNo687utxyissM7cITtH270N03J7WA+TIAWyvngiuGUb3E41PrpVOXKQ168IcxHYKxT9c3bRBm1XXb2kPiNbs4WIgbch2k6ZKGdoAvOR1x9L0URbCy2akHnyacl/abDSeQEHlFQzJ04hjnbsvGjF/LP8llVfqiJyIYfIiTZH5x2BcJh+YgdGv5Tps
  template:
    metadata:
      creationTimestamp: null
      name: secret-perfanalyzer
      namespace: prod-choreo-system

