apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-perf-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgBRK92Rble5J6+xJJ/rq+ElKHZYtuJpVXU3EgyiYOCE7xzsdMF9Zhoye+NjKVshQy+yMi2I+MnGtdVgX/WD+X2ou9BBbHKqrNK742e82Odx4yRcIP+a4RbfBpAhq/yDqcpwPipfGBGGoMeU81Ja9EaObs0xj2sODhTsL3IyV4pllbVCEiWSePayKI5Gb4espylzsZAUzzTJON1fBQxph1wrLyMWEqqmdw4zNWvTugKbvw09EYvfjHzfESD3onIgzmPdtvp/HnPtfL+bqOZuwzXcnJAlFhcSFrOVcYaa0ujRNO6wvCm4Tc9sB2jOVuRG2nAOu8Dx7z3AmbMML4yeqs6itAOI/DN7ILugJnp3w+CSgZezT/HQcJcVTYJOo2JK50PNbw40Dt22vVH1W2yow4NRZSyIqT8NW7XVO0ByC9k8JKP+ta7oGScX7l51+1FF40gJx9BsfQBvd27ZsyHMJBaUh5C4oVR7zPz6Kr/Pr9JrR9rLPln8VB1GBE6Tz/K6iQNmn7FVqO0yPdDyuODvgiFsDzN7cIXPXrJT6Extoch1m4e/ywCQpjyD1ce8wNOvy33ieZgQFhS+n414kf7DfzBso0O5T/lhx7pLQJkwv2/XvLbkT6SeC8/E3DRPB2RTa+22+5UbrBTkiRIGjUKa0FZ99EXcBGXRgTTfHijAbSEu16jREqB20CMfBjQhIu5NGYbsRBtwmLrkO9p+l6RFFPDY
  template:
    metadata:
      creationTimestamp: null
      name: secret-perf-db
      namespace: prod-choreo-system

