apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-program-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgCdy50kjMf9G7i08RFKliPy/qmfFOHHYbRRM3ezerQfr1jyKPMJZTcwWqc7x1sQyodfSwFylwu3ugEskemnCXK+nJI/yoFUvSAVKLhjpFuUgZm5SBS0jaWI0cl65ImLIIm4xL8MyeaE4TbiyX4KUyhTR1sTyXOjMS+DgB8enMqNc41OUm/4eDsRuS2uAGFFUQiummPgzfaBNWUuswaXA3pF75tGbWEKjMybJTzWc0UBnDKUiCDRrFOx0WdJPbU2PMXh5NEa0zKNKQ7TTbfIClIWa1Fg7SWC3QcsavsqhBtGCOVTT9MFnHDaB8iVnTaWAB1lTgdMeMYpjA4OkvCXvMAZ5mt5+Up7k3bpFjQxIJnniqRMlO+njEuYGZDp+qwsd5npY6Jxa+np+BK/2MqB+yRkQu5hLkrRsij9LdX/p+GYGz37o9dUZ4JzKFdiXybGnVN8bz6e+LFtMSpshyZv0ESHcwb38YF4aWjJuKtOBgIpbhn3u6DXdwNH7p0VNP92S8Z7Z725vjBnwXXDU7tr+maDQdJ81LxMq1G56xreB2+dgu66qTxS0AWzLsss7V+OqCyuQzRPAE/7ZrxEnZrhDqrmdUcULaH8U5+Ahicq30n0IvPgFwDvNiUgd1iS3h6k36uIctX1zDTgfG5WcVgJuOpVYklLRAyPZS8xDA8SmSn2ZfO9dK/DpDtyWXZktspqBo6DkbtlAkLHh0Z8wSw1V9y6
  template:
    metadata:
      creationTimestamp: null
      name: secret-program-db
      namespace: prod-choreo-system

