apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-telemetry
  namespace: prod-choreo-system
spec:
  encryptedData:
    EVENTHUB_SHARED_ACCESS_SIGNATURE_KEY: AgCPlHrXzHu7ekNW7Wp9qbRUoZmcnUj7GREn8bmUEAarcb3J2+MjBAMbHNF9HUCEKZbKN7AwyGRzC7mFOKWTVhdXLESeTZKtHUzthImCZgBlhqkbsPZNprFJofCnQnrauET/E2HdjHqWpuDtpH44pmkBAcsbLl+wOJhV7ICo7WJInzYJ4HzoPnkKFNbfhQ7dppcQvbrffA6jtuI+GfFndDvCgjd/0gGKkrVD2QcNFpujCJ+VO6w4O9VYL4mlesicGRUY6enKjvQdXF89mqWu6wzGvABMw7pxIVolReLPqWNHuqw+WL2y5POLuPD3SKTr4X0jZMaETdVIPZ9YN0QBERIzb+gnlbtJWNIrMGk9EgCa68niU5/SBosyshh5FTK52CjFBjfBgHqFdFPpwF9ATw3ACToRVXTOfAdLtGVwdFOQOFo8DxMrY1X6a+X9j2H72QC/TrA0uHonWew8yUqASS38W/zAbTuCx5wU3zJ1fxT7SJgSkk8U9c1QyEumB9fnkOC8XwrtPCe2XsXSLGfzBIpMs40gMzm1/nRXmXDT58HeQ4m+fAPoVW72G+FpolnCTvgq0IeDrHsZX5bZssTybUlfG57KhocVCEqWiqYJNOJ/Ro13HySZFbbSHFm59pmcm7dsjZOWwvJOySeQoX2hENRV0AvZGs3yd5wicJettMPjE3vmKNQn8oMOBle6eosz022c2144TXyUy9hCzhC2SSKaVRJZ8TbWujov8VcCpMAdMYaCqDOUUDxvx+dXTg==
  template:
    metadata:
      creationTimestamp: null
      name: secret-telemetry
      namespace: prod-choreo-system

