apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-telemetry
  namespace: prod-choreo-system
spec:
  encryptedData:
    EVENTHUB_SHARED_ACCESS_SIGNATURE_KEY: AgBlSE5fO78DKb8QjywaHl7aR4UwBf54aF/1GahS2p7ztpEjKv04IjP9YCxHrenhz2WDlUjFauWHzkmmEP27lqSrdvmbCXfPCPb031PGX5umm/GymrT8Ep/ZLgAHXItNd3l5TVLbqjeuw2PCH/EdW/2+uysKtPeKPkgFd3KjhA/p9uYeAbfZmc+PNW64Rv64VjyucTrJnmxiNQCbw7qqRN5dn+LVlI0ELTXuUWXp5yEFRVKrNY2fYIKwEr3g1MCHmcNvMKFpaa6ku5wndTgyYBH1YNMiy0CIr1c6Mu/9rvU+2bwC6F7PsqRK4OUCopxH9UcCbr9PJiBzAqKDVEjV68EDRv1/WnmS0+sdLmVE/ZJxBj2AHFsDeHUkcy8I52y595A4R+frGXuQBKaple16P+LHQ3aM1SHEGRqHKpWY5wZeJxTyLihiH0+lInG9yVjyYRgZrg4aRjq9qkdiPGjr+RPewr5Na17sl6eZqO54LyKwiJQXH439xi9moTwhZcP8w/WQXqIClRJYlV1J6BPhvrRyYVn1BRlm/9h1jTTVG4NVaT0A3Nw7NekJJvyGtXsOkZs7ihgrVtrh7dmpDJSikW4JMLGiDI7k+mz5ho7uJYOzYGcxeh015bT+ndhCuBbje1mFQ5H//FNiRF/bFCE8teNPu4z/xJVhh9YhXtsee8q9E7YT5UMrT2xL4bB3/xQVI7D7e5poKa7FB/TMEaKO6UKuWudY8sO/oOy+NqYmn0knaitql5r1+wMFXql3fA==
  template:
    metadata:
      creationTimestamp: null
      name: secret-telemetry
      namespace: prod-choreo-system

