apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-trace-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgATGKHDRxHdYf1C2YV1+uU/z3XEIndOfHHYifBI4C4HjKw8hGx1UW581ds4bQ6yS8KKsFp8YlSSWvjSvodHve29eHImRf71llo17FrQpv65Zhn2WWKLCNs6QdyRymF41A8UZjUXvopGlrcyfV3RKpK1lH0Wl4pr6z+8seTUocKNNZpT8qrniQcgtPES0LaXRn+7afi9CDdLiCziVhuVFQlhtSTmuSc/oswMIiGZICCTcmZTUQdi06OaedbQTVMDnEaIaka/9TDvnP5XcPpkvp4qa7geUJqEsiocRqu732fKOnI3AhT4MzRbKqIBP9ilzy5OHtLnvNh5Ae8f05cteCnXfn6ur6LQLxvnVGFFdPphVBSyfkQ8b7Y2F1uU+VLHy85A7QsTMUQuz+6X5m2U33JT33VSgo9rDUI3bdEoTg0Jhvg8jSMkFzJCxpqDD5CllSQYrKdf0w1XTp7vdOHtWGCTH4wKVN07+pQVJq+mn9uhZmJXg/c6qOqC3gkgC+KJ1Uq+RKWauNeMhIxeTI+f0PvBXLLmj/+mZVJ+r1SPcUNwyKaFtZYg6aF5JjcqNYiK2QWVmt18BPXgPT8n/PK+dUYCRPR53eoG+QkkERkCTt+QgX/VocCXLj8VWVxhBAoyyTwFY+53eU0P8c+InY2L4OpqFICd2Gfe6IQAuzyHN0MI/xC3q38xeoksGYuclxEuiA9B0nkoxQ5h1p9r7BgcGSqR
  template:
    metadata:
      creationTimestamp: null
      name: secret-trace-db
      namespace: prod-choreo-system

