apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-trace-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgC1j0jiNznMp84hbwmqka40xldFkP+tQqMfi8b2WCRnt6zqpmRbJ55ec9wS5iinr33zc38ClqGqpE06yDL1i1RR4IsCRxBcQI77EOWZW4HMWVjzfA+v15ZOXXispR6dtyCw/l5eiE39iaKh5AKozv2/AnojkMCUymKivFoMIDUoEz8jVMrWSqmICjivOUVbT9xoNYDmeU8aI2Lb8gVSMB/XcKLwmZ3e6byL5vjfKWnKNRXVTzvewEjcQlx22ELbkBpLF0/OYpQCKUo8f6g8TEqi79/LD7i9KrB3jXqgF4FE6l9Mq9+7m+W/FaKSWm4cUlXpIhQJiGnUU2uuFPvWvjk7wyRlBFMpxwLCFtsKgboPR7pfxCRdS5baI+AQj7bZjwlVxSdReIXlHZed2rempizhDqPOOvWvKaPqTczNJqF5I6q+mighnpSUAuu0uWcPQNAA220kMWBLvZaaSTjDoZUP4QF/2zxeFBq6BLrR1M9eZr+jFZuJ6t7oJ9JoPmPIdqUbl3UzdqW9awSrZCbpz+AADQNZSQANfOoraOoBfZlwLIaR9ggPb3jfjM4A3bA/8zobxgDJRXMwRwOwzb3fytpeV8/FO8AIUj0CZ6mte2HY6TWx8C1msYJEuj7+rIC7ZJx3diZPESXiPLyt9R+vGgmLBOQnZ/U8OMEVQSjLr+/xvEwGmRQg33idNkhovP/S5GPz7VNv8H5BzhBqIv6ZLf3J
  template:
    metadata:
      creationTimestamp: null
      name: secret-trace-db
      namespace: prod-choreo-system

