apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-trace-db
  namespace: prod-choreo-system
spec:
  encryptedData:
    CHOREO_DB_PASSWORD: AgB4VIct1XK05XD+z4vO4RDeKcJaAxyS/iJn+nAKFn/dCGw1GsId3L8iwQvuakHj0W7/TeytlQwOBaAjbYWzosQdTAiezhHitqKioVpG5U6v270VYY41p816h0++eRqsFy1wIYhdRU4ifr0OJDxP8VLzeCyK49/9gPo6wsD3IDf0dsTMTrh4DeOibhYroA1wGAfjuoEsFqXZCPcToQxfGjYOgpPyk5Zwg8RJcdeubiwS8cskj25BpKVe280L3VanC5123Y5bSkQLhml6uKPEKpipimygPGqOhjEUIinBSC6Rs7PpD7GneKtwlqYn6xB5KsVoGZdgU4pSs+AUj8fLLPkGOf9zD4rowIM594q6zaZJIbaeuP9UEeqvfkPkjsvf1O+OuaF15DYgw0ER2U2vA9SvUWGG8bbcwP4zecHgMGrkVqn10Tc2ZjGwLSYUzUYhQaYB3b6br5e/+KTba62ZKRMQ6TNuUPuIIEKPP8HqGuPyEfJkgDuTJdjZ2nLvd2u32Jr+/nCckmRIVxa71Sg+0kPonYD1qkJJae0qcshqWdXogfRaCzI4cs1cwcDoIr5UM4hrRkd2X4qGLn0G6Oscb5V0+ui+jrDhkkdcLs4dsuvm6o0vfnNXYFHf+wr0fL3L0r7qJP/RL3dkRNADb3bljB9Tsfdq6Jgu2WVnVbHbbBuZw7LBKbihyQsSHpHTp4A6XtH5Hj625Y9+EVe0nXp6jqRI
  template:
    metadata:
      creationTimestamp: null
      name: secret-trace-db
      namespace: prod-choreo-system

