resources:
  - am.yaml
  - choreo-connect-adapter.yaml
  - choreo-connect-deployment.yaml
  - choreo-connect-global-adapter.yaml
  - choreo-connect-internal-global-adapter.yaml
  - choreo-gateway-nginx.yaml
  - devportal.yaml
