# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dp-cicd
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    {{- include "dp-cicd.labels" . | nindent 4 }}
spec:
  provider: vault
  secretObjects:
    - secretName: dp-cicd
      type: Opaque
      data:
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: GITHUB_APP_CLIENT_SECRET
          key: GITHUB_APP_CLIENT_SECRET
        - objectName: GITHUB_APP_PRIVATE_KEY
          key: GITHUB_APP_PRIVATE_KEY
        - objectName: LOG_ANALYTICS_KEY
          key: LOG_ANALYTICS_KEY
        - objectName: CHOREO_PRIVATE_ACR_SECRET
          key: CHOREO_PRIVATE_ACR_SECRET
        - objectName: DOCKER_REGISTRY_PAT
          key: DOCKER_REGISTRY_PAT
        - objectName: CHOREO_GITHUB_RUNNER_APP_CLIENT_SECRET
          key: CHOREO_GITHUB_RUNNER_APP_CLIENT_SECRET
        - objectName: CHOREO_GITHUB_RUNNER_APP_OPAQUE_CLIENT_SECRET
          key: CHOREO_GITHUB_RUNNER_APP_OPAQUE_CLIENT_SECRET
        - objectName: AZURE_CONTAINER_REGISTRY_PASSWORD
          key: AZURE_CONTAINER_REGISTRY_PASSWORD
        - objectName: GITOPS_APP_CLIENT_SECRET
          key: GITOPS_APP_CLIENT_SECRET
        - objectName: GITOPS_APP_PRIVATE_KEY
          key: GITOPS_APP_PRIVATE_KEY
        {{- range $index, $user := .Values.secrets.dockerHubUsers }}
        - objectName: DOCKER_HUB_USER_{{ add $index 1 }}
          key: DOCKER_HUB_USER_{{ add $index 1 }}
        {{- end }}
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: DB_PASSWORD
        secretKey: {{ .Values.secrets.dbPassword.key | quote }}
        secretPath: {{ .Values.secrets.dbPassword.path | quote }}
      - objectName: GITHUB_APP_CLIENT_SECRET
        secretKey: {{ .Values.secrets.githubAppClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.githubAppClientSecret.path | quote }}
      - objectName: GITHUB_APP_PRIVATE_KEY
        secretKey: {{ .Values.secrets.githubAppPrivateKey.key | quote }}
        secretPath: {{ .Values.secrets.githubAppPrivateKey.path | quote }}
      - objectName: LOG_ANALYTICS_KEY
        secretKey: {{ .Values.secrets.logAnalyticsKey.key | quote }}
        secretPath: {{ .Values.secrets.logAnalyticsKey.path | quote }}
      - objectName: CHOREO_PRIVATE_ACR_SECRET
        secretKey: {{ .Values.secrets.choreoPrivateAcrSecret.key | quote }}
        secretPath: {{ .Values.secrets.choreoPrivateAcrSecret.path | quote }}
      - objectName: DOCKER_REGISTRY_PAT
        secretKey: {{ .Values.secrets.dokerRegistryPat.key | quote }}
        secretPath: {{ .Values.secrets.dokerRegistryPat.path | quote }}
      - objectName: CHOREO_GITHUB_RUNNER_APP_CLIENT_SECRET
        secretKey: {{ .Values.secrets.choreoGithubRunnerAppClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.choreoGithubRunnerAppClientSecret.path | quote }}
      - objectName: CHOREO_GITHUB_RUNNER_APP_OPAQUE_CLIENT_SECRET
        secretKey: {{ .Values.secrets.choreoGithubRunnerAppOpaqueClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.choreoGithubRunnerAppOpaqueClientSecret.path | quote }}
      - objectName: AZURE_CONTAINER_REGISTRY_PASSWORD
        secretKey: {{ .Values.secrets.azureContainerRegistryPassword.key | quote }}
        secretPath: {{ .Values.secrets.azureContainerRegistryPassword.path | quote }}
      - objectName: GITOPS_APP_CLIENT_SECRET
        secretKey: {{ .Values.secrets.gitOpsAppClientSecret.key | quote }}
        secretPath: {{ .Values.secrets.gitOpsAppClientSecret.path | quote }}
      - objectName: GITOPS_APP_PRIVATE_KEY
        secretKey: {{ .Values.secrets.gitOpsAppPrivateKey.key | quote }}
        secretPath: {{ .Values.secrets.gitOpsAppPrivateKey.path | quote }}
      {{- range $index, $user := .Values.secrets.dockerHubUsers }}
      - objectName: DOCKER_HUB_USER_{{ add $index 1 }}
        secretKey: {{ $user.key | quote }}
        secretPath: {{ $user.path | quote }}
      {{- end }}
