apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: choreo-connect-adapter-test-p1
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      choreo.component: choreo-connect-adapter-test-p1
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: choreo-connect-deployment-test-p1
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      choreo.component: choreo-connect-deployment-test-p1
