apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: aks-readonly-cluster-role-binding
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: aks-readonly-cluster-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "${AKS_READONLY_AD_GROUP_ID}"