# --------------------------------------------------------------------
# Copyright (c) 2023, WSO2 LLC. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "docker/default"
    checkov.io/skip1: "CKV_K8S_AZURE_WSO2_2=Linkerd is disable for dataplane"
  labels:
    choreo.component: testgpt
  name: testgpt
spec:
  selector:
    matchLabels:
      choreo.component: testgpt
  template:
    metadata:
      labels:
        choreo.component: testgpt
        antiaffinity: testgpt
      annotations:
        config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
        seccomp.security.alpha.kubernetes.io/pod: "docker/default"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: testgpt
          envFrom:
            - configMapRef:
                name: testgpt-cm
            - secretRef:
                name: testgpt-secret
          image: choreocontrolplane.azurecr.io/choreoipaas/choreo-testgpt-dp:latest
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9090 
              name: testgpt-port
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: testgpt-port
              path: /health
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              port: testgpt-port
              path: /health
          securityContext:
            runAsUser: 10500
            runAsGroup: 10500
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - all
          volumeMounts:
            - name: config
              mountPath: /home/ballerina/Config.toml
              subPath: Config.yaml
              readOnly: true
            - mountPath: /mnt/csi/secret-testgpt
              name: testgpt-secret
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: testgpt-cm-file
        - name: testgpt-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: testgpt-secret
            nodePublishSecretRef:
              name: csi-secret-store-azure
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: antiaffinity
                  operator: In
                  values:
                  - testgpt
              topologyKey: kubernetes.io/hostname
