helmCharts:
  - name: reloader
    includeCRDs: true
    valuesInline:
      fullnameOverride: reloader
      reloader:
        enableHA: true
        deployment:
          replicas: 2
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          containerSecurityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "10m"
              memory: "128Mi"
        readOnlyRootFileSystem: true
        image:
          name: choreocontrolplane.azurecr.io/stakater/reloader
          tag: v1.0.33
          pullPolicy: Always
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
    releaseName: reloader
    namespace: reloader
    version: 1.0.33
    repo: oci://choreocontrolplane.azurecr.io/helm

commonAnnotations:
  kapp.k14s.io/disable-default-label-scoping-rules: ""
