trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: perf-test-tokens

resources:
  repositories:
    - repository: choreo-common-pipeline-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise

parameters:
  - name: emails
    displayName: 'List of email addresses to send the report'
    type: string
    default: "amilad@wso2.com"
  - name: generateChartsOnly
    displayName: 'Only execute the step to generate charts'
    type: boolean
    default: false

steps:
  # Install Python Dependencies
  - script: |
      python3 -m pip install --upgrade pip
      python3 -m pip install gspread google-auth google-auth-oauthlib google-auth-httplib2
      python3 -m pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib matplotlib
    displayName: 'Install Python Dependencies'

  # Run the python script to generate charts
  - script: |
      python3 processing-scripts/generate_charts.py
    env:
      GSHEET_TOKEN: $(gsheet-token)
    displayName: 'Generate Charts'
    workingDirectory: performance-tests/jmeter-scripts

  # Create a folder named charts and copy all generated results
  - script: |
      mkdir -p charts
      cp *.png charts/
    displayName: 'Copy generated Charts'
    workingDirectory: performance-tests/jmeter-scripts

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'performance-tests/jmeter-scripts/charts/'
      ArtifactName: charts
      publishLocation: 'Container'
    displayName: 'Upload Charts as a Pipeline Artifact'

  # Set a variable to control email-sending logic
  - script: |
      echo "##vso[task.setvariable variable=sendEmail]$([ "${{ parameters.generateChartsOnly }}" == "true" ] && echo false || echo true)"
    displayName: 'Set Email Sending Variable'

  # Run the python script to send the email (conditional step)
  - script: |
      python3 processing-scripts/send_perf_report.py ${{ parameters.emails }}
    condition: eq(variables['sendEmail'], 'false')
    displayName: 'Send the email'
    workingDirectory: performance-tests/jmeter-scripts
    env:
      EMAIL_USER: $(email-user)
      EMAIL_PASSWORD: $(email-password)
