trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: perf-test-tokens

resources:
  repositories:
    - repository: choreo-common-pipeline-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise

parameters:
  - name: users
    displayName: 'Number of Users'
    type: number
    default: 5
  - name: userCountStart
    displayName: 'Counter start value'
    type: number
    default: 4000
  - name: userCountEnd
    displayName: 'End counter value'
    type: number
    default: 4020
  - name: iterations
    displayName: 'No of loops per user'
    type: number
    default: 4
  - name: componentCreationWaitTime
    displayName: 'Time to wait in seconds until component creation is completed'
    type: number
    default: 120
  - name: buildWaitTime
    displayName: 'Time to wait in seconds until builds are completed'
    type: number
    default: 300

stages:
  - stage: JMeterTests
    displayName: "Run All JMeter Tests"
    jobs:
      # Signing Test
      - job: SigningTest
        displayName: "Run Signing Test"
        steps:
          - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

          - script: |
              /opt/jmeter/bin/jmeter -n -t signin.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: 'Run Signin Test'

          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: signin.jmx
              containerName: signin

          - template: templates/write-to-gdrive.yaml
            parameters:
              gsheetToken: $(gsheet-token)
              uploadDir: signin
              sheetName: "User Signing In"
              reportFilter: "report-configs/signin.txt"

      # Project Cleanup Test
      - job: ProjectCleanupTest
        displayName: "Run Project Cleanup Test"
        dependsOn: SigningTest
        steps:
          - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

          - script: |
              /opt/jmeter/bin/jmeter -n -t project-cleanup.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: 'Run Project Cleanup Test'

          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: project-cleanup.jmx
              containerName: project-cleanup

          - template: templates/write-to-gdrive.yaml
            parameters:
              gsheetToken: $(gsheet-token)
              uploadDir: component-deletion
              sheetName: "Component Deletion"

      # Project Creation Test
      - job: ProjectCreationTest
        displayName: "Run Project Creation Test"
        dependsOn: ProjectCleanupTest
        steps:
          - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

          - script: |
              /opt/jmeter/bin/jmeter -n -t project-creation.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: "Run Project Creation Test"

          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: project-creation.jmx
              containerName: project-creation

          - template: templates/write-to-gdrive.yaml
            parameters:
              gsheetToken: $(gsheet-token)
              uploadDir: project-creation
              sheetName: "Project Creation"
              reportFilter: "report-configs/project-creation.txt"

      # # Component Creation Test
      - job: ComponentCreationTest
        displayName: "Run Component Creation Test"
        dependsOn: ProjectCreationTest
        steps:
          - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

          - script: |
              /opt/jmeter/bin/jmeter -n -t component-creation.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: "Run Component Creation Test"

          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: component-creation.jmx
              containerName: component-creation

          - template: templates/write-to-gdrive.yaml
            parameters:
              gsheetToken: $(gsheet-token)
              uploadDir: component-creation
              sheetName: "Trigger Component Creation"
              reportFilter: "report-configs/component-creation.txt"

          - script: |
              echo "Waiting for ${{ parameters.componentCreationWaitTime }} seconds to ensure components are ready..."
              sleep ${{ parameters.componentCreationWaitTime }}
            displayName: "Introduce Delay Before Running Build Test"

      # # Trigger Build Test
      - job: TriggerBuildTest
        displayName: "Run Trigger Build Test"
        dependsOn: ComponentCreationTest
        steps:
          - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

          - script: |
              /opt/jmeter/bin/jmeter -n -t trigger-build.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: "Run Trigger Build Test"

          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: trigger-build.jmx
              containerName: trigger-build

          - template: templates/write-to-gdrive.yaml
            parameters:
              gsheetToken: $(gsheet-token)
              uploadDir: component-build
              sheetName: "Trigger Build"
              reportFilter: "report-configs/component-build.txt"

          - script: |
              echo "Waiting for ${{ parameters.componentCreationWaitTime }} seconds to ensure Builds have completed ..."
              sleep ${{ parameters.buildWaitTime }}
            displayName: "Introduce Delay Before Running Deployment Test"

      # Trigger Deploy Test
      - job: TriggerDeployTest
        displayName: "Run Trigger Deploy Test"
        dependsOn: TriggerBuildTest
        steps:
          - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

          - script: |
              /opt/jmeter/bin/jmeter -n -t trigger-deployment.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: "Run Trigger Deployment Test"

          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: trigger-deployment.jmx
              containerName: trigger-deployment

          - template: templates/write-to-gdrive.yaml
            parameters:
              gsheetToken: $(gsheet-token)
              uploadDir: trigger-deploy
              sheetName: "Trigger Deployment"
              reportFilter: "report-configs/trigger-deploy.txt"
