trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: perf-test-tokens

resources:
  repositories:
    - repository: choreo-common-pipeline-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise

parameters:
  - name: users
    displayName: 'Number of Concurrent Threads'
    type: number
    default: 20
  - name: userCountStart
    displayName: 'Counter start value'
    type: number
    default: 4000
  - name: userCountEnd
    displayName: 'End counter value'
    type: number
    default: 4020
  - name: iterations
    displayName: 'No of loops per Thread'
    type: number
    default: 1

steps:
  - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

  - script: |
      /opt/jmeter/bin/jmeter -n -t get-build-status.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
    workingDirectory: performance-tests/jmeter-scripts
    displayName: 'Get Build Statuses'

  - script: |
      python3 -m pip install --upgrade pip
      python3 -m pip install matplotlib pandas numpy
    displayName: 'Install Python Dependencies for Build Details Extraction'

  - script: |
      python3 processing-scripts/extract_build_details.py --buildType=lastBuild --input=result-tree.jtl --output=jmeter_summary.csv
    displayName: 'Generate Build Status Summary'
    workingDirectory: performance-tests/jmeter-scripts

  - script: |
      python3 processing-scripts/summarize_build_details.py --input=jmeter_summary.csv --output=AggregateReport.csv
    displayName: 'Generate Aggregate Report'
    workingDirectory: performance-tests/jmeter-scripts

  - script: |
      mkdir -p results
      cp *.log ./results/
      cp *.txt ./results/
      cp *.jtl ./results/
      cp *.csv ./results/
      cp get-build-status.jmx ./results/
    workingDirectory: performance-tests/jmeter-scripts
    displayName: 'Copy Specific Files for Artifacts'

  - template: templates/write-to-gdrive.yaml
    parameters:
      gsheetToken: $(gsheet-token)
      uploadDir: component-build-throughput
      sheetName: "Component Build Operation"
