trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: users
    displayName: 'Number of Users'
    type: number
    default: 100
  - name: userCountStart
    displayName: 'Counter start value'
    type: number
    default: 4000
  - name: userCountEnd
    displayName: 'End counter value'
    type: number
    default: 4020
  - name: iterations
    displayName: 'No of loops per user'
    type: number
    default: 4

steps:
  - template: templates/install-jmeter.yaml

  - script: |
      /opt/jmeter/bin/jmeter -n -t signin.jmx -l "jmeter_run_result.jtl" -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
    workingDirectory: performance-tests/jmeter-scripts
    displayName: 'Run JMeter Test'

  - template: templates/generate-n-publish-results.yaml
    parameters:
      script-name: signin.jmx
      container-name: signin
