trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: choreo-common-pipeline-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise

parameters:
  - name: users
    displayName: 'Number of Users'
    type: number
    default: 5
  - name: userCountStart
    displayName: 'Counter start value'
    type: number
    default: 4000
  - name: userCountEnd
    displayName: 'End counter value'
    type: number
    default: 4020
  - name: iterations
    displayName: 'No of loops per user'
    type: number
    default: 4


stages:
  - stage: JMeterTests
    displayName: "Run All JMeter Tests"
    jobs:
      # Install JMeter (common step for all tests)
      - job: InstallDependencies
        displayName: "Install Dependencies"
        steps:
          - template: install/install-jmeter.yaml@choreo-common-pipeline-templates
            displayName: "Install JMeter on Agent"

      # Signing Test
      - job: SigningTest
        displayName: "Run Signing Test"
        dependsOn: InstallDependencies
        steps:
          - script: |
              /opt/jmeter/bin/jmeter -n -t signin.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: 'Run Signin Test'
          
          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: signin.jmx
              containerName: signin

      # Project Cleanup Test
      - job: ProjectCleanupTest
        displayName: "Run Project Cleanup Test"
        dependsOn: SigningTest
        steps:
          - script: |
              /opt/jmeter/bin/jmeter -n -t project-cleanup.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
            workingDirectory: performance-tests/jmeter-scripts
            displayName: 'Run Project Cleanup Test'
          
          - template: templates/generate-n-publish-results.yaml
            parameters:
              scriptName: project-cleanup.jmx
              containerName: project-cleanup  

      # Project Creation Test
      # - job: ProjectCreationTest
      #   displayName: "Run Project Creation Test"
      #   dependsOn: ProjectCleanupTest
      #   steps:
      #     - script: |
      #         /usr/share/jmeter/bin/jmeter -n -t project-creation.jmx -Jrampup=10 -Jusers=5 -JuserCountStart=4000 -JuserCountEnd=4020 -Jloops=4
      #       workingDirectory: performance-tests/jmeter-scripts
      #       displayName: "Run Project Creation Test"

      # # Component Creation Test
      # - job: ComponentCreationTest
      #   displayName: "Run Component Creation Test"
      #   dependsOn: ProjectCreationTest
      #   steps:
      #     - script: |
      #         /usr/share/jmeter/bin/jmeter -n -t component-creation.jmx -Jrampup=10 -Jusers=5 -JuserCountStart=4000 -JuserCountEnd=4020 -Jloops=4
      #       workingDirectory: performance-tests/jmeter-scripts
      #       displayName: "Run Component Creation Test"

      # # Trigger Build Test
      # - job: TriggerBuildTest
      #   displayName: "Run Trigger Build Test"
      #   dependsOn: ComponentCreationTest
      #   steps:
      #     - script: |
      #         /usr/share/jmeter/bin/jmeter -n -t trigger-build.jmx -Jrampup=10 -Jusers=5 -JuserCountStart=4000 -JuserCountEnd=4020 -Jloops=4
      #       workingDirectory: performance-tests/jmeter-scripts
      #       displayName: "Run Trigger Build Test"

      # # Trigger Deploy Test
      # - job: TriggerDeployTest
      #   displayName: "Run Trigger Deploy Test"
      #   dependsOn: TriggerBuildTest
      #   steps:
      #     - script: |
      #         /usr/share/jmeter/bin/jmeter -n -t trigger-deployment.jmx -Jrampup=10 -Jusers=5 -JuserCountStart=4000 -JuserCountEnd=4020 -Jloops=4
      #       workingDirectory: performance-tests/jmeter-scripts
      #       displayName: "Run Trigger Deployment Test"
