trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: users
    displayName: 'Number of Users'
    type: number
    default: 5
  - name: userCountStart
    displayName: 'Start counter value'
    type: number
    default: 4000
  - name: userCountEnd
    displayName: 'End counter value'
    type: number
    default: 4020
  - name: iterations
    displayName: 'No of loops per user'
    type: number
    default: 4

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk
      echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" | sudo tee -a /etc/environment
      echo "PATH=\$PATH:\$JAVA_HOME/bin" | sudo tee -a /etc/environment
      source /etc/environment
      echo $JAVA_HOME
      echo $PATH
    displayName: 'Install Java and Set Environment Variables'

  - script: |
      wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
      tar -xzf apache-jmeter-5.6.3.tgz
      sudo mv apache-jmeter-5.6.3 /opt/jmeter
    displayName: 'Install JMeter'

  - script: |
      /opt/jmeter/bin/jmeter --version
    displayName: 'Check JMeter Version'

  - script: |
      /opt/jmeter/bin/jmeter -n -t project-cleanup.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jloops="${{ parameters.iterations }}"
    workingDirectory: performance-tests/jmeter-scripts
    displayName: 'Run Project Cleanup Test'

  - script: |
      mkdir -p results
      cp *.log ./results/
      cp *.txt ./results/
      cp *.jtl ./results/
      cp project-cleanup.jmx ./results/
    workingDirectory: performance-tests/jmeter-scripts
    displayName: 'Copy Specific Files for Artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'performance-tests/jmeter-scripts/results/'
      ArtifactName: 'project-cleanup'
      publishLocation: 'Container'
    displayName: 'Publish JMeter Results as Build Artifact'
