trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: choreo-common-pipeline-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      ref: refs/heads/main
      endpoint: wso2-enterprise

parameters:
  - name: users
    displayName: 'Number of Users'
    type: number
    default: 5
  - name: userCountStart
    displayName: 'Start counter value'
    type: number
    default: 4000
  - name: userCountEnd
    displayName: 'End counter value'
    type: number
    default: 4020
  - name: iterations
    displayName: 'No of loops per user'
    type: number
    default: 4
  - name: buildIterations
    displayName: 'No of iterations to check for the build'
    type: number
    default: 30

steps:
  - template: install/install-jmeter.yaml@choreo-common-pipeline-templates

  - script: |
      /opt/jmeter/bin/jmeter -n -t full-test-service-init-to-invoke.jmx -Jrampup=10 -Jusers="${{ parameters.users }}" -JuserCountStart="${{ parameters.userCountStart }}" -JuserCountEnd="${{ parameters.userCountEnd }}" -Jiterations="${{ parameters.iterations }}" -JbuildIterations="${{ parameters.buildIterations }}"
    workingDirectory: performance-tests/jmeter-scripts
    displayName: 'Run Full Test Component Creation to Invoke Test'

  - template: templates/generate-n-publish-results.yaml
    parameters:
      scriptName: full-test-service-init-to-invoke.jmx
      containerName: full-service-init-to-invoke
