CREATE USER IF NOT EXISTS 'IDP_SHARED_DB_USER'@'%' IDENTIFIED BY 'admin';
CREATE USER IF NOT EXISTS 'IDP_CONFIG_DB_USER'@'%' IDENTIFIED BY 'admin';
CREATE USER IF NOT EXISTS 'IDP_IDENTITY_DB_USER'@'%' IDENTIFIED BY 'admin';
CREATE USER IF NOT EXISTS 'IDP_BPS_DB_USER'@'%' IDENTIFIED BY 'admin';
CREATE USER IF NOT EXISTS 'IDP_USERSTORE_DB_USER'@'%' IDENTIFIED BY 'admin';
-- CREATE USER IF NOT EXISTS 'CONSENT_MGT_USER'@'%' IDENTIFIED BY 'admin';

GRANT ALL ON IDP_SHARED_DB.* TO 'IDP_SHARED_DB_USER'@'%' IDENTIFIED BY 'admin';
GRANT ALL ON IDP_CONFIG_DB.* TO 'IDP_CONFIG_DB_USER'@'%' IDENTIFIED BY 'admin';
GRANT ALL ON IDP_IDENTITY_DB.* TO 'IDP_IDENTITY_DB_USER'@'%' IDENTIFIED BY 'admin';
GRANT ALL ON IDP_BPS_DB.* TO 'IDP_BPS_DB_USER'@'%' IDENTIFIED BY 'admin';
GRANT ALL ON IDP_USERSTORE_DB.* TO 'IDP_USERSTORE_DB_USER'@'%' IDENTIFIED BY 'admin';
-- GRANT ALL ON CONSENT_MGT.* TO 'CONSENT_MGT_USER'@'%' IDENTIFIED BY 'admin';

-- WSO2 IS DB INIT STARTS --

DROP DATABASE IF EXISTS IDP_CONFIG_DB;
CREATE DATABASE IDP_CONFIG_DB character set latin1;
USE IDP_CONFIG_DB;
SOURCE common.sql;

DROP DATABASE IF EXISTS IDP_SHARED_DB;
CREATE DATABASE IDP_SHARED_DB character set latin1;
USE IDP_SHARED_DB;
SOURCE common.sql;

DROP DATABASE IF EXISTS IDP_USERSTORE_DB;
CREATE DATABASE IDP_USERSTORE_DB character set latin1;
USE IDP_USERSTORE_DB;
SOURCE common.sql;

DROP DATABASE IF EXISTS IDP_IDENTITY_DB;
CREATE DATABASE IDP_IDENTITY_DB character set latin1;
USE IDP_IDENTITY_DB;
SOURCE identity.sql;
SOURCE consent.sql;

DROP DATABASE IF EXISTS IDP_BPS_DB;
CREATE DATABASE IDP_BPS_DB character set latin1;
USE IDP_BPS_DB;
SOURCE bps.sql;

-- DROP DATABASE IF EXISTS CONSENT_MGT;
-- CREATE DATABASE CONSENT_MGT character set latin1;
-- USE CONSENT_MGT;
-- SOURCE consent.sql;


-- WSO2 IS DB INIT ENDS --


