/****** Object:  Schema [m2ss]    Script Date: 3/11/2022 3:51:25 AM ******/
CREATE SCHEMA [m2ss]
GO
/****** Object:  Table [dbo].[REG_ASSOCIATION]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_ASSOCIATION](
	[REG_ASSOCIATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_SOURCEPATH] [varchar](2000) NOT NULL,
	[REG_TARGETPATH] [varchar](2000) NOT NULL,
	[REG_ASSOCIATION_TYPE] [varchar](2000) NOT NULL,
	[REG_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REG_ASSOCIATION_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_CLUSTER_LOCK]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_CLUSTER_LOCK](
	[REG_LOCK_NAME] [varchar](20) NOT NULL,
	[REG_LOCK_STATUS] [varchar](20) NULL,
	[REG_LOCKED_TIME] [datetime] NULL,
	[REG_TENANT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[REG_LOCK_NAME] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_COMMENT]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_COMMENT](
	[REG_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_COMMENT_TEXT] [varchar](500) NOT NULL,
	[REG_USER_ID] [varchar](31) NOT NULL,
	[REG_COMMENTED_TIME] [datetime] NOT NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_COMMENT] PRIMARY KEY CLUSTERED 
(
	[REG_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_CONTENT]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_CONTENT](
	[REG_CONTENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_CONTENT_DATA] [varbinary](max) NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_CONTENT] PRIMARY KEY CLUSTERED 
(
	[REG_CONTENT_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_CONTENT_HISTORY]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_CONTENT_HISTORY](
	[REG_CONTENT_ID] [int] NOT NULL,
	[REG_CONTENT_DATA] [varbinary](max) NULL,
	[REG_DELETED] [smallint] NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_CONTENT_HISTORY] PRIMARY KEY CLUSTERED 
(
	[REG_CONTENT_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_LOG]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_LOG](
	[REG_LOG_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_PATH] [varchar](2000) NULL,
	[REG_USER_ID] [varchar](31) NOT NULL,
	[REG_LOGGED_TIME] [datetime] NOT NULL,
	[REG_ACTION] [int] NOT NULL,
	[REG_ACTION_DATA] [varchar](500) NULL,
	[REG_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REG_LOG_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_PATH]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_PATH](
	[REG_PATH_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_PATH_VALUE] [varchar](895) NOT NULL,
	[REG_PATH_PARENT_ID] [int] NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_PATH] PRIMARY KEY CLUSTERED 
(
	[REG_PATH_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UNIQUE_REG_PATH_TENANT_ID] UNIQUE NONCLUSTERED 
(
	[REG_PATH_VALUE] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_PROPERTY]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_PROPERTY](
	[REG_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_NAME] [varchar](100) NOT NULL,
	[REG_VALUE] [varchar](1000) NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_PROPERTY] PRIMARY KEY CLUSTERED 
(
	[REG_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_RATING]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_RATING](
	[REG_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_RATING] [int] NOT NULL,
	[REG_USER_ID] [varchar](31) NOT NULL,
	[REG_RATED_TIME] [datetime] NOT NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_RATING] PRIMARY KEY CLUSTERED 
(
	[REG_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_RESOURCE]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_RESOURCE](
	[REG_PATH_ID] [int] NOT NULL,
	[REG_NAME] [varchar](256) NULL,
	[REG_VERSION] [int] IDENTITY(1,1) NOT NULL,
	[REG_MEDIA_TYPE] [varchar](500) NULL,
	[REG_CREATOR] [varchar](31) NOT NULL,
	[REG_CREATED_TIME] [datetime] NOT NULL,
	[REG_LAST_UPDATOR] [varchar](31) NULL,
	[REG_LAST_UPDATED_TIME] [datetime] NOT NULL,
	[REG_DESCRIPTION] [varchar](1000) NULL,
	[REG_CONTENT_ID] [int] NULL,
	[REG_TENANT_ID] [int] NOT NULL,
	[REG_UUID] [varchar](100) NOT NULL,
 CONSTRAINT [PK_REG_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[REG_VERSION] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_RESOURCE_COMMENT]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_RESOURCE_COMMENT](
	[REG_COMMENT_ID] [int] NOT NULL,
	[REG_VERSION] [int] NULL,
	[REG_PATH_ID] [int] NULL,
	[REG_RESOURCE_NAME] [varchar](256) NULL,
	[REG_TENANT_ID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_RESOURCE_HISTORY]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_RESOURCE_HISTORY](
	[REG_PATH_ID] [int] NOT NULL,
	[REG_NAME] [varchar](256) NULL,
	[REG_VERSION] [int] NOT NULL,
	[REG_MEDIA_TYPE] [varchar](500) NULL,
	[REG_CREATOR] [varchar](31) NOT NULL,
	[REG_CREATED_TIME] [datetime] NOT NULL,
	[REG_LAST_UPDATOR] [varchar](31) NULL,
	[REG_LAST_UPDATED_TIME] [datetime] NOT NULL,
	[REG_DESCRIPTION] [varchar](1000) NULL,
	[REG_CONTENT_ID] [int] NULL,
	[REG_DELETED] [smallint] NULL,
	[REG_TENANT_ID] [int] NOT NULL,
	[REG_UUID] [varchar](100) NOT NULL,
 CONSTRAINT [PK_REG_RESOURCE_HISTORY] PRIMARY KEY CLUSTERED 
(
	[REG_VERSION] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_RESOURCE_PROPERTY]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_RESOURCE_PROPERTY](
	[REG_PROPERTY_ID] [int] NOT NULL,
	[REG_VERSION] [int] NULL,
	[REG_PATH_ID] [int] NULL,
	[REG_RESOURCE_NAME] [varchar](256) NULL,
	[REG_TENANT_ID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_RESOURCE_RATING]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_RESOURCE_RATING](
	[REG_RATING_ID] [int] NOT NULL,
	[REG_VERSION] [int] NULL,
	[REG_PATH_ID] [int] NULL,
	[REG_RESOURCE_NAME] [varchar](256) NULL,
	[REG_TENANT_ID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_RESOURCE_TAG]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_RESOURCE_TAG](
	[REG_TAG_ID] [int] NOT NULL,
	[REG_VERSION] [int] NULL,
	[REG_PATH_ID] [int] NULL,
	[REG_RESOURCE_NAME] [varchar](256) NULL,
	[REG_TENANT_ID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_SNAPSHOT]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_SNAPSHOT](
	[REG_SNAPSHOT_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_PATH_ID] [int] NOT NULL,
	[REG_RESOURCE_NAME] [varchar](256) NULL,
	[REG_RESOURCE_VIDS] [varbinary](max) NOT NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_SNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[REG_SNAPSHOT_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REG_TAG]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REG_TAG](
	[REG_ID] [int] IDENTITY(1,1) NOT NULL,
	[REG_TAG_NAME] [varchar](500) NOT NULL,
	[REG_USER_ID] [varchar](31) NOT NULL,
	[REG_TAGGED_TIME] [datetime] NOT NULL,
	[REG_TENANT_ID] [int] NOT NULL,
 CONSTRAINT [PK_REG_TAG] PRIMARY KEY CLUSTERED 
(
	[REG_ID] ASC,
	[REG_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_ACCOUNT_MAPPING]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_ACCOUNT_MAPPING](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_USER_NAME] [varchar](255) NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
	[UM_USER_STORE_DOMAIN] [varchar](100) NULL,
	[UM_ACC_LINK_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_USER_NAME] ASC,
	[UM_TENANT_ID] ASC,
	[UM_USER_STORE_DOMAIN] ASC,
	[UM_ACC_LINK_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_CLAIM]    Script Date: 3/11/2022 3:51:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_CLAIM](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_DIALECT_ID] [int] NULL,
	[UM_CLAIM_URI] [varchar](255) NULL,
	[UM_DISPLAY_TAG] [varchar](255) NULL,
	[UM_DESCRIPTION] [varchar](255) NULL,
	[UM_MAPPED_ATTRIBUTE_DOMAIN] [varchar](255) NULL,
	[UM_MAPPED_ATTRIBUTE] [varchar](255) NULL,
	[UM_REG_EX] [varchar](255) NULL,
	[UM_SUPPORTED] [smallint] NULL,
	[UM_REQUIRED] [smallint] NULL,
	[UM_DISPLAY_ORDER] [int] NULL,
	[UM_CHECKED_ATTRIBUTE] [smallint] NULL,
	[UM_READ_ONLY] [smallint] NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_DIALECT_ID] ASC,
	[UM_CLAIM_URI] ASC,
	[UM_TENANT_ID] ASC,
	[UM_MAPPED_ATTRIBUTE_DOMAIN] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_CLAIM_BEHAVIOR]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_CLAIM_BEHAVIOR](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_PROFILE_ID] [int] NULL,
	[UM_CLAIM_ID] [int] NULL,
	[UM_BEHAVIOUR] [smallint] NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_DIALECT]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_DIALECT](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_DIALECT_URI] [varchar](255) NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_DIALECT_URI] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_DOMAIN]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_DOMAIN](
	[UM_DOMAIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_DOMAIN_NAME] [varchar](255) NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_DOMAIN_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_DOMAIN_NAME] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_HYBRID_REMEMBER_ME]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_HYBRID_REMEMBER_ME](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_USER_NAME] [varchar](255) NOT NULL,
	[UM_COOKIE_VALUE] [varchar](1024) NULL,
	[UM_CREATED_TIME] [datetime] NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_HYBRID_ROLE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_HYBRID_ROLE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_ROLE_NAME] [varchar](255) NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_ROLE_NAME] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_HYBRID_USER_ROLE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_HYBRID_USER_ROLE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_USER_NAME] [varchar](255) NULL,
	[UM_ROLE_ID] [int] NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
	[UM_DOMAIN_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_USER_NAME] ASC,
	[UM_ROLE_ID] ASC,
	[UM_TENANT_ID] ASC,
	[UM_DOMAIN_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_MODULE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_MODULE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_MODULE_NAME] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_MODULE_NAME] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_MODULE_ACTIONS]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_MODULE_ACTIONS](
	[UM_ACTION] [varchar](255) NOT NULL,
	[UM_MODULE_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ACTION] ASC,
	[UM_MODULE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_PERMISSION]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_PERMISSION](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_RESOURCE_ID] [varchar](255) NOT NULL,
	[UM_ACTION] [varchar](255) NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
	[UM_MODULE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_RESOURCE_ID] ASC,
	[UM_ACTION] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_PROFILE_CONFIG]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_PROFILE_CONFIG](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_DIALECT_ID] [int] NULL,
	[UM_PROFILE_NAME] [varchar](255) NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_ROLE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_ROLE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_ROLE_NAME] [varchar](255) NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
	[UM_SHARED_ROLE] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_ROLE_NAME] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_ROLE_PERMISSION]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_ROLE_PERMISSION](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_PERMISSION_ID] [int] NOT NULL,
	[UM_ROLE_NAME] [varchar](255) NOT NULL,
	[UM_IS_ALLOWED] [smallint] NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
	[UM_DOMAIN_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_PERMISSION_ID] ASC,
	[UM_ROLE_NAME] ASC,
	[UM_TENANT_ID] ASC,
	[UM_DOMAIN_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_SHARED_USER_ROLE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_SHARED_USER_ROLE](
	[UM_ROLE_ID] [int] NOT NULL,
	[UM_USER_ID] [int] NOT NULL,
	[UM_USER_TENANT_ID] [int] NOT NULL,
	[UM_ROLE_TENANT_ID] [int] NOT NULL,
UNIQUE NONCLUSTERED 
(
	[UM_USER_ID] ASC,
	[UM_ROLE_ID] ASC,
	[UM_USER_TENANT_ID] ASC,
	[UM_ROLE_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_SYSTEM_ROLE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_SYSTEM_ROLE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_ROLE_NAME] [varchar](255) NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_ROLE_NAME] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_SYSTEM_USER]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_SYSTEM_USER](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_USER_NAME] [varchar](255) NOT NULL,
	[UM_USER_PASSWORD] [varchar](255) NOT NULL,
	[UM_SALT_VALUE] [varchar](31) NULL,
	[UM_REQUIRE_CHANGE] [bit] NULL,
	[UM_CHANGED_TIME] [datetime] NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_USER_NAME] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_SYSTEM_USER_ROLE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_SYSTEM_USER_ROLE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_USER_NAME] [varchar](255) NULL,
	[UM_ROLE_ID] [int] NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_USER_NAME] ASC,
	[UM_ROLE_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_TENANT]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_TENANT](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_DOMAIN_NAME] [varchar](255) NOT NULL,
	[UM_EMAIL] [varchar](255) NULL,
	[UM_ACTIVE] [bit] NULL,
	[UM_CREATED_DATE] [datetime] NOT NULL,
	[UM_USER_CONFIG] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_DOMAIN_NAME] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_USER]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_USER](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_USER_ID] [varchar](255) NOT NULL,
	[UM_USER_NAME] [varchar](255) NOT NULL,
	[UM_USER_PASSWORD] [varchar](255) NOT NULL,
	[UM_SALT_VALUE] [varchar](31) NULL,
	[UM_REQUIRE_CHANGE] [bit] NULL,
	[UM_CHANGED_TIME] [datetime] NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_USER_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_USER_ATTRIBUTE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_USER_ATTRIBUTE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_ATTR_NAME] [varchar](255) NOT NULL,
	[UM_ATTR_VALUE] [varchar](1024) NULL,
	[UM_PROFILE_ID] [varchar](255) NULL,
	[UM_USER_ID] [int] NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_USER_PERMISSION]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_USER_PERMISSION](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_PERMISSION_ID] [int] NOT NULL,
	[UM_USER_NAME] [varchar](255) NOT NULL,
	[UM_IS_ALLOWED] [smallint] NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_PERMISSION_ID] ASC,
	[UM_USER_NAME] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_USER_ROLE]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_USER_ROLE](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_ROLE_ID] [int] NOT NULL,
	[UM_USER_ID] [int] NOT NULL,
	[UM_TENANT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_USER_ID] ASC,
	[UM_ROLE_ID] ASC,
	[UM_TENANT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UM_UUID_DOMAIN_MAPPER]    Script Date: 3/11/2022 3:51:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UM_UUID_DOMAIN_MAPPER](
	[UM_ID] [int] IDENTITY(1,1) NOT NULL,
	[UM_USER_ID] [varchar](255) NOT NULL,
	[UM_DOMAIN_ID] [int] NOT NULL,
	[UM_TENANT_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[UM_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UM_USER_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REG_ASSOCIATION] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_CLUSTER_LOCK] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_COMMENT] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_CONTENT] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_CONTENT_HISTORY] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_LOG] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_PATH] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_PROPERTY] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RATING] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_COMMENT] ADD  DEFAULT ((0)) FOR [REG_VERSION]
GO
ALTER TABLE [dbo].[REG_RESOURCE_COMMENT] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_HISTORY] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_PROPERTY] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_RATING] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_TAG] ADD  DEFAULT ((0)) FOR [REG_VERSION]
GO
ALTER TABLE [dbo].[REG_RESOURCE_TAG] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_SNAPSHOT] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_TAG] ADD  DEFAULT ((0)) FOR [REG_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_CLAIM] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_CLAIM_BEHAVIOR] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_DIALECT] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_DOMAIN] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_HYBRID_REMEMBER_ME] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_HYBRID_ROLE] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_HYBRID_USER_ROLE] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_PERMISSION] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_PERMISSION] ADD  DEFAULT ((0)) FOR [UM_MODULE_ID]
GO
ALTER TABLE [dbo].[UM_PROFILE_CONFIG] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_ROLE] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_ROLE] ADD  DEFAULT ((0)) FOR [UM_SHARED_ROLE]
GO
ALTER TABLE [dbo].[UM_ROLE_PERMISSION] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_SYSTEM_ROLE] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_SYSTEM_USER] ADD  DEFAULT ((0)) FOR [UM_REQUIRE_CHANGE]
GO
ALTER TABLE [dbo].[UM_SYSTEM_USER] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_SYSTEM_USER_ROLE] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_TENANT] ADD  DEFAULT ((0)) FOR [UM_ACTIVE]
GO
ALTER TABLE [dbo].[UM_USER] ADD  DEFAULT ((0)) FOR [UM_REQUIRE_CHANGE]
GO
ALTER TABLE [dbo].[UM_USER] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_USER_ATTRIBUTE] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_USER_PERMISSION] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_USER_ROLE] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[UM_UUID_DOMAIN_MAPPER] ADD  DEFAULT ((0)) FOR [UM_TENANT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_FK_BY_PATH_ID] FOREIGN KEY([REG_PATH_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PATH] ([REG_PATH_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE] CHECK CONSTRAINT [REG_RESOURCE_FK_BY_PATH_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_COMMENT]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_COMMENT_FK_BY_COMMENT_ID] FOREIGN KEY([REG_COMMENT_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_COMMENT] ([REG_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_COMMENT] CHECK CONSTRAINT [REG_RESOURCE_COMMENT_FK_BY_COMMENT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_COMMENT]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_COMMENT_FK_BY_PATH_ID] FOREIGN KEY([REG_PATH_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PATH] ([REG_PATH_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_COMMENT] CHECK CONSTRAINT [REG_RESOURCE_COMMENT_FK_BY_PATH_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_HISTORY]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_HIST_FK_BY_CONTENT_ID] FOREIGN KEY([REG_CONTENT_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_CONTENT_HISTORY] ([REG_CONTENT_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_HISTORY] CHECK CONSTRAINT [REG_RESOURCE_HIST_FK_BY_CONTENT_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_HISTORY]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_HIST_FK_BY_PATHID] FOREIGN KEY([REG_PATH_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PATH] ([REG_PATH_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_HISTORY] CHECK CONSTRAINT [REG_RESOURCE_HIST_FK_BY_PATHID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_PROPERTY]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_PROPERTY_FK_BY_PATH_ID] FOREIGN KEY([REG_PATH_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PATH] ([REG_PATH_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_PROPERTY] CHECK CONSTRAINT [REG_RESOURCE_PROPERTY_FK_BY_PATH_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_PROPERTY]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_PROPERTY_FK_BY_TAG_ID] FOREIGN KEY([REG_PROPERTY_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PROPERTY] ([REG_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_PROPERTY] CHECK CONSTRAINT [REG_RESOURCE_PROPERTY_FK_BY_TAG_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_RATING]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_RATING_FK_BY_PATH_ID] FOREIGN KEY([REG_PATH_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PATH] ([REG_PATH_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_RATING] CHECK CONSTRAINT [REG_RESOURCE_RATING_FK_BY_PATH_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_RATING]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_RATING_FK_BY_RATING_ID] FOREIGN KEY([REG_RATING_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_RATING] ([REG_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_RATING] CHECK CONSTRAINT [REG_RESOURCE_RATING_FK_BY_RATING_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_TAG]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_TAG_FK_BY_PATH_ID] FOREIGN KEY([REG_PATH_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PATH] ([REG_PATH_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_TAG] CHECK CONSTRAINT [REG_RESOURCE_TAG_FK_BY_PATH_ID]
GO
ALTER TABLE [dbo].[REG_RESOURCE_TAG]  WITH NOCHECK ADD  CONSTRAINT [REG_RESOURCE_TAG_FK_BY_TAG_ID] FOREIGN KEY([REG_TAG_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_TAG] ([REG_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_RESOURCE_TAG] CHECK CONSTRAINT [REG_RESOURCE_TAG_FK_BY_TAG_ID]
GO
ALTER TABLE [dbo].[REG_SNAPSHOT]  WITH NOCHECK ADD  CONSTRAINT [REG_SNAPSHOT_FK_BY_PATH_ID] FOREIGN KEY([REG_PATH_ID], [REG_TENANT_ID])
REFERENCES [dbo].[REG_PATH] ([REG_PATH_ID], [REG_TENANT_ID])
GO
ALTER TABLE [dbo].[REG_SNAPSHOT] CHECK CONSTRAINT [REG_SNAPSHOT_FK_BY_PATH_ID]
GO
ALTER TABLE [dbo].[UM_ACCOUNT_MAPPING]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_ACCOUN__UM_TE__69FBBC1F] FOREIGN KEY([UM_TENANT_ID])
REFERENCES [dbo].[UM_TENANT] ([UM_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_ACCOUNT_MAPPING] CHECK CONSTRAINT [FK__UM_ACCOUN__UM_TE__69FBBC1F]
GO
ALTER TABLE [dbo].[UM_CLAIM]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_CLAIM__72910220] FOREIGN KEY([UM_DIALECT_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_DIALECT] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_CLAIM] CHECK CONSTRAINT [FK__UM_CLAIM__72910220]
GO
ALTER TABLE [dbo].[UM_CLAIM_BEHAVIOR]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_CLAIM_BEHAVIO__7A3223E8] FOREIGN KEY([UM_PROFILE_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_PROFILE_CONFIG] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_CLAIM_BEHAVIOR] CHECK CONSTRAINT [FK__UM_CLAIM_BEHAVIO__7A3223E8]
GO
ALTER TABLE [dbo].[UM_CLAIM_BEHAVIOR]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_CLAIM_BEHAVIO__7B264821] FOREIGN KEY([UM_CLAIM_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_CLAIM] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_CLAIM_BEHAVIOR] CHECK CONSTRAINT [FK__UM_CLAIM_BEHAVIO__7B264821]
GO
ALTER TABLE [dbo].[UM_HYBRID_USER_ROLE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_HYBRID_USER_R__03BB8E22] FOREIGN KEY([UM_ROLE_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_HYBRID_ROLE] ([UM_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_HYBRID_USER_ROLE] CHECK CONSTRAINT [FK__UM_HYBRID_USER_R__03BB8E22]
GO
ALTER TABLE [dbo].[UM_HYBRID_USER_ROLE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_HYBRID_USER_R__04AFB25B] FOREIGN KEY([UM_DOMAIN_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_DOMAIN] ([UM_DOMAIN_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_HYBRID_USER_ROLE] CHECK CONSTRAINT [FK__UM_HYBRID_USER_R__04AFB25B]
GO
ALTER TABLE [dbo].[UM_MODULE_ACTIONS]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_MODULE__UM_MO__4D5F7D71] FOREIGN KEY([UM_MODULE_ID])
REFERENCES [dbo].[UM_MODULE] ([UM_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_MODULE_ACTIONS] CHECK CONSTRAINT [FK__UM_MODULE__UM_MO__4D5F7D71]
GO
ALTER TABLE [dbo].[UM_PROFILE_CONFIG]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_PROFILE_CONFI__76619304] FOREIGN KEY([UM_DIALECT_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_DIALECT] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_PROFILE_CONFIG] CHECK CONSTRAINT [FK__UM_PROFILE_CONFI__76619304]
GO
ALTER TABLE [dbo].[UM_ROLE_PERMISSION]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_ROLE_PERMISSI__56E8E7AB] FOREIGN KEY([UM_PERMISSION_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_PERMISSION] ([UM_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_ROLE_PERMISSION] CHECK CONSTRAINT [FK__UM_ROLE_PERMISSI__56E8E7AB]
GO
ALTER TABLE [dbo].[UM_ROLE_PERMISSION]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_ROLE_PERMISSI__57DD0BE4] FOREIGN KEY([UM_DOMAIN_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_DOMAIN] ([UM_DOMAIN_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_ROLE_PERMISSION] CHECK CONSTRAINT [FK__UM_ROLE_PERMISSI__57DD0BE4]
GO
ALTER TABLE [dbo].[UM_SHARED_USER_ROLE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_SHARED_USER_R__65370702] FOREIGN KEY([UM_ROLE_ID], [UM_ROLE_TENANT_ID])
REFERENCES [dbo].[UM_ROLE] ([UM_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_SHARED_USER_ROLE] CHECK CONSTRAINT [FK__UM_SHARED_USER_R__65370702]
GO
ALTER TABLE [dbo].[UM_SHARED_USER_ROLE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_SHARED_USER_R__662B2B3B] FOREIGN KEY([UM_USER_ID], [UM_USER_TENANT_ID])
REFERENCES [dbo].[UM_USER] ([UM_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_SHARED_USER_ROLE] CHECK CONSTRAINT [FK__UM_SHARED_USER_R__662B2B3B]
GO
ALTER TABLE [dbo].[UM_SYSTEM_USER_ROLE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_SYSTEM_USER_R__0D44F85C] FOREIGN KEY([UM_ROLE_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_SYSTEM_ROLE] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_SYSTEM_USER_ROLE] CHECK CONSTRAINT [FK__UM_SYSTEM_USER_R__0D44F85C]
GO
ALTER TABLE [dbo].[UM_USER_ATTRIBUTE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_USER_ATTRIBUT__42E1EEFE] FOREIGN KEY([UM_USER_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_USER] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_USER_ATTRIBUTE] CHECK CONSTRAINT [FK__UM_USER_ATTRIBUT__42E1EEFE]
GO
ALTER TABLE [dbo].[UM_USER_PERMISSION]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_USER_PERMISSI__5CA1C101] FOREIGN KEY([UM_PERMISSION_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_PERMISSION] ([UM_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_USER_PERMISSION] CHECK CONSTRAINT [FK__UM_USER_PERMISSI__5CA1C101]
GO
ALTER TABLE [dbo].[UM_USER_ROLE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_USER_ROLE__6166761E] FOREIGN KEY([UM_ROLE_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_ROLE] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_USER_ROLE] CHECK CONSTRAINT [FK__UM_USER_ROLE__6166761E]
GO
ALTER TABLE [dbo].[UM_USER_ROLE]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_USER_ROLE__625A9A57] FOREIGN KEY([UM_USER_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_USER] ([UM_ID], [UM_TENANT_ID])
GO
ALTER TABLE [dbo].[UM_USER_ROLE] CHECK CONSTRAINT [FK__UM_USER_ROLE__625A9A57]
GO
ALTER TABLE [dbo].[UM_UUID_DOMAIN_MAPPER]  WITH NOCHECK ADD  CONSTRAINT [FK__UM_UUID_DOMAIN_M__14E61A24] FOREIGN KEY([UM_DOMAIN_ID], [UM_TENANT_ID])
REFERENCES [dbo].[UM_DOMAIN] ([UM_DOMAIN_ID], [UM_TENANT_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UM_UUID_DOMAIN_MAPPER] CHECK CONSTRAINT [FK__UM_UUID_DOMAIN_M__14E61A24]
GO
