[cp.resilient_invocation_service]
servicePort = 9090

[cp.resilient_invocation_service.repository]
host = "{{.MSSQL_HOST}}"
port  = 1433
user = "choreo_cp_ris_db_user"
database = "choreo_cp_ris_db"
mssqlPwdSecretPath = "/mnt/csi/secret-cp-ris/CP_RIS_DB_PASSWORD"

[ballerina.log]
level = "{{.LOG_LEVEL}}"
