apiVersion: batch/v1
kind: CronJob
metadata:
  name: choreo-daily-usage-publisher
  labels:
    choreo.component: choreo-daily-usage-publisher
spec:
  schedule: 45 23 * * *
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 10
      completions: 1
      parallelism: 1
      template:
        metadata:
          annotations:
            seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
            linkerd.io/inject: disabled # https://github.com/linkerd/linkerd2/issues/2833
          labels:
            choreo.component: choreo-daily-usage-publisher
        spec:
          automountServiceAccountToken: false
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          containers:
            - name: choreo-daily-usage-publisher
              image: choreocontrolplane.azurecr.io/choreoipaas/metered-usage-handler-crons:latest
              securityContext:
                runAsUser: 10500
                runAsGroup: 10500
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - all
              envFrom:
                - configMapRef:
                    name: cm-choreo-metered-usage-handler-daily-publisher
                - configMapRef:
                    name: env-choreo-metered-usage-handler
                - secretRef:
                    name: secret-choreo-metered-usage-handler
              resources:
                limits:
                  cpu: 700m
                  memory: 500Mi
                requests:
                  cpu: 600m
                  memory: 400Mi
              volumeMounts:
                - name: config
                  mountPath: /home/ballerina/Config.toml
                  subPath: Config.toml
                - name: secret-choreo-metered-usage-handler
                  mountPath: "/mnt/csi/secret-choreo-metered-usage-handler"
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: config
              configMap:
                name: cm-file-choreo-metered-usage-handler
            - name: secret-choreo-metered-usage-handler
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: secret-choreo-metered-usage-handler
                nodePublishSecretRef:
                  name: csi-secret-store-azure
            - name: tmp
              emptyDir: {}
          serviceAccountName: sa-choreo-default
