---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector-builder-kubectl-executor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-builder-kubectl-executor-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
    resourceNames: ["connector-builder"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-builder-restarter-binding
subjects:
  - kind: ServiceAccount
    name: connector-builder-kubectl-executor-sa
roleRef:
  kind: Role
  name: connector-builder-kubectl-executor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: connector-builder-rollout-restarter
spec:
  schedule: '*/10 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: connector-builder-kubectl-executor-sa
          containers:
            - name: connector-builder-restart-cron
              image: choreocontrolplane.azurecr.io/bitnami/kubectl:1.27.5
              command:
                - kubectl
                - rollout
                - restart
                - deployment/connector-builder
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
