resources:
  - ast-archiver.yaml
  - observability-data-generator.yaml
  - perfanalyzer-updater.yaml
  - program-cleaner.yaml
  - logs-archiver.yaml
  - choreo-userapps-image-deleter.yaml
  - cio-internal-metric-collector.yaml
  - choreo-daily-usage-publisher.yaml
  - choreo-monthly-usage-publisher.yaml
  - choreo-daily-usage-publisher-dynamic-billing-cycle.yaml
  - choreo-offline-runner-cleaner.yaml
  - choreo-offline-build-status-cleaner.yaml
  - connector-builder-restarter.yaml
  - choreo-platform-svc-cost-collector.yaml
