apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: observability-data-generator
  annotations:
    checkov.io/skip1: CKV_K8S_22=Skipping till the issue is fixed
    checkov.io/skip2: CKV_K8S_40=Temporarily suppressing till fixing
    checkov.io/skip3: CKV_K8S_43=Temporarily suppressing till fixing
    checkov.io/skip5: CKV_K8S_28=Temporarily suppressing till fixing
    checkov.io/skip6: CKV_K8S_37=Temporarily suppressing till fixing
  labels:
    choreo.component: observability-data-generator
spec:
  schedule: 30 20 1,15 * *
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          annotations:
            seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
            linkerd.io/inject: disabled # https://github.com/linkerd/linkerd2/issues/2833
          labels:
            choreo.component: observability-data-generator
        spec:
          automountServiceAccountToken: false
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never
          containers:
            - name: observability-data-generator
              image: choreocontrolplane.azurecr.io/choreoipaas/observability-data-generator:latest
              securityContext:
                runAsUser: 1000
                runAsGroup: 3000
                allowPrivilegeEscalation: false
              env:
                - name: APP_DEPLOYER_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      key: APP_DEPLOYER_ADDRESS
                      name: cm-observability-data-generator
                - name: APP_SERVICE_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      key: APP_SERVICE_ADDRESS
                      name: cm-observability-data-generator
                - name: WS_MANAGER_SERVICE_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      key: WS_MANAGER_SERVICE_ADDRESS
                      name: cm-observability-data-generator
              envFrom:
                - configMapRef:
                    name: env-observability-data-generator
              resources:
                limits:
                  cpu: 300m
                  memory: 1024Mi
                requests:
                  cpu: 200m
                  memory: 512Mi
          serviceAccountName: sa-choreo-default
