# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: dp-mizzen
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    {{ include "dp-mizzen.labels" . | indent 4 }}
data:
  PORT: 8080
  SERVICE_RUDDER_URL: http://dp-rudder
  REDIS_TLS: 1
  MSSQL_PORT: 1443
  MSSQL_USERNAME: choreo_mizzen_admin_db_user
  MSSQL_DATABASE: choreo_mizzen_db
  REDIS_PORT: 6380
  NODE_OPTIONS: "--max-http-header-size=65000"
  NODE_ENV: {{ .Values.config.nodeEnvironment }}
  MSSQL_HOST: {{ .Values.config.mssqlHost }}
  REDIS_HOST: {{ .Values.config.redisHost }}
  HOST_DNS: {{ .Values.config.hostDns }}
  RB_HEALTH_CHECK_ENABLED: {{ .Values.config.healthCheckEnabled }}
  RB_HEALTH_CHECK_INITIAL_DELAY_SECONDS: {{ .Values.config.healthCheckInitialDelaySeconds }}
  RB_HEALTH_CHECK_INTERVAL_MS: {{ .Values.config.healthCheckIntervalMiliSeconds }}
  RB_HEALTH_CHECK_HISTORY_LIMIT_SECONDS: {{ .Values.config.healthCheckHistoryLimitSeconds }}
  RB_HEALTH_CHECK_SUCCESS_THRESHOLD: {{ .Values.config.healthCheckSuccessThreshold }}
