# -------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dp-mizzen
  namespace: {{ .Values.global.namespaces.system }}
  labels:
    {{- include "dp-mizzen.labels" . | nindent 4 }}
spec:
  provider: vault
  secretObjects:
    - secretName: dp-mizzen
      type: Opaque
      data:
        - objectName: MSSQL_PASSWORD
          key: MSSQL_PASSWORD
        - objectName: SERVICE_BUS_CONNECTION_STRING
          key: SERVICE_BUS_CONNECTION_STRING
        - objectName: REDIS_PASSWORD
          key: REDIS_PASSWORD
        - objectName: JWT_KEY
          key: JWT_KEY
  parameters:
    vaultAddress: {{ .Values.global.vault.url }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      - objectName: MSSQL_PASSWORD
        secretKey: {{ .Values.secrets.mssqlPassword.key | quote }}
        secretPath: {{ .Values.secrets.mssqlPassword.path | quote }}
      - objectName: SERVICE_BUS_CONNECTION_STRING
        secretKey: {{ .Values.secrets.serviceBusConnectionString.key | quote }}
        secretPath: {{ .Values.secrets.serviceBusConnectionString.path | quote }}
      - objectName: REDIS_PASSWORD
        secretKey: {{ .Values.secrets.redisPassword.key | quote }}
        secretPath: {{ .Values.secrets.redisPassword.path | quote }}
      - objectName: JWT_KEY
        secretKey: {{ .Values.secrets.jwtKey.key | quote }}
        secretPath: {{ .Values.secrets.jwtKey.path | quote }}
