resources:
  - ../base
  - config
  - secret
  - persistence
  - namespace.yaml

namespace: prod-choreo-system

patches:
  - path: http-ingress-patch.yaml
    target:
      kind: Ingress
      name: ingress-http
  - path: grpc-ingress-patch.yaml
    target:
      kind: Ingress
      name: ingress-grpc

patchesStrategicMerge:
  - replica-rollout-strategy.yaml
  - linkerd.yaml
  - requests.yaml

commonLabels:
  app: prod-choreo-control-plane

images:
  - name: choreoipaas/console-app
    newName: choreoctrlplane.azurecr.io/choreoipaas/choreo-console
    newTag: v0.1.2
  - name: choreoipaas/app-service
    newName: choreoctrlplane.azurecr.io/choreoipaas/app-service
    newTag: v0.1.2
  - name: choreoipaas/choreo-logging
    newName: choreoctrlplane.azurecr.io/choreoipaas/choreo-logging
    newTag: v0.1.1
  - name: choreoipaas/choreo-negotiator
    newName: choreoctrlplane.azurecr.io/choreoipaas/choreo-negotiator
    newTag: v0.1.1
  - name: choreoipaas/observability-api
    newName: choreoctrlplane.azurecr.io/choreoipaas/observability-api
    newTag: v0.1.1
  - name: choreoipaas/perfanalyzer
    newName: choreoctrlplane.azurecr.io/choreoipaas/perfanalyzer
    newTag: v0.1.1
  - name: choreoipaas/programanalyzer
    newName: choreoctrlplane.azurecr.io/choreoipaas/programanalyzer
    newTag: v0.1.0
  - name: choreoipaas/choreo-telemetry
    newName: choreoctrlplane.azurecr.io/choreoipaas/choreo-telemetry
    newTag: v0.1.1
  - name: choreoipaas/workspace-cleanup
    newName: choreoctrlplane.azurecr.io/choreoipaas/workspace-cleanup
    newTag: v0.1.2
