resources:
  - ../base
  - namespace.yaml
  - sealed-secret.yaml
  - sealed-ingress-cert.yaml

namespace: prod-choreo-system

configMapGenerator:
  - name: cm-frontend
    behavior: merge
    literals:
      - OBSERVE_API=https://prod.choreo.local/graphql
  - name: cm-negotiator
    behavior: create
    literals:
      - CHOREO_APP_URL=http://prod.choreo.local/observe/app/

patches:
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-http
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-grpc

patchesStrategicMerge:
  - replica-rollout-strategy.yaml