resources:
  - ../base
  - namespace.yaml
  - secret/app-db.yaml
  - secret/appservice.yaml
  - secret/loggingapi.yaml
  - secret/obsapi.yaml
  - secret/perf-db.yaml
  - secret/program-db.yaml
  - secret/telemetry.yaml
  - secret/trace-db.yaml
  - secret/sealed-ingress-cert.yaml

namespace: prod-choreo-system

configMapGenerator:
  - name: cm-frontend
    behavior: merge
    literals:
      - OBSERVE_API=https://prod.choreo.local/graphql
  - name: cm-negotiator
    behavior: create
    literals:
      - CHOREO_APP_URL=http://prod.choreo.local/observe/app/
  - name: cm-choreo-app-db
    behavior: merge
    literals:
      - CHOREO_DB_HOST=choreo-app-db
      - CHOREO_DB_NAME=choreo_app_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
  - name: cm-choreo-perf-db
    behavior: merge
    literals:
      - CHOREO_DB_HOST=choreo-perf-db
      - CHOREO_DB_NAME=choreo_perf_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
  - name: cm-choreo-program-db
    behavior: merge
    literals:
      - CHOREO_DB_HOST=choreo-program-db
      - CHOREO_DB_NAME=choreo_program_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
  - name: cm-choreo-trace-db
    behavior: merge
    literals:
      - CHOREO_DB_HOST=choreo-trace-db
      - CHOREO_DB_NAME=choreo_trace_db
      - CHOREO_DB_PORT=3306
      - CHOREO_DB_USERNAME=root
patches:
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-http
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: ingress-grpc

patchesStrategicMerge:
  - replica-rollout-strategy.yaml
  - linkerd.yaml
  - requests.yaml