package com.wso2.choreo.integration.models.endpoints;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

@Data
public class ByoiEndpoint {
    @JsonProperty("ID")
    private String id;
    @JsonProperty("CreatedAt")
    private String createdAt;
    @JsonProperty("UpdatedAt")
    private String updatedAt;
    @JsonProperty("display_name")
    private String displayName;
    private int port;
    private String protocol;
    @JsonProperty("api_context")
    private String apiContext;
    @JsonProperty("api_definition_path")
    private String apiDefinitionPath;
    @JsonProperty("api_spec_hash")
    private String apiSpecHash;
    @JsonProperty("endpoint_yaml_hash")
    private String endpointYamlHash;
    private String visibility;
    private String type;
    @JsonProperty("apim_id")
    private String apimId;
    @JsonProperty("apim_revision_id")
    private String apimRevisionId;
    @JsonProperty("apim_name")
    private String apimName;
    @JsonProperty("project_url")
    private String projectUrl;
    @JsonProperty("organization_url")
    private String organizationUrl;
    @JsonProperty("public_url")
    private String publicUrl;
    private String state;
    @JsonProperty("state_reason")
    private StateReason stateReason;
    @JsonProperty("release_id")
    private String releaseId;
    @JsonProperty("is_deleted")
    private boolean isDeleted;
    @JsonProperty("deleted_at")
    private String deletedAt;
    @JsonProperty("is_auto_generated")
    private boolean isAutoGenerated;
    @JsonProperty("is_short_url")
    private boolean isShortUrl;
    @JsonProperty("last_generation_reason")
    private String lastGenerationReason;
    @JsonProperty("environment_id")
    private String environmentId;
    @JsonProperty("short_url_reassign_state")
    private String shortUrlReassignState;

    public static class StateReason {
        private String code;
        private String message;
        private String details;
        @JsonProperty("worker_id")
        private String workerId;
    }
}
