apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - choreodp-system
  - ../base/clusterissuers
  - ../routing/choreo-apim
  - ../dataplane/choreo-apim
  - ../dataplane/crd
  - ../dataplane/priorityclass
  - ../routing/clusterissuers

commonLabels:
  app: choreo-dataplane
