apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - choreo-apim
  - choreodp-system
  - clusterissuers
  - ../base/clusterissuers
  - ../dataplane/choreo-apim
  - ../dataplane/crd
  - ../dataplane/priorityclass

commonLabels:
  app: choreo-dataplane
